// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// AbortMigrateVMDiskRequest 取消虚拟机热存储迁移
type AbortMigrateVMDiskRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 虚拟机ID，待调整带宽的虚拟机标识
	VMID *string `json:"VMID" required:"true"`
}
