// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// AbortCustomImageResponse - 取消制作虚拟机镜像
type AbortCustomImageResponse struct {
	response.CommonBase

}
