// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// AbortMigratePaaSInstanceResponse - PaaS 取消计算迁移
type AbortMigratePaaSInstanceResponse struct {
	response.CommonBase

}
