// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// AddNodesToIsolationGroupResponse - 添加节点到隔离组
type AddNodesToIsolationGroupResponse struct {
	response.CommonBase

}
