// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// AddRegionResponse - 纳管新地域
type AddRegionResponse struct {
	response.CommonBase

}
