// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// AliasSetRequest 设置计算集群别名
type AliasSetRequest struct {
	request.CommonBase

	// 集群类型别名，为计算集群类型设置的自定义名称，用于更易读的展示，通过调用RenameResource接口修改资源名称实现，别名长度限制为1-128个字符
	Alias *string `json:"Alias" required:"true"`
	// 地域ID，指定计算集群所属的物理区域
	Region *string `json:"Region" required:"true"`
	// 计算集群类型，用于唯一标识计算集群的类型
	SetType *string `json:"SetType" required:"true"`
}
