// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// AliasStorageSetRequest 设置存储集群别名
type AliasStorageSetRequest struct {
	request.CommonBase

	// 存储集群类型别名，为存储集群类型设置的自定义名称，用于更易读的展示，通过调用RenameResource接口修改资源名称实现，别名长度限制为1-128个字符
	Alias *string `json:"Alias" required:"true"`
	// 地域ID，指定存储集群所属的物理区域
	Region *string `json:"Region" required:"true"`
	// 存储集群类型，用于唯一标识存储集群的类型
	StorageSetType *string `json:"StorageSetType" required:"true"`
}
