// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// AliasStorageSetResponse - 设置存储集群别名
type AliasStorageSetResponse struct {
	response.CommonBase

}
