// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// AllocateNativeNodeVNCSessionResponse - 申请原生节点VNC会话
type AllocateNativeNodeVNCSessionResponse struct {
	response.CommonBase

	// 
	SessionID *string `json:"SessionID"`
}
