// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// AllocateUSBResponse - 分配USB设备
type AllocateUSBResponse struct {
	response.CommonBase

}
