// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// AllocateExternalStorageSetDiskResponse - 分配外置存储集群硬盘
type AllocateExternalStorageSetDiskResponse struct {
	response.CommonBase

}
