// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// AllocateVMSSHSessionRequest 申请虚拟机SSH会话
type AllocateVMSSHSessionRequest struct {
	request.CommonBase

	// 执行命令，连接后自动执行的命令
	CmdName *string `json:"CmdName"`
	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// 私钥内容，用于SSH认证的私钥
	IdentityContent *string `json:"IdentityContent"`
	// 密码，SSH登录密码
	Password *string `json:"Password"`
	// 端口号，SSH服务的端口
	Port *string `json:"Port"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 用户名，SSH登录的用户名
	User *string `json:"User"`
	// 虚拟机ID，待获取SSH会话的虚拟机标识
	VMID *string `json:"VMID" required:"true"`
}
