// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// AllocateVMVNCSessionRequest 申请VNC会话
type AllocateVMVNCSessionRequest struct {
	request.CommonBase

	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 虚拟机ID，待获取VNC会话的虚拟机标识
	VMID *string `json:"VMID" required:"true"`
}
