// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// AllocateK8SSessionRequest 申请console会话
type AllocateK8SSessionRequest struct {
	request.CommonBase

	// 集群Id
	ClusterID *string `json:"ClusterID" required:"true"`
	// 执行命令
	CmdName *string `json:"CmdName"`
	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// 容器名称
	ContainerName *string `json:"ContainerName"`
	// 名字空间
	NameSpace *string `json:"NameSpace"`
	// Pod名称
	PodName *string `json:"PodName" required:"true"`
	// 地域
	Region *string `json:"Region" required:"true"`
}
