// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// AllocateNativeNodeSSHSessionResponse - 申请原生节点SSH会话
type AllocateNativeNodeSSHSessionResponse struct {
	response.CommonBase

	// 
	SessionID *string `json:"SessionID"`
}
