// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// AllocateVMSSHSessionResponse - 申请虚拟机SSH会话
type AllocateVMSSHSessionResponse struct {
	response.CommonBase

	// SSH会话ID，用于建立SSH连接的标识
	SessionID *string `json:"SessionID"`
}
