// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// AllocateK8STerminalResponse - 申请console会话
type AllocateK8STerminalResponse struct {
	response.CommonBase

	// 
	SessionID *string `json:"SessionID"`
}
