// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// AllocateUSBRequest 分配USB设备
type AllocateUSBRequest struct {
	request.CommonBase

	// 项目ID，USB设备分配后归属的项目，未传时尝试分配默认项目
	ProjectID *string `json:"ProjectID"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 目标租户ID，指定USB设备分配给的租户
	TargetCompanyID *int `json:"TargetCompanyID" required:"true"`
	// USB设备ID，指定要分配给租户的USB设备，设备必须处于未挂载且节点授权通过
	USBDeviceID *string `json:"USBDeviceID" required:"true"`
}
