// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// ApplyRedisConfigFileResponse - 应用Redis参数模板
type ApplyRedisConfigFileResponse struct {
	response.CommonBase

}
