// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// ApplyRedisConfigFileResponse - 应用Redis参数模板
type ApplyRedisConfigFileResponse struct {
	response.CommonBase

}
