// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// AssociateVPCPeeringResponse - 创建VPC对等连接
type AssociateVPCPeeringResponse struct {
	response.CommonBase

}
