// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// AssociateVPCPeeringRequest 创建VPC对等连接
type AssociateVPCPeeringRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID" required:"true"`
	// 对端ID，PeerType为VPC时传VPCID，为DC时传DirectConnectID
	PeerID *string `json:"PeerID" required:"true"`
	// 对端类型，取值VPC/DC
	PeerType *string `json:"PeerType" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// VPCID，发起对等连接的源VPC标识符
	VPCID *string `json:"VPCID" required:"true"`
}
