// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// AttachLoadBalancerResponse - 伸缩组关联lb
type AttachLoadBalancerResponse struct {
	response.CommonBase

}
