// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// AttachClusterEIPResponse - 绑定k8s集群外网IP
type AttachClusterEIPResponse struct {
	response.CommonBase

}
