// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// AttachClusterEIPRequest 绑定k8s集群外网IP
type AttachClusterEIPRequest struct {
	request.CommonBase

	// 集群Id
	ClusterID *string `json:"ClusterID" required:"true"`
	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// APIServer EIPID
	EIPID *string `json:"EIPID" required:"true"`
	// Region
	Region *string `json:"Region" required:"true"`
}
