// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// AttachISOResponse - 绑定iso
type AttachISOResponse struct {
	response.CommonBase

}
