// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// AttachLoadBalancerResponse - 伸缩组关联lb
type AttachLoadBalancerResponse struct {
	response.CommonBase

}
