// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// AttachNICRequest 绑定网卡
type AttachNICRequest struct {
	request.CommonBase

	// 租户ID，AttachNIC接口中可选，用于权限校验
	CompanyID *int `json:"CompanyID"`
	// 网卡ID，指定要绑定的网卡资源
	NICID *string `json:"NICID" required:"true"`
	// 物理网卡型号标准编号，用于SR-IOV直通场景；为空表示不启用SR-IOV；与网卡QoS流量整形互斥
	PFCode *string `json:"PFCode"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 资源ID，指定网卡要绑定的目标资源ID，通常为虚拟机ID
	ResourceID *string `json:"ResourceID" required:"true"`
	// 资源类型，指定网卡要绑定的目标资源类型；取值VM
	ResourceType *string `json:"ResourceType" required:"true"`
}
