// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// BindTagResponse - 绑定标签
type BindTagResponse struct {
	response.CommonBase

}
