// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// BindEIPToVPNResponse - 绑定EIP到VPN
type BindEIPToVPNResponse struct {
	response.CommonBase

}
