// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// BindEIPResponse - 绑定弹性IP
type BindEIPResponse struct {
	response.CommonBase

}
