// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// BindSecurityGroupResponse - 绑定安全组
type BindSecurityGroupResponse struct {
	response.CommonBase

}
