// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// BindEIPRequest 绑定弹性IP
type BindEIPRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID" required:"true"`
	// EIP资源ID，弹性IP的唯一标识符
	EIPID *string `json:"EIPID" required:"true"`
	// EIP模式，指定EIP的工作模式，取值Direct/NAT，未指定时默认Direct
	Mode *string `json:"Mode"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 资源ID，要绑定EIP的资源唯一标识符
	ResourceID *string `json:"ResourceID" required:"true"`
	// 资源类型，指定EIP要绑定的资源类型，取值VM/NATGW/VPNGW/LB/DTS/OSS/FS/MYSQL/REDIS
	ResourceType *string `json:"ResourceType" required:"true"`
}
