// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// CancelInstallTaskV2Request 取消装机任务
type CancelInstallTaskV2Request struct {
	request.CommonBase

	// 取消后是否清理已安装的系统，true 或 false，默认值为 false
	CleanOnCancel *string `json:"CleanOnCancel"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
	// 序列号，裸金属的硬件序列号
	SN *string `json:"SN" required:"true"`
	// 任务ID，指定要取消的装机任务
	TaskID *string `json:"TaskID" required:"true"`
}
