// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// ChangeDBSGatewayEIPRequest 换绑备份网关
type ChangeDBSGatewayEIPRequest struct {
	request.CommonBase

	// 租户ID，用于标识资源所属的租户，实现多租户环境下的资源隔离
	CompanyID *int `json:"CompanyID"`
	// DBS网关ID，DBS网关的ID
	DBSGatewayID *string `json:"DBSGatewayID" required:"true"`
	// 外网IPID，外网的IPID
	EIPID *string `json:"EIPID" required:"true"`
	// 地域，备份源的地域
	Region *string `json:"Region" required:"true"`
}
