// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// ChangeDBSGatewayEIPResponse - 换绑备份网关
type ChangeDBSGatewayEIPResponse struct {
	response.CommonBase

}
