// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// ChangeMemberPasswordResponse - 由管理员为子账号更改密码
type ChangeMemberPasswordResponse struct {
	response.CommonBase

}
