// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// CheckMACInUseRequest 查询MAC是否使用中
type CheckMACInUseRequest struct {
	request.CommonBase

	// 租户ID，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// MAC地址，要检查的MAC地址，格式为6组2位十六进制数，以冒号或连字符分隔
	MAC *string `json:"MAC" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
