// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CheckIPInuseResponse - 查询IP是否使用中
type CheckIPInuseResponse struct {
	response.CommonBase

}
