// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// CheckIPInuseRequest 查询IP是否使用中
type CheckIPInuseRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// 扁平网络ID，与SubnetID、SegmentID三选一且只能指定一个，用于指定要检查IP的扁平网络范围
	FlatNetworkID *string `json:"FlatNetworkID"`
	// IP地址，指定要检查使用状态的IP地址
	IP *string `json:"IP" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 网段ID，与SubnetID、FlatNetworkID三选一且只能指定一个，用于指定要检查IP的网段范围
	SegmentID *string `json:"SegmentID"`
	// 子网ID，与SegmentID、FlatNetworkID三选一且只能指定一个，用于指定要检查IP的子网范围
	SubnetID *string `json:"SubnetID"`
}
