// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CleanPXEResponse - 清理PXE环境
type CleanPXEResponse struct {
	response.CommonBase

}
