// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// CloneBMCTypeRequest 克隆BMC类型
type CloneBMCTypeRequest struct {
	request.CommonBase

	// 源BMC类型名称，需为已有的BMC类型名称（可通过ListBMCTypes/GetBMCType获取），克隆时会复制其登录脚本和校验步骤
	Name *string `json:"Name" required:"true"`
	// 新BMC类型名称，为克隆后生成的BMC类型唯一标识，需保证未被占用
	NewName *string `json:"NewName" required:"true"`
	// 地域ID，指定要操作的Kunlun集群地域，确保在对应地域克隆BMC类型
	Region *string `json:"Region" required:"true"`
}
