// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// CloneKickstartTemplateRequest 克隆Kickstart模板
type CloneKickstartTemplateRequest struct {
	request.CommonBase

	// 新模板描述
	Description *string `json:"Description"`
	// 源模板名称
	Name *string `json:"Name" required:"true"`
	// 新模板名称
	NewName *string `json:"NewName" required:"true"`
	// 地域
	Region *string `json:"Region" required:"true"`
}
