// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// CloneCustomImageToBaseImageRequest 自制镜像复制成基础镜像
type CloneCustomImageToBaseImageRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// 目标镜像名称，用于创建基础镜像资源，长度1-128个字符，仅支持中英文、数字、点、下划线和中划线
	DestImageName *string `json:"DestImageName" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 源镜像ID，作为复制来源的自制镜像标识，用于生成基础镜像
	SourceImageID *string `json:"SourceImageID" required:"true"`
}
