// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CloneKickstartTemplateResponse - 克隆Kickstart模板
type CloneKickstartTemplateResponse struct {
	response.CommonBase

	// 模板ID
	ID *string `json:"ID"`
	// 模板名称
	Name *string `json:"Name"`
}
