// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CloseHostNUMAScheduleResponse - 关闭节点NUMA调度
type CloseHostNUMAScheduleResponse struct {
	response.CommonBase

}
