// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CloseKVMSessionV2Response - 关闭KVM会话
type CloseKVMSessionV2Response struct {
	response.CommonBase

}
