// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreateDiskFromSnapshotResponse - 从快照创建数据盘
type CreateDiskFromSnapshotResponse struct {
	response.CommonBase

	// 磁盘ID，创建得到的磁盘标识
	DiskID *string `json:"DiskID"`
}
