// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// CreateOnSiteInspectionRequest 创建一键巡检报告
type CreateOnSiteInspectionRequest struct {
	request.CommonBase

	// 一键巡检报告名称，用于标识和管理巡检任务
	Name *string `json:"Name" required:"true"`
}
