// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// CreateResourceEventNotifyRuleRequest 创建资源事件通知规则
type CreateResourceEventNotifyRuleRequest struct {
	request.CommonBase

	// 租户ID，资源事件通知规则所属租户
	CompanyID *int `json:"CompanyID" required:"true"`
	// 监控级别列表，取值：info/warning/error
	MonitorLevel []string `json:"MonitorLevel" required:"true"`
	// 监控模块列表，指定监控哪些资源模块的事件
	MonitorModule []string `json:"MonitorModule" required:"true"`
	// 监控地域，指定监控地域的资源事件
	MonitorRegion *string `json:"MonitorRegion" required:"true"`
	// 通知组ID，资源事件触发通知目标组ID
	NotifyGroupID *string `json:"NotifyGroupID" required:"true"`
}
