// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateSecurityGroupResponse - 创建安全组
type CreateSecurityGroupResponse struct {
	response.CommonBase

	// 安全组ID，创建成功后返回的安全组唯一标识符
	SGID *string `json:"SGID"`
}
