// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreateRSResponse - 添加服务节点
type CreateRSResponse struct {
	response.CommonBase

	// 真实服务器ID，用于标识服务节点
	RSID *string `json:"RSID"`
}
