// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateBucketLifecycleRuleResponse - 创建桶的生命周期
type CreateBucketLifecycleRuleResponse struct {
	response.CommonBase

	// 生命周期ID，创建得到的生命周期规则标识
	LifeCycleID *string `json:"LifeCycleID"`
}
