// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// CreatePartitionTemplateResponse - 创建分区模板
type CreatePartitionTemplateResponse struct {
	response.CommonBase

	// 模板信息
	Template *models.PartitionTemplateInfo `json:"Template"`
}
