// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreateTimerResponse - 创建定时器
type CreateTimerResponse struct {
	response.CommonBase

	// 定时器ID，创建成功后返回的定时器唯一标识符，用于后续查询、更新和删除操作
	TimerID *string `json:"TimerID"`
}
