// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreateFlatNetworkResponse - 创建扁平网络
type CreateFlatNetworkResponse struct {
	response.CommonBase

	// 扁平网络ID，创建成功后返回的扁平网络唯一标识
	FlatNetworkID *string `json:"FlatNetworkID"`
}
