// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreateDiskResponse - 创建数据盘
type CreateDiskResponse struct {
	response.CommonBase

	// 磁盘ID，磁盘标识
	DiskID *string `json:"DiskID"`
}
