// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// CreateMemberTagRequest 添加角色授权
type CreateMemberTagRequest struct {
	request.CommonBase

	// 成员ID，用于指定被授权的账号
	MemberID *int `json:"MemberID" required:"true"`
	// 项目组ID列表，租户级别用户必填且至少一个项目组ID；系统级/区域级授权可为空
	ProjectIDs []string `json:"ProjectIDs"`
	// 角色ID列表，用于指定要授予的角色集合
	RoleIDs []string `json:"RoleIDs" required:"true"`
}
