// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreateFSResponse - 创建文件存储服务
type CreateFSResponse struct {
	response.CommonBase

	// 文件存储实例ID，创建得到的文件存储标识
	FSID *string `json:"FSID"`
}
