// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// CreateRemoteVPNGWRequest 创建对端网关
type CreateRemoteVPNGWRequest struct {
	request.CommonBase

	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 对端网关IP地址，对端VPN网关公网IP，用于建立IPSec隧道连接，需为合法IPv4或IPv6，同一项目内IP不可重复
	IPAddress *string `json:"IPAddress" required:"true"`
	// 对端网关名称，支持中文、英文字母、数字、点、下划线和中划线，长度1-128字符
	Name *string `json:"Name" required:"true"`
	// 项目ID，用于标识资源所属项目分组，未传时尝试分配默认项目
	ProjectID *string `json:"ProjectID"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 备注，长度0-100字符，禁止http://或https://等非法字符
	Remark *string `json:"Remark"`
	// 标签键值对，格式为Base64编码的key:value字符串，用于资源标记和分类管理
	TagKeyValuePairs []string `json:"TagKeyValuePairs" required:"true"`
}
