// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// CreateNativeNodeRequest 创建k8s集群原生节点
type CreateNativeNodeRequest struct {
	request.CommonBase

	// 系统盘集群ID
	BootDiskSetType *string `json:"BootDiskSetType" required:"true"`
	// 系统盘大小
	BootDiskSpace *int `json:"BootDiskSpace" required:"true"`
	// 原生节点CPU数量
	CPU *int `json:"CPU"`
	// 集群Id
	ClusterID *string `json:"ClusterID" required:"true"`
	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// 计算集群类型
	ComputeclassType *string `json:"ComputeclassType" required:"true"`
	// 数据盘集群ID
	DataDiskSetType *string `json:"DataDiskSetType"`
	// 数据盘大小
	DataDiskSpace *int `json:"DataDiskSpace"`
	// 原生节点外网IP
	EIPID *string `json:"EIPID"`
	// GPU数量
	GPU *int `json:"GPU"`
	// GPU型号
	GPUMdevName *string `json:"GPUMdevName"`
	// 镜像ID
	ImageID *string `json:"ImageID" required:"true"`
	// 原生节点pod数量
	MaxPods *int `json:"MaxPods"`
	// 原生节点内存容量
	Memory *int `json:"Memory"`
	// 节点名称
	NodeName *string `json:"NodeName" required:"true"`
	// 密码
	Password *string `json:"Password"`
	// 地域
	Region *string `json:"Region" required:"true"`
	// 
	SGID *string `json:"SGID"`
	// 容器子网Id 列表
	SubnetIDs []string `json:"SubnetIDs"`
}
