// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// CreateMySQLSlaveRequest 创建MySQL从库
type CreateMySQLSlaveRequest struct {
	request.CommonBase

	// 计费类型，取值Dynamic/Month/Year，分别对应HOUR/MONTH/YEAR
	ChargeType *string `json:"ChargeType" required:"true"`
	// 租户ID，实例所属租户
	CompanyID *int `json:"CompanyID" required:"true"`
	// 存储集群类型，实例数据盘所属存储集群类型
	DiskSetType *string `json:"DiskSetType" required:"true"`
	// 存储容量，单位GiB，且不得小于主库容量
	DiskSpace *int `json:"DiskSpace" required:"true"`
	// 外网IP资源ID，用于绑定公网IP
	EIPID *string `json:"EIPID"`
	// 主库ID，从库所属主库实例ID；必须为主库实例，单主库最多5个从库
	MasterID *string `json:"MasterID" required:"true"`
	// 内存大小，单位MiB，必须是1024的倍数，且不得小于主库内存
	Memory *int `json:"Memory" required:"true"`
	// 从库名称，从库实例名称，支持中文、英文字母、数字、点、下划线和中划线，长度1-128字符
	Name *string `json:"Name" required:"true"`
	// 计费数量，用于指定购买时长的数量，按月/年计费时表示购买的月/年数，按小时计费时默认为1
	Quantity *int `json:"Quantity" required:"true"`
	// 地域ID，实例所属地域
	Region *string `json:"Region" required:"true"`
	// 从库描述，从库实例备注，长度0-100字符，禁止http://或https://等非法字符
	Remark *string `json:"Remark"`
	// 标签键值对，资源标签键值对列表，格式为Base64编码的key:value
	TagKeyValuePairs []string `json:"TagKeyValuePairs" required:"true"`
	// 计算集群类型，实例所属计算集群类型
	VMType *string `json:"VMType" required:"true"`
	// 外网安全组ID，用于外网访问控制
	WANSGID *string `json:"WANSGID"`
}
