// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// CreateVSPolicyRequest 创建转发规则
type CreateVSPolicyRequest struct {
	request.CommonBase

	// CA证书ID，SNI协议开启时的CA证书ID
	CACertificateID *string `json:"CACertificateID"`
	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 请求域名，转发规则关联的请求域名，值可为空表示仅匹配路径，若填写必须符合Nginx server_name规则（最长30字符，支持以*.开头或.*结尾的通配域名），且需与Path组合保持唯一
	Domain *string `json:"Domain"`
	// 负载均衡ID，用于定位需要创建转发规则的负载均衡实例
	LBID *string `json:"LBID" required:"true"`
	// 请求访问路径，转发规则关联的请求访问路径，如'/'，域名和路径至少需要指定一项，且组合必须唯一
	Path *string `json:"Path"`
	// 真实服务器ID列表，用于绑定到该转发规则的服务节点
	RSIDs []string `json:"RSIDs"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// SSL认证模式，SNI协议开启时的SSL模式，取值范围：simplex、duplex
	SSLMode *string `json:"SSLMode"`
	// 服务器证书ID，SNI协议开启时的服务器证书ID
	ServerCertificateID *string `json:"ServerCertificateID"`
	// 虚拟服务器ID，用于定位需要绑定转发规则的监听器，仅支持来源为Default的监听器（Service/Ingress来源由容器系统管理，调用会返回StatusCanNotModifyNoDefaultOriginVS错误）
	VSID *string `json:"VSID" required:"true"`
}
