// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreateInstallTaskV2Response - 创建装机任务
type CreateInstallTaskV2Response struct {
	response.CommonBase

	// 任务ID，创建成功的装机任务标识
	TaskID *string `json:"TaskID"`
}
