// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreateMySQLParamTplResponse - 创建MySQL参数模板
type CreateMySQLParamTplResponse struct {
	response.CommonBase

	// 模板ID，参数模板ID
	TplID *string `json:"TplID"`
}
