// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateVPNGWResponse - 创建网关
type CreateVPNGWResponse struct {
	response.CommonBase

	// VPN网关ID，创建成功的VPN网关唯一标识
	VPNGWID *string `json:"VPNGWID"`
}
