// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreatePMV2Response - 创建裸金属
type CreatePMV2Response struct {
	response.CommonBase

	// 裸金属ID，创建成功的裸金属实例标识
	PMID *string `json:"PMID"`
	// 序列号，从硬件获取的物理机唯一序列号
	SN *string `json:"SN"`
}
