// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreateProductSpecificationResponse - 创建产品规格
type CreateProductSpecificationResponse struct {
	response.CommonBase

	// 规格ID，新创建的规格唯一标识符
	SpecificationID *string `json:"SpecificationID"`
}
