// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateDataCheckTaskResponse - 创建数据校验任务
type CreateDataCheckTaskResponse struct {
	response.CommonBase

	// 校验任务ID，新创建的数据校验任务唯一标识
	DTSID *string `json:"DTSID"`
}
