// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// CreateProjectRequest 创建项目
type CreateProjectRequest struct {
	request.CommonBase

	// 租户ID，用于指定项目所属租户
	CompanyID *int `json:"CompanyID" required:"true"`
	// 项目名称，用于在控制台显示项目，长度为1-50个字符，只能包含中英文、数字、点、下划线和中划线
	Name *string `json:"Name" required:"true"`
	// 备注，用于补充说明项目用途和范围，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符，
	Remark *string `json:"Remark"`
}
