// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateUserResponse - 创建租户
type CreateUserResponse struct {
	response.CommonBase

	// 租户ID，创建成功后返回的租户唯一标识，用于后续查询、授权与资源管理场景
	UserID *int `json:"UserID"`
}
