// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreateRedisConfigFileResponse - 创建配置文件
type CreateRedisConfigFileResponse struct {
	response.CommonBase

	// 配置文件ID，创建成功后返回的模板ID
	ConfigID *string `json:"ConfigID"`
}
