// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreateClusterResponse - 创建k8s集群
type CreateClusterResponse struct {
	response.CommonBase

	// 集群Id
	ClusterID *string `json:"ClusterID"`
}
