// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
	"third_party/platform-sdk-go/services/openapi/models"
)

// CreateSMCRequest 创建SMC任务
type CreateSMCRequest struct {
	request.CommonBase

	// Agent版本号，用于标识迁移源端的Agent版本，如v1.0.1，用于兼容性检查和功能管理
	AgentVersion *string `json:"AgentVersion"`
	// 源端CPU架构类型，用于指导目标云硬盘的初始化，如x86_64或aarch64
	Arch *string `json:"Arch"`
	// 源端启动加载器类型，如BIOS或UEFI，影响目标虚拟机的启动配置
	BootloaderType *string `json:"BootloaderType"`
	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID" required:"true"`
	// 源端CPU核心数，影响迁移性能和目标VM的配置选择
	Cores *int `json:"Cores"`
	// 源端磁盘分区列表，每个磁盘分区记录文件系统类型、大小、挂载点等信息，用于制定磁盘映射策略
	Disks []models.Disk `json:"Disks"`
	// 源端操作系统发行版名称，如CentOS、Ubuntu、Debian等，用于配置兼容的运行环境
	Distribution *string `json:"Distribution"`
	// 源端操作系统发行版版本号，如7.9、20.04等，与Distribution搭配确定精确的系统版本
	DistributionVersion *string `json:"DistributionVersion"`
	// 源端主机名，用于标识源服务器的网络身份
	Hostname *string `json:"Hostname"`
	// 源端IP地址，用于与源服务器通信和数据同步
	IP *string `json:"IP"`
	// 源端操作系统内核版本号，如3.10.0-1160等，用于判断驱动和模块兼容性
	Kernel *string `json:"Kernel"`
	// 源端内存大小，单位MB，用于评估数据同步性能和目标VM配置需求
	Memory *int `json:"Memory"`
	// SMC任务名称，长度为1-128个字符，名称只能包含中英文、数字、点（.）、下划线（_）和中划线（-），用于标识迁移任务
	Name *string `json:"Name" required:"true"`
	// 源端操作系统类型，表示源服务器的操作系统，如Linux或Windows
	OS *string `json:"OS"`
	// 项目ID，用于实现资源的逻辑分组管理，同一项目下的资源可统一计费和权限管理，未传时尝试分配默认项目
	ProjectID *string `json:"ProjectID"`
	// 地域ID，指定SMC任务所属的物理区域，决定了迁移资源在哪个云数据中心部署
	Region *string `json:"Region" required:"true"`
	// 备注说明，用于进行说明和注释，长度为0-100个英文或中文字符，不能包含http://或https://等非法字符
	Remark *string `json:"Remark"`
	// 标签键值对列表，用于资源标记和分类管理，格式为key:value的字符串列表，若需特殊字符应使用Base64编码
	TagKeyValuePairs []string `json:"TagKeyValuePairs" required:"true"`
}
