// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// CreateInstallTaskV2Request 创建装机任务
type CreateInstallTaskV2Request struct {
	request.CommonBase

	// 租户ID，必须分配给非管理员租户才能进行装机（CompanyID不能为0或超级管理员ID）
	CompanyID *int `json:"CompanyID" required:"true"`
	// 磁盘选择器，JSON格式字符串，指定安装目标磁盘，必填，支持by-path、by-id、by-wwn、script四种选择模式
	DiskSelector *string `json:"DiskSelector" required:"true"`
	// 主机名，设置安装后的主机名
	Hostname *string `json:"Hostname" required:"true"`
	// 镜像ID，clone模式必填，指定克隆源镜像
	ImageID *string `json:"ImageID"`
	// 镜像URL，clone模式必填，指定镜像文件访问地址
	ImageURL *string `json:"ImageURL"`
	// 安装模式，指定系统安装方式，clone：克隆模式（从镜像克隆）；kickstart：Kickstart自动化安装，clone模式要求ImageID和ImageURL必填，kickstart模式要求OSMediaID和TemplateID必填
	InstallMode *string `json:"InstallMode" required:"true"`
	// 网络配置，JSON格式字符串，NetworkConfigV2数组，至少配置一个网卡，必填，示例包含物理网卡、Bond、VLAN等多种类型
	Networks *string `json:"Networks" required:"true"`
	// 操作系统发行版，标识操作系统类型
	OSDistribution *string `json:"OSDistribution" required:"true"`
	// 系统镜像ID，kickstart模式必填，指定操作系统ISO镜像
	OSMediaID *string `json:"OSMediaID"`
	// 操作系统完整名称，包含版本和架构信息
	OSName *string `json:"OSName" required:"true"`
	// 裸金属ID，指定要进行装机操作的裸金属实例
	PMID *string `json:"PMID" required:"true"`
	// 分区模板ID，指定磁盘分区方案，可选
	PartitionTemplateID *string `json:"PartitionTemplateID"`
	// 密码，系统管理员密码，用于系统登录
	Password *string `json:"Password" required:"true"`
	// 安装后脚本，在系统安装完成后执行的自定义脚本，可选
	PostInstallScript *string `json:"PostInstallScript"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
	// SSH密钥ID列表，配置SSH公钥认证，可选
	SSHKeyIDs []string `json:"SSHKeyIDs"`
	// SSH公钥列表，直接指定SSH公钥内容，可选
	SSHPublicKeys []string `json:"SSHPublicKeys"`
	// Kickstart模板ID，kickstart模式必填，指定自动化安装模板
	TemplateID *string `json:"TemplateID"`
	// 模板变量，JSON格式字符串，用于Kickstart模板渲染时的变量替换
	TemplateVars *string `json:"TemplateVars"`
	// 用户名，系统管理员用户名，若不指定则默认为root
	Username *string `json:"Username" required:"true"`
}
