// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreateIPGroupResponse - 创建IP组
type CreateIPGroupResponse struct {
	response.CommonBase

	// IP组ID，创建成功后返回的IP组唯一标识符
	IPGroupID *string `json:"IPGroupID"`
}
