// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// CreateKickstartTemplateRequest 创建Kickstart模板
type CreateKickstartTemplateRequest struct {
	request.CommonBase

	// 模板内容
	Content *string `json:"Content"`
	// 模板描述
	Description *string `json:"Description"`
	// 是否设为默认模板
	IsDefault *bool `json:"IsDefault"`
	// 模板名称
	Name *string `json:"Name" required:"true"`
	// 操作系统发行版
	OSDistribution *string `json:"OSDistribution" required:"true"`
	// 地域
	Region *string `json:"Region" required:"true"`
	// 支持的变量列表
	Variables []string `json:"Variables"`
}
