// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// CreateSlaveRedisRequest 创建Redis从库
type CreateSlaveRedisRequest struct {
	request.CommonBase

	// 计费类型，取值Dynamic/Month/Year，分别对应HOUR/MONTH/YEAR
	ChargeType *string `json:"ChargeType" required:"true"`
	// 租户ID，从库实例所属租户
	CompanyID *int `json:"CompanyID" required:"true"`
	// 存储集群类型，从库实例数据盘所属存储集群类型
	DiskSetType *string `json:"DiskSetType"`
	// 外网IP资源ID，用于绑定公网IP
	EIPID *string `json:"EIPID"`
	// 内存容量，单位MiB，且不得小于主库内存
	Memory *int `json:"Memory" required:"true"`
	// 名称，从库实例名称，长度为1-128个字符，名称只能包含中英文、数字、点、下划线和中划线
	Name *string `json:"Name" required:"true"`
	// 密码，从库登录密码
	Password *string `json:"Password"`
	// 计费数量，用于指定购买时长的数量，按月/年计费时表示购买的月/年数，按小时计费时默认为1
	Quantity *int `json:"Quantity"`
	// 主库ID，从库所属主库实例ID；必须为主库实例且状态为Running，单主库最多5个从库
	RedisID *string `json:"RedisID" required:"true"`
	// 地域ID，从库实例所属地域
	Region *string `json:"Region" required:"true"`
	// 描述，从库实例备注，长度为0-100个英文或中文字符，不能包含<script>、<a javascript:>等非法字符，用于XSS防护
	Remark *string `json:"Remark"`
	// 标签键值对，资源标签键值对列表，格式为Base64编码的key:value
	TagKeyValuePairs []string `json:"TagKeyValuePairs" required:"true"`
	// 线程数量，Redis7.0有效
	Threads *int `json:"Threads"`
	// 计算集群类型，从库实例所属计算集群类型
	VMType *string `json:"VMType" required:"true"`
	// Redis版本，取值4.0或7.0，默认4.0；主库为7.0时从库版本必须为7.0
	Version *string `json:"Version"`
	// 安全组ID，用于外网访问控制
	WANSGID *string `json:"WANSGID"`
}
