// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
	"third_party/platform-sdk-go/services/openapi/models"
)

// CreateDTSTaskRequest 创建数据传输任务
type CreateDTSTaskRequest struct {
	request.CommonBase

	// 单批写入大小，用于控制 sinker 每次批量写入的记录数；为0时使用系统默认值1000
	BatchSize *int `json:"BatchSize"`
	// CPU核数，用于指定DTS实例的CPU配置
	CPU *int `json:"CPU" required:"true"`
	// 计费类型，用于指定计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）；兼容历史值：hour、month、year，别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR
	ChargeType *string `json:"ChargeType" required:"true"`
	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID" required:"true"`
	// 计算集群类型，用于指定DTS实例运行的计算集群，需具备集群权限
	ComputeClass *string `json:"ComputeClass" required:"true"`
	// 数据标记表，用于双向同步场景记录已同步数据，格式为database.table_name，若不指定则同步服务自动创建，需确保数据库账户有创建表权限
	DataMarkTable *string `json:"DataMarkTable"`
	// 同步数据库列表，指定需要同步的数据库名称，多个数据库用逗号分隔；不指定则默认同步所有数据库
	Databases *string `json:"Databases"`
	// 目标库GTID集合，用于双向同步场景，指定目标库GTID起始位置，可通过show master status获取，用于反向增量同步
	DestinationEndpointBinlogGTID *string `json:"DestinationEndpointBinlogGTID"`
	// 目标实例地址，当DestinationEndpointInstanceType为External时必填，指定外部数据库访问地址，源与目标地址端口不可完全相同
	DestinationEndpointIP *string `json:"DestinationEndpointIP"`
	// 目标实例ID，当DestinationEndpointInstanceType为Internal时必填，指定平台内部数据库实例，需可用且归属当前租户，且类型与DestinationEngine一致，不能与源实例ID相同
	DestinationEndpointInstanceID *string `json:"DestinationEndpointInstanceID"`
	// 目标实例类型，指定目标数据库的部署位置，取值范围：Internal（平台内部数据库）、External（外部数据库）
	DestinationEndpointInstanceType *string `json:"DestinationEndpointInstanceType" required:"true"`
	// 目标实例密码，当DestinationEngine为MYSQL时必填，用于连接目标数据库的账号密码
	DestinationEndpointPassword *string `json:"DestinationEndpointPassword"`
	// 目标实例端口，当DestinationEndpointInstanceType为External时必填，MYSQL默认3306，REDIS默认6379，源与目标地址端口不可完全相同
	DestinationEndpointPort *int `json:"DestinationEndpointPort"`
	// 目标实例用户名，当DestinationEngine为MYSQL时必填，用于连接目标数据库的账号用户名，需具备写入权限
	DestinationEndpointUserName *string `json:"DestinationEndpointUserName"`
	// 目标实例数据库类型，指定目标数据库引擎类型，取值范围：MYSQL、REDIS，必须与SourceEngine一致
	DestinationEngine *string `json:"DestinationEngine" required:"true"`
	// 弹性公网IPID，当源端或目的端为External时必填，用于DTS与外部数据库建立网络连接，EIP需未绑定其他资源
	EIPID *string `json:"EIPID"`
	// 心跳间隔秒数，指定推进binlog位点的时间间隔（秒），用于防止长时间无数据变更导致位点不更新
	HeartbeatInterval *int `json:"HeartbeatInterval"`
	// 心跳表名称，用于增量或双向同步场景定时推进binlog位点，格式为database.table_name，若不指定则同步服务自动创建，需确保数据库账户有创建表权限
	HeartbeatTable *string `json:"HeartbeatTable"`
	// 忽略数据库列表，指定需要排除的数据库名称，多个数据库用逗号分隔，与Databases互斥使用
	IgnoreDatabases *string `json:"IgnoreDatabases"`
	// 忽略数据表列表，指定需要排除的数据表，支持通配符，格式为database.table，多个表用逗号分隔，与Tables互斥使用
	IgnoreTables *string `json:"IgnoreTables"`
	// 增量同步阶段的 DTS 自恢复策略；不传表示沿用 DTS 默认自恢复策略，显式 Enabled=false 表示关闭 DTS 自恢复
	IncrementalRestart *models.DTSServiceRestartPolicy `json:"IncrementalRestart"`
	// 最大每秒同步记录数，用于限制数据同步速率，取值最小范围为100，最大范围根据DTS实例CPU核数确定，1核上限为20000，2核上限为40000
	MaxRPS *int `json:"MaxRPS" required:"true"`
	// 内存大小，单位GB，用于指定DTS实例的内存配置
	Memory *int `json:"Memory" required:"true"`
	// DTS任务名称，支持中文、英文字母、数字、点、下划线和中划线，长度1-128字符
	Name *string `json:"Name" required:"true"`
	// 项目ID，用于标识资源所属项目分组，未传时尝试分配默认项目
	ProjectID *string `json:"ProjectID"`
	// 计费数量，用于指定购买时长的数量，按月/年计费时表示购买的月/年数，按小时计费时默认为1，
	Quantity *int `json:"Quantity" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 备注，长度0-100字符，禁止http://或https://等非法字符
	Remark *string `json:"Remark"`
	// binlog GTID集合，用于MYSQL增量或全量加增量同步时基于GTID模式同步，可通过show master status获取，
	SourceEndpointBinlogGTID *string `json:"SourceEndpointBinlogGTID"`
	// binlog文件名，用于MYSQL增量或全量加增量同步时指定起始binlog位置，可通过show master status获取，
	SourceEndpointBinlogName *string `json:"SourceEndpointBinlogName"`
	// binlog位点，用于MYSQL增量或全量加增量同步时指定起始binlog偏移量，可通过show master status获取，
	SourceEndpointBinlogPos *int `json:"SourceEndpointBinlogPos"`
	// 源实例地址，当SourceEndpointInstanceType为External时必填，指定外部数据库访问地址，源与目标地址端口不可完全相同
	SourceEndpointIP *string `json:"SourceEndpointIP"`
	// 源实例ID，当SourceEndpointInstanceType为Internal时必填，指定平台内部数据库实例，需可用且归属当前租户，且类型与SourceEngine一致
	SourceEndpointInstanceID *string `json:"SourceEndpointInstanceID"`
	// 源实例类型，指定源数据库的部署位置，取值范围：Internal（平台内部数据库）、External（外部数据库）
	SourceEndpointInstanceType *string `json:"SourceEndpointInstanceType" required:"true"`
	// 源实例密码，当SourceEngine为MYSQL时必填，用于连接源数据库的账号密码
	SourceEndpointPassword *string `json:"SourceEndpointPassword"`
	// 源实例端口，当SourceEndpointInstanceType为External时必填，MYSQL默认3306，REDIS默认6379，源与目标地址端口不可完全相同
	SourceEndpointPort *int `json:"SourceEndpointPort"`
	// 服务器ID，当SourceEngine为MYSQL时必填，用于标识DTS服务作为从库的唯一ID，需确保不与现有slave的server_id重复
	SourceEndpointServerID *string `json:"SourceEndpointServerID"`
	// 源实例用户名，当SourceEngine为MYSQL时必填，用于连接源数据库的账号用户名，需具备读取权限
	SourceEndpointUserName *string `json:"SourceEndpointUserName"`
	// 源实例数据库类型，指定源数据库引擎类型，取值范围：MYSQL、REDIS，必须与DestinationEngine一致
	SourceEngine *string `json:"SourceEngine" required:"true"`
	// 存储集群类型，用于指定DTS实例系统盘所在存储集群，需具备集群权限
	StorageClass *string `json:"StorageClass" required:"true"`
	// 同步数据表列表，指定需要同步的数据表，支持通配符，格式为database.table，多个表用逗号分隔；不指定则同步所有数据表
	Tables *string `json:"Tables"`
	// 标签键值对，格式为Base64编码的key:value字符串，用于资源标记和分类管理
	TagKeyValuePairs []string `json:"TagKeyValuePairs" required:"true"`
	// 任务类型，指定数据传输的同步模式，取值范围：full（全量迁移）、incremental（增量同步）、full+incremental（全量加增量）
	TaskMode *string `json:"TaskMode" required:"true"`
}
