// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreateVPNTunnelResponse - 创建隧道
type CreateVPNTunnelResponse struct {
	response.CommonBase

	// VPN隧道ID，创建成功的VPN隧道唯一标识
	VPNTunnelID *string `json:"VPNTunnelID"`
}
