// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateVSResponse - 创建VS
type CreateVSResponse struct {
	response.CommonBase

	// 虚拟服务器ID，用于标识监听器实例
	VSID *string `json:"VSID"`
}
