// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// CreateExternalStorageSetRequest 创建外置存储集群
type CreateExternalStorageSetRequest struct {
	request.CommonBase

	// CSI插件地址，存储集群CSI插件的访问地址，格式为IP:Port，支持多个地址用逗号分隔
	CSIPluginAddress *string `json:"CSIPluginAddress" required:"true"`
	// 租户ID，外置存储集群所属租户
	CompanyID *int `json:"CompanyID"`
	// IQN禁用列表，符合iqn.YYYY-MM.domain[:suffix]格式的IQN列表
	DisableTargetIQNs []string `json:"DisableTargetIQNs"`
	// IQN启用列表，符合iqn.YYYY-MM.domain[:suffix]格式的IQN列表
	EnableTargetIQNs []string `json:"EnableTargetIQNs"`
	// 名称，存储集群名称，1-128个字符，仅支持中文、英文字母、数字、点（.）、下划线（_）和中划线（-）
	Name *string `json:"Name" required:"true"`
	// 密码，登录存储集群的密码，最多50个字符
	Password *string `json:"Password"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
	// 用户名，登录存储集群的用户名，最多50个字符
	UserName *string `json:"UserName"`
}
