// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreateDBSGatewayResponse - 创建DBS网关
type CreateDBSGatewayResponse struct {
	response.CommonBase

	// DBS网关ID，DBS网关的ID
	DBSGatewayID *string `json:"DBSGatewayID"`
}
