// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreateResourceEventNotifyRuleResponse - 创建资源事件通知规则
type CreateResourceEventNotifyRuleResponse struct {
	response.CommonBase

	// 规则ID，资源事件通知规则ID
	RuleID *string `json:"RuleID"`
}
