// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreateVSPolicyResponse - 创建转发规则
type CreateVSPolicyResponse struct {
	response.CommonBase

	// 转发规则ID，用于定位新建的转发规则
	PolicyID *string `json:"PolicyID"`
}
