// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreateFSDirResponse - 创建目录
type CreateFSDirResponse struct {
	response.CommonBase

}
