// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// CreateOSMediaV2Request 创建系统镜像
type CreateOSMediaV2Request struct {
	request.CommonBase

	// 租户ID，用于在Taishan侧记录系统镜像归属，需与调用者所属租户一致以便后续权限控制
	CompanyID *int `json:"CompanyID" required:"true"`
	// 镜像ID，Kunlun侧已有的基础镜像，创建系统镜像时会引用该镜像文件
	ImageID *string `json:"ImageID" required:"true"`
	// 系统镜像名称，长度1-128个字符，仅支持中英文、数字、点（.）、下划线（_）、中划线（-），用于Kunlun与云管展示
	Name *string `json:"Name" required:"true"`
	// 操作系统发行版（如：CentOS、OpenEuler），用于区分不同系列的ISO镜像，可为空
	OSDistribution *string `json:"OSDistribution"`
	// 操作系统完整名称（如：CentOS 7.4 x86_64），用于界面展示和后续筛选，可为空
	OSName *string `json:"OSName"`
	// 项目组ID，镜像所属项目，便于资源隔离和计费，未传时尝试分配默认项目
	ProjectID *string `json:"ProjectID"`
	// 地域ID，指定系统镜像所属地域，系统会在该地域的Kunlun集群创建镜像并写入Taishan资源记录
	Region *string `json:"Region" required:"true"`
	// 备注，0-100个中英文字符，禁止包含http://或https://，用于补充镜像用途说明
	Remark *string `json:"Remark"`
	// 标签键值对，用于资源标记和分类管理，格式为key:value并以Base64编码传输
	TagKeyValuePairs []string `json:"TagKeyValuePairs" required:"true"`
	// 系统镜像类型，仅支持ISO，表示使用ISO安装介质
	Type *string `json:"Type" required:"true"`
}
