// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreatePlatformStorageDiskResponse - 创建平台通用存储云盘
type CreatePlatformStorageDiskResponse struct {
	response.CommonBase

	// 磁盘ID，创建成功后返回的云盘ID
	DiskID *string `json:"DiskID"`
}
