// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// CreateBucketResponse - 创建桶
type CreateBucketResponse struct {
	response.CommonBase

}
