// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// CreateAlertNotifyGroupRequest 创建告警通知组
type CreateAlertNotifyGroupRequest struct {
	request.CommonBase

	// 租户ID，通知组所属租户
	CompanyID *int `json:"CompanyID"`
	// 通知组名称，长度1-128字符，支持中英文、数字、点、下划线和中划线
	Name *string `json:"Name" required:"true"`
	// 地域ID，通知组所属地域
	Region *string `json:"Region" required:"true"`
}
