// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateDOSTokenResponse - 创建令牌
type CreateDOSTokenResponse struct {
	response.CommonBase

}
