// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DeleteSubnetRouteRequest 删除子网路由
type DeleteSubnetRouteRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID" required:"true"`
	// 目的地址，路由策略目的地址，IPv4CIDR格式，仅支持删除VIP/VM/Custom类型路由，系统路由不可删除
	Destination *string `json:"Destination" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 子网ID
	SubnetID *string `json:"SubnetID" required:"true"`
}
