// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteVMSnapshotResponse - 虚拟机删除快照
type DeleteVMSnapshotResponse struct {
	response.CommonBase

	// 快照ID列表，被删除的快照标识列表
	SPIDs []string `json:"SPIDs"`
}
