// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteWorkflowResponse - 删除自定义流程
type DeleteWorkflowResponse struct {
	response.CommonBase

}
