// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeletePartitionTemplateResponse - 删除分区模板
type DeletePartitionTemplateResponse struct {
	response.CommonBase

}
