// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteMySQLResponse - 删除MySQL
type DeleteMySQLResponse struct {
	response.CommonBase

}
