// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DeleteDBSBackupRequest 删除备份
type DeleteDBSBackupRequest struct {
	request.CommonBase

	// 备份ID，待删除的备份ID
	BackupID *string `json:"BackupID" required:"true"`
	// 租户ID，备份所属租户
	CompanyID *int `json:"CompanyID"`
	// 地域ID，备份源资源所属地域
	Region *string `json:"Region" required:"true"`
}
