// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteSecurityGroupRuleResponse - 删除安全组规则
type DeleteSecurityGroupRuleResponse struct {
	response.CommonBase

}
