// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DeleteBMCTypeRequest 删除BMC类型
type DeleteBMCTypeRequest struct {
	request.CommonBase

	// BMC类型名称
	Name *string `json:"Name" required:"true"`
	// 地域
	Region *string `json:"Region" required:"true"`
}
