// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteNATGWRuleResponse - 删除NAT网关规则
type DeleteNATGWRuleResponse struct {
	response.CommonBase

}
