// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteProductSpecificationResponse - 删除产品规格
type DeleteProductSpecificationResponse struct {
	response.CommonBase

	// 规格ID，已删除的规格唯一标识符
	SpecificationID *string `json:"SpecificationID"`
}
