// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteAlertNotifyReceiverResponse - 删除告警通知人
type DeleteAlertNotifyReceiverResponse struct {
	response.CommonBase

}
