// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteSegmentRouteResponse - 删除外网线路路由
type DeleteSegmentRouteResponse struct {
	response.CommonBase

}
