// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeletePlatformStorageDiskResponse - 删除平台通用存储云盘
type DeletePlatformStorageDiskResponse struct {
	response.CommonBase

}
