// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteVMInstanceResponse - 删除虚拟机
type DeleteVMInstanceResponse struct {
	response.CommonBase

}
