// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteBucketResponse - 删除桶
type DeleteBucketResponse struct {
	response.CommonBase

}
