// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DeleteRedisConfigFileRequest 删除配置文件
type DeleteRedisConfigFileRequest struct {
	request.CommonBase

	// 配置ID，参数模板ID
	ConfigID *string `json:"ConfigID" required:"true"`
}
