// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteOnSiteInspectionResponse - 删除一键巡检报告
type DeleteOnSiteInspectionResponse struct {
	response.CommonBase

}
