// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteResourceUsageResponse - 删除资源使用情况报告
type DeleteResourceUsageResponse struct {
	response.CommonBase

}
