// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteClusterResponse - 删除k8s集群
type DeleteClusterResponse struct {
	response.CommonBase

}
