// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteMemberTagResponse - 删除角色授权
type DeleteMemberTagResponse struct {
	response.CommonBase

}
