// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteResourceEventNotifyRuleResponse - 删除资源事件通知规则
type DeleteResourceEventNotifyRuleResponse struct {
	response.CommonBase

}
