// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DeleteMySQLParamTplRequest 删除MySQL参数模板
type DeleteMySQLParamTplRequest struct {
	request.CommonBase

	// 租户ID，模板所属租户
	CompanyID *int `json:"CompanyID"`
	// 地域ID，模板所属地域
	Region *string `json:"Region" required:"true"`
	// 模板ID，参数模板ID
	TplID *string `json:"TplID" required:"true"`
}
