// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DeleteAdminRequest 删除管理员
type DeleteAdminRequest struct {
	request.CommonBase

	// 成员ID，指定要删除的管理员账号标识
	MemberID *int `json:"MemberID" required:"true"`
}
