// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteSecurityGroupResponse - 删除安全组
type DeleteSecurityGroupResponse struct {
	response.CommonBase

}
