// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DeleteExternalStorageSetRequest 删除外置存储集群
type DeleteExternalStorageSetRequest struct {
	request.CommonBase

	// 租户ID，存储集群所属租户
	CompanyID *int `json:"CompanyID"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
	// 存储集群ID，待删除的外置存储集群ID
	SetID *string `json:"SetID" required:"true"`
}
