// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteVPNTunnelResponse - 删除隧道
type DeleteVPNTunnelResponse struct {
	response.CommonBase

}
