// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DeletePlatformStorageDiskRequest 删除平台通用存储云盘
type DeletePlatformStorageDiskRequest struct {
	request.CommonBase

	// 磁盘ID，待删除的平台通用存储云盘ID
	DiskID *string `json:"DiskID" required:"true"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
}
