// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteSnapshotResponse - 删除快照
type DeleteSnapshotResponse struct {
	response.CommonBase

}
