// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteContainerImageRepositoryResponse - 删除镜像仓库
type DeleteContainerImageRepositoryResponse struct {
	response.CommonBase

}
