// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteRedisResponse - 删除redis实例
type DeleteRedisResponse struct {
	response.CommonBase

}
