// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteTrafficMirrorResponse - 删除流量镜像
type DeleteTrafficMirrorResponse struct {
	response.CommonBase

}
