// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteVSPolicyResponse - 删除转发规则
type DeleteVSPolicyResponse struct {
	response.CommonBase

}
