// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DeleteSecurityGroupRuleRequest 删除安全组规则
type DeleteSecurityGroupRuleRequest struct {
	request.CommonBase

	// 租户ID，标识安全组所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID" required:"true"`
	// 地域ID，用于标识安全组所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 安全组ID，指定规则所属的安全组唯一标识符
	SGID *string `json:"SGID" required:"true"`
	// 安全组规则ID，指定要删除的规则唯一标识符
	SGRuleID *string `json:"SGRuleID" required:"true"`
}
