// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteKickstartTemplateResponse - 删除Kickstart模板
type DeleteKickstartTemplateResponse struct {
	response.CommonBase

}
