// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteSubnetResponse - 删除子网
type DeleteSubnetResponse struct {
	response.CommonBase

}
