// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DeleteMySQLRequest 删除MySQL
type DeleteMySQLRequest struct {
	request.CommonBase

	// 租户ID，资源所属租户
	CompanyID *int `json:"CompanyID" required:"true"`
	// MySQL实例ID，指定要删除的MySQL实例；注意：开启删除保护(TerminationPolicy=0)或版本升级中的资源不可删除
	MySQLID *string `json:"MySQLID" required:"true"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
}
