// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteInstallProfileResponse - 删除装机配置模板
type DeleteInstallProfileResponse struct {
	response.CommonBase

}
