// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DeleteSecurityGroupRequest 删除安全组
type DeleteSecurityGroupRequest struct {
	request.CommonBase

	// 租户ID，标识安全组所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID" required:"true"`
	// 地域ID，用于标识安全组所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 安全组ID，指定待删除的安全组唯一标识符；删除前会检查是否存在资源绑定
	SGID *string `json:"SGID" required:"true"`
}
