// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DeleteKickstartTemplateRequest 删除Kickstart模板
type DeleteKickstartTemplateRequest struct {
	request.CommonBase

	// 模板ID
	ID *string `json:"ID" required:"true"`
	// 地域
	Region *string `json:"Region" required:"true"`
}
