// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteSubnetRouteResponse - 删除子网路由
type DeleteSubnetRouteResponse struct {
	response.CommonBase

}
