// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DeleteOrchTaskRequest 删除编排任务
type DeleteOrchTaskRequest struct {
	request.CommonBase

	// 租户ID，任务所属租户
	CompanyID *int `json:"CompanyID"`
	// 地域，编排任务所属地域
	Region *string `json:"Region" required:"true"`
	// 任务ID，待删除的编排任务ID，仅允许删除资源类型为编排任务且状态为Available的任务
	TaskID *string `json:"TaskID" required:"true"`
}
