// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteDBSGatewayResponse - 解绑备份网关
type DeleteDBSGatewayResponse struct {
	response.CommonBase

}
