// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteComputeClassDRSResponse - 删除计算集群DRS规则
type DeleteComputeClassDRSResponse struct {
	response.CommonBase

}
