// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteTimerResponse - 删除定时器
type DeleteTimerResponse struct {
	response.CommonBase

}
