// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteAlertTemplateRuleResponse - 删除告警模版规则
type DeleteAlertTemplateRuleResponse struct {
	response.CommonBase

}
