// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteDTSTaskResponse - 删除 DTS 任务
type DeleteDTSTaskResponse struct {
	response.CommonBase

}
