// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteTagResponse - 删除标签
type DeleteTagResponse struct {
	response.CommonBase

}
