// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeletePMV2Response - 删除裸金属
type DeletePMV2Response struct {
	response.CommonBase

}
