// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DeleteRemoteVPNGWRequest 删除对端网关
type DeleteRemoteVPNGWRequest struct {
	request.CommonBase

	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 对端网关ID，待删除的对端网关唯一标识，删除后会级联删除其下隧道
	RemoteVPNGWID *string `json:"RemoteVPNGWID" required:"true"`
}
