// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DeleteAlertNotifyReceiverRequest 删除告警通知人
type DeleteAlertNotifyReceiverRequest struct {
	request.CommonBase

	// 接收人ID，待删除的接收人ID，可通过创建或查询接收人接口获取
	NotifyReceiverID *string `json:"NotifyReceiverID" required:"true"`
}
