// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteResourceTemplateResponse - 删除资源模版
type DeleteResourceTemplateResponse struct {
	response.CommonBase

}
