// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DeleteNativeNodeRequest 删除k8s集群原生节点
type DeleteNativeNodeRequest struct {
	request.CommonBase

	// 集群Id
	ClusterID *string `json:"ClusterID" required:"true"`
	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// 节点名称
	NodeName *string `json:"NodeName" required:"true"`
	// 地域
	Region *string `json:"Region" required:"true"`
}
