// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DeleteAlertNotifyGroupResponse - 删除告警通知组
type DeleteAlertNotifyGroupResponse struct {
	response.CommonBase

}
