// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DeleteInstallProfileRequest 删除装机配置模板
type DeleteInstallProfileRequest struct {
	request.CommonBase

	// 租户ID，预留字段，当前不生效
	CompanyID *int `json:"CompanyID"`
	// 模板ID，指定要删除的模板
	ProfileID *string `json:"ProfileID" required:"true"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
}
