// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeBaseImageResponse - 获取基础镜像权限信息
type DescribeBaseImageResponse struct {
	response.CommonBase

	// 基础镜像详情列表，包含符合查询条件的镜像授权与属性信息
	Infos []models.BaseImageInfo `json:"Infos"`
	// 总记录数，返回满足查询条件的基础镜像资源总量
	TotalCount *int `json:"TotalCount"`
}
