// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeRedisConfigParamsRequest 查询配置文件详情
type DescribeRedisConfigParamsRequest struct {
	request.CommonBase

	// 配置ID，参数模板ID
	ConfigID *string `json:"ConfigID" required:"true"`
	// 分页大小，指定每页返回的记录数，默认10
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数，默认0
	Offset *int `json:"Offset"`
}
