// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeTagResourceRequest 查询标签资源
type DescribeTagResourceRequest struct {
	request.CommonBase

	// 资源ID，用于精确查询指定资源的标签绑定情况
	BindResource *string `json:"BindResource"`
	// 资源类型，用于过滤指定类型的资源，支持包括DISK、VM等多种资源类型，如果传入无效类型会返回StatusResourceTypeInvalid错误
	BindResourceType *string `json:"BindResourceType"`
	// 租户ID，用于标识资源所属的租户，实现多租户环境下的资源隔离，若不指定则根据用户权限返回可见标签资源，权限控制与DescribeTag相同：System/Region/Company级管理员分别可查所有/授权地域/租户授权地域资源，普通用户仅查项目资源（通过getSubuserResourceIDs获取）
	CompanyID *int `json:"CompanyID"`
	// 标签键名，用于过滤绑定了指定标签键的资源
	Key *string `json:"Key"`
	// 分页大小，指定每页返回的记录数，用于控制返回数据量
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数，用于实现分页查询
	Offset *int `json:"Offset"`
	// 标签值列表，用于过滤绑定了指定标签值的资源，支持多值过滤
	Values []string `json:"Values" required:"true"`
}
