// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeProductSpecificationResponse - 查询产品规格
type DescribeProductSpecificationResponse struct {
	response.CommonBase

	// 产品规格列表
	Infos []models.Specification `json:"Infos"`
	// 规格总数
	TotalCount *int `json:"TotalCount"`
}
