// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeHostPodsResponse - 获取物理机上Pod信息
type DescribeHostPodsResponse struct {
	response.CommonBase

	// Pod信息列表，返回Pod详细信息
	Infos []models.PodInfo `json:"Infos"`
	// 总记录数，返回满足查询条件的Pod总数
	TotalCount *int `json:"TotalCount"`
}
