// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeVMWareVMsResponse - 获取 vmware 虚拟机信息
type DescribeVMWareVMsResponse struct {
	response.CommonBase

	// VMWare虚拟机信息列表，返回VMware虚拟机详情
	Infos []models.VMWareVM `json:"Infos"`
	// 总记录数，返回满足查询条件的记录总数
	TotalCount *int `json:"TotalCount"`
}
