// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DescribePlatformStorageResponse - 查询平台通用存储状态
type DescribePlatformStorageResponse struct {
	response.CommonBase

	// 默认存储集群类型，平台通用存储使用的默认集群类型
	DefaultSetType *string `json:"DefaultSetType"`
	// 状态，平台通用存储的运行状态
	Status *string `json:"Status"`
	// 总量，平台通用存储总容量，单位GiB
	Total *int `json:"Total"`
	// 已使用，平台通用存储已使用容量，单位GiB
	Used *int `json:"Used"`
}
