// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeVMInstanceResponse - 获取虚拟机信息
type DescribeVMInstanceResponse struct {
	response.CommonBase

	// 虚拟机列表，包含符合查询条件的虚拟机详情
	Infos []models.VMInfo `json:"Infos"`
	// 总记录数，返回满足查询条件的资源总量
	TotalCount *int `json:"TotalCount"`
}
