// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeIsolationGroupsResponse - 获取隔离组信息
type DescribeIsolationGroupsResponse struct {
	response.CommonBase

	// 隔离组详情列表，返回的隔离组明细信息
	Infos []models.IG `json:"Infos"`
	// 总记录数，返回满足查询条件的隔离组总数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
