// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeRechargeResponse - 获取充值信息
type DescribeRechargeResponse struct {
	response.CommonBase

	// 充值信息列表，包含查询条件范围内的所有充值记录
	Infos []models.Recharge `json:"Infos"`
	// 充值记录总数量，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
