// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeAlertNotifyWebhookResponse - 获取告警回调接口
type DescribeAlertNotifyWebhookResponse struct {
	response.CommonBase

	// 详情，Webhook列表
	Infos []models.AlertNotifyWebhookInfo `json:"Infos"`
	// 总数，查询到的Webhook总数
	TotalCount *int `json:"TotalCount"`
}
