// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeFSFileRequest 获取文件存储目录文件
type DescribeFSFileRequest struct {
	request.CommonBase

	// 租户ID，资源所属租户标识
	CompanyID *int `json:"CompanyID"`
	// 文件存储实例ID，要查询的文件存储标识
	FSID *string `json:"FSID" required:"true"`
	// 文件路径，要查询的目录或文件的绝对路径
	FilePath *string `json:"FilePath" required:"true"`
	// 分页大小，指定每页返回的记录数，为0时默认10
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数
	Offset *int `json:"Offset"`
	// 地域ID，指定资源所属的地域
	Region *string `json:"Region" required:"true"`
	// 是否显示隐藏文件，true表示显示隐藏文件
	ShowHidden *bool `json:"ShowHidden"`
}
