// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeNICResponse - 查询弹性网卡信息,如果指定资源查询就是查询资源绑定的所有网卡
type DescribeNICResponse struct {
	response.CommonBase

	// 网卡信息列表，包含查询到的网卡详细信息
	Infos []models.NICInfo `json:"Infos"`
	// 总记录数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
