// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeUserRequest 获取租户列表
type DescribeUserRequest struct {
	request.CommonBase

	// 租户ID列表，请求传入用于按租户ID过滤；列表筛选场景使用；为空表示不筛选
	CompanyIDs []int `json:"CompanyIDs"`
	// 搜索关键词，请求传入用于按租户名称、邮箱或手机号匹配筛选；查询租户列表场景使用；为空表示不筛选
	Keyword *string `json:"Keyword"`
	// 分页大小，请求传入用于控制返回记录数；列表分页场景使用；Limit为0时默认10
	Limit *int `json:"Limit"`
	// 分页偏移量，请求传入用于分页起始位置；列表分页场景使用；Offset为0表示从头开始
	Offset *int `json:"Offset"`
	// 产品类型，请求传入用于筛选具备该产品能力的租户；产品能力筛选场景使用；需为合法产品类型，无效会返回参数非法或产品类型不存在
	ProductType *string `json:"ProductType"`
	// 地域ID，请求传入用于筛选租户所属区域；产品能力筛选场景使用；与ProductType同时使用时用于排除该地域已禁用租户
	Region *string `json:"Region"`
	// 用户ID列表，请求传入用于按用户ID过滤租户；列表筛选场景使用；为空表示不筛选
	UserIDs []int `json:"UserIDs"`
}
