// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeWithdrawResponse - 获取提现流水列表
type DescribeWithdrawResponse struct {
	response.CommonBase

	// 详情
	Infos []models.WithdrawTradeInfo `json:"Infos"`
	// 提现记录总数量
	TotalCount *int `json:"TotalCount"`
}
