// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeWithdrawRequest 获取提现流水列表
type DescribeWithdrawRequest struct {
	request.CommonBase

	// 查询起始时间，提现记录创建时间的起始时间戳，单位为秒，必须小于结束时间
	BeginTime *int `json:"BeginTime" required:"true"`
	// 租户ID，过滤指定租户的提现记录，不指定则查询所有租户（需系统管理员权限）
	CompanyID *int `json:"CompanyID"`
	// 查询结束时间，提现记录创建时间的结束时间戳，单位为秒，必须大于起始时间
	EndTime *int `json:"EndTime" required:"true"`
	// 分页大小，指定每页返回的提现记录数量
	Limit *int `json:"Limit"`
	// 分页偏移量，指定从第几条记录开始返回
	Offset *int `json:"Offset"`
}
