// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeLBResponse - 获取负载均衡信息
type DescribeLBResponse struct {
	response.CommonBase

	// 负载均衡详情列表
	Infos []models.LBInfo `json:"Infos"`
	// 总记录数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
