// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeTimerTaskResponse - 查询定时器执行记录
type DescribeTimerTaskResponse struct {
	response.CommonBase

	// 任务执行记录列表
	Infos []models.TaskInfo `json:"Infos"`
	// 总记录数，返回满足查询条件的任务执行记录总数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
