// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeOPLogsResponse - 获取操作日志
type DescribeOPLogsResponse struct {
	response.CommonBase

	// 操作日志详情列表，返回符合筛选条件的日志集合
	Infos []models.OPLogInfo `json:"Infos"`
	// 总记录数，匹配条件的日志数量
	TotalCount *int `json:"TotalCount"`
}
