// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DescribePMAURLResponse - 获取 PMA URL
type DescribePMAURLResponse struct {
	response.CommonBase

	// PMAURL，Web管理地址
	PMAURL *string `json:"PMAURL"`
}
