// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeContainerImageTagResponse - 查询容器镜像tags
type DescribeContainerImageTagResponse struct {
	response.CommonBase

	// 详情，镜像标签信息列表
	Infos []models.ContainerImageTagInfo `json:"Infos"`
	// 总数，查询到的标签总数
	TotalCount *int `json:"TotalCount"`
}
