// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeTrafficMirrorResponse - 查询流量镜像
type DescribeTrafficMirrorResponse struct {
	response.CommonBase

	// 流量镜像信息列表，包含流量镜像的详细信息
	Infos []models.TrafficMirrorInfo `json:"Infos"`
	// 流量镜像总数，符合查询条件的记录总数
	TotalCount *int `json:"TotalCount"`
}
