// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeStorageSetResponse - 查询存储集群信息
type DescribeStorageSetResponse struct {
	response.CommonBase

	// 存储集群信息列表，包含存储集群的详细信息，如容量、使用量、冗余策略、绑定的计算集群等
	Infos []models.StorageSetInfo `json:"Infos"`
	// 存储集群总数，返回符合查询条件的存储集群总数量
	TotalCount *int `json:"TotalCount"`
}
