// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeComputeClassDRSScoreRequest 查看计算集群DRS评分
type DescribeComputeClassDRSScoreRequest struct {
	request.CommonBase

	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// 地域ID
	Region *string `json:"Region" required:"true"`
	// 计算集群ID
	SetID *string `json:"SetID" required:"true"`
}
