// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeMySQLConfigParamResponse - 获取MySQL配置参数
type DescribeMySQLConfigParamResponse struct {
	response.CommonBase

	// 参数信息，配置参数信息列表
	Infos []models.MySQLConfigParamInfo `json:"Infos"`
	// 总数，查询得到的记录总数
	TotalCount *int `json:"TotalCount"`
}
