// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeLBRequest 获取负载均衡信息
type DescribeLBRequest struct {
	request.CommonBase

	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 关键词，用于搜索负载均衡实例
	Keyword *string `json:"Keyword"`
	// 负载均衡ID列表，用于筛选指定负载均衡实例
	LBIDs []string `json:"LBIDs"`
	// 分页大小，指定每页返回的记录数
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数
	Offset *int `json:"Offset"`
	// 项目ID列表，用于过滤指定项目的负载均衡
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 负载均衡状态，用于筛选指定状态的负载均衡实例
	Status []string `json:"Status"`
	// 子网ID，用于筛选指定子网内的负载均衡
	SubnetID *string `json:"SubnetID"`
	// VPCID，用于筛选指定VPC内的负载均衡
	VPCID *string `json:"VPCID"`
}
