// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeVPNGWResponse - 获取网关信息
type DescribeVPNGWResponse struct {
	response.CommonBase

	// VPN网关详情列表，用于展示VPN网关信息
	Infos []models.VPNGWInfo `json:"Infos"`
	// 总记录数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
