// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeTransactionRequest 获取交易记录
type DescribeTransactionRequest struct {
	request.CommonBase

	// 查询起始时间，Unix秒时间戳，必须早于EndTime
	BeginTime *int `json:"BeginTime" required:"true"`
	// 查询结束时间，Unix秒时间戳，必须大于BeginTime
	EndTime *int `json:"EndTime" required:"true"`
	// 分页大小，指定每页返回的交易记录数量
	Limit *int `json:"Limit"`
	// 分页偏移量，指定从第几条记录开始返回
	Offset *int `json:"Offset"`
	// 项目组ID列表，保留字段，当前接口不会根据项目过滤
	ProjectIDs []string `json:"ProjectIDs" required:"true"`
	// 地域ID，指定交易所属地域；传入all或空字符串会查询所有地域（充值/提现类交易本身无地域概念）
	Region *string `json:"Region"`
	// 交易类型，取值：CHARGE/RECHARGE/REFUND/WITHDRAW/FREE_RECHARGE/FREE_WITHDRAW，不填写则返回所有交易类型
	TransactionType *string `json:"TransactionType"`
	// 用户账号ID（即CompanyID），交易查询依据的唯一租户标识
	UserAccountID *int `json:"UserAccountID"`
}
