// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeAlertNotifyReceiverResponse - 获取告警通知人
type DescribeAlertNotifyReceiverResponse struct {
	response.CommonBase

	// 接收人详细信息列表，接收人列表
	Infos []models.AlertNotifyReceiverInfo `json:"Infos"`
	// 接收人总数，满足查询条件的接收人总数
	TotalCount *int `json:"TotalCount"`
}
