// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeRedisSlowlogResponse - 慢日志查询
type DescribeRedisSlowlogResponse struct {
	response.CommonBase

	// 慢日志信息，慢日志记录列表
	Infos []models.RedisSlowlog `json:"Infos"`
	// 总数，查询得到的记录总数
	TotalCount *int `json:"TotalCount"`
}
