// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeDOSTokenRequest 获取令牌列表
type DescribeDOSTokenRequest struct {
	request.CommonBase

	// 租户ID，用于标识令牌所属的租户上下文；公司级账号需填写自身CompanyID，系统/地域管理员可不填或指定目标租户
	CompanyID *string `json:"CompanyID"`
	// 分页大小，指定每页返回的记录数，为0时默认10
	Limit *int `json:"Limit"`
	// OSSID，对象存储实例标识
	OSSID *string `json:"OSSID" required:"true"`
	// 分页偏移量，指定跳过的记录数
	Offset *int `json:"Offset"`
	// 地域ID，指定资源所属的地域
	Region *string `json:"Region" required:"true"`
}
