// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeDataCheckTaskResponse - 获取数据校验任务列表
type DescribeDataCheckTaskResponse struct {
	response.CommonBase

	// 数据校验任务信息列表，用于展示校验任务概览
	Infos []models.DataCheckTaskOverview `json:"Infos"`
	// 总记录数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
