// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeDBSGatewayResponse - 获取DBS网关
type DescribeDBSGatewayResponse struct {
	response.CommonBase

	// DBS网关信息，DBS网关列表
	Infos []models.DBSGateway `json:"Infos"`
	// 总数，查询得到的总数
	TotalCount *int `json:"TotalCount"`
}
