// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeEIPResponse - 获取弹性IP
type DescribeEIPResponse struct {
	response.CommonBase

	// EIP信息列表，包含普通EIP、弹性网卡EIP和外网VIP的信息
	Infos []models.EIPInfo `json:"Infos"`
	// 总记录数，返回满足查询条件的EIP总数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
