// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeMySQLSlowLogRecordsRequest 查询 MySQL 慢日志记录
type DescribeMySQLSlowLogRecordsRequest struct {
	request.CommonBase

	// 开始时间，查询慢日志的开始时间（Unix秒级时间戳）
	BeginTime *int `json:"BeginTime" required:"true"`
	// 结束时间，查询慢日志的结束时间（Unix秒级时间戳）
	EndTime *int `json:"EndTime" required:"true"`
	// 分页大小，指定每页返回的记录数，默认10
	Limit *int `json:"Limit"`
	// MySQL实例ID，指定要查询慢日志的MySQL实例；注意：资源必须为AVAILABLE状态且为工作状态，只查询Ready状态的VM
	MySQLID *string `json:"MySQLID" required:"true"`
	// 分页偏移量，指定跳过的记录数，默认0
	Offset *int `json:"Offset"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
}
