// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeComputeClassVMsAddToDRSRuleRequest 查看可加入计算集群规则的虚拟机
type DescribeComputeClassVMsAddToDRSRuleRequest struct {
	request.CommonBase

	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// 关键词，可按虚拟机ID或名称模糊过滤结果
	Keyword *string `json:"Keyword"`
	// 分页大小，默认10
	Limit *int `json:"Limit"`
	// 分页偏移量，默认0
	Offset *int `json:"Offset"`
	// 地域ID
	Region *string `json:"Region" required:"true"`
	// 计算集群ID，指定要查询候选虚拟机的ComputeClass
	SetID *string `json:"SetID" required:"true"`
}
