// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeSecurityGroupResourceResponse - 获取安全组关联资源
type DescribeSecurityGroupResourceResponse struct {
	response.CommonBase

	// 绑定资源详情列表，包含资源类型、ID、名称、网卡类型等信息
	Infos []models.SGResourceInfo `json:"Infos"`
	// 总记录数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
