// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeSubnetResponse - 获取子网
type DescribeSubnetResponse struct {
	response.CommonBase

	// 子网信息
	Infos []models.SubnetInfo `json:"Infos"`
	// 总记录数，返回满足查询条件的子网总数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
