// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeDirectConnectResponse - 查询DirectConnect专线接入
type DescribeDirectConnectResponse struct {
	response.CommonBase

	// 专线接入的信息详情
	Infos []models.DirectConnectDetailInfo `json:"Infos"`
	// 查询得到的总数
	TotalCount *int `json:"TotalCount"`
}
