// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeDTSTaskResponse - 获取传输任务列表
type DescribeDTSTaskResponse struct {
	response.CommonBase

	// DTS任务信息列表，用于展示DTS任务详情
	Infos []models.DTSTaskInfo `json:"Infos"`
	// 总记录数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
