// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeSubnetRequest 获取子网
type DescribeSubnetRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// 搜索关键词，用于按名称或备注模糊查询
	Keyword *string `json:"Keyword"`
	// 分页大小，用于限制单次返回条数
	Limit *int `json:"Limit"`
	// 分页偏移量，用于指定返回结果起始位置
	Offset *int `json:"Offset"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 子网ID列表，用于查询指定的子网
	SubnetIDs []string `json:"SubnetIDs"`
	// VPCID，用于筛选指定VPC下的子网
	VPCID *string `json:"VPCID"`
}
