// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeTrafficMirrorSourcesRequest 查询流量镜像源设备信息
type DescribeTrafficMirrorSourcesRequest struct {
	request.CommonBase

	// 关键字，用于搜索虚拟机名称或ID
	Keyword *string `json:"Keyword"`
	// 分页大小，指定每页返回的记录数
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数
	Offset *int `json:"Offset"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
}
