// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeVMHostResponse - 获取虚拟机物理机信息
type DescribeVMHostResponse struct {
	response.CommonBase

	// 物理机信息列表，返回物理宿主机详细信息
	Infos []models.HostInfo `json:"Infos"`
	// 总记录数，返回满足查询条件的物理机总数
	TotalCount *int `json:"TotalCount"`
}
