// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeIPGroupResponse - 查询IP组
type DescribeIPGroupResponse struct {
	response.CommonBase

	// IP组详情列表，包含IP规则与使用的安全组等信息
	Infos []models.IPGroupInfo `json:"Infos"`
	// 总记录数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
