// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribePortGroupRequest 查询端口组
type DescribePortGroupRequest struct {
	request.CommonBase

	// 租户ID，指定查询范围内的租户组织，若不指定则返回当前租户的端口组
	CompanyID *int `json:"CompanyID"`
	// 关键词，用于模糊搜索端口组名称等字段
	Keyword *string `json:"Keyword"`
	// 分页大小，指定每页返回的记录数
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数
	Offset *int `json:"Offset"`
	// 端口组ID列表，用于精确查询指定的端口组
	PortGroupIDs []string `json:"PortGroupIDs"`
	// 项目ID列表，用于按项目筛选端口组
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域ID，用于标识端口组所属的地理区域
	Region *string `json:"Region" required:"true"`
}
