// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DescribeStorageSetSortPolicyResponse - 获取存储集群排序策略
type DescribeStorageSetSortPolicyResponse struct {
	response.CommonBase

	// 排序策略，当前配置的存储集群排序策略，值为default、available、ssd、hdd或defined之一
	Policy *string `json:"Policy"`
	// 自定义集群ID列表，当Policy为defined时返回，表示存储集群的优先级顺序
	SetIDs []string `json:"SetIDs"`
}
