// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeAuditLogResponse - 获取审计日志
type DescribeAuditLogResponse struct {
	response.CommonBase

	// 审计日志事件，从资源注解hhpaas.AK_AUDIT_EVENTS中读取的当前配置
	AuditEvents *string `json:"AuditEvents"`
	// 审计日志列表，包含所有匹配的审计日志详细信息，按执行时间倒序排列
	Infos []models.AuditLogInfos `json:"Infos"`
	// 总数，成功解析且未被IgnoreQuery过滤的审计日志条目数
	TotalCount *int `json:"TotalCount"`
}
