// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeImageOSVersionsResponse - 查询镜像系统规格
type DescribeImageOSVersionsResponse struct {
	response.CommonBase

	// 操作系统详情列表，包含支持的发行版、版本、架构等枚举信息
	Infos []models.ImageOSInfo `json:"Infos"`
	// 总记录数，返回当前平台支持的所有操作系统版本总量
	TotalCount *int `json:"TotalCount"`
}
