// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeVMCResponse - 获取 VMC 资源信息
type DescribeVMCResponse struct {
	response.CommonBase

	// VMC任务列表，包含满足条件的克隆任务详情
	Infos []models.VMCInfo `json:"Infos"`
	// 总记录数，返回满足查询条件的记录总数
	TotalCount *int `json:"TotalCount"`
}
