// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeQuotaUsageResponse - 查询配额资源用量列表
type DescribeQuotaUsageResponse struct {
	response.CommonBase

	// 配额使用情况列表
	Infos []models.QuotaUsage `json:"Infos"`
	// 配额使用情况总数
	TotalCount *int `json:"TotalCount"`
}
