// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeProductRequest 获取产品类型
type DescribeProductRequest struct {
	request.CommonBase

	// 产品类型列表，用于筛选指定产品
	ProductTypes []string `json:"ProductTypes"`
	// 地域ID，用于限定查询范围；为空表示查询全部地域
	Region *string `json:"Region"`
}
