// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeASGroupResponse - 查询伸缩组
type DescribeASGroupResponse struct {
	response.CommonBase

	// 伸缩组详情列表，符合查询条件的伸缩组信息
	Infos []models.ASGroupInfo `json:"Infos"`
	// 总记录数，符合查询条件的伸缩组总数
	TotalCount *int `json:"TotalCount"`
}
