// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeSetAllocateUsageResponse - 查询集群资源用量列表
type DescribeSetAllocateUsageResponse struct {
	response.CommonBase

	// 内存使用情况列表
	MemoryUsageInfos []models.MemoryUsageInfo `json:"MemoryUsageInfos"`
	// 存储使用情况列表
	StorageUsageInfos []models.StorageUsageInfo `json:"StorageUsageInfos"`
	// vCPU使用情况列表
	VCPUUsageInfos []models.VCPUUsageInfo `json:"VCPUUsageInfos"`
}
