// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeSecurityGroupRuleResponse - 获取安全组规则
type DescribeSecurityGroupRuleResponse struct {
	response.CommonBase

	// 安全组规则详情列表，包含符合查询条件的所有规则的详细信息
	Infos []models.SGRuleInfo `json:"Infos"`
	// 总记录数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
