// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeMySQLParamTplsResponse - 查询MySQL参数模板列表
type DescribeMySQLParamTplsResponse struct {
	response.CommonBase

	// 模板信息，参数模板信息列表
	Infos []models.MySQLParamTplInfo `json:"Infos"`
	// 总数，查询得到的记录总数
	TotalCount *int `json:"TotalCount"`
}
