// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeRedisResponse - 查询redis实例
type DescribeRedisResponse struct {
	response.CommonBase

	// Redis信息，实例信息列表
	Infos []models.RedisInfo `json:"Infos"`
	// 总数，查询得到的记录总数
	TotalCount *int `json:"TotalCount"`
}
