// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeVMTypeResponse - 查询主机机型
type DescribeVMTypeResponse struct {
	response.CommonBase

	// 计算集群类型信息列表，包含计算集群类型的详细信息，如类型名称、别名、架构、权限等
	Infos []models.SetTypeInfo `json:"Infos"`
	// 计算集群类型总数，返回符合权限的计算集群类型总数量
	TotalCount *int `json:"TotalCount"`
}
