// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeOrchTaskTypeResponse - 查询支持的编排任务
type DescribeOrchTaskTypeResponse struct {
	response.CommonBase

	// 详情，任务类型列表
	Infos []models.TaskTypeInfo `json:"Infos"`
	// 总数，任务类型总数
	TotalCount *int `json:"TotalCount"`
}
