// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeResourceChartResponse - 获取资源用量图表
type DescribeResourceChartResponse struct {
	response.CommonBase

	// 图表内容列表，包含各类资源用量的图表数据
	Infos []models.ChartInfo `json:"Infos"`
}
