// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeFSRequest 获取文件存储列表
type DescribeFSRequest struct {
	request.CommonBase

	// 租户ID，资源所属租户标识
	CompanyID *int `json:"CompanyID"`
	// 文件存储实例ID列表，用于查询指定文件存储信息
	FSIDs []string `json:"FSIDs"`
	// 搜索关键词，用于模糊匹配文件存储名称或备注
	Keyword *string `json:"Keyword"`
	// 分页大小，指定每页返回的记录数，为0时默认10
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数
	Offset *int `json:"Offset"`
	// 项目组ID列表，用于筛选指定项目组下的文件存储资源
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域ID，指定资源所属的地域
	Region *string `json:"Region" required:"true"`
	// 文件存储状态列表，用于筛选指定状态的文件存储资源
	Status []string `json:"Status"`
}
