// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeVPNTunnelResponse - 获取隧道信息
type DescribeVPNTunnelResponse struct {
	response.CommonBase

	// VPN隧道详情列表，用于展示VPN隧道信息
	Infos []models.VPNTunnelInfo `json:"Infos"`
	// 总记录数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
