// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeResourceEventNotifyRuleRequest 获取资源事件通知规则
type DescribeResourceEventNotifyRuleRequest struct {
	request.CommonBase

	// 租户ID，过滤指定租户的资源事件通知规则
	CompanyID *int `json:"CompanyID"`
	// 搜索关键字，按规则名称模糊搜索
	Keyword *string `json:"Keyword"`
	// 分页大小，指定每页返回的记录数，Limit为0时默认10
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数
	Offset *int `json:"Offset"`
}
