// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeStorageTypeResponse - 查询存储类型
type DescribeStorageTypeResponse struct {
	response.CommonBase

	// 存储类型信息列表，包含存储集群类型的详细信息，如类型名称、别名、架构、权限等
	Infos []models.StorageSetTypeInfo `json:"Infos"`
	// 存储类型总数，返回符合权限的存储集群类型总数量
	TotalCount *int `json:"TotalCount"`
}
