// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeFSFileResponse - 获取文件存储目录文件
type DescribeFSFileResponse struct {
	response.CommonBase

	// 文件信息列表，返回目录下的文件与子目录
	Infos []models.FileInfo `json:"Infos"`
	// 总记录数，符合条件的文件数量
	TotalCount *int `json:"TotalCount"`
}
