// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeExternalDiskResponse - 查询外置存储集群硬盘
type DescribeExternalDiskResponse struct {
	response.CommonBase

	// 
	Infos []models.ExternalDiskInfo `json:"Infos"`
	// 
	TotalCount *int `json:"TotalCount"`
}
