// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeHostPodsRequest 获取物理机上Pod信息
type DescribeHostPodsRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// 物理机ID，用于筛选指定物理机上的Pod
	HostID *string `json:"HostID"`
	// 关键词，用于模糊匹配Pod名称或IP
	Keyword *string `json:"Keyword"`
	// 分页大小，用于限制单次返回条数
	Limit *int `json:"Limit"`
	// 分页偏移量，用于指定返回结果起始位置
	Offset *int `json:"Offset"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 计算集群ID，用于筛选指定集群上的Pod
	SetID *string `json:"SetID"`
}
