// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeRegionResponse - 获取租户已授权地域
type DescribeRegionResponse struct {
	response.CommonBase

	// 地域详细信息列表，查询结果返回地域基础信息与资源统计
	Infos []models.RegionInfo `json:"Infos"`
	// 地域总数，当前账号可访问的地域数量
	TotalCount *int `json:"TotalCount"`
}
