// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeAlertNotifyGroupResponse - 获取告警通知组
type DescribeAlertNotifyGroupResponse struct {
	response.CommonBase

	// 通知组详细信息列表，通知组列表
	Infos []models.AlertNotifyGroupInfo `json:"Infos"`
	// 通知组总数，满足查询条件的通知组总数
	TotalCount *int `json:"TotalCount"`
}
