// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeSecurityGroupResponse - 获取安全组
type DescribeSecurityGroupResponse struct {
	response.CommonBase

	// 安全组详情列表，包含规则与绑定资源数量等信息
	Infos []models.SGDetailInfo `json:"Infos"`
	// 总记录数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
