// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeNATGWRuleRequest 获取NAT网关规则
type DescribeNATGWRuleRequest struct {
	request.CommonBase

	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 搜索关键词，用于按规则关键字模糊搜索SNAT规则
	Keyword *string `json:"Keyword"`
	// 分页大小，指定每页返回的记录数，用于控制返回数据量
	Limit *int `json:"Limit"`
	// NAT网关ID，用于筛选指定NAT网关的SNAT规则
	NATGWID *string `json:"NATGWID"`
	// 分页偏移量，指定跳过的记录数，用于实现分页查询
	Offset *int `json:"Offset"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// SNAT规则ID列表，用于筛选指定SNAT规则
	RuleIDs []string `json:"RuleIDs"`
}
