// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeLoginWhitelistRequest 获取用户登录IP白名单
type DescribeLoginWhitelistRequest struct {
	request.CommonBase

	// 租户ID，请求传入用于查询登录白名单所属租户
	CompanyID *int `json:"CompanyID" required:"true"`
}
