// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeDBSRestoreRangeInfoResponse - 查看可恢复时间段详情
type DescribeDBSRestoreRangeInfoResponse struct {
	response.CommonBase

	// 最早可恢复时间，最早可恢复时间戳
	BeginTimestamp *int `json:"BeginTimestamp"`
	// 最晚可恢复时间，最晚可恢复时间戳
	EndTimestamp *int `json:"EndTimestamp"`
	// 恢复时间信息，恢复时间范围列表
	RestoreRangeInfos []models.RestoreRangeInfo `json:"RestoreRangeInfos"`
	// 备份源ID，备份源资源ID
	SourceInstanceID *string `json:"SourceInstanceID"`
}
