// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeTenantResourcesRequest 获取租户资源
type DescribeTenantResourcesRequest struct {
	request.CommonBase

	// 租户ID，请求传入并指定要查询资源的租户；租户资源查询场景使用
	CompanyID *int `json:"CompanyID" required:"true"`
	// 分页大小，请求传入用于控制返回记录数；列表分页场景使用；Limit为0时默认10
	Limit *int `json:"Limit"`
	// 分页偏移量，请求传入用于分页起始位置；列表分页场景使用；Offset为0表示从头开始
	Offset *int `json:"Offset"`
	// 地域ID，请求传入并指定资源所属物理区域；租户资源查询场景使用
	Region *string `json:"Region" required:"true"`
}
