// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeNodeResponse - 获取物理机节点信息
type DescribeNodeResponse struct {
	response.CommonBase

	// 节点信息列表，返回节点详细信息
	Infos []models.NodeInfo `json:"Infos"`
	// 总记录数，返回满足查询条件的节点总数
	TotalCount *int `json:"TotalCount"`
}
