// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeVPCRequest 获取VPC信息
type DescribeVPCRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// 搜索关键词，用于按名称或备注模糊查询
	Keyword *string `json:"Keyword"`
	// 分页大小，用于限制单次返回条数
	Limit *int `json:"Limit"`
	// 分页偏移量，用于指定返回结果起始位置
	Offset *int `json:"Offset"`
	// 对端ID，用于筛选包含指定对等连接的VPC
	PeerID *string `json:"PeerID"`
	// 项目ID列表，用于按项目维度筛选资源
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// VPC状态列表，用于按多个状态过滤VPC，支持前端按Status.0、Status.1等形式传参
	Status []string `json:"Status"`
	// VPCID列表，用于查询指定的虚拟私有网络
	VPCIDs []string `json:"VPCIDs"`
}
