// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeNATGWRuleResponse - 获取NAT网关规则
type DescribeNATGWRuleResponse struct {
	response.CommonBase

	// SNAT规则详情列表
	Infos []models.NATGWRuleInfo `json:"Infos"`
	// 总记录数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
