// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeNATGWPolicyResponse - 查询端口转发
type DescribeNATGWPolicyResponse struct {
	response.CommonBase

	// DNAT规则详情列表
	Infos []models.NATGWPolicyInfo `json:"Infos"`
	// 总记录数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
