// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribePlatformStorageRequest 查询平台通用存储状态
type DescribePlatformStorageRequest struct {
	request.CommonBase

	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
}
