// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeSecurityGroupResourceRequest 获取安全组关联资源
type DescribeSecurityGroupResourceRequest struct {
	request.CommonBase

	// 返回粒度，Resource 表示按资源聚合（默认，兼容旧行为），NIC 表示按网卡粒度返回；仅对存在网卡概念的资源生效
	GroupBy *string `json:"GroupBy"`
	// 分页大小，指定每页返回的记录数
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数
	Offset *int `json:"Offset"`
	// 地域ID，用于标识安全组所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 安全组ID，指定要查询绑定资源的安全组唯一标识符
	SGID *string `json:"SGID" required:"true"`
}
