// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeSubnetRouteResponse - 查询子网路由
type DescribeSubnetRouteResponse struct {
	response.CommonBase

	// 子网路由信息
	Infos []models.SubnetRouteInfo `json:"Infos"`
	// 总记录数，返回满足查询条件的子网路由总数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
