// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeFlatNetworkRouteResponse - 查询扁平网络路由
type DescribeFlatNetworkRouteResponse struct {
	response.CommonBase

	// 路由列表，返回的路由详细信息
	Infos []models.FlatNetworkRoute `json:"Infos"`
	// 总记录数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
