// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeExternalStorageTypeRequest 查询外置存储集群类型
type DescribeExternalStorageTypeRequest struct {
	request.CommonBase

	// 租户ID，权限上下文
	CompanyID *int `json:"CompanyID"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
}
