// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeNetworkTopologyRequest 获取网络拓扑信息
type DescribeNetworkTopologyRequest struct {
	request.CommonBase

	// 租户ID，指定要查询网络拓扑的租户，若不指定则查询所有租户
	CompanyID *int `json:"CompanyID"`
	// 专线ID列表，已弃用，参数无效
	DirectConnectIDs []string `json:"DirectConnectIDs"`
	// 扁平网络ID列表，指定要查询的扁平网络范围
	FlatNetworkIDs []string `json:"FlatNetworkIDs"`
	// 分页大小，指定每页返回的记录数，若不指定则默认为10
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数
	Offset *int `json:"Offset"`
	// 项目组ID列表，指定要查询网络拓扑的项目组范围，ProjectID 采用 project- 前缀加14位随机字符格式
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域ID，指定要查询网络拓扑的地域
	Region *string `json:"Region" required:"true"`
	// 资源ID列表，指定要查询网络拓扑的资源范围，每个ResourceID格式为类型前缀-14位随机字符
	ResourceIDs []string `json:"ResourceIDs"`
	// 资源类型列表，指定要查询网络拓扑的资源类型
	ResourceTypes []string `json:"ResourceTypes"`
	// 外网线路ID列表，指定要查询的外网线路范围
	SegmentIDs []string `json:"SegmentIDs"`
	// 子网ID列表，指定要查询的子网范围
	SubnetIDs []string `json:"SubnetIDs"`
	// 子网查询情况下的IP协议版本，支持IPv4或IPv6，若不指定则查询所有协议
	SubnetIPVersion *string `json:"SubnetIPVersion"`
}
