// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeTransactionResponse - 获取交易记录
type DescribeTransactionResponse struct {
	response.CommonBase

	// 交易信息列表，包含查询条件范围内的所有交易记录
	Infos []models.Transaction `json:"Infos"`
	// 交易记录总数量，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
