// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeMySQLRequest 查询MySQL信息
type DescribeMySQLRequest struct {
	request.CommonBase

	// 租户唯一标识ID，用于过滤指定租户的资源，实现多租户环境下的资源隔离，若不指定则查询当前用户有权限访问的所有租户的资源
	CompanyID *int `json:"CompanyID"`
	// 搜索关键词，用于模糊搜索MySQL实例名称或ID
	Keyword *string `json:"Keyword"`
	// 分页大小，指定每页返回的记录数
	Limit *int `json:"Limit"`
	// MySQL实例ID列表，用于查询指定的MySQL实例，若同时提供Keyword，则取两者的交集
	MySQLIDs []string `json:"MySQLIDs"`
	// 分页偏移量，指定跳过的记录数，用于实现分页查询
	Offset *int `json:"Offset"`
	// 项目ID列表，用于按项目过滤资源，支持多项目查询
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
	// MySQL状态列表，用于按状态过滤实例，可选值包括：Running（运行中）、Stopped（已停止）、Creating（创建中）等
	Status []string `json:"Status"`
}
