// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeDBSBackupRequest 获取备份
type DescribeDBSBackupRequest struct {
	request.CommonBase

	// 备份ID列表，筛选指定备份
	BackupIDs []string `json:"BackupIDs"`
	// 备份类型，取值Logical/Physical/Snapshot/Incremental
	BackupType *string `json:"BackupType"`
	// 租户ID，用于筛选指定租户的备份
	CompanyID *int `json:"CompanyID"`
	// 分页大小，指定每页返回的记录数，默认10
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数，默认0
	Offset *int `json:"Offset"`
	// 计划ID，筛选指定备份计划
	PlanID *string `json:"PlanID"`
	// 源资源ID，备份源资源ID
	SrcResourceID *string `json:"SrcResourceID"`
	// 源数据地域，备份源资源所属地域
	SrcResourceRegion *string `json:"SrcResourceRegion"`
	// 存储池ID，筛选指定存储池
	StorageID *string `json:"StorageID"`
}
