// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeResourceTemplateRequest 查询资源模板
type DescribeResourceTemplateRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// 查询关键字，用于模糊搜索模板名称或备注
	Keyword *string `json:"Keyword"`
	// 分页大小，用于限制单次返回条数
	Limit *int `json:"Limit"`
	// 分页偏移量，用于指定返回结果起始位置
	Offset *int `json:"Offset"`
	// 项目ID列表，用于筛选指定项目下的模板
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域ID，用于筛选模板所属地域
	Region *string `json:"Region"`
	// 模板ID列表，用于精确查询指定的模板
	TemplateIDs []string `json:"TemplateIDs"`
}
