// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeNATGWResponse - 获取NAT网关
type DescribeNATGWResponse struct {
	response.CommonBase

	// NAT网关详情列表
	Infos []models.NATGWInfo `json:"Infos"`
	// 总记录数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
