// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeAlertNotifyReceiverRequest 获取告警通知人
type DescribeAlertNotifyReceiverRequest struct {
	request.CommonBase

	// 分页大小，指定每页返回的记录数，取值范围1-100，Limit为0时默认10，结果按创建时间倒序返回
	Limit *int `json:"Limit"`
	// 通知组ID，查询指定通知组下的接收人，若指定则查询该组的所有接收人
	NotifyGroupID *string `json:"NotifyGroupID" required:"true"`
	// 分页偏移量，指定跳过的记录数，与Limit配合遍历所有接收人
	Offset *int `json:"Offset"`
}
