// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeSecurityGroupRequest 获取安全组
type DescribeSecurityGroupRequest struct {
	request.CommonBase

	// 租户ID，指定查询范围内的租户组织，若不指定则返回当前租户的安全组
	CompanyID *int `json:"CompanyID"`
	// 关键词，用于模糊搜索安全组名称等字段
	Keyword *string `json:"Keyword"`
	// 分页大小，指定每页返回的记录数
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数
	Offset *int `json:"Offset"`
	// 项目ID列表，用于按项目筛选安全组
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域ID，用于标识安全组所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 安全组ID列表，用于精确查询指定的安全组
	SGIDs []string `json:"SGIDs"`
	// 安全组状态列表，用于按多个状态过滤安全组，支持前端按Status.0、Status.1等形式传参
	Status []string `json:"Status"`
}
