// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeFlatNetworkRouteRequest 查询扁平网络路由
type DescribeFlatNetworkRouteRequest struct {
	request.CommonBase

	// 扁平网络ID，指定要查询路由的扁平网络唯一标识
	FlatNetworkID *string `json:"FlatNetworkID" required:"true"`
	// 分页大小，指定每页返回的记录数
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数
	Offset *int `json:"Offset"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
