// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeMulticastGroupResponse - 获取组播组列表
type DescribeMulticastGroupResponse struct {
	response.CommonBase

	// 组播组详细信息列表，融合资源中心与黄河Networking的配置数据（如VPC名称、网段、源/目的成员）
	Infos []models.MulticastGroupInfo `json:"Infos"`
	// 总记录数，满足查询条件的组播组总数量
	TotalCount *int `json:"TotalCount"`
}
