// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeClusterResponse - 查询k8s集群
type DescribeClusterResponse struct {
	response.CommonBase

	// 详情
	Infos []models.ClusterInfo `json:"Infos"`
	// 总数
	TotalCount *int `json:"TotalCount"`
}
