// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeOrderResponse - 获取订单信息
type DescribeOrderResponse struct {
	response.CommonBase

	// 返回开始时间到结束时间租户所有的订单信息列表
	Infos []models.Order `json:"Infos"`
	// 返回开始时间到结束时间租户所有的订单数量
	TotalCount *int `json:"TotalCount"`
}
