// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeNativeNodeRequest 查询k8s集群原生节点
type DescribeNativeNodeRequest struct {
	request.CommonBase

	// 集群Id
	ClusterID *string `json:"ClusterID" required:"true"`
	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// 
	Limit *int `json:"Limit"`
	// 节点名称列表
	NodeNames []string `json:"NodeNames"`
	// 
	Offset *int `json:"Offset"`
	// 地域
	Region *string `json:"Region" required:"true"`
}
