// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeComputeClassVMsAddToDRSRuleResponse - 查看可加入计算集群规则的虚拟机
type DescribeComputeClassVMsAddToDRSRuleResponse struct {
	response.CommonBase

	// 候选虚拟机列表
	Infos []models.DRSRuleVMInfo `json:"Infos"`
	// 总数
	TotalCount *int `json:"TotalCount"`
}
