// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeBucketsResponse - 桶列表
type DescribeBucketsResponse struct {
	response.CommonBase

	// 桶信息列表，查询到的桶信息
	Infos []models.BucketInfo `json:"Infos"`
	// 总记录数，符合条件的桶数量
	TotalCount *int `json:"TotalCount"`
}
