// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeStorageSetSortPolicyRequest 获取存储集群排序策略
type DescribeStorageSetSortPolicyRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，普通租户需填写自身CompanyID；管理员租户（CompanyID=200000231）或留空时按管理员权限查询
	CompanyID *int `json:"CompanyID"`
	// 地域ID，指定存储集群所属的物理区域
	Region *string `json:"Region" required:"true"`
}
