// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeMySQLErrorLogsResponse - 查询 MySQL 错误日志
type DescribeMySQLErrorLogsResponse struct {
	response.CommonBase

	// 错误日志信息，错误日志记录列表
	Infos []models.ErrorLogInfo `json:"Infos"`
	// 总数，查询得到的记录总数
	TotalCount *int `json:"TotalCount"`
}
