// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeComputeClassDRSResponse - 查看计算集群DRS规则
type DescribeComputeClassDRSResponse struct {
	response.CommonBase

	// drs列表
	Infos []models.DRS `json:"Infos"`
	// 总数
	TotalCount *int `json:"TotalCount"`
}
