// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeRecycledResourceResponse - 获取回收站资源
type DescribeRecycledResourceResponse struct {
	response.CommonBase

	// 回收资源信息，回收站资源列表
	Infos []models.RecycleResourceInfo `json:"Infos"`
	// 总回收资源数量，满足条件的回收资源总数
	TotalCount *int `json:"TotalCount"`
}
