// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// DescribeAlertResponse - 查询告警
type DescribeAlertResponse struct {
	response.CommonBase

	// 告警详细信息列表，告警列表，包含系统告警和自定义告警
	Infos []models.AlertInfo `json:"Infos"`
	// 告警总数，满足查询条件的告警总数
	TotalCount *int `json:"TotalCount"`
}
