// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeAlertTemplateResponse - 获取告警模版
type DescribeAlertTemplateResponse struct {
	response.CommonBase

	// 告警模板详细信息列表，告警模板列表，包含模板的完整配置信息
	Infos []models.AlertTemplateInfo `json:"Infos"`
	// 告警模板总数，满足查询条件的告警模板总数
	TotalCount *int `json:"TotalCount"`
}
