// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeBillDetailResponse - 获取账单详情
type DescribeBillDetailResponse struct {
	response.CommonBase

	// 详情，账单详情信息列表
	Infos []models.BillDetailInfo `json:"Infos"`
	// 总数量，符合条件的记录总数
	TotalCount *int `json:"TotalCount"`
}
