// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeSegmentRouteResponse - 查询外网线路路由
type DescribeSegmentRouteResponse struct {
	response.CommonBase

	// 外网线路路由详情信息
	Infos []models.SegmentRouteInfo `json:"Infos"`
	// 查询得到的总数
	TotalCount *int `json:"TotalCount"`
}
