// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeRedisRequest 查询redis实例
type DescribeRedisRequest struct {
	request.CommonBase

	// 租户ID，用于标识资源所属的租户，实现多租户环境下的资源隔离
	CompanyID *int `json:"CompanyID"`
	// 搜索关键字，用于模糊搜索实例名称或ID
	Keyword *string `json:"Keyword"`
	// 分页数量，分页查询的每页数量
	Limit *int `json:"Limit"`
	// 分页偏移量，分页查询的偏移量
	Offset *int `json:"Offset"`
	// 项目组ID，用于资源分组管理
	ProjectIDs []string `json:"ProjectIDs"`
	// Redis实例ID，筛选指定实例的ID列表
	RedisIDs []string `json:"RedisIDs"`
	// 地域ID，地域，一批可共享的物理资源使用集合
	Region *string `json:"Region" required:"true"`
	// Redis状态，用于按状态过滤实例
	Status []string `json:"Status"`
}
