// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeDBSBackupResponse - 获取备份
type DescribeDBSBackupResponse struct {
	response.CommonBase

	// 备份列表，备份信息列表
	Infos []models.DBSBackupInfo `json:"Infos"`
	// 总数，查询得到的记录总数
	TotalCount *int `json:"TotalCount"`
}
