// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeCertificateRequest 查询证书
type DescribeCertificateRequest struct {
	request.CommonBase

	// 证书ID列表，用于筛选指定证书，当Origin为Ingress时必填
	CertificateIDs []string `json:"CertificateIDs"`
	// 证书类型，证书的类型，取值范围：ServerCrt、CACrt，空表示不筛选类型
	CertificateType *string `json:"CertificateType"`
	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 搜索关键词，用于搜索证书
	Keyword *string `json:"Keyword"`
	// 负载均衡ID，用于筛选已绑定证书的负载均衡，当Origin为Ingress时必填
	LBID *string `json:"LBID"`
	// 分页大小，指定每页返回的记录数
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数
	Offset *int `json:"Offset"`
	// 证书来源，证书的来源，取值范围：Default、Ingress，空表示不筛选来源
	Origin *string `json:"Origin"`
	// 项目ID列表，用于筛选指定项目的证书
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 虚拟服务器ID，用于筛选已绑定证书的虚拟服务器，当Origin为Ingress时必填
	VSID *string `json:"VSID"`
}
