// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DescribeRemoteVPNGWRequest 获取对端网关信息
type DescribeRemoteVPNGWRequest struct {
	request.CommonBase

	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 搜索关键词，模糊匹配对端网关名称或ID
	Keyword *string `json:"Keyword"`
	// 分页大小，指定每页返回的记录数，用于控制返回数据量，取值范围：1-100
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数，用于实现分页查询，取值范围：≥0
	Offset *int `json:"Offset"`
	// 项目ID列表，按项目过滤对端网关，支持多个项目
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 对端网关ID列表，指定要查询的对端网关ID，支持批量查询
	RemoteVPNGWIDs []string `json:"RemoteVPNGWIDs"`
}
