// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// DescribeTimerResponse - 查询定时器
type DescribeTimerResponse struct {
	response.CommonBase

	// 定时器详情列表
	Infos []models.OldTimerInfo `json:"Infos"`
	// 总记录数，返回满足查询条件的定时器总数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
