// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DetachDiskResponse - 解绑磁盘
type DetachDiskResponse struct {
	response.CommonBase

}
