// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DetachUSBRequest 卸载USB设备
type DetachUSBRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织
	CompanyID *int `json:"CompanyID"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// USB设备ID，指定要从虚拟机卸载的USB设备
	USBDeviceID *string `json:"USBDeviceID" required:"true"`
}
