// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DetachClusterEIPRequest 解绑k8s集群外网IP
type DetachClusterEIPRequest struct {
	request.CommonBase

	// 集群Id
	ClusterID *string `json:"ClusterID" required:"true"`
	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// Region
	Region *string `json:"Region" required:"true"`
}
