// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DetachISOResponse - 解绑iso
type DetachISOResponse struct {
	response.CommonBase

}
