// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DetachUSBResponse - 卸载USB设备
type DetachUSBResponse struct {
	response.CommonBase

}
