// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DiscoverPMHardwareV2Request 硬件发现
type DiscoverPMHardwareV2Request struct {
	request.CommonBase

	// 裸金属ID，指定要进行硬件发现的裸金属实例
	PMID *string `json:"PMID" required:"true"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
}
