// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DiskLightOnResponse - 磁盘点灯
type DiskLightOnResponse struct {
	response.CommonBase

}
