// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DissociateVPCPeeringResponse - 删除VPC对等连接
type DissociateVPCPeeringResponse struct {
	response.CommonBase

}
