// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DOSLoginRequest 获取S3登录信息
type DOSLoginRequest struct {
	request.CommonBase

	// 桶名称，存储桶名称
	Bucket *string `json:"Bucket" required:"true"`
	// 租户ID，用于校验对象存储资源的租户归属；公司级账号必须填写自身CompanyID，其它角色可不填或传0
	CompanyID *int `json:"CompanyID"`
	// 对象存储ID，对象存储实例标识
	OSSID *string `json:"OSSID" required:"true"`
	// 地域ID，指定资源所属的地域
	Region *string `json:"Region" required:"true"`
}
