// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// DowngradeMySQLRequest 降级MySQL
type DowngradeMySQLRequest struct {
	request.CommonBase

	// 租户ID，资源所属租户
	CompanyID *int `json:"CompanyID" required:"true"`
	// 内存大小，单位MiB，最小2048 MiB（2GB），必须是1024的倍数，且必须小于当前内存
	Memory *int `json:"Memory" required:"true"`
	// MySQL实例ID，指定要降级的实例；注意：资源必须为AVAILABLE且状态为Stopped
	MySQLID *string `json:"MySQLID" required:"true"`
	// 地域ID，实例所属地域
	Region *string `json:"Region" required:"true"`
}
