// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DowngradeLBResponse - 降级LB
type DowngradeLBResponse struct {
	response.CommonBase

}
