// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// DowngradeRedisResponse - 降级redis内存
type DowngradeRedisResponse struct {
	response.CommonBase

}
