// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// EnableASGroupResponse - 启用伸缩组
type EnableASGroupResponse struct {
	response.CommonBase

}
