// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// FlushRedisRequest 清空数据
type FlushRedisRequest struct {
	request.CommonBase

	// Redis实例ID，指定要清空数据的实例；注意：资源必须为AVAILABLE且状态为Running
	RedisID *string `json:"RedisID" required:"true"`
	// 地域ID，实例所属地域
	Region *string `json:"Region" required:"true"`
}
