// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// FlushBucketResponse - 清空桶数据
type FlushBucketResponse struct {
	response.CommonBase

	// 被清理的对象数量，清理掉的对象总数
	Count *int `json:"Count"`
}
