// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// ForwardClusterRequest 代理k8s集群请求
type ForwardClusterRequest struct {
	request.CommonBase

	// 响应体格式
	Accept *string `json:"Accept"`
	// 集群名称
	ClusterID *string `json:"ClusterID" required:"true"`
	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// 请求体格式
	ContentType *string `json:"ContentType"`
	// 转发Body数据是否被编码
	EncodedBody *bool `json:"EncodedBody"`
	// 语言
	Language *string `json:"Language"`
	// 请求类型
	Method *string `json:"Method"`
	// 请求路径
	Path *string `json:"Path"`
	// Region
	Region *string `json:"Region" required:"true"`
	// 转发Body数据
	RequestBody *string `json:"RequestBody"`
	// 请求版本
	Version *string `json:"Version"`
}
