// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// FreezeUserRequest 冻结租户
type FreezeUserRequest struct {
	request.CommonBase

	// 租户ID，请求传入并定位要冻结的租户，用于冻结租户账号与资源操作场景
	CompanyID *int `json:"CompanyID" required:"true"`
}
