// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// GetBMCTypeResponse - 获取BMC类型详情
type GetBMCTypeResponse struct {
	response.CommonBase

	// BMC类型信息
	BMCType *models.BMCType `json:"BMCType"`
}
