// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// GetClusterPriceResponse - 获取K8S价格
type GetClusterPriceResponse struct {
	response.CommonBase

	// 
	Infos []models.K8SPriceInfo `json:"Infos"`
}
