// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// GetClusterPaymentOfPremiumResponse - 获取K8S修改配置后的差价
type GetClusterPaymentOfPremiumResponse struct {
	response.CommonBase

	// 计费类型
	OrderType *string `json:"OrderType"`
	// 价格
	Price *float64 `json:"Price"`
}
