// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// GetCreateNICPriceRequest 获取弹性IP价格
type GetCreateNICPriceRequest struct {
	request.CommonBase

	// 带宽，单位Mbps，指定网卡的带宽规格
	Bandwidth *int `json:"Bandwidth" required:"true"`
	// 计费类型，用于指定计费模式；取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费），兼容hour/month/year；计费类型别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR，hour->HOUR、month->MONTH、year->YEAR
	ChargeType *string `json:"ChargeType" required:"true"`
	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID" required:"true"`
	// 购买数量，指定一次性购买的网卡数量，用于批量询价
	Count *int `json:"Count" required:"true"`
	// 外网线路ID，指定外网网卡使用的线路，用于计算价格
	OpertatorName *string `json:"OpertatorName" required:"true"`
	// 计费数量，按月/年计费时表示购买Quantity个月/年
	Quantity *int `json:"Quantity" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
