// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// GetContainerLogsRequest 查询容器日志
type GetContainerLogsRequest struct {
	request.CommonBase

	// 集群id
	ClusterID *string `json:"ClusterID" required:"true"`
	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// 容器名
	Container *string `json:"Container" required:"true"`
	// 结束时间,unixnano
	End *int `json:"End"`
	// 关键词
	Keywords []string `json:"Keywords"`
	// 关键词排除
	KeywordsIgnore []string `json:"KeywordsIgnore"`
	// 数量限制
	LineLimit *int `json:"LineLimit"`
	// 命名空间
	Namespace *string `json:"Namespace" required:"true"`
	// 是否在集群内
	NotInCluster *bool `json:"NotInCluster"`
	// pod名字
	Pod *string `json:"Pod" required:"true"`
	// Region
	Region *string `json:"Region" required:"true"`
	// 起始时间,unixnano
	Start *int `json:"Start"`
}
