// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// GetCreateDiskPriceResponse - 获取创建硬盘价格
type GetCreateDiskPriceResponse struct {
	response.CommonBase

	// 磁盘价格信息，价格明细列表
	Infos []models.DiskPriceInfo `json:"Infos"`
}
