// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// GetClusterPriceRequest 获取K8S价格
type GetClusterPriceRequest struct {
	request.CommonBase

	// CPU核数
	CPU *int `json:"CPU"`
	// 计费类型
	ChargeType *string `json:"ChargeType" required:"true"`
	// ClusterID
	ClusterID *string `json:"ClusterID"`
	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// 计算集群类型
	ComputeclassType *string `json:"ComputeclassType" required:"true"`
	// 高可用
	HighAvailability *string `json:"HighAvailability"`
	// 内存大小
	Memory *int `json:"Memory"`
	// 计费周期
	Quantity *int `json:"Quantity"`
	// 地域
	Region *string `json:"Region" required:"true"`
	// 存储集群类型
	StorageclassType *string `json:"StorageclassType" required:"true"`
}
