// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// GetDTSTaskConfigureRequest 获取传输任务配置
type GetDTSTaskConfigureRequest struct {
	request.CommonBase

	// DTS任务ID，待查询配置的DTS任务唯一标识
	DTSID *string `json:"DTSID" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
