// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// GetDiskPriceResponse - 获取数据盘的价格
type GetDiskPriceResponse struct {
	response.CommonBase

	// 磁盘价格信息，价格明细列表
	Infos []models.DiskPriceInfo `json:"Infos"`
}
