// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// GetDHCPNetworkResponse - 获取DHCP网络配置
type GetDHCPNetworkResponse struct {
	response.CommonBase

	// DHCP 地址池列表，每个机房一条
	Pools []models.DHCPPoolInfo `json:"Pools"`
	// DHCPServer 配置
	Server *models.DHCPServerInfo `json:"Server"`
}
