// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// GetDHCPServerStateRequest 获取DHCP服务器状态
type GetDHCPServerStateRequest struct {
	request.CommonBase

	// 地域
	Region *string `json:"Region" required:"true"`
}
