// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// GetDHCPServerStateResponse - 获取DHCP服务器状态
type GetDHCPServerStateResponse struct {
	response.CommonBase

	// DHCP 服务器状态. dead: 未运行, running: 运行中
	Results []models.DHCPServerStateResult `json:"Results"`
}
