// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// GetDataCheckTaskResultResponse - 获取数据校验任务详细结果
type GetDataCheckTaskResultResponse struct {
	response.CommonBase

	// 详细差异日志列表，包含数据表级别差异详情，当Result为Inconsistent时返回
	Logs []string `json:"Logs"`
	// 校验结果，数据一致性校验的最终结果，取值范围：Consistent（数据一致）、Inconsistent（数据不一致）
	Result *string `json:"Result"`
}
