// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// GetDTSPriceResponse - 获取数据传输任务价格
type GetDTSPriceResponse struct {
	response.CommonBase

	// 价格信息列表，用于展示DTS询价结果
	Infos []models.DTSPriceInfo `json:"Infos"`
}
