// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// GetDTSPriceRequest 获取数据传输任务价格
type GetDTSPriceRequest struct {
	request.CommonBase

	// CPU核数，用于指定DTS实例的CPU配置
	CPU *int `json:"CPU" required:"true"`
	// 计费类型，用于指定计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）；兼容历史值：hour、month、year，别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR
	ChargeType *string `json:"ChargeType" required:"true"`
	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 计算集群类型，用于指定DTS实例运行的计算集群
	ComputeClass *string `json:"ComputeClass" required:"true"`
	// 购买数量，用于批量购买时指定购买的DTS实例数量
	Count *int `json:"Count" required:"true"`
	// DTS任务ID，用于计算升级配置时的费用差价；不指定则计算新购价格
	DTSID *string `json:"DTSID"`
	// 内存大小，单位GB，用于指定DTS实例的内存配置
	Memory *int `json:"Memory" required:"true"`
	// 计费数量，用于指定购买时长的数量，按月/年计费时表示购买的月/年数，按小时计费时默认为1，
	Quantity *int `json:"Quantity" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 存储集群类型，用于指定DTS实例系统盘所在存储集群
	StorageClass *string `json:"StorageClass" required:"true"`
}
