// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// GetDataCheckTaskResultRequest 获取数据校验任务详细结果
type GetDataCheckTaskResultRequest struct {
	request.CommonBase

	// DTS任务ID，数据校验任务所属的DTS任务唯一标识
	DTSID *string `json:"DTSID" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 校验任务ID，待查询结果的数据校验任务唯一标识
	TaskID *string `json:"TaskID" required:"true"`
}
