// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// GetEIPPriceResponse - 获取弹性IP价格
type GetEIPPriceResponse struct {
	response.CommonBase

	// IP价格信息列表，包含EIP价格和计费类型等信息
	Infos []models.IpPriceInfo `json:"Infos"`
}
