// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// GetFSPriceResponse - 获取文件存储价格
type GetFSPriceResponse struct {
	response.CommonBase

	// 价格信息列表，返回计费模式与价格
	Infos []models.FsPriceInfo `json:"Infos"`
}
