// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// GetFilterKeywordsResponse - 获取规格/价格/配额分类筛选关键字
type GetFilterKeywordsResponse struct {
	response.CommonBase

	// 价格筛选关键字，包含可用的产品ID和集群类型
	BillPriceGroupInfo *models.BillPriceGroupInfo `json:"BillPriceGroupInfo"`
	// 配额筛选关键字，包含可用的产品类型和配额因子
	QuotaInfo *models.QuotaInfo `json:"QuotaInfo"`
	// 规格筛选关键字，包含可用的产品类型和集群类型
	SpecificationInfo *models.SpecificationInfo `json:"SpecificationInfo"`
}
