// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// GetInstallLogsV2Request 获取装机日志
type GetInstallLogsV2Request struct {
	request.CommonBase

	// 日志行数，限制返回的日志行数，0表示不限制
	Lines *int `json:"Lines"`
	// 裸金属ID，物理机唯一标识
	PMID *string `json:"PMID" required:"true"`
	// 地域
	Region *string `json:"Region" required:"true"`
	// 起始时间，RFC3339格式时间戳，例如2024-01-01T00:00:00Z，若不指定则从日志开始返回
	Since *string `json:"Since"`
	// 任务ID，安装任务唯一标识
	TaskID *string `json:"TaskID" required:"true"`
}
