// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// GetImageDownloadURLResponse - 获取镜像下载地址
type GetImageDownloadURLResponse struct {
	response.CommonBase

	// 镜像下载URL详情，用于返回签名下载参数
	Info *models.ImageDownloadInfo `json:"Info"`
}
