// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// GetInstallTaskV2Response - 获取装机任务详情
type GetInstallTaskV2Response struct {
	response.CommonBase

	// 任务信息
	Task *models.InstallTaskInfoV2 `json:"Task"`
}
