// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// GetKickstartTemplateResponse - 获取Kickstart模板详情
type GetKickstartTemplateResponse struct {
	response.CommonBase

	// 模板信息
	Template *models.KickstartTemplateInfo `json:"Template"`
}
