// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// GetKickstartTemplateRequest 获取Kickstart模板详情
type GetKickstartTemplateRequest struct {
	request.CommonBase

	// 模板名称
	Name *string `json:"Name" required:"true"`
	// 地域
	Region *string `json:"Region" required:"true"`
}
