// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// GetLatestInstallConfigResponse - 获取裸金属最近一次安装配置
type GetLatestInstallConfigResponse struct {
	response.CommonBase

	// 任务所属租户ID
	CompanyID *int `json:"CompanyID"`
	// 裸金属安装配置详情
	Config *models.PMInstallConfig `json:"Config"`
	// 创建时间
	CreatedAt *int `json:"CreatedAt"`
	// 元数据
	Metadata *models.InstallMetadata `json:"Metadata"`
	// 配置模式版本
	SchemaVersion *string `json:"SchemaVersion"`
	// 配置版本
	Version *int `json:"Version"`
}
