// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// GetLatestInstallConfigRequest 获取裸金属最近一次安装配置
type GetLatestInstallConfigRequest struct {
	request.CommonBase

	// 机器序列号
	MachineSN *string `json:"MachineSN" required:"true"`
	// 地域
	Region *string `json:"Region" required:"true"`
}
