// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// GetLBPriceResponse - 获取负载均衡价格
type GetLBPriceResponse struct {
	response.CommonBase

	// 
	Infos []models.LbPriceInfo `json:"Infos"`
}
