// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// GetMySQLPriceResponse - 查询MySQL价格
type GetMySQLPriceResponse struct {
	response.CommonBase

	// 价格信息，计费价格列表
	Infos []models.MysqlPriceInfo `json:"Infos"`
}
