// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// GetMemberInfoRequest 获取用户访问控制信息
type GetMemberInfoRequest struct {
	request.CommonBase

}
