// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// GetMemberInfoResponse - 获取用户访问控制信息
type GetMemberInfoResponse struct {
	response.CommonBase

	// 当前用户信息，返回当前账号的完整访问控制信息
	Info *models.UserAccessInfo `json:"Info"`
}
