// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// GetNativeNodePriceResponse - 获取K8S原生节点价格
type GetNativeNodePriceResponse struct {
	response.CommonBase

	// 订单类型
	OrderType *string `json:"OrderType"`
	// 价格
	Price *float64 `json:"Price"`
}
