// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// GetNATGWPriceRequest 获取NAT网关价格
type GetNATGWPriceRequest struct {
	request.CommonBase

	// 计费类型，取值范围：Dynamic、Month、Year；兼容历史值：hour、month、year，别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR
	ChargeType *string `json:"ChargeType" required:"true"`
	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 高可用模式，NAT网关的高可用配置方式，ActiveStandy为主备高可用，Standalone为单机模式，默认ActiveStandy
	HighAvailability *string `json:"HighAvailability"`
	// NAT网关ID，用于查询升级到指定高可用模式的差价，不填写则查询新建价格
	NATGWID *string `json:"NATGWID"`
	// 计费数量，用于指定购买时长的数量，按月/年计费时表示购买的月/年数，按小时计费时默认为1，
	Quantity *int `json:"Quantity" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 计算集群类型，用于指定NAT网关虚拟机运行的计算集群
	VMType *string `json:"VMType" required:"true"`
}
