// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// GetNodeCPUGovernorRequest 获取节点 CPU 电源模式
type GetNodeCPUGovernorRequest struct {
	request.CommonBase

	// 节点ID，用于标识节点唯一标识
	HostID *string `json:"HostID" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
