// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// GetOSMediaV2Request 获取系统镜像详情
type GetOSMediaV2Request struct {
	request.CommonBase

	// 系统镜像ID
	MediaID *string `json:"MediaID" required:"true"`
	// 地域
	Region *string `json:"Region" required:"true"`
}
