// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// GetOnSiteInspectionResponse - 获取巡检报告详情
type GetOnSiteInspectionResponse struct {
	response.CommonBase

	// 巡检报告详细信息，包含完整的巡检结果数据
	Info *models.InspectionReport `json:"Info"`
}
