// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// GetOSSPriceRequest 获取对象存储价格
type GetOSSPriceRequest struct {
	request.CommonBase

	// CPU核数，用于价格计算，取值范围：2、4、6、8、10、12、14、16
	CPU *int `json:"CPU"`
	// 计费类型，计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）；兼容历史值：hour、month、year，别名映射：Dynamic→HOUR、Month→MONTH、Year→YEAR
	ChargeType *string `json:"ChargeType"`
	// 租户ID，资源所属租户标识
	CompanyID *int `json:"CompanyID"`
	// 存储集群类型，数据盘所在存储集群类型
	DiskSetType *string `json:"DiskSetType" required:"true"`
	// 存储容量，单位GiB，最小值100
	DiskSpace *int `json:"DiskSpace" required:"true"`
	// 对象存储ID，空表示新建价格，非空表示升级价格
	OSSID *string `json:"OSSID"`
	// 计费数量，用于指定购买时长的数量，按月/年计费时表示购买的月/年数，按小时计费时默认为1
	Quantity *int `json:"Quantity"`
	// 地域ID，指定资源所属的地域
	Region *string `json:"Region" required:"true"`
	// 计算集群类型，系统会根据集群架构自动确定系统盘大小
	VMType *string `json:"VMType" required:"true"`
}
