// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// GetProjectResponse - 获取项目详情
type GetProjectResponse struct {
	response.CommonBase

	// 项目详情，返回指定项目的完整信息
	Info *models.ProjectInfo `json:"Info"`
}
