// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// GetPriceRequest 获取价格
type GetPriceRequest struct {
	request.CommonBase

	// 计费类型，用于指定计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）；兼容历史值：hour、month、year，别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR
	ChargeType *string `json:"ChargeType" required:"true"`
	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 购买数量，需要购买的VPN网关数量，用于批量询价
	Count *int `json:"Count" required:"true"`
	// 高可用模式，VPN网关高可用配置方式，影响价格计算，ActiveStandy为主备高可用（2个实例），Standalone为单机（1个实例），若不指定则默认为ActiveStandy
	HighAvailability *string `json:"HighAvailability"`
	// 计费数量，用于指定购买时长的数量，按月/年计费时表示购买的月/年数，按小时计费时默认为1，
	Quantity *int `json:"Quantity" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 计算集群类型，用于指定VPN网关虚拟机运行的计算集群，影响价格计算
	VMType *string `json:"VMType" required:"true"`
	// VPN网关ID，若指定则按该网关规格查询续费或升级价格，若不指定则查询新购价格
	VPNGWID *string `json:"VPNGWID"`
}
