// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// GetPaymentOfPremiumResponse - 获取修改配置后的差价
type GetPaymentOfPremiumResponse struct {
	response.CommonBase

	// 订单类型，标识变更的性质，取值：0（无变更）、3（升级）、7（降级）
	OrderType *string `json:"OrderType"`
	// 差价，变更配置所需的预估费用，单位：元
	Price *float64 `json:"Price"`
}
