// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// GetPaymentOfPremiumRequest 获取修改配置后的差价
type GetPaymentOfPremiumRequest struct {
	request.CommonBase

	// 核心数，变更后的vCPU核心数量
	CPU *int `json:"CPU" required:"true"`
	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// GPU数量，变更后的物理GPU数量，仅在GPUType为GPU时有效且必填
	GPU *int `json:"GPU"`
	// GPU规格，变更后的物理GPU型号，仅在GPUType为GPU时有效且必填
	GPUMdevName *string `json:"GPUMdevName"`
	// GPU类型，变更后的GPU资源类型，取值：GPU、VGPU，暂未支持VGPU
	GPUType *string `json:"GPUType"`
	// vGPU规格，变更后的虚拟GPU规格，仅在GPUType为VGPU时有效且必填，预留字段，暂未支持
	MdevName *string `json:"MdevName"`
	// 内存容量，变更后的内存大小，单位：MiB
	Memory *int `json:"Memory" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 虚拟机ID，待变更配置的虚拟机标识
	VMID *string `json:"VMID" required:"true"`
}
