// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// GetRedisPriceResponse - 获取redis创建升级价格
type GetRedisPriceResponse struct {
	response.CommonBase

	// 价格信息，计费价格信息
	Info *models.RedisPriceInfo `json:"Info"`
}
