// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// GetSubnetAvailableIPQuotaResponse - 获取子网可用IP数量
type GetSubnetAvailableIPQuotaResponse struct {
	response.CommonBase

	// 主网段可用IP数量
	AvailableCount *int `json:"AvailableCount"`
	// 主网段已用IP数量
	UsedCount *int `json:"UsedCount"`
}
