// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// GetSSOConfigRequest 获取sso配置信息
type GetSSOConfigRequest struct {
	request.CommonBase

}
