// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// GetSSOConfigResponse - 获取sso配置信息
type GetSSOConfigResponse struct {
	response.CommonBase

	// SSO单点登录配置信息
	Info *models.SSOConfigInfo `json:"Info"`
}
