// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// GetVMSpiceInfoResponse - 获取Spice信息
type GetVMSpiceInfoResponse struct {
	response.CommonBase

	// Spice信息，包含Spice连接详情
	Info *models.SpiceInfo `json:"Info"`
}
