// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// GetVMInstancePriceRequest 获取虚拟机价格
type GetVMInstancePriceRequest struct {
	request.CommonBase

	// 系统盘集群ID，指定引导盘所在的存储池位置，影响磁盘的I/O性能和可靠性级别，若未指定，系统将根据策略自动选择
	BootDiskSetType *string `json:"BootDiskSetType"`
	// 系统盘容量，虚拟机的启动盘大小，单位：GiB
	BootDiskSpace *int `json:"BootDiskSpace"`
	// 核心数，虚拟机的vCPU核心数量
	CPU *int `json:"CPU" required:"true"`
	// 计费类型，资源的计费模式，取值：Dynamic（按小时）、Month（按月）、Year（按年）
	ChargeType *string `json:"ChargeType" required:"true"`
	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// 购买数量，批量购买的实例个数
	Count *int `json:"Count" required:"true"`
	// GPU数量，挂载的物理GPU数量，仅在GPUType为GPU时有效且必填
	GPU *int `json:"GPU"`
	// GPU规格，挂载的物理GPU型号，仅在GPUType为GPU时有效且必填
	GPUMdevName *string `json:"GPUMdevName"`
	// GPU类型，虚拟机挂载的GPU资源类型，取值：GPU、VGPU，暂未支持VGPU
	GPUType *string `json:"GPUType"`
	// 镜像ID，创建虚拟机所使用的镜像标识
	ImageID *string `json:"ImageID"`
	// vGPU规格，挂载的虚拟GPU规格，仅在GPUType为VGPU时有效且必填，预留字段，暂未支持
	MdevName *string `json:"MdevName"`
	// 内存容量，虚拟机的内存大小，单位：MiB
	Memory *int `json:"Memory" required:"true"`
	// 计费周期，购买的时长，按月/年计费时表示月数/年数，按小时计费时固定为1
	Quantity *int `json:"Quantity" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 存储类型，磁盘的存储介质类型
	StorageType *string `json:"StorageType"`
	// 计算集群ID，指定虚拟机所属的计算资源池，决定了虚拟机的CPU架构（如x86、ARM）和可用的宿主机范围
	VMType *string `json:"VMType" required:"true"`
}
