// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// ListProductPermissionsRequest 获取租户可用接口
type ListProductPermissionsRequest struct {
	request.CommonBase

}
