// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/openapi/models"
)

// ListInstallProfilesResponse - 获取装机配置模板列表
type ListInstallProfilesResponse struct {
	response.CommonBase

	// 模板列表
	Infos []models.InstallProfileInfo `json:"Infos"`
	// 总数
	TotalCount *int `json:"TotalCount"`
}
