// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// ListKickstartTemplatesResponse - 获取Kickstart模板列表
type ListKickstartTemplatesResponse struct {
	response.CommonBase

	// 模板列表
	Infos []models.KickstartTemplateInfo `json:"Infos"`
	// 总数
	TotalCount *int `json:"TotalCount"`
}
