// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// ListGlobalConfigsRequest 按照类型和地域获取全局配置
type ListGlobalConfigsRequest struct {
	request.CommonBase

	// 配置类型，用于筛选全局配置的分类，如系统配置、安全配置等
	ConfigType *string `json:"ConfigType" required:"true"`
}
