// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// ListOSMediaV2Response - 获取系统镜像列表
type ListOSMediaV2Response struct {
	response.CommonBase

	// 系统镜像列表
	Infos []models.OSMediaInfoV2 `json:"Infos"`
	// 总数
	TotalCount *int `json:"TotalCount"`
}
