// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// ListProductPermissionsResponse - 获取租户可用接口
type ListProductPermissionsResponse struct {
	response.CommonBase

	// 产品权限信息列表，返回可授权的产品与动作集合
	Infos []models.ProductPermission `json:"Infos"`
	// 总记录数，匹配条件的产品权限数量
	TotalCount *int `json:"TotalCount"`
}
