// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// ListOnSiteInspectionsRequest 获取巡检报告列表
type ListOnSiteInspectionsRequest struct {
	request.CommonBase

	// 关键字搜索，用于按巡检报告名称搜索，支持模糊匹配
	Keyword *string `json:"Keyword"`
	// 分页大小，指定每页返回的记录数，若不指定则默认为10
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数
	Offset *int `json:"Offset"`
}
