// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// ListRolesResponse - 查询租户级角色列表
type ListRolesResponse struct {
	response.CommonBase

	// 角色详情列表，返回符合筛选条件的角色信息集合
	Infos []models.RoleInfo `json:"Infos"`
	// 总记录数，匹配筛选条件的角色数量
	TotalCount *int `json:"TotalCount"`
}
