// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// ListAdminResponse - 列出管理员
type ListAdminResponse struct {
	response.CommonBase

	// 管理员详情列表，返回符合筛选条件的管理员信息集合
	Infos []models.AdminInfo `json:"Infos"`
	// 总记录数，匹配筛选条件的管理员数量
	TotalCount *int `json:"TotalCount"`
}
