// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// ListProductTypeCompanysResponse - 获取某产品已授权的租户信息
type ListProductTypeCompanysResponse struct {
	response.CommonBase

	// 租户详情列表，返回匹配条件的租户信息集合
	Infos []models.CompanyInfo `json:"Infos"`
	// 总记录数，匹配条件的租户数量
	TotalCount *int `json:"TotalCount"`
}
