// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// ListBMCTypesResponse - 获取BMC类型列表
type ListBMCTypesResponse struct {
	response.CommonBase

	// BMC类型列表
	Infos []models.BMCType `json:"Infos"`
	// 总数
	TotalCount *int `json:"TotalCount"`
}
