// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// ListUSBsResponse - 获取USB设备信息
type ListUSBsResponse struct {
	response.CommonBase

	// USB设备详情列表
	Infos []models.USBInfo `json:"Infos"`
	// 总记录数，返回满足查询条件的USB设备总数
	TotalCount *int `json:"TotalCount"`
}
