// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// ListResourceUsagesResponse - 获取资源使用情况列表
type ListResourceUsagesResponse struct {
	response.CommonBase

	// 资源用量信息列表，包含资源用量报告的基本信息
	Infos []models.ResourceUsageBaseInfo `json:"Infos"`
	// 资源用量总数，返回符合条件的资源用量报告总数量
	TotalCount *int `json:"TotalCount"`
}
