// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// ListPMV2Response - 获取裸金属列表
type ListPMV2Response struct {
	response.CommonBase

	// 裸金属列表，返回符合条件的裸金属实例信息
	Infos []models.PMInfoV2 `json:"Infos"`
	// 总数，符合条件的裸金属总数量
	TotalCount *int `json:"TotalCount"`
}
