// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// ListInstallTasksV2Request 获取装机任务列表
type ListInstallTasksV2Request struct {
	request.CommonBase

	// 租户ID，过滤指定租户下的装机任务，若不指定则返回所有租户的任务
	CompanyID *int `json:"CompanyID"`
	// 关键词搜索，支持按任务ID、裸金属ID、序列号、安装模式、状态进行关键词搜索
	Keyword *string `json:"Keyword"`
	// 每页数量，指定每页返回的记录数，默认值为20，最大值为100
	Limit *int `json:"Limit"`
	// 机器序列号过滤，支持精确匹配
	MachineSN *string `json:"MachineSN"`
	// 偏移量，指定跳过的记录数，最小值为0
	Offset *int `json:"Offset"`
	// 项目ID列表，过滤指定项目下的装机任务
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
	// 状态过滤，可选值：waiting（待安装）、installing（安装中）、completed（已完成）、failed（失败）、canceled（已取消）
	Status *string `json:"Status"`
}
