// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// ListPMV2Request 获取裸金属列表
type ListPMV2Request struct {
	request.CommonBase

	// 租户ID，过滤指定租户下的裸金属资源，若不指定则返回所有租户的资源
	CompanyID *int `json:"CompanyID"`
	// 主机名，按 Kunlun 机器主机名进行模糊匹配
	Hostname *string `json:"Hostname"`
	// 带外IP，按 Kunlun 机器 IPMI IP 进行模糊匹配
	IPMIIP *string `json:"IPMIIP"`
	// 关键词搜索，支持按裸金属ID、序列号、机架位置进行模糊匹配
	Keyword *string `json:"Keyword"`
	// 每页数量，指定每页返回的记录数，默认值为20，最大值为100
	Limit *int `json:"Limit"`
	// 偏移量，指定跳过的记录数，最小值为0
	Offset *int `json:"Offset"`
	// 裸金属ID列表，精确匹配指定ID的裸金属
	PMIDs []string `json:"PMIDs"`
	// 项目ID列表，过滤指定项目下的裸金属资源
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
	// 序列号列表，精确匹配指定序列号的裸金属
	SNs []string `json:"SNs"`
	// 搜索字段，Tag 表示仅按资源标签 key/value 搜索
	SearchField *string `json:"SearchField"`
	// 标签键值对筛选，格式为 key:value 的 Base64 编码字符串；相同 key 的多个 value 按 OR 处理，不同 key 之间按 AND 处理
	TagKeyValuePairs []string `json:"TagKeyValuePairs" required:"true"`
}
