// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// ListRegionConfigSyncStatusResponse - 查询地域配置同步状态
type ListRegionConfigSyncStatusResponse struct {
	response.CommonBase

	// 地域配置同步状态列表
	Infos []models.RegionConfigSyncStatusInfo `json:"Infos"`
	// 配置项总数
	TotalCount *int `json:"TotalCount"`
}
