// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// ListInstallTasksV2Response - 获取装机任务列表
type ListInstallTasksV2Response struct {
	response.CommonBase

	// 任务列表
	Infos []models.InstallTaskInfoV2 `json:"Infos"`
	// 总数
	TotalCount *int `json:"TotalCount"`
}
