// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// ListRegionConfigSyncStatusRequest 查询地域配置同步状态
type ListRegionConfigSyncStatusRequest struct {
	request.CommonBase

	// 配置键列表，指定要查询同步状态的地域配置项；不传则返回指定地域全部配置项的同步状态
	ConfigKeys []string `json:"ConfigKeys"`
	// 地域ID，指定要查询配置同步状态的地域
	Region *string `json:"Region" required:"true"`
}
