// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// ListProjectsRequest 查询项目列表
type ListProjectsRequest struct {
	request.CommonBase

	// 租户ID，用于限定查询的租户范围
	CompanyID *int `json:"CompanyID"`
	// 关键词，用于按项目名称检索
	Keyword *string `json:"Keyword"`
	// 分页大小，控制单次返回数量
	Limit *int `json:"Limit"`
	// 分页偏移量，用于分页起点
	Offset *int `json:"Offset"`
	// 项目组ID列表，用于筛选指定项目集合
	ProjectIDs []string `json:"ProjectIDs"`
}
