// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// LogoutTokenRequest 登出
type LogoutTokenRequest struct {
	request.CommonBase

}
