// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// LogoutTokenRequest 登出
type LogoutTokenRequest struct {
	request.CommonBase

}
