// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// MigrateStorageBandWidthResponse - 虚拟机热存储迁移带宽设置
type MigrateStorageBandWidthResponse struct {
	response.CommonBase

}
