// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// MigrateVMStorageResponse - 虚拟机热存储迁移
type MigrateVMStorageResponse struct {
	response.CommonBase

}
