// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// MigrateVMInstanceResponse - 虚机迁移
type MigrateVMInstanceResponse struct {
	response.CommonBase

}
