// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// ModifyNameAndRemarkResponse - 修改地域下资源名称和备注
type ModifyNameAndRemarkResponse struct {
	response.CommonBase

}
