// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// ModifyEIPBandwidthResponse - 调整带宽
type ModifyEIPBandwidthResponse struct {
	response.CommonBase

}
