// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// MoveProjectResourceRequest 修改资源所在的项目
type MoveProjectResourceRequest struct {
	request.CommonBase

	// 租户ID，用于标识资源所属租户并进行权限校验
	CompanyID *int `json:"CompanyID" required:"true"`
	// 项目组ID，用于指定资源迁移后的目标项目
	ProjectID *string `json:"ProjectID" required:"true"`
	// 资源ID列表，用于指定需要迁移的资源集合
	ResourceIDs []string `json:"ResourceIDs" required:"true"`
}
