// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// OperateAlertRequest 操作告警处理状态
type OperateAlertRequest struct {
	request.CommonBase

	// 告警指纹，前端可从DescribeAlert返回中透传，用于辅助展示与历史关联；当前写接口的精确定位以 AlertOccurrenceKey 为准
	AlertFingerprint *string `json:"AlertFingerprint"`
	// 告警实例标识，前端从DescribeAlert返回中透传，用于精确定位一条当前告警实例
	AlertOccurrenceKey *string `json:"AlertOccurrenceKey" required:"true"`
	// 租户ID，告警所属租户；普通租户不传时默认使用当前租户，管理员代操作其他租户时必须明确传入
	CompanyID *int `json:"CompanyID"`
	// 忽略截止时间，Unix时间戳(秒)；当Operation=Ignore时必填且必须大于当前时间，其它操作忽略该值
	IgnoreUntil *int `json:"IgnoreUntil"`
	// 操作类型，取值：Handle、Reopen、Ignore、CancelIgnore；命名为 Operation 以避免与通用 API 路由字段 Action 冲突
	Operation *string `json:"Operation" required:"true"`
	// 地域，告警所属地域，用于校验当前告警归属并在状态不存在时回查实时告警
	Region *string `json:"Region" required:"true"`
	// 操作备注，用于记录处理说明，长度0-255字符
	Remark *string `json:"Remark"`
	// 资源ID，触发告警的目标资源ID，用于权限校验和回查当前告警
	TargetID *string `json:"TargetID" required:"true"`
}
