// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// OperateAlertResponse - 操作告警处理状态
type OperateAlertResponse struct {
	response.CommonBase

}
