// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// PoweroffVMInstanceResponse - 断电主机
type PoweroffVMInstanceResponse struct {
	response.CommonBase

}
