// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// PowerControlPMV2Response - 电源控制
type PowerControlPMV2Response struct {
	response.CommonBase

}
