// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// PreviewKickstartTemplateResponse - 预览Kickstart模板渲染结果
type PreviewKickstartTemplateResponse struct {
	response.CommonBase

	// 生成的Kickstart模板内容
	RenderedContent *string `json:"RenderedContent"`
	// 模板名称
	TemplateName *string `json:"TemplateName"`
}
