// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// PreviewKickstartCommandsResponse - 预览Kickstart分区命令
type PreviewKickstartCommandsResponse struct {
	response.CommonBase

	// Kickstart分区命令
	Preview *string `json:"Preview"`
	// 警告信息
	Warnings []string `json:"Warnings"`
}
