// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// RecoverPaaSConfigRequest 恢复 PaaS 产品配置
type RecoverPaaSConfigRequest struct {
	request.CommonBase

	// 地域ID，指定资源所属地域，用于调用对应的资源服务
	Region *string `json:"Region" required:"true"`
	// 资源ID，指定要恢复配置的PaaS资源，仅支持MYSQL/REDIS/OSS/FS四类资源。默认要求资源处于AVAILABLE且hhpaas状态为Config_Mismatch；对于带 legacy 标记且尚未 normalized 的 Running 状态 MySQL，也允许执行恢复配置
	ResourceID *string `json:"ResourceID" required:"true"`
}
