// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// ReinstallVMInstanceResponse - 重装系统
type ReinstallVMInstanceResponse struct {
	response.CommonBase

}
