// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// RemoveNodesFromIsolationGroupRequest 从隔离组移除节点
type RemoveNodesFromIsolationGroupRequest struct {
	request.CommonBase

	// 隔离组ID，指定目标隔离组
	IGID *string `json:"IGID" required:"true"`
	// 节点ID列表，指定要从隔离组移除的节点
	NodeIDs []string `json:"NodeIDs" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
