// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// RemoveASMemberResponse - 移除伸缩成员
type RemoveASMemberResponse struct {
	response.CommonBase

}
