// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// RemoveVMFromIsolationGroupResponse - 从隔离组移除VM
type RemoveVMFromIsolationGroupResponse struct {
	response.CommonBase

}
