// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// RenameRoleResponse - 重命名角色名称备注
type RenameRoleResponse struct {
	response.CommonBase

}
