// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// RenameRoleRequest 重命名角色名称备注
type RenameRoleRequest struct {
	request.CommonBase

	// 角色名称，用于更新角色显示名称，长度为1-50个字符，只能包含中英文、数字、点、下划线和中划线
	Name *string `json:"Name" required:"true"`
	// 备注，用于补充说明角色用途和权限范围，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符，
	Remark *string `json:"Remark"`
	// 角色ID，用于指定要重命名的角色
	RoleID *string `json:"RoleID" required:"true"`
}
