// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// RenameProjectRequest 重命名项目名称备注
type RenameProjectRequest struct {
	request.CommonBase

	// 项目名称，用于更新项目显示名称，长度为1-50个字符，只能包含中英文、数字、点、下划线和中划线
	Name *string `json:"Name" required:"true"`
	// 项目组ID，用于指定要重命名的项目
	ProjectID *string `json:"ProjectID" required:"true"`
	// 备注，用于补充说明项目用途和范围，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符，
	Remark *string `json:"Remark"`
}
