// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// ReplaceIPResponse - 更新产品内网IP
type ReplaceIPResponse struct {
	response.CommonBase

}
