// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// ResetOSSPasswordResponse - 重置对象存储密码
type ResetOSSPasswordResponse struct {
	response.CommonBase

}
