// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// ResizeVMConfigResponse - 修改虚拟机配置
type ResizeVMConfigResponse struct {
	response.CommonBase

}
