// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// ResizePlatformStorageDiskRequest 扩容平台通用存储云盘
type ResizePlatformStorageDiskRequest struct {
	request.CommonBase

	// 磁盘ID，待扩容的平台通用存储云盘ID
	DiskID *string `json:"DiskID" required:"true"`
	// 磁盘大小，扩容后的目标容量，单位GiB
	DiskSpace *int `json:"DiskSpace" required:"true"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
}
