// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// RestoreVMInstanceResponse - 虚拟机恢复快照
type RestoreVMInstanceResponse struct {
	response.CommonBase

}
