// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// RestartMySQLInstanceResponse - 重启 MySQL 实例
type RestartMySQLInstanceResponse struct {
	response.CommonBase

}
