// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// RestartMySQLInstanceRequest 重启 MySQL 实例
type RestartMySQLInstanceRequest struct {
	request.CommonBase

	// 租户ID，实例所属租户
	CompanyID *int `json:"CompanyID"`
	// MySQL实例ID，指定要重启的实例；注意：资源必须为AVAILABLE且状态为Running
	MySQLID *string `json:"MySQLID" required:"true"`
	// 地域ID，实例所属地域
	Region *string `json:"Region" required:"true"`
}
