// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// ResumeDBSBackupRequest 恢复定时备份
type ResumeDBSBackupRequest struct {
	request.CommonBase

	// 租户ID，用于标识资源所属的租户，实现多租户环境下的资源隔离
	CompanyID *int `json:"CompanyID"`
	// 计划ID，备份计划的ID；仅支持ScheduleType=Timer的计划
	PlanID *string `json:"PlanID" required:"true"`
	// 地域，备份源的地域
	Region *string `json:"Region"`
}
