// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// ResumeDBSBackupResponse - 恢复定时备份
type ResumeDBSBackupResponse struct {
	response.CommonBase

}
