// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// RetryInstallTaskV2Response - 重试装机任务
type RetryInstallTaskV2Response struct {
	response.CommonBase

	// 状态
	Status *string `json:"Status"`
	// 任务ID
	TaskID *string `json:"TaskID"`
}
