// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// RollbackSnapshotRequest 快照回滚
type RollbackSnapshotRequest struct {
	request.CommonBase

	// 租户ID，资源所属租户标识
	CompanyID *int `json:"CompanyID"`
	// 磁盘ID，要回滚的目标磁盘标识，磁盘必须处于可用状态且不在回收站
	DiskID *string `json:"DiskID" required:"true"`
	// 地域ID，指定资源所属的地域
	Region *string `json:"Region" required:"true"`
	// 快照ID，要回滚到的快照标识
	SnapshotID *string `json:"SnapshotID" required:"true"`
}
