// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// RunDTSPrecheckResponse - 执行数据传输预检查
type RunDTSPrecheckResponse struct {
	response.CommonBase

	// 预检查项列表，包含所有预检查项结果详情
	PrecheckItems []models.DTSPrecheckItem `json:"PrecheckItems"`
}
