// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// S3LoginRequest 获取S3登录信息
type S3LoginRequest struct {
	request.CommonBase

	// 桶名称，Scenes=OSS 时指定目标桶；Scenes=ImageUpload 场景固定登录 mirror 桶，可不填
	Bucket *string `json:"Bucket"`
	// 租户ID，标识请求所属租户，Scenes=OSS 且当前登录账号为公司级权限时必须填写，用于校验对象存储资源归属
	CompanyID *int `json:"CompanyID"`
	// 目标S3资源ID，Scenes=OSS 时必填且必须以 oss- 开头，对应对象存储实例ID
	ID *string `json:"ID"`
	// 地域ID，指定资源所属的地域
	Region *string `json:"Region" required:"true"`
	// 使用场景，ImageUpload 表示镜像上传使用 S3（系统自动使用 mirror 桶），OSS 表示访问指定对象存储实例并复用请求中的桶信息
	Scenes *string `json:"Scenes" required:"true"`
}
