// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// S3LoginResponse - 获取S3登录信息
type S3LoginResponse struct {
	response.CommonBase

	// 密钥ID，用于S3访问认证
	AccessKey *string `json:"AccessKey"`
	// 桶名称，最终登录的S3桶，Scenes=ImageUpload 固定为 mirror，Scenes=OSS 返回请求指定的桶
	Bucket *string `json:"Bucket"`
	// 访问地址，S3访问端点
	Endpoint *string `json:"Endpoint"`
	// 密钥，用于S3访问认证
	SecretKey *string `json:"SecretKey"`
	// S3会话认证信息，用于后续请求鉴权
	SessionID *string `json:"SessionID"`
}
