// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// ScanFCSANRequest 扫描 FCSAN 外置存储集群硬盘
type ScanFCSANRequest struct {
	request.CommonBase

	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
}
