// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// SetComputeClassDRSVMRuleResponse - 设置计算集群DRS虚拟机规则
type SetComputeClassDRSVMRuleResponse struct {
	response.CommonBase

}
