// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// SetComputeClassDRSResponse - 设置计算集群DRS规则
type SetComputeClassDRSResponse struct {
	response.CommonBase

}
