// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// SetComputeClassDRSSuspendRequest 设置计算集群DRS是否暂停
type SetComputeClassDRSSuspendRequest struct {
	request.CommonBase

	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// 地域ID
	Region *string `json:"Region" required:"true"`
	// 计算集群ID
	SetID *string `json:"SetID" required:"true"`
	// 是否暂停，为true时停止调度，为false恢复调度
	Suspend *bool `json:"Suspend"`
}
