// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
	"third_party/platform-sdk-go/services/openapi/models"
)

// SetDHCPNetworkRequest 设置DHCP网络配置
type SetDHCPNetworkRequest struct {
	request.CommonBase

	// 探测 IP，绑定到 lo
	EndIP *string `json:"EndIP" required:"true"`
	// 配置模式：single=单网段，multi=多网段（DHCP Relay）
	Mode *string `json:"Mode" required:"true"`
	// DHCP Server 所在网段 CIDR，如 192.170.60.64/28
	Network *string `json:"Network" required:"true"`
	// 新增网段地址池列表
	PoolCreates []models.DHCPPoolCreate `json:"PoolCreates"`
	// 删除网段地址池 ID 列表
	PoolDeleteIDs []int `json:"PoolDeleteIDs"`
	// 地址池开关批量更新
	PoolEnabledUpdates []models.DHCPPoolEnabledUpdate `json:"PoolEnabledUpdates"`
	// 单网段模式地址池结束 IP
	PoolEndIP *string `json:"PoolEndIP"`
	// 单网段模式地址池起始 IP
	PoolStartIP *string `json:"PoolStartIP"`
	// 修改网段地址池列表
	PoolUpdates []models.DHCPPoolUpdate `json:"PoolUpdates"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
	// DHCP Server IP，绑定到 bond0
	StartIP *string `json:"StartIP" required:"true"`
	// VLAN ID
	VLANID *int `json:"VLANID"`
}
