// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// SetDefaultPartitionTemplateResponse - 设置默认分区模板
type SetDefaultPartitionTemplateResponse struct {
	response.CommonBase

}
