// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// SetShareAbleExternalStorageRequest 外置存储盘设置为可共享的磁盘
type SetShareAbleExternalStorageRequest struct {
	request.CommonBase

	// 租户ID，资源所属租户的权限上下文
	CompanyID *int `json:"CompanyID"`
	// 磁盘ID，待设置为共享盘的外置存储盘ID
	DiskID *string `json:"DiskID" required:"true"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
}
