// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
	"third_party/platform-sdk-go/services/openapi/models"
)

// SetupSMCRequest 设置SMC任务
type SetupSMCRequest struct {
	request.CommonBase

	// 带宽限速，单位Mbps，用于控制迁移数据传输的网络带宽，0表示不限速，null时不做限制
	Bandwidth *int `json:"Bandwidth"`
	// 磁盘映射关系列表，指定源端磁盘与目标云硬盘的映射关系，每个源端磁盘分区必须映射到一个目标云硬盘
	DiskMappings []models.DiskMapping `json:"DiskMappings" required:"true"`
	// 传输IP地址，目标虚拟机的IP地址或网络接口地址，用于数据传输的网络连接目标
	Host *string `json:"Host" required:"true"`
	// 目标虚拟机SSH密码（明文），用于传输数据通道的认证，若不指定，则系统自动从虚拟机获取root用户凭证，输入的密码将使用VMID作为密钥进行AES-ECB加密存储
	Password *string `json:"Password"`
	// 地域ID，指定SMC任务所属的物理区域，与SMCID对应的区域必须相同
	Region *string `json:"Region" required:"true"`
	// SMC任务唯一标识ID，标识要配置的迁移任务，任务必须处于ONLINE或SYNCED状态
	SMCID *string `json:"SMCID" required:"true"`
	// 目标虚拟机SSH用户名，用于传输数据通道的认证，若不指定且未提供Password，则系统自动从虚拟机获取root用户凭证；当Password不为空时必填
	User *string `json:"User"`
	// 目标传输虚拟机ID，用于接收源端迁移数据，虚拟机必须运行且网络可通
	VMID *string `json:"VMID" required:"true"`
}
