// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// StartDTSTaskResponse - 启动 DTS 任务
type StartDTSTaskResponse struct {
	response.CommonBase

}
