// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// StartVMInstanceResponse - 启动主机
type StartVMInstanceResponse struct {
	response.CommonBase

}
