// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// StartSMCResponse - 开始迁移
type StartSMCResponse struct {
	response.CommonBase

}
