// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// StartPaaSInstanceResponse - Paas 实例开机
type StartPaaSInstanceResponse struct {
	response.CommonBase

}
