// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// SuspendDTSTaskResponse - 暂停 DTS 任务
type SuspendDTSTaskResponse struct {
	response.CommonBase

}
