// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// TerminateResourceRequest 销毁资源
type TerminateResourceRequest struct {
	request.CommonBase

	// 租户ID，资源所属租户的权限上下文
	CompanyID *int `json:"CompanyID"`
	// 项目ID，资源所属项目，当前不影响销毁逻辑
	ProjectID *string `json:"ProjectID"`
	// 地域ID，资源所属的物理区域
	Region *string `json:"Region" required:"true"`
	// 资源ID，待销毁的回收站资源ID
	ResourceID *string `json:"ResourceID" required:"true"`
}
