// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// TestBMCTypeResponse - 测试BMC类型
type TestBMCTypeResponse struct {
	response.CommonBase

	// 测试结果
	Result *models.TestBMCTypeResult `json:"Result"`
}
