// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// TriggerDRSOnceResponse - 触发一次drs任务
type TriggerDRSOnceResponse struct {
	response.CommonBase

}
