// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UnbindAlertTemplateRequest 解绑告警模版
type UnbindAlertTemplateRequest struct {
	request.CommonBase

	// 地域，目标资源所属地域
	Region *string `json:"Region" required:"true"`
	// 目标资源ID，待解绑告警模板的资源ID，非管理员租户需验证资源归属权限
	TargetID *string `json:"TargetID" required:"true"`
}
