// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UnbindEIPFromLBResponse - 从 LB 解绑 eip
type UnbindEIPFromLBResponse struct {
	response.CommonBase

}
