// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UnbindStorageFromDBSResponse - 从DBS解绑存储系统
type UnbindStorageFromDBSResponse struct {
	response.CommonBase

}
