// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UnBindSecurityGroupResponse - 解绑安全组
type UnBindSecurityGroupResponse struct {
	response.CommonBase

}
