// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UnbindEIPFromNATGWResponse - 从NAT网关上解绑EIP
type UnbindEIPFromNATGWResponse struct {
	response.CommonBase

}
