// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UnBindEIPResponse - 解绑弹性IP
type UnBindEIPResponse struct {
	response.CommonBase

}
