// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UnBindSecurityGroupRequest 解绑安全组
type UnBindSecurityGroupRequest struct {
	request.CommonBase

	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID" required:"true"`
	// 网卡ID，绑定安全组时指定的网络接口唯一标识符，Flat时传入,其他场景传空字符串
	NICID *string `json:"NICID"`
	// 网卡类型，取值LAN/WAN；需与绑定时的类型一致
	NICType *string `json:"NICType" required:"true"`
	// 地域ID，用于标识资源和安全组所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 资源ID，指定要解绑安全组的资源唯一标识符，支持VM、ELASTIC_NIC、OSS、FS、MySQL、Redis等资源类型
	ResourceID *string `json:"ResourceID" required:"true"`
}
