// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UnbindAlertTemplateResponse - 解绑告警模版
type UnbindAlertTemplateResponse struct {
	response.CommonBase

}
