// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UnFreezeUserResponse - 解冻租户
type UnFreezeUserResponse struct {
	response.CommonBase

}
