// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UnFreezeSubMemberResponse - 解冻子账号
type UnFreezeSubMemberResponse struct {
	response.CommonBase

}
