// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UnFreezeUserRequest 解冻租户
type UnFreezeUserRequest struct {
	request.CommonBase

	// 租户ID，请求传入并定位要解冻的租户，用于恢复租户账号与资源操作场景
	CompanyID *int `json:"CompanyID" required:"true"`
}
