// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UnlockHostResponse - 解锁物理机
type UnlockHostResponse struct {
	response.CommonBase

}
