// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UnSetBootFromCdromRequest 设置虚拟机不从Cdrom启动
type UnSetBootFromCdromRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// 镜像ID，指定取消引导的ISO镜像标识
	ImageID *string `json:"ImageID" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 虚拟机ID，待取消ISO引导的虚拟机标识
	VMID *string `json:"VMID" required:"true"`
}
