// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateBucketLifecycleRuleResponse - 更新桶的生命周期
type UpdateBucketLifecycleRuleResponse struct {
	response.CommonBase

}
