// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateContainerImageRepositoryResponse - 更新镜像仓库
type UpdateContainerImageRepositoryResponse struct {
	response.CommonBase

}
