// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateMemberEmailRequest 修改账号邮箱
type UpdateMemberEmailRequest struct {
	request.CommonBase

	// 租户ID，用于授权校验与账号归属识别
	CompanyID *int `json:"CompanyID"`
	// 成员ID，指定要修改邮箱的账号标识
	MemberID *int `json:"MemberID" required:"true"`
	// 账号邮箱，用于更新账号的登录与通知邮箱
	UserEmail *string `json:"UserEmail" required:"true"`
}
