// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateAuditLogResponse - 开关数据库审计
type UpdateAuditLogResponse struct {
	response.CommonBase

}
