// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateBucketQuotaRequest 更新存储桶配额
type UpdateBucketQuotaRequest struct {
	request.CommonBase

	// 桶名称，存储桶名称
	BucketName *string `json:"BucketName" required:"true"`
	// 对象存储ID，对象存储实例标识
	OSSID *string `json:"OSSID" required:"true"`
	// 桶配额，单位GB，0表示不限制并移除配额
	Quota *int `json:"Quota"`
	// 地域ID，指定资源所属的地域
	Region *string `json:"Region" required:"true"`
}
