// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UpdateAlertTemplateRuleRequest 更新告警通知规则
type UpdateAlertTemplateRuleRequest struct {
	request.CommonBase

	// 条件类型，告警触发比较方式，取值：GE/LE/ET/NE/LT/GT
	ConditionType *string `json:"ConditionType" required:"true"`
	// 持续时间，超过阈值需持续的秒数才触发告警
	ForSeconds *int `json:"ForSeconds" required:"true"`
	// 监控指标名称，必须是合法的Prometheus指标名，且不能包含大括号
	Metric *string `json:"Metric" required:"true"`
	// 通知组ID，告警触发通知目标组ID；若规则所属模板为REGION类型，则此字段对管理员不可修改
	NotifyGroupID *string `json:"NotifyGroupID" required:"true"`
	// PromQL查询表达式，必须是合法的Prometheus查询语法
	Query *string `json:"Query" required:"true"`
	// 告警规则ID，待更新的规则ID，非管理员租户需验证规则所属模板的归属权限
	RuleID *string `json:"RuleID" required:"true"`
	// 告警级别，定义告警严重程度，取值：warning/critical/error
	Severity *string `json:"Severity" required:"true"`
	// 告警摘要，描述告警的触发条件和意义，将在告警通知中展示
	Summary *string `json:"Summary" required:"true"`
	// 告警阈值，触发告警的指标值
	Thresholds *float64 `json:"Thresholds" required:"true"`
}
