// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateClusterCapacityResponse - 更新k8s集群容量配额
type UpdateClusterCapacityResponse struct {
	response.CommonBase

}
