// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateDOSTokenResponse - 更新令牌
type UpdateDOSTokenResponse struct {
	response.CommonBase

}
