// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateLBLogRequest 更新负载均衡
type UpdateLBLogRequest struct {
	request.CommonBase

	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 负载均衡ID，用于定位需要更新访问日志配置的负载均衡实例
	LBID *string `json:"LBID" required:"true"`
	// 访问日志开关，是否开启访问日志，取值范围：On、Off
	LogAccessEnable *string `json:"LogAccessEnable" required:"true"`
	// 日志存储OSS ID，用于存储访问日志的OSS实例ID，当访问日志开关为On时必填，该OSS实例必须存在、状态可用，且与负载均衡位于同一VPC
	LogOssID *string `json:"LogOssID"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
