// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UpdateDigitalCertRequest 更新数字证书
type UpdateDigitalCertRequest struct {
	request.CommonBase

	// 证书ID列表，多个ID用逗号分隔，总长度不超过255字符且数量不超过系统限制
	CertIDs *string `json:"CertIDs"`
}
