// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateVMBootBootLoaderTypeResponse - 设置虚拟机引导方式
type UpdateVMBootBootLoaderTypeResponse struct {
	response.CommonBase

}
