// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdatePartitionTemplateRequest 更新分区模板
type UpdatePartitionTemplateRequest struct {
	request.CommonBase

	// 分区配置
	Config *string `json:"Config"`
	// 模板描述
	Description *string `json:"Description"`
	// 模板ID
	ID *string `json:"ID" required:"true"`
	// 是否默认
	IsDefault *string `json:"IsDefault"`
	// 模板名称
	Name *string `json:"Name"`
	// 地域
	Region *string `json:"Region" required:"true"`
}
