// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UpdateMemberPhoneRequest 修改账号安全手机
type UpdateMemberPhoneRequest struct {
	request.CommonBase

	// 成员ID，指定要更新手机号的账号标识
	MemberID *int `json:"MemberID" required:"true"`
	// 手机号，用于安全通知或验证码接收，需为合法手机号
	PhoneNum *string `json:"PhoneNum" required:"true"`
}
