// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateMulticastGroupRequest 更新组播组
type UpdateMulticastGroupRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID" required:"true"`
	// 接收方虚拟机ID列表，更新后的组播接收端，数量范围1-9个，虚拟机必须与该组播组所属VPC匹配，不能包含发送方，且在同一VPC下IP+Port相同的组播组中不得重复；违反会返回StatusMulticastGroupMemberVPCMismatch或StatusMulticastGroupMemberDuplicate
	MulticastDest []string `json:"MulticastDest" required:"true"`
	// 组播组ID，指定要更新的组播组唯一标识符
	MulticastGroupID *string `json:"MulticastGroupID" required:"true"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
}
