// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateVFLogicCountResponse - 调整逻辑VF数量限制
type UpdateVFLogicCountResponse struct {
	response.CommonBase

}
