// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateAlertNotifyReceiverResponse - 更新告警通知人
type UpdateAlertNotifyReceiverResponse struct {
	response.CommonBase

}
