// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateNICTrafficShapingResponse - 更新网卡流量整形信息
type UpdateNICTrafficShapingResponse struct {
	response.CommonBase

}
