// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateNICMACResponse - 修改网卡的MAC
type UpdateNICMACResponse struct {
	response.CommonBase

}
