// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateDBSBackupPlanResponse - 更新备份计划
type UpdateDBSBackupPlanResponse struct {
	response.CommonBase

}
