// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateVMVCPUBindingResponse - 虚拟机更新VCPU绑定
type UpdateVMVCPUBindingResponse struct {
	response.CommonBase

}
