// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateBucketAccessTypeResponse - 更新桶访问类型
type UpdateBucketAccessTypeResponse struct {
	response.CommonBase

}
