// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateAlertNotifyGroupResponse - 更新告警通知组
type UpdateAlertNotifyGroupResponse struct {
	response.CommonBase

}
