// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdatePaaSDiskQoSResponse - 设置PaaS产品硬盘QoS
type UpdatePaaSDiskQoSResponse struct {
	response.CommonBase

}
