// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateCompanyEmailResponse - 修改租户邮箱
type UpdateCompanyEmailResponse struct {
	response.CommonBase

}
