// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UpdateRegionConfigRequest 更新地域配置
type UpdateRegionConfigRequest struct {
	request.CommonBase

	// 配置键，要更新的地域配置项唯一标识符，
	ConfigKey *string `json:"ConfigKey" required:"true"`
	// 配置值，要设置的新配置值，ConfigKey为VPCNetwork时，需为有效的VPC网段（CIDR格式）
	ConfigValue *string `json:"ConfigValue"`
	// 地域ID，指定要更新配置的地域
	Region *string `json:"Region" required:"true"`
}
