// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UpdateRedisPasswordRequest 更新redis密码
type UpdateRedisPasswordRequest struct {
	request.CommonBase

	// 租户ID，资源所属租户
	CompanyID *int `json:"CompanyID"`
	// 新密码，满足paaspassword校验规则
	Password *string `json:"Password"`
	// Redis实例ID，指定要更新密码的实例；注意：资源必须为AVAILABLE且状态为Running
	RedisID *string `json:"RedisID" required:"true"`
	// 地域ID，资源所属的物理区域
	Region *string `json:"Region" required:"true"`
}
