// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateOrchTaskResponse - 更新编排任务
type UpdateOrchTaskResponse struct {
	response.CommonBase

}
