// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateDirectConnectBandwidthResponse - 修改DirectConnect专线接入限速
type UpdateDirectConnectBandwidthResponse struct {
	response.CommonBase

}
