// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateTrafficMirrorRuleResponse - 更新流量镜像规则
type UpdateTrafficMirrorRuleResponse struct {
	response.CommonBase

}
