// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateNativeNodeInstanceStatusResponse - 更新k8s集群NativeNode实例状态
type UpdateNativeNodeInstanceStatusResponse struct {
	response.CommonBase

}
