// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateMySQLParamTplResponse - 更新MySQL参数模板
type UpdateMySQLParamTplResponse struct {
	response.CommonBase

}
