// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateResourceTemplateResponse - 更新资源模板
type UpdateResourceTemplateResponse struct {
	response.CommonBase

}
