// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UpdateDirectConnectRemoteSubnetCIDRsRequest 修改DirectConnect专线接入远端子网网段
type UpdateDirectConnectRemoteSubnetCIDRsRequest struct {
	request.CommonBase

	// 远端子网网段列表，用户数据中心需要通过专线互连的网段，必须为CIDR格式，此操作会替换专线接入的所有远端子网网段
	CIDRs []string `json:"CIDRs" required:"true"`
	// 专线接入ID，指定要更新远端子网网段的专线接入资源ID
	DirectConnectID *string `json:"DirectConnectID" required:"true"`
	// 地域ID，指定要更新的专线接入所属的物理区域
	Region *string `json:"Region" required:"true"`
}
