// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateASGroupResponse - 更新伸缩组
type UpdateASGroupResponse struct {
	response.CommonBase

}
