// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateNICMACRequest 修改网卡的MAC
type UpdateNICMACRequest struct {
	request.CommonBase

	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID" required:"true"`
	// MAC地址，新的MAC地址，格式为6组2位十六进制数，以冒号或连字符分隔
	MAC *string `json:"MAC" required:"true"`
	// 网卡ID，指定要修改MAC地址的网卡资源
	NICID *string `json:"NICID" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
