// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateDirectConnectRemoteSubnetCIDRsResponse - 修改DirectConnect专线接入远端子网网段
type UpdateDirectConnectRemoteSubnetCIDRsResponse struct {
	response.CommonBase

}
