// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateVMAdvancedOptionsResponse - 设置虚拟机高级参数(DNS)
type UpdateVMAdvancedOptionsResponse struct {
	response.CommonBase

}
