// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// UpdateSecurityGroupRuleResponse - 更新安全组规则
type UpdateSecurityGroupRuleResponse struct {
	response.CommonBase

	// 更新后的规则详情列表，包含更新后的所有规则信息
	Infos []models.SGRuleInfo `json:"Infos"`
	// 规则总数，更新后的规则总数量
	TotalCount *int `json:"TotalCount"`
}
