// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateVMNICModelResponse - 更新虚拟机网卡型号
type UpdateVMNICModelResponse struct {
	response.CommonBase

}
