// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateMemberOAuth2UniqueIDRequest 修改账号OAuth2唯一标识ID
type UpdateMemberOAuth2UniqueIDRequest struct {
	request.CommonBase

	// 成员ID，指定要更新OAuth2标识的账号
	MemberID *int `json:"MemberID" required:"true"`
	// OAuth2唯一标识ID，用于绑定外部身份；留空表示清除该字段，长度不超过200字符
	OAuth2UniqueID *string `json:"OAuth2UniqueID"`
}
