// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateTimerRequest 更新定时器
type UpdateTimerRequest struct {
	request.CommonBase

	// 特定参数，任务策略配置的key:value数组，可用键：PolicySetID、PolicyCompanyIDs、PolicyProjectIDs、PolicyResourceTypes、PolicyDays、PolicyDirPath、PolicyNotifyGroup、PolicyNotifyWhenWarning
	Annotations []string `json:"Annotations"`
	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// 日期，当调度类型为TIMER_TYPE_MONTHLY时必填，指定每月执行日期列表，取值范围1-32，其中32表示每月最后一天（自动适配大小月和二月）
	Days []int `json:"Days"`
	// 固定间隔，当调度类型为TIMER_TYPE_FIXED_INTERVAL时必填，取值范围60-86400秒
	FixedInterval *int `json:"FixedInterval"`
	// 小时，当调度类型为TIMER_TYPE_DAILY、TIMER_TYPE_WEEKLY、TIMER_TYPE_MONTHLY时必填，指定每天执行小时列表，取值范围0-23
	Hours []int `json:"Hours"`
	// 保留数量，当Task为CreateSnapshot/CreateInspection/CreateResUsed时使用，取值范围1-42，默认10
	KeepNum *int `json:"KeepNum"`
	// 定时器名称，更新后的名称用于标识和区分定时任务
	Name *string `json:"Name" required:"true"`
	// 项目ID，定时器所属项目分组标识，更新时保持不变
	ProjectID *string `json:"ProjectID"`
	// 地域ID，用于标识定时器所属的地理区域，更新时可变更定时器所属地域
	Region *string `json:"Region" required:"true"`
	// 备注信息，更新后用于补充说明定时器用途或业务场景
	Remark *string `json:"Remark"`
	// 资源ID列表，当Task为CreateSnapshot时必填，用于指定快照目标资源
	ResourceIDs []string `json:"ResourceIDs"`
	// 资源类型，当Task为CreateSnapshot时有效，默认DISK，DIRECTORY表示文件目录
	ResourceType *string `json:"ResourceType"`
	// 保留时长（单位：天），当Task为PlatformFileBackup/PlatformDBBackup时使用，默认10天
	Retention *int `json:"Retention"`
	// 任务类型，定时器执行的业务操作类型，取值：CreateSnapshot（为云硬盘创建快照，用于数据备份和恢复）、DBSBackUP（数据库备份任务）、CreateInspection（平台巡检任务，用于系统健康检查）、CreateResUsed（资源用量统计任务，用于生成资源使用报表）PlatformDBBackup(平台数据库备份) PlatformFileBackup(平台配置文件备份)
	Task *string `json:"Task" required:"true"`
	// 定时器ID，用于指定需要更新的定时器，要求定时器处于可用状态
	TimerID *string `json:"TimerID" required:"true"`
	// 单次触发时间，当调度类型为TIMER_TYPE_ONCE时必填，秒级Unix时间戳且必须大于当前时间
	TriggerTime *int `json:"TriggerTime"`
	// 调度类型，定义定时器触发规则，取值：TIMER_TYPE_ONCE（单次执行，在指定时间点执行一次）、TIMER_TYPE_DAILY（每日执行，每天在指定时间执行）、TIMER_TYPE_WEEKLY（每周执行，每周在指定星期和时间执行）、TIMER_TYPE_MONTHLY（每月执行，每月在指定日期和时间执行）、TIMER_TYPE_FIXED_INTERVAL（固定间隔执行，按指定时间间隔周期性执行）
	Type *string `json:"Type" required:"true"`
	// 星期，当调度类型为TIMER_TYPE_WEEKLY时必填，指定每周执行星期列表，取值范围0-7对应周一到周日
	Weeks []int `json:"Weeks"`
}
