// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateTrafficMirrorResponse - 更新流量镜像
type UpdateTrafficMirrorResponse struct {
	response.CommonBase

}
