// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateLBLogResponse - 更新负载均衡
type UpdateLBLogResponse struct {
	response.CommonBase

}
