// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateDTSInstanceSpecResponse - 更新 DTS 实例规格
type UpdateDTSInstanceSpecResponse struct {
	response.CommonBase

}
