// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateNICPFResponse - 修改网卡的物理型号
type UpdateNICPFResponse struct {
	response.CommonBase

}
