// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateLoginWhitelistResponse - 设置用户登录IP白名单
type UpdateLoginWhitelistResponse struct {
	response.CommonBase

}
