// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateNICIPBandwidthRequest 修改弹性外网网卡的IP带宽
type UpdateNICIPBandwidthRequest struct {
	request.CommonBase

	// 带宽，单位Mbps，指定网卡的新带宽值；WAN会触发计费差价
	Bandwidth *int `json:"Bandwidth" required:"true"`
	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID" required:"true"`
	// 弹性网卡ID，指定要修改带宽的网卡资源；仅支持WAN/Flat类型
	NICID *string `json:"NICID" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
