// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateMemberEmailResponse - 修改账号邮箱
type UpdateMemberEmailResponse struct {
	response.CommonBase

}
