// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateDiscountResponse - 更新折扣
type UpdateDiscountResponse struct {
	response.CommonBase

}
