// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateVIPBindResourceResponse - 更新VIP绑定资源
type UpdateVIPBindResourceResponse struct {
	response.CommonBase

}
