// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UpdateNICPFRequest 修改网卡的物理型号
type UpdateNICPFRequest struct {
	request.CommonBase

	// 租户ID，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 网卡ID，指定要修改物理网卡型号的网卡资源
	NICID *string `json:"NICID" required:"true"`
	// 物理网卡型号标准编号，用于SR-IOV直通场景；传空字符串表示取消SR-IOV；操作前提：1.网卡已绑定给虚拟机2.虚拟机已关机
	PFCode *string `json:"PFCode"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
