// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UpdateNodeCPUGovernorRequest 更新节点 CPU 电源模式
type UpdateNodeCPUGovernorRequest struct {
	request.CommonBase

	// 电源模式，取值performance（性能）、powersave（节能）、ondemand（自动，部分机器不支持）
	Governor *string `json:"Governor" required:"true"`
	// 节点ID，用于标识节点唯一标识
	HostID *string `json:"HostID" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
