// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateDiscountResponse - 更新折扣
type UpdateDiscountResponse struct {
	response.CommonBase

}
