// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateVMDefaultGWResponse - 设置虚拟机出口
type UpdateVMDefaultGWResponse struct {
	response.CommonBase

}
