// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateCompanyRegionRequest 修改租户地域授权
type UpdateCompanyRegionRequest struct {
	request.CommonBase

	// 租户ID，请求传入用于定位要授权地域的租户，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID" required:"true"`
	// 地域ID列表，请求传入用于授予租户访问权限的地域集合，控制租户可创建和管理资源的物理区域范围
	Regions []string `json:"Regions" required:"true"`
}
