// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UpdateImageRequest 修改镜像属性
type UpdateImageRequest struct {
	request.CommonBase

	// 引导类型，取值bios、uefi
	BootloaderType *string `json:"BootloaderType"`
	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID" required:"true"`
	// 镜像ID，需修改属性的目标镜像标识，镜像需处于可用状态
	ImageID *string `json:"ImageID" required:"true"`
	// 操作系统发行版，如Ubuntu、CentOS
	OSDistribution *string `json:"OSDistribution" required:"true"`
	// 操作系统类型，如Linux、Windows
	OSType *string `json:"OSType" required:"true"`
	// 操作系统版本，标识内部安装的具体补丁或版本号
	OSVersion *string `json:"OSVersion" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 架构类型，基于计算集群支持的指令集，如x86_64、aarch64
	SetArch *string `json:"SetArch" required:"true"`
	// Cloud-Init支持，标识镜像是否支持自动化初始化
	SupportCloudInit *bool `json:"SupportCloudInit"`
	// QEMU Guest Agent支持，标识镜像是否支持QGA通讯
	SupportQGA *bool `json:"SupportQGA"`
}
