// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UpdateAlertTemplateRequest 更新告警模版
type UpdateAlertTemplateRequest struct {
	request.CommonBase

	// 告警模板名称，长度1-128字符，支持中英文、数字、点、下划线和中划线
	Name *string `json:"Name" required:"true"`
	// 备注信息，用于对告警模板的补充说明，长度0-100字符，不能包含http://或https://等URL
	Remark *string `json:"Remark"`
	// 告警模板ID，指定要更新的告警模板ID，必须为当前租户可管理的模板
	TemplateID *string `json:"TemplateID" required:"true"`
}
