// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateCompanyRegionResponse - 修改租户地域授权
type UpdateCompanyRegionResponse struct {
	response.CommonBase

}
