// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateVPNTunnelResponse - 更新隧道信息
type UpdateVPNTunnelResponse struct {
	response.CommonBase

}
