// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateApplicationNodeResponse - 更新审批节点信息
type UpdateApplicationNodeResponse struct {
	response.CommonBase

}
