// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateAdminRegionResponse - 修改管理员地域授权
type UpdateAdminRegionResponse struct {
	response.CommonBase

}
