// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateVMISOSlotResponse - 设置虚拟机iso插槽数量
type UpdateVMISOSlotResponse struct {
	response.CommonBase

}
