// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateMySQLParamTplResponse - 更新MySQL参数模板
type UpdateMySQLParamTplResponse struct {
	response.CommonBase

}
