// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateLoginWhitelistRequest 设置用户登录IP白名单
type UpdateLoginWhitelistRequest struct {
	request.CommonBase

	// 租户ID，请求传入用于设置登录白名单的租户
	CompanyID *int `json:"CompanyID" required:"true"`
	// IP白名单，请求传入并设置允许登录的IP或网段，多个值用逗号分隔；为空表示不限制；安全控制场景使用，仅主账号或系统管理员可设置
	Whitelist *string `json:"Whitelist"`
}
