// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateBucketObjectLockResponse - 更新桶的对象锁定开关
type UpdateBucketObjectLockResponse struct {
	response.CommonBase

}
