// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UpdateVMDiskCacheModeRequest 设置虚拟机磁盘缓存类型
type UpdateVMDiskCacheModeRequest struct {
	request.CommonBase

	// 缓存类型，取值 directsync、none、writeback
	CacheMode *string `json:"CacheMode"`
	// 磁盘id
	Disk *string `json:"Disk"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 虚拟机ID，待修改配置的虚拟机标识
	VMID *string `json:"VMID" required:"true"`
}
