// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateBucketVersioningResponse - 更新桶的多版本开关
type UpdateBucketVersioningResponse struct {
	response.CommonBase

}
