// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// UpdateBMCTypeResponse - 更新BMC类型
type UpdateBMCTypeResponse struct {
	response.CommonBase

	// BMC类型信息
	BMCType *models.BMCType `json:"BMCType"`
}
