// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateResourcePermissionResponse - 修改资源权限
type UpdateResourcePermissionResponse struct {
	response.CommonBase

}
