// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateIsolationGroupResponse - 更新隔离组
type UpdateIsolationGroupResponse struct {
	response.CommonBase

}
