// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateNICIPResponse - 更新网卡的IP
type UpdateNICIPResponse struct {
	response.CommonBase

}
