// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UpdateVMCPUHypervisorRequest 设置虚拟机CPU虚拟化隐藏标记
type UpdateVMCPUHypervisorRequest struct {
	request.CommonBase

	// 是否隐藏虚拟化标记，true表示隐藏，false表示不隐藏
	CPUHypervisorDisable *bool `json:"CPUHypervisorDisable"`
	// 租户唯一标识ID
	CompanyID *int `json:"CompanyID"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 虚拟机ID
	VMID *string `json:"VMID" required:"true"`
}
