// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UpdateIsolationGroupRequest 更新隔离组
type UpdateIsolationGroupRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID" required:"true"`
	// 隔离组ID，指定要更新的隔离组
	IGID *string `json:"IGID" required:"true"`
	// 是否启用，设置策略是否生效，不传表示不修改
	IsEnable *bool `json:"IsEnable"`
	// 是否强制执行，设置策略执行方式，不传表示不修改
	IsForce *bool `json:"IsForce"`
	// 策略对象列表，用于更新隔离组策略对象
	PolicyObj []string `json:"PolicyObj"`
	// 策略类型，用于更新隔离组策略类型，取值VMAffinity/VMAntiAffinity
	PolicyType *string `json:"PolicyType"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
