// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateRedisConfigParamsRequest 更新配置项
type UpdateRedisConfigParamsRequest struct {
	request.CommonBase

	// 租户ID，配置所属租户
	CompanyID *int `json:"CompanyID"`
	// 配置文件ID，参数模板ID或Redis实例ID（redis-config-前缀表示模板ID）
	ConfigID *string `json:"ConfigID" required:"true"`
	// Redis配置项，配置参数列表，格式为key:value
	Params []string `json:"Params" required:"true"`
}
