// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateVMUserDataResponse - 设置虚拟机用户数据
type UpdateVMUserDataResponse struct {
	response.CommonBase

}
