// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateMemberNameResponse - 修改账号名称
type UpdateMemberNameResponse struct {
	response.CommonBase

}
