// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdatePortGroupResponse - 更新端口组
type UpdatePortGroupResponse struct {
	response.CommonBase

}
