// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateResourceEventNotifyRuleResponse - 更新资源事件通知规则
type UpdateResourceEventNotifyRuleResponse struct {
	response.CommonBase

}
