// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UpdateFlatNetworkRouteRequest 更新扁平网络路由
type UpdateFlatNetworkRouteRequest struct {
	request.CommonBase

	// 目的地址CIDR，指定要更新的路由目标网段；该路由必须已存在
	Destination *string `json:"Destination" required:"true"`
	// 扁平网络ID，指定路由所属的扁平网络唯一标识
	FlatNetworkID *string `json:"FlatNetworkID" required:"true"`
	// 下一跳地址，更新数据包转发的网关IP地址，必须在扁平网络的CIDR范围内
	NextHop *string `json:"NextHop" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 备注信息，用于说明和注释，长度0-100字符，禁止http://或https://等非法字符
	Remark *string `json:"Remark"`
}
