// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateBucketLifecycleRuleResponse - 更新桶的生命周期
type UpdateBucketLifecycleRuleResponse struct {
	response.CommonBase

}
