// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UpdateVMMACRequest 修改网卡的MAC
type UpdateVMMACRequest struct {
	request.CommonBase

	// MAC地址，新的物理地址，格式为XX:XX:XX:XX:XX:XX
	MAC *string `json:"MAC" required:"true"`
	// 网卡类型，待修改MAC的网卡类型，取值：LAN、WAN、Flat
	NICType *string `json:"NICType" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 虚拟机ID，待修改MAC的虚拟机标识
	VMID *string `json:"VMID" required:"true"`
}
