// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdatePriceResponse - 更新价格
type UpdatePriceResponse struct {
	response.CommonBase

}
