// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateNativeNodeWANResponse - 更新k8s集群NativeNode外网
type UpdateNativeNodeWANResponse struct {
	response.CommonBase

}
