// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateTrafficMirrorSourcesResponse - 更新流量镜像源设备信息
type UpdateTrafficMirrorSourcesResponse struct {
	response.CommonBase

}
