// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UpdatePaaSDiskQoSRequest 设置PaaS产品硬盘QoS
type UpdatePaaSDiskQoSRequest struct {
	request.CommonBase

	// 租户唯一标识ID，保留字段，当前不会作为后端校验条件
	CompanyID *int `json:"CompanyID" required:"true"`
	// 磁盘带宽（MB/s），0表示不限速，其他值会写入资源注解AK_BandWidth并将状态置为UpdatingQoS
	DiskBandwidth *int `json:"DiskBandwidth"`
	// 磁盘IOPS，0表示不限速，其他值会写入资源注解AK_IOPS并将状态置为UpdatingQoS
	DiskIOPS *int `json:"DiskIOPS"`
	// 地域ID，保留字段；资源所属地域由ResourceID决定，但仍需按标准传入
	Region *string `json:"Region" required:"true"`
	// 资源ID，指定要设置磁盘QoS的PaaS资源，仅支持FS/OSS/MYSQL类型，其余类型会返回错误
	ResourceID *string `json:"ResourceID" required:"true"`
}
