// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateVSRequest 更新VS
type UpdateVSRequest struct {
	request.CommonBase

	// 后端协议，后端使用的协议，取值范围：空（默认HTTP）、HTTP、HTTPS，仅在协议为HTTPS时有效
	BackendProtocol *string `json:"BackendProtocol"`
	// CA证书ID，用于验证客户端证书的签名，仅当协议为HTTPS且SSLMode为双向认证时有效
	CACertificateID *string `json:"CACertificateID"`
	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// HTTP健康检查域名，HTTP检查时校验的HOST字段域名，当健康检查类型为Path时可配置，且需满足validate.IsValidDomain规则（与Nginx server_name一致，支持*.example.com/mail.*等通配）
	Domain *string `json:"Domain"`
	// 健康检查类型，健康检查的类型，取值范围：Port、Path，TCP和UDP协议只支持Port类型
	HealthcheckType *string `json:"HealthcheckType"`
	// 请求体大小限制，单位MB，最大512；仅HTTP/HTTPS协议有效，0表示保留原值
	HttpClientMaxBodySizeMB *int `json:"HttpClientMaxBodySizeMB"`
	// 请求头大小限制，单位KB，最大512；仅HTTP/HTTPS协议有效，0表示保留原值
	HttpClientMaxHeaderSizeKB *int `json:"HttpClientMaxHeaderSizeKB"`
	// 连接空闲超时时间，负载均衡的连接空闲超时时间，单位为秒，默认值为60s
	KeepaliveTimeout *int `json:"KeepaliveTimeout"`
	// 负载均衡ID，用于定位需要更新监听器的负载均衡实例
	LBID *string `json:"LBID" required:"true"`
	// HTTP健康检查路径，HTTP检查时的请求路径，当健康检查类型为Path时可配置，且必须指定以/开头的合法URL路径
	Path *string `json:"Path"`
	// 会话保持KEY，会话保持的键，当类型为Manual时为必填，仅当协议为HTTP时有效
	PersistenceKey *string `json:"PersistenceKey"`
	// 会话保持类型，会话保持的类型，取值范围：None、Auto、Manual，若不指定则默认为None
	PersistenceType *string `json:"PersistenceType"`
	// 虚拟服务器端口，VServer的监听端口，端口范围为1~65535，其中323、9102~9105、60909~60910被系统占用
	Port *int `json:"Port"`
	// TCP Proxy Protocol开关，是否开启TCP Proxy Protocol，取值范围：On、Off
	ProxyProtocolEnable *string `json:"ProxyProtocolEnable"`
	// HTTP重定向开关，是否开启HTTP重定向，仅HTTP协议有效；取值范围：On、Off
	RedirectEnable *string `json:"RedirectEnable"`
	// HTTP重定向目标VSID，重定向到的虚拟服务器ID，仅当RedirectEnable=On时必填，其余情况下必须为空
	RedirectVsID *string `json:"RedirectVsID"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// SSL认证模式，SSL的认证模式，取值范围：simplex（单向认证）、duplex（双向认证），必填字段，仅HTTPS协议时生效
	SSLMode *string `json:"SSLMode" required:"true"`
	// 调度算法，负载均衡的调度算法，取值范围：wrr、least_conn、hash、ip_hash
	Scheduler *string `json:"Scheduler"`
	// 服务器证书ID，用于证明服务器的身份，仅当协议为HTTPS时有效
	ServerCertificateID *string `json:"ServerCertificateID"`
	// 虚拟服务器ID，用于定位需要更新的监听器实例，仅支持来源为Default的监听器（Service/Ingress来源由容器系统管理，调用会返回StatusCanNotModifyNoDefaultOriginVS错误）
	VSID *string `json:"VSID" required:"true"`
}
