// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateVMDiskCacheModeResponse - 设置虚拟机磁盘缓存类型
type UpdateVMDiskCacheModeResponse struct {
	response.CommonBase

}
