// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateConfigResponse - 更新配置
type UpdateConfigResponse struct {
	response.CommonBase

}
