// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateCompanyNameResponse - 更新租户名称
type UpdateCompanyNameResponse struct {
	response.CommonBase

}
