// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UpdateOPLogNotifyRuleRequest 更新操作日志通知规则
type UpdateOPLogNotifyRuleRequest struct {
	request.CommonBase

	// 监控级别列表，取值：success/failure
	MonitorLevel []string `json:"MonitorLevel" required:"true"`
	// 监控模块列表，指定监控哪些资源模块的操作日志
	MonitorModule []string `json:"MonitorModule" required:"true"`
	// 监控地域，指定监控地域的操作日志
	MonitorRegion *string `json:"MonitorRegion" required:"true"`
	// 通知组ID，通知规则所属通知组ID
	NotifyGroupID *string `json:"NotifyGroupID" required:"true"`
	// 规则ID，操作日志通知规则ID
	RuleID *string `json:"RuleID" required:"true"`
}
