// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateBucketEventLoggingRequest 更新对象存储桶是否开启事件日志
type UpdateBucketEventLoggingRequest struct {
	request.CommonBase

	// 桶名称，存储桶名称
	Bucket *string `json:"Bucket" required:"true"`
	// 事件日志开关，取值范围：on/off
	EventLoggingSwitch *string `json:"EventLoggingSwitch" required:"true"`
	// 对象存储ID，对象存储实例标识
	OSSID *string `json:"OSSID" required:"true"`
	// 地域ID，指定资源所属的地域
	Region *string `json:"Region" required:"true"`
}
