// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateBucketQuotaResponse - 更新存储桶配额
type UpdateBucketQuotaResponse struct {
	response.CommonBase

}
