// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateAlertTemplateRuleResponse - 更新告警通知规则
type UpdateAlertTemplateRuleResponse struct {
	response.CommonBase

}
