// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateAlertNotifyWebhookResponse - 更新告警回调接口
type UpdateAlertNotifyWebhookResponse struct {
	response.CommonBase

}
