// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateVMBootBootLoaderTypeRequest 设置虚拟机引导方式
type UpdateVMBootBootLoaderTypeRequest struct {
	request.CommonBase

	// 引导方式，虚拟机的系统引导协议，取值：bios、uefi
	BootloaderType *string `json:"BootloaderType"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 虚拟机ID，待修改配置的虚拟机标识
	VMID *string `json:"VMID" required:"true"`
}
