// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateDTSInstanceSpecRequest 更新 DTS 实例规格
type UpdateDTSInstanceSpecRequest struct {
	request.CommonBase

	// CPU核数，升级后的CPU配置，任务需处于可用状态
	CPU *int `json:"CPU" required:"true"`
	// DTS任务ID，待升级规格的DTS任务唯一标识
	DTSID *string `json:"DTSID" required:"true"`
	// 内存大小，单位GB，升级后的内存配置，任务需处于可用状态
	Memory *int `json:"Memory" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
