// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateImageResponse - 修改镜像属性
type UpdateImageResponse struct {
	response.CommonBase

}
