// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UpdatePMV2Request 更新裸金属
type UpdatePMV2Request struct {
	request.CommonBase

	// BMC类型名称，标识硬件厂商的BMC类型，可选
	BMCTypeName *string `json:"BMCTypeName"`
	// 自定义监控地址，用于Prometheus等监控系统采集指标，可选
	CustomMetricsPath *string `json:"CustomMetricsPath"`
	// IPMI管理IP地址，用于带外管理访问，可选
	IPMIIP *string `json:"IPMIIP"`
	// IPMI密码，用于IPMI身份验证，可选
	IPMIPassword *string `json:"IPMIPassword"`
	// IPMI用户名，用于IPMI身份验证，可选
	IPMIUsername *string `json:"IPMIUsername"`
	// 生产厂商，从BMC/IPMI FRU信息采集，可选
	Manufacturer *string `json:"Manufacturer"`
	// 资源名称，长度为1-128个字符，名称只能包含中英文、数字、点（.）、下划线（_）和中划线（-），可选，若不指定则不更新
	Name *string `json:"Name"`
	// 裸金属ID，指定要更新的裸金属实例
	PMID *string `json:"PMID" required:"true"`
	// 产品名称，从BMC/IPMI FRU信息采集，可选
	ProductName *string `json:"ProductName"`
	// 机架位置，标识裸金属在数据中心的物理位置，可选
	RackLocation *string `json:"RackLocation"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
	// 备注，用于进行说明和注释，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符，可选，若不指定则不更新
	Remark *string `json:"Remark"`
}
