// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateNodeCPUGovernorResponse - 更新节点 CPU 电源模式
type UpdateNodeCPUGovernorResponse struct {
	response.CommonBase

}
