// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpdateWorkflowResponse - 更新自定义流程
type UpdateWorkflowResponse struct {
	response.CommonBase

}
