// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateRegionRequest 更新地域
type UpdateRegionRequest struct {
	request.CommonBase

	// 地址，请求传入并更新数据中心详细物理地址
	Address *string `json:"Address"`
	// 城市，请求传入并更新地域所属行政城市名称
	City *string `json:"City" required:"true"`
	// 地域名称，请求传入并更新地域显示名称，用于展示地域信息，长度为1-30个字符，只能包含中英文、数字、点、下划线和中划线
	Name *string `json:"Name" required:"true"`
	// 地域ID，请求传入并定位要更新的地域
	Region *string `json:"Region" required:"true"`
	// 备注，请求传入并更新地域说明信息，可用于备注用途或状态，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符，
	Remark *string `json:"Remark"`
}
