// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpgradeFSResponse - 文件存储扩容
type UpgradeFSResponse struct {
	response.CommonBase

}
