// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpgradeLBToHAResponse - 升级为高可用版本
type UpgradeLBToHAResponse struct {
	response.CommonBase

}
