// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpgradeMySQLToHAResponse - 升级为高可用版本
type UpgradeMySQLToHAResponse struct {
	response.CommonBase

}
