// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/request"
)

// UpgradeOSSRequest 对象存储升级
type UpgradeOSSRequest struct {
	request.CommonBase

	// CPU核数，扩容后的CPU核数需大于或等于当前值，取值范围：2、4、6、8、10、12、14、16
	CPU *int `json:"CPU"`
	// 租户ID，资源所属租户标识
	CompanyID *int `json:"CompanyID"`
	// 存储容量，单位GiB，扩容后容量需大于或等于当前容量，最小值100
	DiskSpace *int `json:"DiskSpace" required:"true"`
	// 对象存储ID，要扩容的对象存储标识，对象存储状态必须为Running或Stopped
	OSSID *string `json:"OSSID" required:"true"`
	// 地域ID，指定资源所属的地域
	Region *string `json:"Region" required:"true"`
}
