// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// UpgradeMySQLResponse - 升级MySQL
type UpgradeMySQLResponse struct {
	response.CommonBase

}
