// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
	"third_party/platform-sdk-go/services/openapi/models"
)

// ValidatePartitionConfigResponse - 验证分区配置
type ValidatePartitionConfigResponse struct {
	response.CommonBase

	// 验证结果
	Result *models.ValidatePartitionConfigResult `json:"Result"`
}
