// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// ValidateKickstartTemplateRequest 验证Kickstart模板语法
type ValidateKickstartTemplateRequest struct {
	request.CommonBase

	// 模板名称
	Name *string `json:"Name" required:"true"`
	// 地域
	Region *string `json:"Region" required:"true"`
}
