// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"third_party/platform-sdk-go/common/response"
)

// VerifyEmailAvailabilityResponse - 验证邮箱服务器可用性
type VerifyEmailAvailabilityResponse struct {
	response.CommonBase

}
