// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// AbortMigratePaaSInstanceRequest PaaS 取消计算迁移
type AbortMigratePaaSInstanceRequest struct {
	request.CommonBase

	// 租户ID，保留字段
	CompanyID *int `json:"CompanyID" required:"true"`
	// 实例ID，只有当迁移进度仍为0或迁移已报错( MigrationError=true )时才允许取消；其他状态会返回参数错误
	InstanceID *string `json:"InstanceID" required:"true"`
	// 地域ID，指定资源所属地域
	Region *string `json:"Region" required:"true"`
	// 资源ID，仅当资源处于计算迁移中时才能取消迁移
	ResourceID *string `json:"ResourceID" required:"true"`
}
