// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// AbortMigrateVMInstanceResponse - 取消虚机迁移
type AbortMigrateVMInstanceResponse struct {
	response.CommonBase

}
