// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// AbortMigrateVMDiskResponse - 取消虚拟机热存储迁移
type AbortMigrateVMDiskResponse struct {
	response.CommonBase

}
