// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// AddVMToIsolationGroupResponse - 添加VM到隔离组
type AddVMToIsolationGroupResponse struct {
	response.CommonBase

}
