// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// AddVPCNetworkResponse - 添加VPC IPv6网络
type AddVPCNetworkResponse struct {
	response.CommonBase

}
