// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// AllocateVIPResponse - 申请VIP
type AllocateVIPResponse struct {
	response.CommonBase

	// VIPID，VIP的唯一标识符，用于后续管理操作
	VIPID *string `json:"VIPID"`
}
