// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// AllocatePMResponse - 分配裸金属给租户
type AllocatePMResponse struct {
	response.CommonBase

}
