// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// AllocateK8SSessionResponse - 申请console会话
type AllocateK8SSessionResponse struct {
	response.CommonBase

	// 
	SessionID *string `json:"SessionID"`
}
