// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// AllocateEIPResponse - 申请弹性IP
type AllocateEIPResponse struct {
	response.CommonBase

	// EIP资源ID，弹性IP的唯一标识符，申请成功后系统自动生成
	EIPID *string `json:"EIPID"`
}
