// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// AllocateNodeHostDeviceResponse - 分配外置设备给租户
type AllocateNodeHostDeviceResponse struct {
	response.CommonBase

}
