// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// ApplyMySQLParamTplResponse - 应用MySQL参数模板
type ApplyMySQLParamTplResponse struct {
	response.CommonBase

}
