// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// AttachUSBResponse - 加载USB设备
type AttachUSBResponse struct {
	response.CommonBase

}
