// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// AttachPlatformStorageDiskRequest 绑定平台通用存储云盘
type AttachPlatformStorageDiskRequest struct {
	request.CommonBase

	// 磁盘ID，待绑定的平台通用存储云盘ID
	DiskID *string `json:"DiskID" required:"true"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
}
