// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// BindTagResponse - 绑定标签
type BindTagResponse struct {
	response.CommonBase

}
