// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// BindSecurityGroupRequest 绑定安全组
type BindSecurityGroupRequest struct {
	request.CommonBase

	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID" required:"true"`
	// 网卡类型，取值LAN/WAN；对于MySQL/Redis/OSS/FS仅支持WAN
	NICType *string `json:"NICType" required:"true"`
	// 地域ID，用于标识资源和安全组所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 资源ID，指定要绑定安全组的资源唯一标识符，支持VM、ELASTIC_NIC、OSS、FS、MySQL、Redis等资源类型
	ResourceID *string `json:"ResourceID" required:"true"`
	// 安全组ID，指定要绑定的安全组唯一标识符；安全组需处于Available状态
	SGID *string `json:"SGID" required:"true"`
}
