// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// CloneBMCTypeResponse - 克隆BMC类型
type CloneBMCTypeResponse struct {
	response.CommonBase

	// BMC类型信息
	BMCType *models.BMCType `json:"BMCType"`
}
