// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// CountTenantResourceByStatusResponse - 获取资源状态统计图表
type CountTenantResourceByStatusResponse struct {
	response.CommonBase

	// 资源状态数量列表，包含各类资源状态的数量
	Infos []models.ResourceStatusCountInfo `json:"Infos"`
}
