// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateRemoteVPNGWResponse - 创建对端网关
type CreateRemoteVPNGWResponse struct {
	response.CommonBase

	// 对端网关ID，创建成功的对端网关唯一标识
	RemoteVPNGWID *string `json:"RemoteVPNGWID"`
}
