// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// CreateClusterRequest 创建k8s集群
type CreateClusterRequest struct {
	request.CommonBase

	// 审批名称
	ApplicationName *string `json:"ApplicationName"`
	// 审批理由
	ApplicationReason *string `json:"ApplicationReason"`
	// 计费类型
	ChargeType *string `json:"ChargeType" required:"true"`
	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// 计算集群类型
	ComputeclassType *string `json:"ComputeclassType" required:"true"`
	// APIServer EIPID
	EIPID *string `json:"EIPID"`
	// 高可用类型
	HighAvailability *string `json:"HighAvailability"`
	// k8s版本号。可为1.25.0
	K8SVersion *string `json:"K8SVersion" required:"true"`
	// 名称
	Name *string `json:"Name" required:"true"`
	// Pod子网ID
	PodSubnetIDs []string `json:"PodSubnetIDs"`
	// 项目组ID，未传时尝试分配默认项目
	ProjectID *string `json:"ProjectID"`
	// 计费数量
	Quantity *int `json:"Quantity" required:"true"`
	// 地域
	Region *string `json:"Region" required:"true"`
	// 备注
	Remark *string `json:"Remark"`
	// Service CIDR
	ServiceCIDR *string `json:"ServiceCIDR" required:"true"`
	// 存储集群类型
	StorageclassType *string `json:"StorageclassType" required:"true"`
	// 子网Id
	SubnetID *string `json:"SubnetID" required:"true"`
	// 标签键值对
	TagKeyValuePairs []string `json:"TagKeyValuePairs" required:"true"`
	// VpcID
	VpcID *string `json:"VpcID" required:"true"`
}
