// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateSegmentResponse - 创建外网线路
type CreateSegmentResponse struct {
	response.CommonBase

	// 线路ID，创建成功返回的外网线路ID
	SegmentID *string `json:"SegmentID"`
}
