// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// CreateFlatNetworkRequest 创建扁平网络
type CreateFlatNetworkRequest struct {
	request.CommonBase

	// 网段CIDR，定义扁平网络的IP地址范围
	CIDR *string `json:"CIDR"`
	// DHCP服务器IP地址，指定DHCP服务监听的IP地址，启用DHCP时建议传入，不启用时为空
	DHCPServerIP *string `json:"DHCPServerIP"`
	// 物理网卡设备名称，指定扁平网络绑定的物理网络接口
	Device *string `json:"Device" required:"true"`
	// 是否开启DHCP服务，启用后将为接入网络的主机自动分配IP地址
	EnableDHCP *bool `json:"EnableDHCP"`
	// 可用IP范围，指定从网段中可分配的IP地址范围，支持多个范围用逗号分隔，格式为192.168.1.10-192.168.1.20
	IPRange *string `json:"IPRange"`
	// 扁平网络名称，用于标识扁平网络资源，长度为1-128个字符，名称只能包含中英文、数字、点、下划线和中划线
	Name *string `json:"Name" required:"true"`
	// 权限配置，指定可访问该扁平网络的租户范围；传all表示所有租户可用，传租户ID列表(逗号分隔)表示仅指定租户可用
	Permission *string `json:"Permission" required:"true"`
	// 权限模式，控制租户访问权限的模式，可选值：all（所有租户可用，默认值）、whitelist（白名单，仅指定租户可用）、blacklist（黑名单，仅指定租户不可用）
	PermissionMode *string `json:"PermissionMode"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 备注信息，用于说明和注释，长度0-100字符，禁止http://或https://等非法字符
	Remark *string `json:"Remark"`
	// 标签键值对，格式为Base64编码的key:value字符串，用于资源标记和分类管理
	TagKeyValuePairs []string `json:"TagKeyValuePairs" required:"true"`
	// VLAN标识，用于网络隔离和流量标记，可选，取值范围1-4094，不传或传0表示不设置VLAN
	Vlan *string `json:"Vlan"`
}
