// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateMemberTagResponse - 添加角色授权
type CreateMemberTagResponse struct {
	response.CommonBase

}
