// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// CreateFlatNetworkRouteRequest 创建扁平网络路由
type CreateFlatNetworkRouteRequest struct {
	request.CommonBase

	// 目的地址CIDR，指定路由目标网段；单个扁平网络最多50条路由；目的地址已存在则创建失败
	Destination *string `json:"Destination" required:"true"`
	// 扁平网络ID，指定要添加路由的扁平网络唯一标识
	FlatNetworkID *string `json:"FlatNetworkID" required:"true"`
	// 下一跳地址，指定数据包转发的网关IP地址，必须在扁平网络的CIDR范围内
	NextHop *string `json:"NextHop" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 备注信息，用于说明和注释，长度0-100字符，禁止http://或https://等非法字符
	Remark *string `json:"Remark"`
}
