// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// CreateSecurityGroupRuleRequest 新建安全组规则
type CreateSecurityGroupRuleRequest struct {
	request.CommonBase

	// 租户ID，标识安全组所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID" required:"true"`
	// 项目ID，规则所属项目分组标识
	ProjectID *string `json:"ProjectID"`
	// 地域ID，用于标识安全组所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 安全组规则列表，定义要添加的流量控制策略；每条规则格式：协议|端口|地址|动作|优先级|方向|备注；协议支持TCP/UDP/ICMP/ICMPv4/ICMPv6/ALL，端口支持1-65535或端口范围，地址支持IP/CIDR或group:IPGroupID，动作支持ACCEPT/DROP，优先级支持HIGH/MEDIUM/LOW，方向1为入站0为出站；端口组引用格式：group:PortGroupID|-|地址|动作|优先级|方向|备注；备注长度不超过100字符
	Rules []string `json:"Rules" required:"true"`
	// 安全组ID，指定要添加规则的安全组唯一标识符；安全组需处于Available状态
	SGID *string `json:"SGID" required:"true"`
}
