// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateAlertNotifyGroupResponse - 创建告警通知组
type CreateAlertNotifyGroupResponse struct {
	response.CommonBase

	// 通知组ID，通知组唯一标识，格式为ng-前缀加14位随机字符
	NotifyGroupID *string `json:"NotifyGroupID"`
}
