// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateNICResponse - 创建网卡
type CreateNICResponse struct {
	response.CommonBase

	// 弹性网卡ID，新创建的网卡资源的唯一标识
	NICID *string `json:"NICID"`
}
