// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateContainerImageRepositoryResponse - 创建镜像仓库
type CreateContainerImageRepositoryResponse struct {
	response.CommonBase

}
