// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// CreateResourceTemplateRequest 创建资源模板
type CreateResourceTemplateRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID" required:"true"`
	// 模板内容，JSON字符串格式，等同于相应资源的创建接口入参，用于生成模板资源的公共字段及业务配置
	Content *string `json:"Content" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 模板类型，当前仅支持虚拟机模板
	TemplateType *string `json:"TemplateType" required:"true"`
}
