// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateSecurityGroupRuleResponse - 新建安全组规则
type CreateSecurityGroupRuleResponse struct {
	response.CommonBase

}
