// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateVPCResponse - 创建VPC
type CreateVPCResponse struct {
	response.CommonBase

	// VPCID，新创建的虚拟私有网络唯一标识符
	VPCID *string `json:"VPCID"`
}
