// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateSubMemberResponse - 创建用户
type CreateSubMemberResponse struct {
	response.CommonBase

	// 成员ID，创建成功后返回的账号标识
	MemberID *int `json:"MemberID"`
}
