// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateNativeNodeResponse - 创建k8s集群原生节点
type CreateNativeNodeResponse struct {
	response.CommonBase

	// 节点名称
	NodeName *string `json:"NodeName"`
}
