// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateSnapshotResponse - 创建快照
type CreateSnapshotResponse struct {
	response.CommonBase

	// 快照ID，创建得到的快照标识
	SnapshotID *string `json:"SnapshotID"`
}
