// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// CreateRSRequest 添加服务节点
type CreateRSRequest struct {
	request.CommonBase

	// 绑定资源ID，BindResourceType为空或VM时传虚拟机ID，BindResourceType为OSS时传对象存储ID
	BindResourceID *string `json:"BindResourceID" required:"true"`
	// 绑定资源类型，空或VM表示虚拟机，OSS表示对象存储
	BindResourceType *string `json:"BindResourceType"`
	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 负载均衡ID，用于定位需要添加服务节点的负载均衡实例
	LBID *string `json:"LBID" required:"true"`
	// 服务端口，服务节点暴露的服务端口号
	Port *int `json:"Port" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 虚拟服务器ID，用于定位需要添加服务节点的监听器实例，仅支持来源为Default的监听器（Service/Ingress来源由容器系统管理，调用会返回StatusCanNotModifyNoDefaultOriginVS错误）
	VSID *string `json:"VSID" required:"true"`
	// 权重，服务节点的权重，用于负载均衡的加权轮训
	Weight *int `json:"Weight" required:"true"`
}
