// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateFlatNetworkRouteResponse - 创建扁平网络路由
type CreateFlatNetworkRouteResponse struct {
	response.CommonBase

}
