// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateMySQLSlaveResponse - 创建MySQL从库
type CreateMySQLSlaveResponse struct {
	response.CommonBase

	// MySQL从库ID，创建成功后返回的从库实例ID
	MySQLID *string `json:"MySQLID"`
}
