// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// CreateNodeHostDeviceResponse - 创建外置设备
type CreateNodeHostDeviceResponse struct {
	response.CommonBase

}
