// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// CreateSubnetRequest 创建子网
type CreateSubnetRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID" required:"true"`
	// 子网名称，用于标识子网，长度为1-128个字符，仅支持中文、英文字母、数字、点（.）、下划线（_）和中划线（-）
	Name *string `json:"Name" required:"true"`
	// 子网网段，CIDR格式的地址范围
	Network *string `json:"Network" required:"true"`
	// 项目ID，资源所属项目分组标识
	ProjectID *string `json:"ProjectID"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 备注，用于进行说明和注释，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符，可为空
	Remark *string `json:"Remark"`
	// 标签键值对，用于资源标记和分类管理，格式为Base64的key:value
	TagKeyValuePairs []string `json:"TagKeyValuePairs" required:"true"`
	// VPCID，子网所属的VPC唯一标识符
	VPCID *string `json:"VPCID" required:"true"`
}
