// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DeleteAlertNotifyWebhookRequest 删除告警回调接口
type DeleteAlertNotifyWebhookRequest struct {
	request.CommonBase

	// 通知WebhookID，待删除的Webhook ID
	NotifyWebhookID *string `json:"NotifyWebhookID" required:"true"`
}
