// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteContainerImageResponse - 删除容器镜像
type DeleteContainerImageResponse struct {
	response.CommonBase

}
