// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteSubnetRouteResponse - 删除子网路由
type DeleteSubnetRouteResponse struct {
	response.CommonBase

}
