// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DeleteRSRequest 删除服务节点
type DeleteRSRequest struct {
	request.CommonBase

	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 负载均衡ID，用于定位需要删除服务节点的负载均衡实例
	LBID *string `json:"LBID" required:"true"`
	// 真实服务器ID，用于定位需要删除的服务节点
	RSID *string `json:"RSID" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 虚拟服务器ID，用于定位需要删除服务节点的监听器实例，仅支持来源为Default的监听器（Service/Ingress来源由容器系统管理，调用会返回StatusCanNotModifyNoDefaultOriginVS错误）
	VSID *string `json:"VSID" required:"true"`
}
