// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteVMNICResponse - 删除虚拟机网卡
type DeleteVMNICResponse struct {
	response.CommonBase

}
