// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteIsolationGroupResponse - 删除隔离组
type DeleteIsolationGroupResponse struct {
	response.CommonBase

}
