// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteSegmentResponse - 删除外网线路
type DeleteSegmentResponse struct {
	response.CommonBase

}
