// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteFSResponse - 删除文件存储服务
type DeleteFSResponse struct {
	response.CommonBase

}
