// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DeleteFlatNetworkRequest 删除扁平网络
type DeleteFlatNetworkRequest struct {
	request.CommonBase

	// 扁平网络ID，指定要删除的扁平网络唯一标识
	FlatNetworkID *string `json:"FlatNetworkID" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
