// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DeleteBucketRequest 删除桶
type DeleteBucketRequest struct {
	request.CommonBase

	// 桶名称，存储桶名称
	Name *string `json:"Name" required:"true"`
	// 对象存储ID，对象存储实例标识
	OSSID *string `json:"OSSID" required:"true"`
	// 地域ID，指定资源所属的地域
	Region *string `json:"Region" required:"true"`
}
