// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteLBResponse - 删除负载均衡
type DeleteLBResponse struct {
	response.CommonBase

}
