// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteContainerImageTagResponse - 删除容器镜像tag
type DeleteContainerImageTagResponse struct {
	response.CommonBase

}
