// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteExternalStorageSetResponse - 删除外置存储集群
type DeleteExternalStorageSetResponse struct {
	response.CommonBase

}
