// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DeleteLBRequest 删除负载均衡
type DeleteLBRequest struct {
	request.CommonBase

	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 负载均衡ID，用于定位需要删除的负载均衡实例
	LBID *string `json:"LBID" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
