// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteTagResponse - 删除标签
type DeleteTagResponse struct {
	response.CommonBase

}
