// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DeleteOnSiteInspectionRequest 删除一键巡检报告
type DeleteOnSiteInspectionRequest struct {
	request.CommonBase

	// 一键巡检报告ID，指定要删除的巡检报告
	InspectionID *string `json:"InspectionID" required:"true"`
}
