// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteVMCResponse - 删除 VMC 资源
type DeleteVMCResponse struct {
	response.CommonBase

}
