// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteSubnetResponse - 删除子网
type DeleteSubnetResponse struct {
	response.CommonBase

}
