// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DeleteComputeClassDRSRequest 删除计算集群DRS规则
type DeleteComputeClassDRSRequest struct {
	request.CommonBase

	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// 地域ID
	Region *string `json:"Region" required:"true"`
	// 计算集群ID，指定待删除DRS策略的ComputeClass
	SetID *string `json:"SetID" required:"true"`
}
