// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DeleteDirectConnectRequest 删除DirectConnect专线接入
type DeleteDirectConnectRequest struct {
	request.CommonBase

	// 专线接入ID，指定要删除的专线接入资源ID，删除时会：1）先删除底层Huanghe DC资源；2）删除Taishan资源表记录；3）删除相关配额记录（DeleteSpecificationByDimension），删除失败会返回相应错误码
	DirectConnectID *string `json:"DirectConnectID" required:"true"`
	// 地域ID，指定要删除的专线接入所属的物理区域
	Region *string `json:"Region" required:"true"`
}
