// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteWorkflowResponse - 删除自定义流程
type DeleteWorkflowResponse struct {
	response.CommonBase

}
