// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeletePlatformStorageDiskResponse - 删除平台通用存储云盘
type DeletePlatformStorageDiskResponse struct {
	response.CommonBase

}
