// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteSMCResponse - 删除SMC任务
type DeleteSMCResponse struct {
	response.CommonBase

}
