// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DeleteIPGroupResponse - 删除IP组
type DeleteIPGroupResponse struct {
	response.CommonBase

}
