// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DeleteNATGWRequest 删除NAT网关
type DeleteNATGWRequest struct {
	request.CommonBase

	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *string `json:"CompanyID"`
	// NAT网关ID，用于定位需要删除的NAT网关实例
	NATGWID *string `json:"NATGWID" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
