// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeNativeNodeResponse - 查询k8s集群原生节点
type DescribeNativeNodeResponse struct {
	response.CommonBase

	// 详情
	Infos []models.NativeNodeInfo `json:"Infos"`
	// 总数
	TotalCount *int `json:"TotalCount"`
}
