// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DescribeDTSLogResponse - 获取任务日志
type DescribeDTSLogResponse struct {
	response.CommonBase

	// 日志内容列表，包含实际日志文本，每个元素为一条日志记录
	Logs []string `json:"Logs"`
	// 日志总数，返回的日志记录总数量
	TotalCount *int `json:"TotalCount"`
}
