// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeBindableTagResourceResponse - 查询可绑定标签的资源
type DescribeBindableTagResourceResponse struct {
	response.CommonBase

	// 标签资源信息
	Infos []models.BindableTagResourceInfo `json:"Infos"`
	// 总记录数
	TotalCount *int `json:"TotalCount"`
}
