// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeComputeClassDRSSuggestionsResponse - 查看计算集群DRS建议
type DescribeComputeClassDRSSuggestionsResponse struct {
	response.CommonBase

	// drs建议列表
	Infos []models.VMMigrationReport `json:"Infos"`
	// 总数
	TotalCount *int `json:"TotalCount"`
}
