// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeParametersHistoriesResponse - 查询参数修改记录
type DescribeParametersHistoriesResponse struct {
	response.CommonBase

	// 参数修改历史列表，来源于审计日志解析结果，按更新时间倒序排列
	Infos []models.ParametersHistoriesInfos `json:"Infos"`
	// 总数，匹配条件的参数修改条目数量，按照更新时间倒序统计
	TotalCount *int `json:"TotalCount"`
}
