// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeOSSResponse - 获取对象存储列表
type DescribeOSSResponse struct {
	response.CommonBase

	// 对象存储信息列表，查询到的对象存储信息
	Infos []models.OSSInfo `json:"Infos"`
	// 总记录数，符合条件的对象存储数量
	TotalCount *int `json:"TotalCount"`
}
