// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeResourceEventResponse - 获取资源事件
type DescribeResourceEventResponse struct {
	response.CommonBase

	// 资源事件信息列表，包含符合条件的所有资源事件的详细信息
	Infos []models.ResourceEventInfo `json:"Infos"`
	// 总数，符合条件的资源事件总数量
	TotalCount *int `json:"TotalCount"`
}
