// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeResourceTemplateResponse - 查询资源模板
type DescribeResourceTemplateResponse struct {
	response.CommonBase

	// 模板详细信息列表
	Infos []models.ResourceTemplateInfo `json:"Infos"`
	// 总记录数，返回满足查询条件的模板总数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
