// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeRedisConfigFileRequest 查询配置文件列表
type DescribeRedisConfigFileRequest struct {
	request.CommonBase

	// 租户ID，模板所属租户
	CompanyID *int `json:"CompanyID"`
	// 配置文件ID，参数模板ID
	ConfigID *string `json:"ConfigID"`
	// 分页大小，指定每页返回的记录数，默认10
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数，默认0
	Offset *int `json:"Offset"`
	// 地域ID，模板所属地域
	Region *string `json:"Region" required:"true"`
	// Redis版本，筛选指定版本
	Version *string `json:"Version"`
}
