// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeTimerRequest 查询定时器
type DescribeTimerRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// 关键词，用于按定时器名称模糊搜索
	Keyword *string `json:"Keyword"`
	// 分页大小，用于限制单次返回条数
	Limit *int `json:"Limit"`
	// 分页偏移量，用于指定返回结果起始位置
	Offset *int `json:"Offset"`
	// 项目ID列表，用于筛选指定项目下的定时器
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域ID，用于筛选定时器所属地域，为空时查询授权地域
	Region *string `json:"Region"`
	// 集群ID，用于筛选PolicySetID匹配的定时器
	SetID *string `json:"SetID"`
	// 任务类型，用于筛选特定业务任务
	Task *string `json:"Task"`
	// 定时器ID列表，用于精确查询指定定时器
	TimerIDs []string `json:"TimerIDs"`
	// 定时器状态列表，取值Normal、Paused；为空时默认Normal
	TimerStatus []string `json:"TimerStatus"`
	// 调度类型列表，用于筛选特定调度规则
	Types []string `json:"Types"`
}
