// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeUserResponse - 获取租户列表
type DescribeUserResponse struct {
	response.CommonBase

	// 租户详细信息列表，查询结果返回并用于展示租户基础信息、状态与额度等信息
	Infos []models.TenantTenantInfoRes `json:"Infos"`
	// 查询到的租户总记录数，用于分页展示；当使用产品类型筛选时已排除禁用租户
	TotalCount *int `json:"TotalCount"`
}
