// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeDBSBackupResponse - 获取备份
type DescribeDBSBackupResponse struct {
	response.CommonBase

	// 备份列表，备份信息列表
	Infos []models.DBSBackupInfo `json:"Infos"`
	// 总数，查询得到的记录总数
	TotalCount *int `json:"TotalCount"`
}
