// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeRechargeRequest 获取充值信息
type DescribeRechargeRequest struct {
	request.CommonBase

	// 查询起始时间，充值记录创建时间的起始时间戳，单位为秒，必须小于结束时间
	BeginTime *int `json:"BeginTime" required:"true"`
	// 租户ID，过滤指定租户的充值记录，普通租户传自身CompanyID；系统管理员可传0或留空以查询所有租户
	CompanyID *int `json:"CompanyID"`
	// 查询结束时间，充值记录创建时间的结束时间戳，单位为秒，必须大于起始时间
	EndTime *int `json:"EndTime" required:"true"`
	// 来源类型，保留字段，当前不会根据该字段过滤，典型值：ALIPAY/WECHAT_PAY/INNER/OFFLINE
	FromType *string `json:"FromType"`
	// 分页大小，指定每页返回的充值记录数量
	Limit *int `json:"Limit"`
	// 分页偏移量，指定从第几条记录开始返回
	Offset *int `json:"Offset"`
	// 充值类型，保留字段，当前接口不会根据该字段过滤，填写1（现金）或2（赠金）不会影响查询结果
	RechargeType *string `json:"RechargeType"`
	// 用户账号ID，保留字段，与CompanyID等价，当前不会影响查询结果
	UserAccountID *int `json:"UserAccountID"`
}
