// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribePriceResponse - 获取价格信息
type DescribePriceResponse struct {
	response.CommonBase

	// 价格信息列表，包含查询条件范围内的所有价格信息
	Infos []models.Price `json:"Infos"`
	// 价格信息总数量，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
