// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeClusterRequest 查询k8s集群
type DescribeClusterRequest struct {
	request.CommonBase

	// 集群Id
	ClusterIDs []string `json:"ClusterIDs"`
	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// 关键词
	Keyword *string `json:"Keyword"`
	// 
	Limit *int `json:"Limit"`
	// 
	Offset *int `json:"Offset"`
	// 项目组ID
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域
	Region *string `json:"Region" required:"true"`
	// 状态列表，按状态过滤容器集群
	Status []string `json:"Status"`
}
