// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeProductResponse - 获取产品类型
type DescribeProductResponse struct {
	response.CommonBase

	// 产品列表，返回产品类型与授权启用信息
	Infos []models.ProductTypeInfo `json:"Infos"`
	// 总记录数，匹配条件的产品数量
	TotalCount *int `json:"TotalCount"`
}
