// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeAuditLogRequest 获取审计日志
type DescribeAuditLogRequest struct {
	request.CommonBase

	// 开始时间，Unix秒时间戳，作为QueryLog的startTime参数传入Agent
	BeginTime *int `json:"BeginTime" required:"true"`
	// 租户唯一标识ID，保留字段，当前接口不会根据该字段过滤日志
	CompanyID *int `json:"CompanyID" required:"true"`
	// 结束时间，Unix秒时间戳，作为QueryLog的endTime，建议晚于BeginTime以避免空结果
	EndTime *int `json:"EndTime" required:"true"`
	// 忽略审计语句关键字，多个关键字用逗号分隔，后端会去除空格并转成大写后按前缀匹配SQL语句，命中则直接丢弃该日志
	IgnoreQuery *string `json:"IgnoreQuery"`
	// 分页大小，用于对已采集到的审计日志做本地分页
	Limit *int `json:"Limit"`
	// 分页偏移量，只在本地分页时使用
	Offset *int `json:"Offset"`
	// 地域ID，指定MySQL实例所属地域
	Region *string `json:"Region" required:"true"`
	// 资源ID，指定要查询审计日志的MySQL资源，要求实例处于AVAILABLE且hhpaas状态Running
	ResourceID *string `json:"ResourceID" required:"true"`
}
