// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeSuperNodeResponse - 查询k8s集群Node
type DescribeSuperNodeResponse struct {
	response.CommonBase

	// 详情
	Infos []models.SuperNodeInfo `json:"Infos"`
	// 总数
	TotalCount *int `json:"TotalCount"`
}
