// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeHostVMInstanceResponse - 获取物理机上虚拟机信息
type DescribeHostVMInstanceResponse struct {
	response.CommonBase

	// 虚拟机信息列表，返回虚拟机详细信息
	Infos []models.CIInfo `json:"Infos"`
	// 总记录数，返回满足查询条件的虚拟机总数
	TotalCount *int `json:"TotalCount"`
}
