// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeDTSTaskRequest 获取传输任务列表
type DescribeDTSTaskRequest struct {
	request.CommonBase

	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// DTS任务ID列表，用于精确查询指定的DTS任务
	DTSIDs []string `json:"DTSIDs"`
	// 搜索关键词，支持按任务名称模糊搜索DTS任务
	Keyword *string `json:"Keyword"`
	// 分页大小，指定每页返回的记录数
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数
	Offset *int `json:"Offset"`
	// 项目ID列表，用于筛选指定项目下的DTS任务
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
