// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeResourceEventNotifyRuleResponse - 获取资源事件通知规则
type DescribeResourceEventNotifyRuleResponse struct {
	response.CommonBase

	// 资源事件通知规则详情，规则列表
	Infos []models.ResourceEventNotifyRuleInfo `json:"Infos"`
	// 资源总数，查询到的规则总数
	TotalCount *int `json:"TotalCount"`
}
