// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeAlertTemplateTargetRequest 获取告警模版绑定目标
type DescribeAlertTemplateTargetRequest struct {
	request.CommonBase

	// 分页大小，指定每页返回的记录数，Limit为0时默认10
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数
	Offset *int `json:"Offset"`
	// 地域，指定查询该地域下的绑定关系
	Region *string `json:"Region" required:"true"`
	// 目标资源ID，精确查询指定资源ID，若指定则Limit自动设为1
	TargetID *string `json:"TargetID"`
	// 告警模板ID，过滤指定模板绑定的资源列表
	TemplateID *string `json:"TemplateID"`
}
