// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DescribeComputeClassDRSScoreResponse - 查看计算集群DRS评分
type DescribeComputeClassDRSScoreResponse struct {
	response.CommonBase

	// 集群CPU评分
	CPU *int `json:"CPU"`
	// 集群内存评分
	Memory *int `json:"Memory"`
}
