// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeOrderRequest 获取订单信息
type DescribeOrderRequest struct {
	request.CommonBase

	// 查询起始时间，订单创建时间的起始时间戳，单位为秒，必须小于结束时间
	BeginTime *int `json:"BeginTime" required:"true"`
	// 查询结束时间，订单创建时间的结束时间戳，单位为秒，必须大于起始时间
	EndTime *int `json:"EndTime" required:"true"`
	// 分页大小，指定每页返回的订单记录数量
	Limit *int `json:"Limit"`
	// 分页偏移量，指定从第几条记录开始返回
	Offset *int `json:"Offset"`
	// 项目组ID列表，保留字段，当前接口不会根据项目进行过滤；传空字符串时表示筛选未归属项目组数据
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域ID，指定订单资源所属的物理区域，传入all或空值表示查询所有地域的订单
	Region *string `json:"Region"`
	// 租户唯一标识ID，用于标识资源所属的租户，实现多租户环境下的资源隔离和权限控制，根据此租户ID查询所有订单
	UserAccountID *int `json:"UserAccountID"`
}
