// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeDBSStorageRequest 获取DBS存储系统
type DescribeDBSStorageRequest struct {
	request.CommonBase

	// 租户ID，用于筛选指定租户的存储池
	CompanyID *int `json:"CompanyID"`
	// 分页大小，指定每页返回的记录数，默认10
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数，默认0
	Offset *int `json:"Offset"`
	// 地域ID，存储池所属地域
	Region *string `json:"Region" required:"true"`
}
