// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeQuotaResponse - 查询配额列表
type DescribeQuotaResponse struct {
	response.CommonBase

	// 配额列表
	Infos []models.Quota `json:"Infos"`
	// 配额总数
	TotalCount *int `json:"TotalCount"`
}
