// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeDBSStorageResponse - 获取DBS存储系统
type DescribeDBSStorageResponse struct {
	response.CommonBase

	// 备份存储池列表，存储池信息列表
	Infos []models.DBSStorageInfo `json:"Infos"`
	// 总数，查询得到的记录总数
	TotalCount *int `json:"TotalCount"`
}
