// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeRemoteVPNGWResponse - 获取对端网关信息
type DescribeRemoteVPNGWResponse struct {
	response.CommonBase

	// 对端网关详情列表，用于展示对端网关信息
	Infos []models.RemoteVPNGWInfo `json:"Infos"`
	// 总记录数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
