// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeComputeClassDRSRecordsRequest 查看计算集群DRS记录
type DescribeComputeClassDRSRecordsRequest struct {
	request.CommonBase

	// 开始时间，秒级Unix时间戳，与EndTime一起限定任务创建时间区间，缺省表示不限制
	BeginTime *int `json:"BeginTime"`
	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// 结束时间，秒级Unix时间戳，需大于等于BeginTime，缺省表示不限制
	EndTime *int `json:"EndTime"`
	// 虚拟机ID关键字，非空时仅返回包含该关键字的虚拟机记录
	Keyword *string `json:"Keyword"`
	// 分页大小，默认10
	Limit *int `json:"Limit"`
	// 分页偏移量，默认0
	Offset *int `json:"Offset"`
	// 地域ID
	Region *string `json:"Region" required:"true"`
	// 计算集群ID，指定要查询的DRS记录所属ComputeClass
	SetID *string `json:"SetID" required:"true"`
}
