// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeMySQLParamTplsRequest 查询MySQL参数模板列表
type DescribeMySQLParamTplsRequest struct {
	request.CommonBase

	// 租户ID，模板所属租户
	CompanyID *int `json:"CompanyID"`
	// 分页大小，指定每页返回的记录数，默认10
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数，默认0
	Offset *int `json:"Offset"`
	// 地域ID，配置模板所属地域
	Region *string `json:"Region" required:"true"`
	// 模板ID列表，筛选指定模板
	TplIDs []string `json:"TplIDs"`
}
