// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeMulticastGroupRequest 获取组播组列表
type DescribeMulticastGroupRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// 关键词，用于模糊匹配组播组名称进行搜索
	Keyword *string `json:"Keyword"`
	// 分页大小，指定每页返回的记录数，用于控制返回数据量，取值范围：1-100，默认值：10
	Limit *int `json:"Limit"`
	// 组播组ID列表，用于精确查询指定组播组的集合；当同时指定VPCID时，底层接口不支持组合查询会返回参数不支持错误，因此建议二者只选择其一
	MulticastGroupIDs []string `json:"MulticastGroupIDs"`
	// 分页偏移量，指定跳过的记录数，用于实现分页查询，取值范围：≥0，默认值：0
	Offset *int `json:"Offset"`
	// 项目ID列表，用于按项目维度筛选资源集合
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
	// VPC ID，虚拟私有网络的唯一标识符，用于筛选指定VPC的全部组播组；与MulticastGroupIDs不能复合使用，否则底层会返回查询条件不支持错误
	VPCID *string `json:"VPCID"`
}
