// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeContainerImageResponse - 查询容器镜像
type DescribeContainerImageResponse struct {
	response.CommonBase

	// 仓库地址，仓库外网地址
	ContainerImageRepositoryAddress *string `json:"ContainerImageRepositoryAddress"`
	// 仓库内网地址，仓库内网地址
	ContainerImageRepositoryInternalAddress *string `json:"ContainerImageRepositoryInternalAddress"`
	// 详情，镜像信息列表
	Infos []models.ContainerImageInfo `json:"Infos"`
	// 总数，查询到的镜像总数
	TotalCount *int `json:"TotalCount"`
}
