// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeResourceEventRequest 获取资源事件
type DescribeResourceEventRequest struct {
	request.CommonBase

	// 开始时间，Unix时间戳(秒)，查询该时间点之后发生的事件
	BeginTime *int `json:"BeginTime"`
	// 租户ID，指定要查询资源事件的租户，若不指定则查询所有租户
	CompanyID *int `json:"CompanyID"`
	// 结束时间，Unix时间戳(秒)，查询该时间点之前发生的事件，必须大于开始时间
	EndTime *int `json:"EndTime"`
	// 事件类型列表，指定要查询的事件类型
	EventTypes []string `json:"EventTypes"`
	// 事件等级列表，指定要查询的事件严重程度，取值范围：Info、Warning、Error
	Levels []string `json:"Levels"`
	// 分页大小，指定每页返回的记录数，若不指定则使用默认值
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数
	Offset *int `json:"Offset"`
	// 项目组ID列表，指定要查询事件的项目组范围，ProjectID 采用 project- 前缀加14位随机字符格式
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域ID，指定要查询资源事件的地域
	Region *string `json:"Region"`
	// 资源ID列表，指定要查询事件的资源范围，每个ResourceID格式为类型前缀-14位随机字符
	ResourceIDs []string `json:"ResourceIDs"`
	// 资源类型列表，指定要查询事件的资源类型范围
	ResourceTypes []string `json:"ResourceTypes"`
}
