// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeLBResponse - 获取负载均衡信息
type DescribeLBResponse struct {
	response.CommonBase

	// 负载均衡详情列表
	Infos []models.LBInfo `json:"Infos"`
	// 总记录数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
