// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeDBSBackupPlanResponse - 获取备份计划
type DescribeDBSBackupPlanResponse struct {
	response.CommonBase

	// 备份计划信息，备份计划列表
	Infos []models.DBSPlanInfo `json:"Infos"`
	// 总数，查询得到的记录总数
	TotalCount *int `json:"TotalCount"`
}
