// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeSRIOVStateRequest 查询物理网卡SR-IOV状态
type DescribeSRIOVStateRequest struct {
	request.CommonBase

	// 节点ID，用于查询SR-IOV状态的节点
	NodeID *string `json:"NodeID" required:"true"`
	// 网卡PCI地址，用于查询物理网卡SR-IOV状态
	PCIAddress *string `json:"PCIAddress" required:"true"`
	// 地域ID，用于查询资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
