// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeProductSpecificationResponse - 查询产品规格
type DescribeProductSpecificationResponse struct {
	response.CommonBase

	// 产品规格列表
	Infos []models.Specification `json:"Infos"`
	// 规格总数
	TotalCount *int `json:"TotalCount"`
}
