// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// DescribeFlatNetworkResponse - 查询扁平网络
type DescribeFlatNetworkResponse struct {
	response.CommonBase

	// 扁平网络列表，返回的扁平网络详细信息
	Infos []models.FlatNetwork `json:"Infos"`
	// 总记录数，用于分页计算
	TotalCount *int `json:"TotalCount"`
}
