// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeRecycledResourceRequest 获取回收站资源
type DescribeRecycledResourceRequest struct {
	request.CommonBase

	// 租户ID，指定回收站资源所属的租户
	CompanyID *int `json:"CompanyID"`
	// 搜索关键词，用于回收站资源全文检索
	Keyword *string `json:"Keyword"`
	// 分页大小，默认10
	Limit *int `json:"Limit"`
	// 分页偏移量，默认0
	Offset *int `json:"Offset"`
	// 父资源ID，用于按父资源查询回收站资源，支持VPC/子网/网段父资源；VPC返回子网，子网返回VM，网段返回EIP
	ParentResourceID *string `json:"ParentResourceID"`
	// 项目ID列表，筛选项目维度的回收站资源
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域ID，指定回收站资源所属的物理区域
	Region *string `json:"Region" required:"true"`
	// 资源ID列表，指定需要查询的回收站资源ID，未指定时返回该租户在该地域的全部回收站资源
	ResourceIDs []string `json:"ResourceIDs"`
	// 状态，保留字段，当前不参与过滤
	Status *string `json:"Status"`
}
