// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeOPLogNotifyRuleRequest 获取操作日志通知规则
type DescribeOPLogNotifyRuleRequest struct {
	request.CommonBase

	// 租户ID，过滤指定租户的操作日志通知规则
	CompanyID *int `json:"CompanyID"`
	// 搜索关键字，按规则名称模糊搜索
	Keyword *string `json:"Keyword"`
	// 分页大小，指定每页返回的记录数，Limit为0时默认10
	Limit *int `json:"Limit"`
	// 分页偏移量，指定跳过的记录数
	Offset *int `json:"Offset"`
}
