// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DescribeImageRequest 获取镜像
type DescribeImageRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// 镜像格式，用于筛选镜像格式，取值qcow2、iso
	ImageFormat *string `json:"ImageFormat"`
	// 镜像ID列表，用于精确筛选指定镜像集合
	ImageIDs []string `json:"ImageIDs"`
	// 镜像类型，用于筛选镜像类型，取值Base、Custom
	ImageType *string `json:"ImageType"`
	// 关键词，用于对镜像名称或备注进行模糊检索
	Keyword *string `json:"Keyword"`
	// 分页记录数，用于限制单次返回条数
	Limit *int `json:"Limit"`
	// 起始偏移量，用于指定返回结果集的起始位置
	Offset *int `json:"Offset"`
	// 项目ID列表，用于筛选自定义镜像所属项目，基础镜像不生效
	ProjectIDs []string `json:"ProjectIDs"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
