// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DetachExternalDiskResponse - 解绑外置存储
type DetachExternalDiskResponse struct {
	response.CommonBase

}
