// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DetachISORequest 解绑iso
type DetachISORequest struct {
	request.CommonBase

	// 租户ID，资源所属租户标识
	CompanyID *int `json:"CompanyID"`
	// ISO镜像ID，要卸载的ISO镜像标识
	ImageID *string `json:"ImageID" required:"true"`
	// 地域ID，指定资源所属的地域
	Region *string `json:"Region" required:"true"`
	// 资源ID，要卸载ISO镜像的目标资源标识
	ResourceID *string `json:"ResourceID" required:"true"`
}
