// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DiskLightOnRequest 磁盘点灯
type DiskLightOnRequest struct {
	request.CommonBase

	// RAID卡ControllerID，用于指定磁盘所属RAID控制器
	ControllerID *string `json:"ControllerID" required:"true"`
	// 持续时长，点灯持续时间，单位秒
	Duration *int `json:"Duration"`
	// 磁盘柜编号，用于指定磁盘所在磁盘柜位置
	Enclosure *string `json:"Enclosure" required:"true"`
	// 物理机IP地址，用于指定磁盘所在宿主机
	HostIP *string `json:"HostIP" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 磁盘插槽号，用于指定磁盘在磁盘柜中的插槽位置
	Slot *string `json:"Slot" required:"true"`
}
