// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DOSLoginResponse - 获取S3登录信息
type DOSLoginResponse struct {
	response.CommonBase

	// 密钥ID，用于访问桶的认证标识
	AccessKey *string `json:"AccessKey"`
	// S3会话认证信息，用于客户端临时认证
	DOSAuth *string `json:"DOSAuth"`
	// 访问地址，S3访问端点
	Endpoint *string `json:"Endpoint"`
	// 密钥，用于访问桶的认证密钥
	SecretKey *string `json:"SecretKey"`
}
