// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// DowngradeLBRequest 降级LB
type DowngradeLBRequest struct {
	request.CommonBase

	// CPU核数，负载均衡降级后的CPU核数，必须小于当前CPU核数，且负载均衡必须处于Stopped状态
	CPU *int `json:"CPU" required:"true"`
	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 负载均衡ID，用于定位需要降级规格的负载均衡实例，负载均衡必须处于Stopped状态才能降级
	LBID *string `json:"LBID" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
