// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// DowngradeOSSResponse - 对象存储降配
type DowngradeOSSResponse struct {
	response.CommonBase

}
