// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// EnableRSResponse - 启用节点
type EnableRSResponse struct {
	response.CommonBase

}
