// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// GenerateVMWareConsoleTicketRequest 创建 vmware 虚拟机控制台凭证
type GenerateVMWareConsoleTicketRequest struct {
	request.CommonBase

	// vmware配置名称，指定VMware连接配置标识
	ConfigName *string `json:"ConfigName" required:"true"`
	// 数据中心名称，VMware数据中心标识
	Datacenter *string `json:"Datacenter" required:"true"`
	// 虚拟机ID，VMware虚拟机标识
	VMID *string `json:"VMID" required:"true"`
	// 虚拟机名称，VMware虚拟机显示名称
	VMName *string `json:"VMName" required:"true"`
}
