// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// GetCreateDiskPriceRequest 获取创建硬盘价格
type GetCreateDiskPriceRequest struct {
	request.CommonBase

	// 计费类型，计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）；兼容历史值：hour、month、year，别名映射：Dynamic→HOUR、Month→MONTH、Year→YEAR
	ChargeType *string `json:"ChargeType" required:"true"`
	// 租户ID，资源所属租户标识
	CompanyID *int `json:"CompanyID"`
	// 磁盘数量，用于价格计算
	Count *int `json:"Count"`
	// 磁盘大小，单位GiB，用于价格计算
	DiskSpace *int `json:"DiskSpace" required:"true"`
	// 计费数量，用于指定购买时长的数量，按月/年计费时表示购买的月/年数，按小时计费时默认为1
	Quantity *int `json:"Quantity" required:"true"`
	// 地域ID，指定资源所属的地域
	Region *string `json:"Region" required:"true"`
	// 存储集群类型，指定磁盘所属的存储集群
	SetType *string `json:"SetType" required:"true"`
}
