// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// GetLBPriceRequest 获取负载均衡价格
type GetLBPriceRequest struct {
	request.CommonBase

	// CPU核数，用于指定负载均衡计费规格的CPU配置
	CPU *int `json:"CPU"`
	// 计费类型，取值范围：Dynamic、Month、Year；兼容历史值：hour、month、year，别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR
	ChargeType *string `json:"ChargeType" required:"true"`
	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 高可用模式，用于指定负载均衡计费规格的高可用配置方式
	HighAvailability *string `json:"HighAvailability"`
	// 负载均衡ID，用于标识需要计价的负载均衡实例
	LBID *string `json:"LBID"`
	// 计费数量，用于指定购买时长的数量，按月/年计费时表示购买的月/年数，按小时计费时默认为1，
	Quantity *int `json:"Quantity"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 规格，用于指定负载均衡计费规格
	Specification *string `json:"Specification"`
	// 计算集群类型，用于指定负载均衡运行的计算集群
	VMType *string `json:"VMType" required:"true"`
}
