// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// GetMigratePaaSInstancePriceResponse - 获取PaaS 计算迁移差价
type GetMigratePaaSInstancePriceResponse struct {
	response.CommonBase

	// 订单类型，表示差价的订单类型，如upgrade（升级）、downgrade（降级）
	OrderType *string `json:"OrderType"`
	// 价格，计算迁移的差价金额（单位：元），正数表示需补差价，负数表示退款
	Price *float64 `json:"Price"`
}
