// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// GetMySQLPriceRequest 查询MySQL价格
type GetMySQLPriceRequest struct {
	request.CommonBase

	// 计费类型，用于指定计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）
	ChargeType *string `json:"ChargeType" required:"true"`
	// 租户唯一标识ID，用于标识资源所属的租户，实现多租户环境下的资源隔离
	CompanyID *int `json:"CompanyID"`
	// 存储集群ID，指定云硬盘所在的存储集群
	DiskSetType *string `json:"DiskSetType" required:"true"`
	// 存储容量，单位GiB，最小值为10GB
	DiskSpace *int `json:"DiskSpace" required:"true"`
	// MySQL数据库高可用类型，影响价格计算（双节点vs单节点），取值范围：Standalone（单机版）、ActiveStandy（高可用版/双节点主备）
	HighAvailability *string `json:"HighAvailability" required:"true"`
	// 内存大小，单位MiB，必须是1024的倍数
	Memory *int `json:"Memory" required:"true"`
	// MySQL实例ID，用于区分查询类型，若为空，查询新购价格；若不为空，查询升级差价
	MySQLID *string `json:"MySQLID"`
	// 计费时长，按月/年计费时表示购买的月数/年数，按小时计费时为1
	Quantity *int `json:"Quantity" required:"true"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
	// 计算集群类型，用于获取bootDiskSpace信息进行价格计算
	VMType *string `json:"VMType" required:"true"`
}
