// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// GetOSSPriceResponse - 获取对象存储价格
type GetOSSPriceResponse struct {
	response.CommonBase

	// 价格信息列表，返回计费模式与价格
	Infos []models.OssPriceInfo `json:"Infos"`
}
