// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// GetOnSiteInspectionRequest 获取巡检报告详情
type GetOnSiteInspectionRequest struct {
	request.CommonBase

	// 一键巡检报告ID，指定要查询的巡检报告
	InspectionID *string `json:"InspectionID" required:"true"`
}
