// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// GetPMHardwareV2Request 获取硬件信息
type GetPMHardwareV2Request struct {
	request.CommonBase

	// 裸金属ID，指定要获取硬件信息的裸金属实例
	PMID *string `json:"PMID" required:"true"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
}
