// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// GetPartitionTemplateRequest 获取分区模板详情
type GetPartitionTemplateRequest struct {
	request.CommonBase

	// 模板ID
	ID *string `json:"ID" required:"true"`
	// 地域
	Region *string `json:"Region" required:"true"`
}
