// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// GetRenewPriceResponse - 获取续费价格
type GetRenewPriceResponse struct {
	response.CommonBase

	// 续费的价格，单位为元，精确到分，根据资源配置、续费时长和租户折扣计算得出
	Price *float64 `json:"Price"`
}
