// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// GetResourceUsageRequest 获取资源使用情况详细信息
type GetResourceUsageRequest struct {
	request.CommonBase

	// 资源用量ID，指定要查询的资源用量报告
	ResourceUsageID *string `json:"ResourceUsageID" required:"true"`
}
