// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// GetUpgradeDiskPriceResponse - 获取升级虚拟硬盘的差价
type GetUpgradeDiskPriceResponse struct {
	response.CommonBase

	// 磁盘价格信息，价格明细列表
	Infos []models.DiskPriceInfo `json:"Infos"`
	// 差价，升级产生的差价金额
	Price *float64 `json:"Price"`
}
