// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// GetVMInstancePriceResponse - 获取虚拟机价格
type GetVMInstancePriceResponse struct {
	response.CommonBase

	// 价格详情，包含不同计费模式的价格信息
	Infos []models.VmPriceInfo `json:"Infos"`
}
