// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// GetVMWareClusterDatastoreRequest 获取 vmware 计算集群的信息
type GetVMWareClusterDatastoreRequest struct {
	request.CommonBase

	// 集群ID，VMware计算集群标识
	ClusterID *string `json:"ClusterID" required:"true"`
	// 集群名称，VMware计算集群标识
	ClusterName *string `json:"ClusterName" required:"true"`
	// vmware配置名称，指定VMware连接配置标识
	ConfigName *string `json:"ConfigName" required:"true"`
	// 数据中心名称，VMware数据中心标识
	Datacenter *string `json:"Datacenter" required:"true"`
}
