// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// GetVIPPriceResponse - 获取外网VIP价格
type GetVIPPriceResponse struct {
	response.CommonBase

	// VIP价格信息列表，包含不同计费类型的价格信息
	Infos []models.VipPriceInfo `json:"Infos"`
}
