// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// GetVPNTunnelConfigResponse - 获取隧道配置
type GetVPNTunnelConfigResponse struct {
	response.CommonBase

	// VPN隧道配置内容，用于配置客户端VPN的配置文本
	Info *string `json:"Info"`
}
