// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// ImportImageRequest 上传镜像
type ImportImageRequest struct {
	request.CommonBase

	// 引导类型，取值bios、uefi，未指定时默认bios
	BootloaderType *string `json:"BootloaderType"`
	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID" required:"true"`
	// 镜像描述，用于补充说明，需符合uremark规则（0-100字符，禁止包含<script>/javascript）
	ImageDescription *string `json:"ImageDescription"`
	// 镜像格式，指定导入的虚拟化文件格式，取值qcow2、iso
	ImageFormat *string `json:"ImageFormat" required:"true"`
	// 镜像名称，用于标识导入的镜像资源
	ImageName *string `json:"ImageName" required:"true"`
	// 镜像大小，单位GiB，最大不超过2000，Remote模式下由系统根据URL探测
	ImageSize *int `json:"ImageSize"`
	// 上传类型，Remote表示远程URL，Local表示本地分片上传
	ImportType *string `json:"ImportType" required:"true"`
	// 来源URL，仅在远程模式下有效，当ImportType为Remote时必填，用于拉取镜像文件
	LoadURL *string `json:"LoadURL"`
	// 操作系统发行版，如Ubuntu、CentOS
	OSDistribution *string `json:"OSDistribution" required:"true"`
	// 操作系统类型，如Linux、Windows
	OSType *string `json:"OSType" required:"true"`
	// 操作系统版本，指定镜像内部安装的具体发行版本号
	OSVersion *string `json:"OSVersion" required:"true"`
	// 项目ID，资源所属的项目分组标识
	ProjectID *string `json:"ProjectID"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 镜像密钥，用于镜像在存储层的解密与使用
	Secret *string `json:"Secret"`
	// 架构类型，基于计算集群支持的指令集，如x86_64、aarch64
	SetArch *string `json:"SetArch" required:"true"`
	// Cloud-Init支持，标识镜像是否支持自动化初始化配置
	SupportCloudInit *bool `json:"SupportCloudInit"`
	// QEMU Guest Agent支持，标识镜像内是否预装QGA组件
	SupportQGA *bool `json:"SupportQGA"`
	// 标签键值对，用于资源标签管理与检索，格式为Base64的key:value，列表项不能为空且key不可重复
	TagKeyValuePairs []string `json:"TagKeyValuePairs" required:"true"`
}
