// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// ListGPUsRequest 获取GPU信息列表
type ListGPUsRequest struct {
	request.CommonBase

	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// GPUID列表，用于查询指定GPU信息
	GPUIDs []string `json:"GPUIDs"`
	// 物理机ID，用于筛选指定主机的GPU
	HostID *string `json:"HostID"`
	// 分页大小，用于限制单次返回条数
	Limit *int `json:"Limit"`
	// 分页偏移量，用于指定返回结果起始位置
	Offset *int `json:"Offset"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
}
