// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// ListPartitionTemplatesResponse - 获取分区模板列表
type ListPartitionTemplatesResponse struct {
	response.CommonBase

	// 模板列表
	Infos []models.PartitionTemplateInfo `json:"Infos"`
	// 总数
	TotalCount *int `json:"TotalCount"`
}
