// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// ListInstallProfilesRequest 获取装机配置模板列表
type ListInstallProfilesRequest struct {
	request.CommonBase

	// 模板ID列表过滤
	IDs []string `json:"IDs"`
	// 关键词搜索，按模板名称进行模糊匹配
	Keyword *string `json:"Keyword"`
	// 每页数量，指定每页返回记录数，默认20，最大100
	Limit *int `json:"Limit"`
	// 偏移量，指定跳过记录数，最小值为0
	Offset *int `json:"Offset"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
}
