// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// MigratePaaSStorageResponse - PaaS产品存储热迁移
type MigratePaaSStorageResponse struct {
	response.CommonBase

}
