// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// OperateOrchTaskResponse - 操作编排任务
type OperateOrchTaskResponse struct {
	response.CommonBase

}
