// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// PowerControlPMV2Request 电源控制
type PowerControlPMV2Request struct {
	request.CommonBase

	// 裸金属ID，指定要进行电源操作的裸金属实例
	PMID *string `json:"PMID" required:"true"`
	// 电源操作，指定要执行的电源控制动作，on：开机；off：强制关机；soft：软关机（向操作系统发送关机信号）；reset：强制重启；cycle：电源循环重启（先断电再上电）
	PowerAction *string `json:"PowerAction" required:"true"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
}
