// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// RechargeResponse - 充值
type RechargeResponse struct {
	response.CommonBase

	// 交易号，充值成功后生成的交易唯一标识，可用于后续查询交易记录
	TransactonNo *string `json:"TransactonNo"`
}
