// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// RemoveSubnetNetworkResponse - 移除子网IPv6网络
type RemoveSubnetNetworkResponse struct {
	response.CommonBase

}
