// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// RenewResourceRequest 续费
type RenewResourceRequest struct {
	request.CommonBase

	// 计费类型，取值：Dynamic/Month/Year，后台会阻止降级（例如Year改为Month），安全产品只允许Month；同时兼容传入大写值HOUR/MONTH/YEAR
	ChargeType *string `json:"ChargeType"`
	// 租户ID，从该租户账户扣费
	CompanyID *int `json:"CompanyID"`
	// 续费时长，按Hour续费时系统固定为1小时；按Month续费最多11个月，按Year续费最多5年
	Quantity *int `json:"Quantity"`
	// 地域ID，必须与资源实际所在地域一致，用于匹配历史订单
	Region *string `json:"Region" required:"true"`
	// 资源ID，要续费的资源唯一标识；若传入虚拟机启动盘（ID以-boot结尾）会自动改为对应虚拟机ID并同时续费启动盘
	ResourceID *string `json:"ResourceID" required:"true"`
}
