// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// ResetMySQLPasswordRequest 修改MySQL密码
type ResetMySQLPasswordRequest struct {
	request.CommonBase

	// 租户ID，资源所属租户
	CompanyID *int `json:"CompanyID" required:"true"`
	// MySQL实例ID，指定要修改密码的MySQL实例；注意：资源必须为AVAILABLE且状态为Running
	MySQLID *string `json:"MySQLID" required:"true"`
	// root密码，满足paaspassword校验规则
	Password *string `json:"Password" required:"true"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
}
