// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// ResizePlatformStorageDiskResponse - 扩容平台通用存储云盘
type ResizePlatformStorageDiskResponse struct {
	response.CommonBase

}
