// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// RestoreVMInstanceRequest 虚拟机恢复快照
type RestoreVMInstanceRequest struct {
	request.CommonBase

	// 允许跨机，标识是否允许调度到其他宿主机
	AllowOtherHost *bool `json:"AllowOtherHost"`
	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 快照ID，从快照恢复时指定，从暂存恢复时可为空
	SPID *string `json:"SPID"`
	// 虚拟机ID，待恢复的虚拟机标识
	VMID *string `json:"VMID" required:"true"`
}
