// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// RetryResourceUsageResponse - 重试重新生成资源使用情况报告
type RetryResourceUsageResponse struct {
	response.CommonBase

}
