// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// ScanISCSIDiskResponse - 扫描外置存储集群硬盘
type ScanISCSIDiskResponse struct {
	response.CommonBase

	// 
	Infos []models.ExternalDiskInfo `json:"Infos"`
	// 
	TotalCount *int `json:"TotalCount"`
}
