// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// ScanISCSIDiskRequest 扫描外置存储集群硬盘
type ScanISCSIDiskRequest struct {
	request.CommonBase

	// 租户ID，权限上下文
	CompanyID *int `json:"CompanyID"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
	// 集群ID，外置存储集群ID
	SetID *string `json:"SetID" required:"true"`
}
