// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// SetBootFromCdromResponse - 设置虚拟机从Cdrom启动
type SetBootFromCdromResponse struct {
	response.CommonBase

}
