// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// SetupSMCResponse - 设置SMC任务
type SetupSMCResponse struct {
	response.CommonBase

}
