// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// TerminateResourceResponse - 销毁资源
type TerminateResourceResponse struct {
	response.CommonBase

}
