// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// TriggerDRSOnceResponse - 触发一次drs任务
type TriggerDRSOnceResponse struct {
	response.CommonBase

}
