// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UnBindTagResponse - 标签解绑
type UnBindTagResponse struct {
	response.CommonBase

}
