// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UnbindEIPFromNATGWRequest 从NAT网关上解绑EIP
type UnbindEIPFromNATGWRequest struct {
	request.CommonBase

	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 弹性公网IPID，用于从NAT网关解绑，EIP必须已绑定到该NAT网关
	EIPID *string `json:"EIPID" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// NAT网关ID，用于定位需要解绑EIP的NAT网关实例，该NAT网关需处于运行或停止状态且不能正在进行版本升级
	ResourceID *string `json:"ResourceID" required:"true"`
}
