// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
	"github.com/ucloud/ustack-sdk-go/services/ucloudstack/models"
)

// UpdateMySQLConfigParamResponse - 更新MySQL配置参数
type UpdateMySQLConfigParamResponse struct {
	response.CommonBase

	// 配置变更日志，配置参数变更记录
	Infos []models.MySQLConfigOpLogInfo `json:"Infos"`
}
