// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateAuditLogRequest 开关数据库审计
type UpdateAuditLogRequest struct {
	request.CommonBase

	// 审计日志事件，写入资源注解的事件列表，多个事件用逗号分隔；未填写时默认写入QUERY
	AuditEvents *string `json:"AuditEvents"`
	// 审计状态，0表示关闭审计日志，1表示开启审计日志，状态必须为以下两个值之一
	AuditStatus *int `json:"AuditStatus"`
	// 地域ID，指定资源所属的物理区域
	Region *string `json:"Region" required:"true"`
	// 资源ID，指定要开关审计日志的数据库资源，如MySQL实例，资源状态必须为AVAILABLE且运行状态为Running
	ResourceID *string `json:"ResourceID" required:"true"`
	// 资源类型，目前仅支持MYSQL，传入其他取值会被校验拒绝
	ResourceType *string `json:"ResourceType" required:"true"`
}
