// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateOPLogNotifyRuleResponse - 更新操作日志通知规则
type UpdateOPLogNotifyRuleResponse struct {
	response.CommonBase

}
