// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateTimerResponse - 更新定时器
type UpdateTimerResponse struct {
	response.CommonBase

}
