// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateVMCPULimitPercentResponse - 修改虚拟机CPU资源限制
type UpdateVMCPULimitPercentResponse struct {
	response.CommonBase

}
