// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateCompanyEmailRequest 修改租户邮箱
type UpdateCompanyEmailRequest struct {
	request.CommonBase

	// 租户ID，请求传入用于定位要更新邮箱的租户
	CompanyID *int `json:"CompanyID" required:"true"`
	// 租户邮箱，请求传入并更新租户主账号邮箱，用于登录与通知；邮箱需全局唯一
	Email *string `json:"Email" required:"true"`
}
