// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateVMDNSResponse - 设置虚拟机DNS
type UpdateVMDNSResponse struct {
	response.CommonBase

}
