// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateDTSTaskConfigureResponse - 更新数据传输任务配置
type UpdateDTSTaskConfigureResponse struct {
	response.CommonBase

}
