// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateDBSBackupPlanSimpleRequest 更新备份计划的名称和remark
type UpdateDBSBackupPlanSimpleRequest struct {
	request.CommonBase

	// 名称，备份计划名称，长度1-128字符，支持中英文、数字、点、下划线和中划线
	Name *string `json:"Name" required:"true"`
	// 计划ID，待更新的备份计划ID
	PlanID *string `json:"PlanID" required:"true"`
	// 备注，备份计划描述信息，长度0-100字符，禁止http://或https://等非法字符
	Remark *string `json:"Remark"`
}
