// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateFlatNetworkRouteResponse - 更新扁平网络路由
type UpdateFlatNetworkRouteResponse struct {
	response.CommonBase

}
