// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateIPGroupResponse - 更新IP组
type UpdateIPGroupResponse struct {
	response.CommonBase

}
