// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateVMSetBoundStorageSetRequest 更新计算集群绑定的存储集群
type UpdateVMSetBoundStorageSetRequest struct {
	request.CommonBase

	// 地域ID，指定计算集群所属的物理区域
	Region *string `json:"Region" required:"true"`
	// 计算集群ID，指定要绑定存储集群的计算集群唯一标识
	SetID *string `json:"SetID" required:"true"`
	// 存储集群ID列表，指定要绑定到该计算集群的存储集群ID列表，必须从该计算集群的物理绑定存储列表（StorageClassList）中选择，用于限制虚拟机可使用的存储资源，支持RBD、CJFS、Ustorbs、UDisk、QoL等存储Provider类型
	StorageSetIDs []string `json:"StorageSetIDs" required:"true"`
}
