// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateDiskQoSRequest 设置硬盘QoS
type UpdateDiskQoSRequest struct {
	request.CommonBase

	// 租户ID，资源所属租户标识
	CompanyID *int `json:"CompanyID"`
	// 硬盘带宽限制，单位MBps，取值范围0-1000，0表示不限制
	DiskBandwidth *int `json:"DiskBandwidth"`
	// 磁盘ID，要更新QoS配置的磁盘标识
	DiskID *string `json:"DiskID" required:"true"`
	// 硬盘IOPS限制，取值范围0-50000，0表示不限制
	DiskIOPS *int `json:"DiskIOPS"`
	// 地域ID，指定资源所属的地域
	Region *string `json:"Region" required:"true"`
}
