// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateKickstartTemplateResponse - 更新Kickstart模板
type UpdateKickstartTemplateResponse struct {
	response.CommonBase

}
