// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateSegmentResponse - 更新外网线路
type UpdateSegmentResponse struct {
	response.CommonBase

}
