// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateTrafficMirrorResponse - 更新流量镜像
type UpdateTrafficMirrorResponse struct {
	response.CommonBase

}
