// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateSegmentRouteRequest 更新外网线路路由
type UpdateSegmentRouteRequest struct {
	request.CommonBase

	// 目的地址，路由的目标网段，必须为CIDR格式，用于定位要更新的路由规则，若该路由不存在则返回错误StatusRouteNotFound
	Destination *string `json:"Destination" required:"true"`
	// 下一跳IP地址，必须为合法的IP地址格式，且必须在外网线路网段范围内
	NextHop *string `json:"NextHop" required:"true"`
	// 地域ID，指定要更新的外网线路路由所属的物理区域
	Region *string `json:"Region" required:"true"`
	// 备注，用于进行说明和注释，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符
	Remark *string `json:"Remark"`
	// 外网线路ID，指定要更新路由规则的外网线路
	SegmentID *string `json:"SegmentID" required:"true"`
}
