// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateTrafficMirrorEnableResponse - 是否启用流量镜像
type UpdateTrafficMirrorEnableResponse struct {
	response.CommonBase

}
