// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateConfigRequest 更新配置
type UpdateConfigRequest struct {
	request.CommonBase

	// 配置键，要更新的全局配置项唯一标识符
	ConfigKey *string `json:"ConfigKey" required:"true"`
	// 配置值，要设置的新配置值，服务端会根据配置的ValueType与ValueRange校验取值是否符合要求，文件类型的配置也需要将Base64内容直接写入该字段，单独填写FileBytes不会生效
	ConfigValue *string `json:"ConfigValue"`
	// 文件内容Base64编码，保留字段，当前版本不会读取该字段，仍需将内容写入ConfigValue
	FileBytes *string `json:"FileBytes"`
}
