// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateVMNICQueuesResponse - 更新虚拟机网卡队列
type UpdateVMNICQueuesResponse struct {
	response.CommonBase

}
