// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateVMCPUModelResponse - 设置虚拟机cpu模型
type UpdateVMCPUModelResponse struct {
	response.CommonBase

}
