// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdatePartitionTemplateResponse - 更新分区模板
type UpdatePartitionTemplateResponse struct {
	response.CommonBase

}
