// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdatePortGroupRequest 更新端口组
type UpdatePortGroupRequest struct {
	request.CommonBase

	// 租户ID，标识端口组所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 端口组ID，指定要更新的端口组唯一标识符
	PortGroupID *string `json:"PortGroupID" required:"true"`
	// 地域ID，用于标识端口组所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 端口组规则，新的协议端口组合列表，将替换现有规则，格式为协议:端口或协议:端口范围，多条规则以逗号分隔
	Rules *string `json:"Rules" required:"true"`
}
