// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateVMHighAvailabilityRequest 设置虚拟机高可用
type UpdateVMHighAvailabilityRequest struct {
	request.CommonBase

	// 高可用模式，虚拟机的HA策略，取值：NeverStop（默认）、None
	HighAvailability *string `json:"HighAvailability"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// 虚拟机ID，待修改配置的虚拟机标识
	VMID *string `json:"VMID" required:"true"`
}
