// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateTrafficMirrorRuleResponse - 更新流量镜像规则
type UpdateTrafficMirrorRuleResponse struct {
	response.CommonBase

}
