// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateSuperNodeGPURequest 更新k8s集群SuperNodeGPU
type UpdateSuperNodeGPURequest struct {
	request.CommonBase

	// 集群Id
	ClusterID *string `json:"ClusterID" required:"true"`
	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// GPU的颗数
	GPU *int `json:"GPU"`
	// GPU的规格
	GPUMdevName *string `json:"GPUMdevName" required:"true"`
	// 节点名称
	NodeName *string `json:"NodeName" required:"true"`
	// 地域
	Region *string `json:"Region" required:"true"`
}
