// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateSubnetRouteResponse - 更新子网路由
type UpdateSubnetRouteResponse struct {
	response.CommonBase

}
