// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateVMCPUHypervisorResponse - 设置虚拟机CPU虚拟化隐藏标记
type UpdateVMCPUHypervisorResponse struct {
	response.CommonBase

}
