// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpdateNATGWRuleRequest 修改NAT网关规则
type UpdateNATGWRuleRequest struct {
	request.CommonBase

	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *string `json:"CompanyID"`
	// 弹性公网IPID，SNAT规则使用的新EIP，必须已绑定到该NAT网关
	EIPID *string `json:"EIPID" required:"true"`
	// NAT网关ID，用于定位SNAT规则所属的NAT网关实例，该NAT网关必须处于运行状态
	NATGWID *string `json:"NATGWID" required:"true"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// SNAT规则ID，用于定位需要修改的SNAT规则
	RuleID *string `json:"RuleID" required:"true"`
}
