// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateTerminationPolicyResponse - 修改 PaaS产品 删除保护
type UpdateTerminationPolicyResponse struct {
	response.CommonBase

}
