// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateRedisPasswordResponse - 更新redis密码
type UpdateRedisPasswordResponse struct {
	response.CommonBase

}
