// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpdateClusterResponse - 更新k8s集群
type UpdateClusterResponse struct {
	response.CommonBase

}
