// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpgradeVPNGWToHARequest 升级为高可用版本
type UpgradeVPNGWToHARequest struct {
	request.CommonBase

	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region" required:"true"`
	// VPN网关ID，待升级为高可用模式的VPN网关唯一标识，网关需处于Running且资源可用，当前为Standalone时才执行升级
	VPNGWID *string `json:"VPNGWID" required:"true"`
}
