// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// UpgradeFSRequest 文件存储扩容
type UpgradeFSRequest struct {
	request.CommonBase

	// 租户ID，资源所属租户标识
	CompanyID *int `json:"CompanyID"`
	// 存储容量，单位GiB，扩容后的容量必须大于当前容量，最小值100
	DiskSpace *int `json:"DiskSpace" required:"true"`
	// 文件存储实例ID，要扩容的文件存储标识，文件存储状态必须为Running或Stopped
	FSID *string `json:"FSID" required:"true"`
	// 地域ID，指定资源所属的地域
	Region *string `json:"Region" required:"true"`
}
