// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpgradeDiskResponse - 升级虚拟硬盘
type UpgradeDiskResponse struct {
	response.CommonBase

}
