// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpgradeRedisResponse - 升级redis内存
type UpgradeRedisResponse struct {
	response.CommonBase

}
