// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/response"
)

// UpgradeMySQLResponse - 升级MySQL
type UpgradeMySQLResponse struct {
	response.CommonBase

}
