// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// ValidatePartitionConfigRequest 验证分区配置
type ValidatePartitionConfigRequest struct {
	request.CommonBase

	// 分区配置
	Config *string `json:"Config" required:"true"`
	// 地域
	Region *string `json:"Region" required:"true"`
}
