// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// VerifyEmailAvailabilityRequest 验证邮箱服务器可用性
type VerifyEmailAvailabilityRequest struct {
	request.CommonBase

	// 收件人邮箱地址，用于验证邮件服务器是否可用
	Receiver *string `json:"Receiver" required:"true"`
}
