// Code generated by sdk-generator. DO NOT EDIT.

package apis

import (
	"github.com/ucloud/ustack-sdk-go/common/request"
)

// WithdrawRequest 申请提现
type WithdrawRequest struct {
	request.CommonBase

	// 租户ID，指定要提现的租户唯一标识，从该租户账户扣除提现金额
	CompanyID *int `json:"CompanyID" required:"true"`
	// 源账户类型，指定提现的账户类型，FREE表示从内部账户（赠金）提现，REAL表示从外部账户（现金）提现
	SrcAccountType *string `json:"SrcAccountType" required:"true"`
	// 提现金额，要提现的金额，单位为元，必须大于0且不能超过账户可提现余额
	WithdrawAmount *float64 `json:"WithdrawAmount" required:"true"`
}
