// Code generated by sdk-generator. DO NOT EDIT.

package models


// AttachExternalShareBlock 
type AttachExternalShareBlock struct {
	// 
	AttachResourceID *string `json:"AttachResourceID"`
	// 
	AttachResourceName *string `json:"AttachResourceName"`
	// 
	AttachResourceType *string `json:"AttachResourceType"`
	// 
	AttachStatus *string `json:"AttachStatus"`
}
