// Code generated by sdk-generator. DO NOT EDIT.

package models


// AuditLogInfos 
type AuditLogInfos struct {
	// 账户名，执行SQL语句的数据库账户名称
	AccountName *string `json:"AccountName"`
	// 客户端IP，执行SQL语句的客户端IP地址
	ClientIP *string `json:"ClientIP"`
	// 操作数据库，SQL语句操作的数据库名称
	ExecutionDB *string `json:"ExecutionDB"`
	// 执行结果，MySQL审计日志中的ReturnCode，0表示成功，非0表示失败
	ExecutionResult *int `json:"ExecutionResult"`
	// 执行时间，日志时间戳（Unix时间），由Agent返回的LogMessage.Timestamp转换
	ExecutionTime *int `json:"ExecutionTime"`
	// 日志类型，审计日志的事件类型，如QUERY、QUERY_DDL等
	LogType *string `json:"LogType"`
	// 执行命令，实际执行的SQL语句内容
	SQLCommand *string `json:"SQLCommand"`
}
