// Code generated by sdk-generator. DO NOT EDIT.

package models


// AuthorizationInfo 
type AuthorizationInfo struct {
	// 创建时间，授权关系建立的Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// 账号邮箱，被授权账号的登录邮箱
	Email *string `json:"Email"`
	// 成员ID，被授予角色权限的账号标识
	MemberID *int `json:"MemberID"`
	// 项目ID，用于对云资源进行逻辑分组的唯一标识符
	ProjectID *string `json:"ProjectID"`
	// 项目名称，资源所属项目的显示名称
	ProjectName *string `json:"ProjectName"`
	// 角色ID，系统生成的权限定义唯一标识符
	RoleID *string `json:"RoleID"`
	// 角色名称，用于展示的权限角色名称
	RoleName *string `json:"RoleName"`
	// 角色类型，标识授权角色来源，取值：System或Custom
	RoleType *string `json:"RoleType"`
}
