// Code generated by sdk-generator. DO NOT EDIT.

package models


// BillOverViewDetail 
type BillOverViewDetail struct {
	// 金额，该维度的总金额，单位为元
	Amount *float64 `json:"Amount"`
	// 内部账号金额，该维度的内部账号金额，单位为元
	AmountFree *float64 `json:"AmountFree"`
	// 外部账号金额，该维度的外部账号金额，单位为元
	AmountReal *float64 `json:"AmountReal"`
	// 维度，统计的维度类型，如product、region等
	Dimension *string `json:"Dimension"`
	// 名称，维度对应的名称
	Name *string `json:"Name"`
}
