// Code generated by sdk-generator. DO NOT EDIT.

package models


// BillPriceGroupInfo 
type BillPriceGroupInfo struct {
	// 产品ID列表，价格管理中可用的产品ID
	ProductIDs []string `json:"ProductIDs"`
	// 集群类型列表，价格管理中可用的集群类型
	SetTypes []string `json:"SetTypes"`
}
