// Code generated by sdk-generator. DO NOT EDIT.

package models


// ChartSubItem 
type ChartSubItem struct {
	// 显示值，细分数据项经过单位换算后的显示数值
	DisplayValue *float64 `json:"DisplayValue"`
	// 子图表项名称，细分数据项的显示名称
	Name *string `json:"Name"`
	// 单位，细分数据项的计量单位
	Unit *string `json:"Unit"`
	// 子图表值，细分数据项的原始数值
	Value *float64 `json:"Value"`
}
