// Code generated by sdk-generator. DO NOT EDIT.

package models


// CIStatusInfo 
type CIStatusInfo struct {
	// CIID，容器实例标识（如果适用）
	CIID *string `json:"CIID"`
	// CI状态，容器实例的运行状态
	CIStatus *string `json:"CIStatus"`
	// 资源ID，对应的虚拟机等资源标识
	ResourceID *string `json:"ResourceID"`
}
