// Code generated by sdk-generator. DO NOT EDIT.

package models


// ContainerStatus 
type ContainerStatus struct {
	// 容器名
	Container *string `json:"Container"`
	// pod名
	PodName *string `json:"PodName"`
	// 是否就绪
	Ready *bool `json:"Ready"`
	// 状态或原因
	Reason *string `json:"Reason"`
}
