// Code generated by sdk-generator. DO NOT EDIT.

package models


// ContainerInfo 
type ContainerInfo struct {
	// CPU资源上限，单位核
	CPULimit *int `json:"CPULimit"`
	// CPU资源下限，单位核
	CPURequest *int `json:"CPURequest"`
	// 内存资源上限，单位GiB
	MemoryLimit *int `json:"MemoryLimit"`
	// 内存资源下限，单位GiB
	MemoryRequest *int `json:"MemoryRequest"`
	// 容器名称，用于展示容器名称
	Name *string `json:"Name"`
}
