// Code generated by sdk-generator. DO NOT EDIT.

package models


// CPU 
type CPU struct {
	// 核数，CPU物理核数
	Cores *int `json:"Cores"`
	// 制造商，CPU厂商
	Manufacturer *string `json:"Manufacturer"`
	// 名称，CPU型号名称
	Name *string `json:"Name"`
	// 插槽数，CPU插槽数量
	Sockets *int `json:"Sockets"`
	// 线程数，CPU线程数
	Threads *int `json:"Threads"`
}
