// Code generated by sdk-generator. DO NOT EDIT.

package models


// CreateVMInstanceRequestDataDisk 
type CreateVMInstanceRequestDataDisk struct {
	// 总线类型，取值 virtio，ide，scsi
	Bus *string `json:"Bus"`
	// 磁盘缓存模式，当前生效的磁盘I/O缓存策略
	CacheMode *string `json:"CacheMode"`
	// 磁盘ID，需挂载的已有数据盘标识
	DiskID *string `json:"DiskID"`
	// 磁盘集群类型，指定新建数据盘所属的存储集群
	DiskSetType *string `json:"DiskSetType"`
	// 磁盘容量，指定新建数据盘的大小，单位：GiB
	DiskSpace *int `json:"DiskSpace"`
	// 磁盘镜像ID
	ImageID *string `json:"ImageID"`
	// QoS限速读带宽，单位MB/s，0表示不限制
	ReadBandwidth *int `json:"ReadBandwidth"`
	// QoS限速读IOPS，0表示不限制
	ReadIOPS *int `json:"ReadIOPS"`
	// QoS限速总带宽，单位MB/s，0表示不限制
	TotalBandwidth *int `json:"TotalBandwidth"`
	// QoS限速总IOPS，0表示不限制
	TotalIOPS *int `json:"TotalIOPS"`
	// QoS限速写带宽，单位MB/s，0表示不限制
	WriteBandwidth *int `json:"WriteBandwidth"`
	// QoS限速写IOPS，0表示不限制
	WriteIOPS *int `json:"WriteIOPS"`
}
