// Code generated by sdk-generator. DO NOT EDIT.

package models


// DataCheckTaskOverview 
type DataCheckTaskOverview struct {
	// 结束时间，秒级Unix时间戳
	EndTime *int `json:"EndTime"`
	// 校验结果，取值范围：Consistent、Inconsistent
	Result *string `json:"Result"`
	// 采样频率，每多少条记录采样一次
	SampleInterval *int `json:"SampleInterval"`
	// 开始时间，秒级Unix时间戳
	StartTime *int `json:"StartTime"`
	// 任务状态，数据校验任务状态
	Status *string `json:"Status"`
	// 校验任务ID，数据校验任务唯一标识
	TaskID *string `json:"TaskID"`
}
