// Code generated by sdk-generator. DO NOT EDIT.

package models


// DBSBackupInfo 
type DBSBackupInfo struct {
	// 备份ID，备份唯一标识
	BackupID *string `json:"BackupID"`
	// 备份库表，备份库表列表
	BackupTables []string `json:"BackupTables"`
	// 备份类型，备份类型字符串
	BackupType *string `json:"BackupType"`
	// 集群类型，备份源实例集群类型
	ClusterType *string `json:"ClusterType"`
	// 租户邮箱，租户联系邮箱
	CompanyEmail *string `json:"CompanyEmail"`
	// 租户ID，备份所属租户
	CompanyID *int `json:"CompanyID"`
	// 租户名称，租户显示名称
	CompanyName *string `json:"CompanyName"`
	// 创建时间，备份创建时间戳
	CreateTime *int `json:"CreateTime"`
	// 存储池状态，备份存储池状态
	DBSStorageStatus *string `json:"DBSStorageStatus"`
	// 过期时间，备份过期时间戳
	ExpireTime *int `json:"ExpireTime"`
	// 备份实例版本，备份源实例版本
	InstanceVersion *string `json:"InstanceVersion"`
	// 备份存放路径，备份文件路径
	Path *string `json:"Path"`
	// 计划ID，备份计划ID
	PlanID *string `json:"PlanID"`
	// 计划名称，备份计划名称
	PlanName *string `json:"PlanName"`
	// 失败原因，备份失败原因
	Reason *string `json:"Reason"`
	// 保留时间，备份保留时长
	RetentionTime *int `json:"RetentionTime"`
	// 分片数，备份源实例分片数
	ShardCount *int `json:"ShardCount"`
	// 备份大小，备份文件大小
	Size *int `json:"Size"`
	// 源存储集群，备份源存储集群类型
	SrcDiskSetType *string `json:"SrcDiskSetType"`
	// 源磁盘空间，备份源磁盘空间
	SrcDiskSpace *int `json:"SrcDiskSpace"`
	// 备份源ID，备份源资源ID
	SrcID *string `json:"SrcID"`
	// 备份源名称，备份源资源名称
	SrcName *string `json:"SrcName"`
	// 备份源地域，备份源资源所属地域
	SrcRegion *string `json:"SrcRegion"`
	// 备份源类型，备份源资源类型
	SrcType *string `json:"SrcType"`
	// 备份状态，备份状态字符串
	Status *string `json:"Status"`
	// 存储池ID，备份存储池ID
	StorageID *string `json:"StorageID"`
	// 存储池名称，备份存储池名称
	StorageName *string `json:"StorageName"`
	// 更新时间，备份更新时间戳
	UpdateTime *int `json:"UpdateTime"`
}
