// Code generated by sdk-generator. DO NOT EDIT.

package models


// DBSPlanInfo 
type DBSPlanInfo struct {
	// 备份数量，计划下备份数量
	BackupCount *int `json:"BackupCount"`
	// 备份库表，备份库表范围
	BackupTables []string `json:"BackupTables"`
	// 备份类型，取值Logical/Physical/Snapshot/Incremental
	BackupType *string `json:"BackupType"`
	// 租户邮箱，租户联系邮箱
	CompanyEmail *string `json:"CompanyEmail"`
	// 租户ID，备份计划所属租户
	CompanyID *int `json:"CompanyID"`
	// 租户名称，租户显示名称
	CompanyName *string `json:"CompanyName"`
	// 创建时间，备份计划创建时间戳
	CreateTime *int `json:"CreateTime"`
	// Email，租户联系邮箱
	Email *string `json:"Email"`
	// 增量备份周期，增量备份间隔
	IncrementalInterval *int `json:"IncrementalInterval"`
	// 增量备份源ID，增量备份源资源ID
	IncrementalSrcResourceID *string `json:"IncrementalSrcResourceID"`
	// 名称，备份计划名称
	Name *string `json:"Name"`
	// 暂停原因，备份计划暂停原因
	PauseReason *string `json:"PauseReason"`
	// 备份计划ID，计划唯一标识
	PlanID *string `json:"PlanID"`
	// 失败原因，备份计划失败原因
	Reason *string `json:"Reason"`
	// 关联的全量备份计划ID，增量备份关联的全量备份计划ID
	RelatedPlanID *string `json:"RelatedPlanID"`
	// 备注，备份计划描述信息
	Remark *string `json:"Remark"`
	// 保留时间，备份保留时长
	RetentionTime *int `json:"RetentionTime"`
	// 调度类型，取值Manual或Timer
	ScheduleType *string `json:"ScheduleType"`
	// 备份源ID，备份源资源ID
	SrcID *string `json:"SrcID"`
	// 备份源名称，备份源资源名称
	SrcName *string `json:"SrcName"`
	// 备份源地域，备份源资源所属地域
	SrcRegion *string `json:"SrcRegion"`
	// 备份源类型，备份源资源类型
	SrcType *string `json:"SrcType"`
	// 状态，备份计划状态
	Status *string `json:"Status"`
	// 存储池ID，备份存储池ID
	StorageID *string `json:"StorageID"`
	// 存储池名称，备份存储池名称
	StorageName *string `json:"StorageName"`
	// 备份资源存储集群架构，备份存储集群架构
	StorageSetArch *string `json:"StorageSetArch"`
	// 执行日期，TimerType为TIMER_TYPE_MONTHLY时必填
	TimerDays []int `json:"TimerDays"`
	// 执行小时，TimerType为TIMER_TYPE_DAILY时必填
	TimerHours []int `json:"TimerHours"`
	// 定时器ID，定时器唯一标识
	TimerID *string `json:"TimerID"`
	// 定时器类型，ScheduleType为Timer时必填
	TimerType *string `json:"TimerType"`
	// 执行星期，TimerType为TIMER_TYPE_WEEKLY时必填
	TimerWeeks []int `json:"TimerWeeks"`
	// 更新时间，备份计划更新时间戳
	UpdateTime *int `json:"UpdateTime"`
}
