// Code generated by sdk-generator. DO NOT EDIT.

package models


// DHCPServerStateResult 
type DHCPServerStateResult struct {
	// DHCP 服务器主机IP地址
	HostIP *string `json:"HostIP"`
	// DHCP 服务器主机名
	Hostname *string `json:"Hostname"`
	// DHCP 服务器状态. dead: 未运行, running: 运行中
	Stage *string `json:"Stage"`
	// 操作是否成功
	Success *bool `json:"Success"`
}
