// Code generated by sdk-generator. DO NOT EDIT.

package models


// DiskSelectorV2 
type DiskSelectorV2 struct {
	// 磁盘选择模式，by-path：按设备路径选择；by-id：按设备ID选择；by-wwn：按WWN选择（Kickstart模式会自动转换为by-id）；script：使用自定义脚本选择
	Mode *string `json:"Mode"`
	// 自定义脚本，当Mode为script时使用，用于动态选择磁盘
	Script *string `json:"Script"`
	// 选择器表达式，根据Mode指定磁盘标识，在Kickstart模式且Mode为by-wwn时，系统会自动在Selector前添加wwn-前缀转换为by-id格式
	Selector *string `json:"Selector"`
}
