// Code generated by sdk-generator. DO NOT EDIT.

package models


// Disk 
type Disk struct {
	// 磁盘可用空间大小，单位GB，表示源端磁盘的剩余容量
	Avail *float64 `json:"Avail"`
	// 设备名称或分区标识，如/dev/sda1、/dev/vda1等，用于唯一标识磁盘分区
	Device *string `json:"Device"`
	// 文件系统类型，用于标识磁盘的格式类型
	FsType *string `json:"FsType"`
	// 是否为根分区，用于标识该分区是否为操作系统根分区（挂载点为/）
	IsRoot *bool `json:"IsRoot"`
	// 挂载点路径，表示磁盘分区在源端操作系统中的挂载位置
	MountPoint *string `json:"MountPoint"`
	// 磁盘总大小，单位GB，表示源端磁盘的总容量
	Size *float64 `json:"Size"`
}
