// Code generated by sdk-generator. DO NOT EDIT.

package models


// DTSPrecheckItem 
type DTSPrecheckItem struct {
	// 检查结果，标识该检查项是否通过，true表示通过，false表示未通过
	Passed *bool `json:"Passed"`
	// 检查项名称，说明该预检查项检查的具体内容
	PreCheckName *string `json:"PreCheckName"`
	// 失败原因，当Passed为false时说明未通过原因及建议处理方式
	Reason *string `json:"Reason"`
}
