// Code generated by sdk-generator. DO NOT EDIT.

package models


// DTSTaskInfo 
type DTSTaskInfo struct {
	// 是否允许启动，0表示不允许，1表示允许
	AllowStart *int `json:"AllowStart"`
	// 架构，DTS实例架构
	Arch *string `json:"Arch"`
	// CPU核数，DTS实例CPU配置
	CPU *int `json:"CPU"`
	// 计费类型，取值范围：Dynamic、Month、Year；兼容历史值：hour、month、year，别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR
	ChargeType *string `json:"ChargeType"`
	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 租户名称，资源所属租户名称
	CompanyName *string `json:"CompanyName"`
	// 计算集群类型，DTS实例所在计算集群
	ComputeClass *string `json:"ComputeClass"`
	// 创建时间，秒级Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// DTS任务ID，数据传输任务唯一标识
	DTSID *string `json:"DTSID"`
	// 目标实例ID，当目标为Internal时返回
	DestinationEndpointInstanceID *string `json:"DestinationEndpointInstanceID"`
	// 目标实例名称，目标端内部实例名称
	DestinationEndpointInstanceName *string `json:"DestinationEndpointInstanceName"`
	// 目标实例数据库类型，取值范围：MYSQL、REDIS
	DestinationEngine *string `json:"DestinationEngine"`
	// 弹性公网IP地址，绑定到DTS实例的公网地址
	EIP *string `json:"EIP"`
	// 弹性公网IPID，绑定到DTS实例的EIP
	EIPID *string `json:"EIPID"`
	// 弹性公网IP名称，绑定到DTS实例的EIP名称
	EIPName *string `json:"EIPName"`
	// 租户邮箱，资源所属租户的联系邮箱
	Email *string `json:"Email"`
	// 过期时间，秒级Unix时间戳
	ExpireTime *int `json:"ExpireTime"`
	// 最大每秒同步记录数，用于限制同步速率，取值最小范围为100，最大范围根据DTS实例CPU核数确定，1核上限为20000，2核上限为40000
	MaxRPS *int `json:"MaxRPS"`
	// 内存大小，单位GB，DTS实例内存配置
	Memory *int `json:"Memory"`
	// DTS任务名称，用于展示资源名称
	Name *string `json:"Name"`
	// 项目ID，资源所属项目分组
	ProjectID *string `json:"ProjectID"`
	// 项目名称，资源所属项目名称
	ProjectName *string `json:"ProjectName"`
	// 失败原因，任务失败时的错误信息
	Reason *string `json:"Reason"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region"`
	// 地域名称，地域显示名
	RegionAlias *string `json:"RegionAlias"`
	// 备注，数据传输任务的描述信息
	Remark *string `json:"Remark"`
	// 源实例ID，当源为Internal时返回
	SourceEndpointInstanceID *string `json:"SourceEndpointInstanceID"`
	// 源实例名称，源端内部实例名称
	SourceEndpointInstanceName *string `json:"SourceEndpointInstanceName"`
	// 源实例数据库类型，取值范围：MYSQL、REDIS
	SourceEngine *string `json:"SourceEngine"`
	// 状态，DTS任务状态，来自资源状态与运行状态
	Status *string `json:"Status"`
	// 存储集群类型，DTS实例系统盘所在存储集群
	StorageClass *string `json:"StorageClass"`
	// 标签列表，用于资源标记和分类管理
	Tags []UnifiedTag `json:"Tags"`
	// 任务类型，数据传输任务同步模式
	TaskMode *string `json:"TaskMode"`
	// 任务阶段状态列表，包含各阶段状态
	TaskStages []TaskStage `json:"TaskStages"`
	// 更新时间，秒级Unix时间戳
	UpdateTime *int `json:"UpdateTime"`
}
