// Code generated by sdk-generator. DO NOT EDIT.

package models


// ExpiredResourceInfo 
type ExpiredResourceInfo struct {
	// 过期资源列表，包含该资源类型下的所有过期资源
	Items []BaseExpiredResourceInfo `json:"Items"`
	// 资源类型，资源的分类标识
	ResourceType *string `json:"ResourceType"`
}
