// Code generated by sdk-generator. DO NOT EDIT.

package models


// ExternalStorageSetInfo 
type ExternalStorageSetInfo struct {
	// 
	CSIPluginAddress *string `json:"CSIPluginAddress"`
	// 
	CreateTime *int `json:"CreateTime"`
	// 
	DisableTargetIQNs []string `json:"DisableTargetIQNs"`
	// 
	EnableTargetIQNs []string `json:"EnableTargetIQNs"`
	// 
	LUNCount *int `json:"LUNCount"`
	// 
	Reason *string `json:"Reason"`
	// 
	Region *string `json:"Region"`
	// 
	SetAlias *string `json:"SetAlias"`
	// 
	SetArch *string `json:"SetArch"`
	// 
	SetID *string `json:"SetID"`
	// 
	SetType *string `json:"SetType"`
	// 
	Status *string `json:"Status"`
	// 
	StorageCap *int `json:"StorageCap"`
	// 
	UserName *string `json:"UserName"`
}
