// Code generated by sdk-generator. DO NOT EDIT.

package models


// FileInfo 
type FileInfo struct {
	// 文件路径，文件或目录的绝对路径
	FilePath *string `json:"FilePath"`
	// 是否为目录，用于区分文件与目录
	IsDir *bool `json:"IsDir"`
	// 文件修改时间，Unix 时间戳（秒级）
	ModTime *int `json:"ModTime"`
	// 文件名，文件或目录的名称
	Name *string `json:"Name"`
	// 文件大小，单位：字节
	Size *int `json:"Size"`
}
