// Code generated by sdk-generator. DO NOT EDIT.

package models


// FSInfo 
type FSInfo struct {
	// 带宽，磁盘吞吐量（MB/s）
	Bandwidth *int `json:"Bandwidth"`
	// 计费类型，计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）；兼容历史值：hour、month、year，别名映射：Dynamic→HOUR、Month→MONTH、Year→YEAR
	ChargeType *string `json:"ChargeType"`
	// 租户ID，文件存储所属租户标识
	CompanyID *int `json:"CompanyID"`
	// 租户名称，文件存储所属租户名称
	CompanyName *string `json:"CompanyName"`
	// 创建时间，Unix 时间戳（秒级）
	CreateTime *int `json:"CreateTime"`
	// 磁盘ID，文件存储挂载的数据盘标识
	DiskID *string `json:"DiskID"`
	// 存储容量，单位GiB
	DiskSpace *int `json:"DiskSpace"`
	// 租户邮箱，文件存储所属租户联系邮箱
	Email *string `json:"Email"`
	// 网络信息，文件存储访问终端信息
	Endpoints []FsEndpoint `json:"Endpoints"`
	// 过期时间，Unix 时间戳（秒级）
	ExpireTime *int `json:"ExpireTime"`
	// 文件存储实例ID，文件存储标识
	FSID *string `json:"FSID"`
	// IOPS，磁盘每秒输入输出操作次数
	IOPS *int `json:"IOPS"`
	// 名称，文件存储服务名称
	Name *string `json:"Name"`
	// 项目组ID，文件存储所属项目组
	ProjectID *string `json:"ProjectID"`
	// 项目组名称，文件存储所属项目组名称
	ProjectName *string `json:"ProjectName"`
	// 失败原因，创建或回收失败的原因
	Reason *string `json:"Reason"`
	// 地域，文件存储所属地域
	Region *string `json:"Region"`
	// 地域别名，用于展示
	RegionAlias *string `json:"RegionAlias"`
	// 备注，用于说明文件存储用途
	Remark *string `json:"Remark"`
	// 计算集群架构，取值范围：x86_64、AArch64
	SetArch *string `json:"SetArch"`
	// 状态，文件存储运行状态，取值范围：Running、Stopped、Starting、Stopping、Upgrading
	Status *string `json:"Status"`
	// 存储集群架构，数据盘所在存储集群架构
	StorageSetArch *string `json:"StorageSetArch"`
	// 存储集群类型，数据盘所在存储集群类型
	StorageSetType *string `json:"StorageSetType"`
	// 存储集群名称，数据盘所在存储集群名称
	StorageSetTypeAlias *string `json:"StorageSetTypeAlias"`
	// 子网ID，文件存储所属子网标识
	SubnetID *string `json:"SubnetID"`
	// 子网名称，文件存储所属子网名称
	SubnetName *string `json:"SubnetName"`
	// 标签，资源标签列表
	Tags []UnifiedTag `json:"Tags"`
	// 删除保护策略，取值范围：0（开启删除保护）、1（关闭删除保护）
	TerminationPolicy *int `json:"TerminationPolicy"`
	// 更新时间，Unix 时间戳（秒级）
	UpdateTime *int `json:"UpdateTime"`
	// 计算集群类型，文件存储所在计算集群类型
	VMType *string `json:"VMType"`
	// 计算集群名称，文件存储所在计算集群名称
	VMTypeAlias *string `json:"VMTypeAlias"`
	// VPC ID，文件存储所属VPC标识
	VPCID *string `json:"VPCID"`
	// VPC名称，文件存储所属VPC名称
	VPCName *string `json:"VPCName"`
}
