// Code generated by sdk-generator. DO NOT EDIT.

package models


// HostVGPUUsedInfo 
type HostVGPUUsedInfo struct {
	// 可用vGPU，该规格剩余可分配数量
	Allocable *int `json:"Allocable"`
	// vGPU总量，该规格可分配总数
	Count *int `json:"Count"`
	// 锁定vGPU，该规格已锁定待分配数量
	Locked *int `json:"Locked"`
	// vGPU规格名称，虚拟GPU配置规格
	MdevName *string `json:"MdevName"`
	// 已用vGPU，该规格已分配数量
	Used *int `json:"Used"`
}
