// Code generated by sdk-generator. DO NOT EDIT.

package models


// HostGPUUsedInfo 
type HostGPUUsedInfo struct {
	// 可用GPU，剩余可分配数量
	Allocable *int `json:"Allocable"`
	// GPU总量，物理GPU总数
	Count *int `json:"Count"`
	// GPU硬件名称，物理GPU设备名称
	HDName *string `json:"HDName"`
	// 锁定GPU，已锁定待分配数量
	Locked *int `json:"Locked"`
	// vGPU规格名称，支持的虚拟GPU规格
	MdevName *string `json:"MdevName"`
	// 已用GPU，已分配数量
	Used *int `json:"Used"`
}
