// Code generated by sdk-generator. DO NOT EDIT.

package models


// HostInfo 
type HostInfo struct {
	// 可用CPU，剩余可分配的CPU核心数
	CPUAllocable *int `json:"CPUAllocable"`
	// CPU总数，物理CPU核心总数
	CPUCount *int `json:"CPUCount"`
	// CPU类型，处理器型号信息
	CPUType *string `json:"CPUType"`
	// 已用CPU，已分配的CPU核心数
	CPUUsed *int `json:"CPUUsed"`
	// 创建时间，资源创建的秒级Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// 可用GPU，剩余可分配的GPU数量
	GPUAllocable *int `json:"GPUAllocable"`
	// GPU总量，物理GPU设备总数
	GPUCount *int `json:"GPUCount"`
	// GPU信息，物理GPU使用详情
	GPUInfos []HostGPUUsedInfo `json:"GPUInfos"`
	// GPU类型，GPU设备型号
	GPUType *string `json:"GPUType"`
	// 已用GPU，已分配的GPU数量
	GPUUsed *int `json:"GPUUsed"`
	// 物理机ID，物理机唯一标识（通常为IP）
	HostID *string `json:"HostID"`
	// 物理机IP，物理机管理IP地址
	HostIP *string `json:"HostIP"`
	// 物理机IPv6，物理机管理IPv6地址
	HostIPv6 *string `json:"HostIPv6"`
	// 物理机状态，当前运行状态
	HostStatus *string `json:"HostStatus"`
	// 可用内存，剩余可分配的内存容量，单位GiB
	MemoryAllocable *int `json:"MemoryAllocable"`
	// 总内存，内存总容量，单位GiB
	MemoryCap *int `json:"MemoryCap"`
	// 系统内存，物理机自身使用的内存，单位GiB
	MemoryPhysicUsed *int `json:"MemoryPhysicUsed"`
	// 预留内存，系统预留的内存，单位GiB
	MemoryReserved *int `json:"MemoryReserved"`
	// 已用内存，已分配的内存容量，单位GiB
	MemoryUsed *int `json:"MemoryUsed"`
	// NUMA节点数，物理机的NUMA节点数量
	NumaNodes *int `json:"NumaNodes"`
	// 地域ID，资源所属的地理标识
	Region *string `json:"Region"`
	// 资源数量，运行的实例（如VM）数量
	ResourceCount *int `json:"ResourceCount"`
	// 计算集群ID，所属计算集群标识
	SetID *string `json:"SetID"`
	// 集群类型，所属计算集群类型
	SetType *string `json:"SetType"`
	// 更新时间，资源更新的秒级Unix时间戳
	UpdateTime *int `json:"UpdateTime"`
	// 绑定启用，标识是否启用vCPU绑定
	VCPUBindingEnabled *bool `json:"VCPUBindingEnabled"`
	// 驱动未就绪，标识vGPU驱动是否异常
	VGPUDriverNotReady *bool `json:"VGPUDriverNotReady"`
	// vGPU信息，虚拟GPU使用详情
	VGPUInfos []HostVGPUUsedInfo `json:"VGPUInfos"`
	// 调度权重，负载均衡调度权重值
	Weight *int `json:"Weight"`
}
