// Code generated by sdk-generator. DO NOT EDIT.

package models


// IG 
type IG struct {
	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// 租户名称，用于展示资源所属租户
	CompanyName *string `json:"CompanyName"`
	// 创建时间，秒级Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// 租户邮箱，用于展示资源所属租户的联系邮箱
	Email *string `json:"Email"`
	// 隔离组ID，系统生成的唯一标识
	IGID *string `json:"IGID"`
	// 是否启用，标识隔离组策略是否生效
	IsEnable *bool `json:"IsEnable"`
	// 是否强制执行，强制模式下即使不满足策略也会执行
	IsForce *bool `json:"IsForce"`
	// 隔离组名称，用于标识隔离组并便于检索管理，长度1-128个字符，仅支持中文、英文字母、数字、点（.）、下划线（_）和中划线（-）
	Name *string `json:"Name"`
	// 策略对象列表，PolicyToVG时为隔离组ID列表，PolicyToNode时为节点标识列表
	PolicyObj []string `json:"PolicyObj"`
	// 策略对象类型，取值PolicyToNode/PolicyToVG
	PolicyObjType *string `json:"PolicyObjType"`
	// 策略类型，取值VMAffinity/VMAntiAffinity
	PolicyType *string `json:"PolicyType"`
	// 项目ID，资源所属项目分组标识
	ProjectID *string `json:"ProjectID"`
	// 项目名称，用于展示资源所属项目
	ProjectName *string `json:"ProjectName"`
	// 失败原因，资源处于失败状态时的错误说明
	Reason *string `json:"Reason"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region"`
	// 地域别名，地域的人性化显示名称
	RegionAlias *string `json:"RegionAlias"`
	// 备注，用于补充说明隔离组用途，长度0-100个字符，禁止包含<script>标签或javascript链接
	Remark *string `json:"Remark"`
	// 计算集群名称，用于展示计算集群的显示名称
	SetAlias *string `json:"SetAlias"`
	// 计算集群ID，隔离组所属的计算集群
	SetID *string `json:"SetID"`
	// 计算集群类型，表示隔离组所属集群类型
	SetType *string `json:"SetType"`
	// 状态，取值Available/Error，当资源状态非Available时返回资源状态
	Status *string `json:"Status"`
	// 资源标签，用于展示资源关联的标签信息
	Tags []UnifiedTag `json:"Tags"`
	// 虚拟机列表，展示隔离组关联的虚拟机信息
	VMs []IGVM `json:"VMs"`
}
