// Code generated by sdk-generator. DO NOT EDIT.

package models


// IGVM 
type IGVM struct {
	// 宿主机IP地址，虚拟机所在宿主机地址
	HostIP *string `json:"HostIP"`
	// 隔离组ID列表，虚拟机所属的隔离组
	IGIDs []string `json:"IGIDs"`
	// 隔离组信息，描述虚拟机与隔离组的关系
	Message *string `json:"Message"`
	// 虚拟机名称，用于展示虚拟机标识
	Name *string `json:"Name"`
	// 调度状态
	ScheduleStatus *string `json:"ScheduleStatus"`
	// 虚拟机状态，用于展示运行状态
	Status *string `json:"Status"`
	// 虚拟机ID，指定虚拟机唯一标识
	VMID *string `json:"VMID"`
}
