// Code generated by sdk-generator. DO NOT EDIT.

package models


// ImageDownloadInfo 
type ImageDownloadInfo struct {
	// 下载Query，已做URL编码，需要拼接当前地域S3地址获取完整下载链接，例如http://s3.example.com/download?{DownloadQuery}
	DownloadQuery *string `json:"DownloadQuery"`
	// 过期时间，秒级Unix时间戳
	ExpiredTime *int `json:"ExpiredTime"`
}
