// Code generated by sdk-generator. DO NOT EDIT.

package models


// InspectionNetwork 
type InspectionNetwork struct {
	// 带宽，网络带宽大小(Mbps)
	Bandwidth *int `json:"Bandwidth"`
	// 租户ID，标识该网络拓扑所属的租户
	CompanyID *int `json:"CompanyID"`
	// 邮箱，租户的邮箱地址，从DescribeUser接口返回
	Email *string `json:"Email"`
	// 扁平网络ID，扁平网络的ID，包含flatnet前缀和14位随机字符
	FlatNetworkID *string `json:"FlatNetworkID"`
	// 扁平网络名称，扁平网络的显示名称
	FlatNetworkName *string `json:"FlatNetworkName"`
	// IP地址，资源绑定的IP地址
	IpAddress *string `json:"IpAddress"`
	// IP ID，IP地址资源的ID，包含ip前缀和14位随机字符
	IpID *string `json:"IpID"`
	// IP版本，IP地址的协议版本
	IpVersion *string `json:"IpVersion"`
	// 是否主网卡，标识该网卡是否为资源的主要网络接口
	IsPrimary *bool `json:"IsPrimary"`
	// 是否VIP，标识IP是否为虚拟IP
	IsVip *bool `json:"IsVip"`
	// MAC地址列表，资源绑定的网卡MAC地址
	MacAddresses []string `json:"MacAddresses"`
	// 网络类型，网络连接的类型
	NetworkType *string `json:"NetworkType"`
	// 地域ID，标识该网络拓扑所属的地域
	Region *string `json:"Region"`
	// 资源ID，资源的唯一标识，包含资源类型前缀和14位随机字符
	ResourceID *string `json:"ResourceID"`
	// 资源名称，资源的显示名称
	ResourceName *string `json:"ResourceName"`
	// 资源类型
	ResourceType *string `json:"ResourceType"`
	// 资源层类型属性，用于分类统计的资源类型标识，与ResourceType对应但可能有差异
	ResourceTypeAttr *string `json:"ResourceTypeAttr"`
	// 线路ID，外网线路的ID，包含segment前缀和14位随机字符
	SegmentID *string `json:"SegmentID"`
	// 线路名称，外网线路的显示名称
	SegmentName *string `json:"SegmentName"`
	// 线路网络，外网线路的网络段
	SegmentNetwork *string `json:"SegmentNetwork"`
	// 状态，资源或IP的当前状态
	Status *string `json:"Status"`
	// 子网ID，资源所属子网的ID，包含subnet前缀和14位随机字符
	SubnetID *string `json:"SubnetID"`
	// 子网名称，资源所属子网的显示名称
	SubnetName *string `json:"SubnetName"`
	// VPC ID，资源所属VPC的ID，包含vpc前缀和14位随机字符
	VpcID *string `json:"VpcID"`
	// VPC名称，资源所属VPC的显示名称
	VpcName *string `json:"VpcName"`
}
