// Code generated by sdk-generator. DO NOT EDIT.

package models


// InstallBondConfig 
type InstallBondConfig struct {
	// Bond模式
	Mode *string `json:"Mode"`
	// Bond名称
	Name *string `json:"Name"`
	// 从属设备列表
	Slaves []string `json:"Slaves"`
}
