// Code generated by sdk-generator. DO NOT EDIT.

package models


// InstallLogEntryV2 
type InstallLogEntryV2 struct {
	// 级别
	Level *string `json:"Level"`
	// 消息
	Message *string `json:"Message"`
	// 时间
	Time *string `json:"Time"`
}
