// Code generated by sdk-generator. DO NOT EDIT.

package models


// LbBindVSInfo 
type LbBindVSInfo struct {
	// 负载均衡ID，用于标识关联的负载均衡实例
	LBID *string `json:"LBID"`
	// 负载均衡名称，用于展示关联的负载均衡名称
	LBName *string `json:"LBName"`
	// 虚拟服务器端口，用于展示监听器端口，取值范围：1~65535
	Port *int `json:"Port"`
	// 虚拟服务器协议，用于展示监听器协议，取值范围：TCP、UDP、HTTP、HTTPS
	Protocol *string `json:"Protocol"`
	// 虚拟服务器ID，用于标识关联的监听器实例
	VSID *string `json:"VSID"`
}
