// Code generated by sdk-generator. DO NOT EDIT.

package models


// LbVSPolicyInfo 
type LbVSPolicyInfo struct {
	// CA证书ID，SNI协议开启时的CA证书ID
	CACertificateID *string `json:"CACertificateID"`
	// 创建时间，秒级Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// 请求域名，转发规则关联的请求域名，值可为空表示仅匹配路径，若填写则遵循Nginx server_name规则（最长30字符，可使用*.example.com或mail.*一类通配格式）
	Domain *string `json:"Domain"`
	// 负载均衡ID，用于标识所属负载均衡实例
	LBID *string `json:"LBID"`
	// 请求访问路径，转发规则关联的请求访问路径，如'/'，
	Path *string `json:"Path"`
	// 转发规则ID，用于定位转发规则
	PolicyID *string `json:"PolicyID"`
	// 转发规则状态，转发规则的状态，取值范围：Available（有效）、Deleted（已删除）
	PolicyStatus *string `json:"PolicyStatus"`
	// 真实服务器列表，转发规则关联的真实服务器列表
	RSInfos []LbRSInfo `json:"RSInfos"`
	// HTTP重定向转发规则ID，HTTP重定向指向的转发规则ID
	RedirectPolicyID *string `json:"RedirectPolicyID"`
	// SSL认证模式，SNI协议开启时的SSL模式，取值范围：simplex、duplex
	SSLMode *string `json:"SSLMode"`
	// 服务器证书ID，SNI协议开启时的服务器证书ID
	ServerCertificateID *string `json:"ServerCertificateID"`
	// 更新时间，秒级Unix时间戳
	UpdateTime *int `json:"UpdateTime"`
	// 虚拟服务器ID，用于标识所属监听器
	VSID *string `json:"VSID"`
}
