// Code generated by sdk-generator. DO NOT EDIT.

package models


// LoadBalancerInfo 
type LoadBalancerInfo struct {
	// 负载均衡ID
	LBID *string `json:"LBID"`
	// 负载均衡名称
	Name *string `json:"Name"`
	// 监听端口，伸缩成员加入负载均衡时使用的端口号
	Port *int `json:"Port"`
	// 监听器ID
	VServerID *string `json:"VServerID"`
	// 负载均衡权重，伸缩成员在负载均衡中的权重值
	Weight *int `json:"Weight"`
}
