// Code generated by sdk-generator. DO NOT EDIT.

package models


// MenuOne 
type MenuOne struct {
	// 二级菜单列表，包含该地域下的各个检查分类
	Children []MenuTwo `json:"Children"`
	// 一级菜单ID，地域ID
	Key *string `json:"Key"`
	// 一级菜单名称，地域名称(已转换为别名)
	Title *string `json:"Title"`
}
