// Code generated by sdk-generator. DO NOT EDIT.

package models


// Metric 
type Metric struct {
	// 权限列表，定义哪些角色或用户可以访问和使用该监控指标
	Authority []string `json:"Authority"`
	// 监控指标详细信息列表，包含该资源类型下所有可用的具体监控指标
	Infos []MetricInfo `json:"Infos"`
	// 是否支持告警功能，标识该指标是否可以用于配置告警规则
	IsAlerting *bool `json:"IsAlerting"`
	// 资源类型，标识该监控指标所监控的资源类型，如虚拟机、磁盘、网络等
	TargetType *string `json:"TargetType"`
	// 是否需要单位转换回调，标识在显示指标数据时是否需要进行单位转换处理
	UseYCallback *bool `json:"UseYCallback"`
}
