// Code generated by sdk-generator. DO NOT EDIT.

package models


// MySQLInfo 
type MySQLInfo struct {
	// 集群架构，实例计算架构
	Arch *string `json:"Arch"`
	// SQL审计状态，0:关闭;1:开启
	AuditStatus *string `json:"AuditStatus"`
	// 带宽，单位：Mbps
	Bandwidth *int `json:"Bandwidth"`
	// 计费类型，用于指定计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）
	ChargeType *string `json:"ChargeType"`
	// 租户ID，用于标识资源所属的租户，实现多租户环境下的资源隔离
	CompanyID *int `json:"CompanyID"`
	// 租户名称，租户的名称
	CompanyName *string `json:"CompanyName"`
	// 创建时间，Unix时间戳（秒级）
	CreateTime *int `json:"CreateTime"`
	// 磁盘ID，实例数据盘ID
	DiskID *string `json:"DiskID"`
	// 存储容量，单位：GiB
	DiskSpace *int `json:"DiskSpace"`
	// 租户邮箱，租户注册时提供的用于接收通知和联系的邮箱
	Email *string `json:"Email"`
	// MySQL网络信息，实例网络信息列表
	Endpoints []MysqlEndpoint `json:"Endpoints"`
	// 过期时间，Unix时间戳（秒级）
	ExpireTime *int `json:"ExpireTime"`
	// MySQL数据库高可用类型，实例高可用类型
	HighAvailability *string `json:"HighAvailability"`
	// IOPS，单位：IOPS
	IOPS *int `json:"IOPS"`
	// legacy 配置是否已完成归一化，true 表示已归一化并退出兼容 bypass
	LegacyConfigNormalized *string `json:"LegacyConfigNormalized"`
	// legacy 升级来源标记，仅用于标识老版本升级进入 2.13.x 的兼容实例
	LegacyUpgradeFrom *string `json:"LegacyUpgradeFrom"`
	// 内存大小，单位：MiB
	Memory *int `json:"Memory"`
	// MySQL实例ID，实例唯一标识
	MySQLID *string `json:"MySQLID"`
	// MySQL名称，实例名称
	Name *string `json:"Name"`
	// 项目组ID，用于资源分组管理
	ProjectID *string `json:"ProjectID"`
	// 项目组名称，项目组的名称
	ProjectName *string `json:"ProjectName"`
	// 创建失败原因，实例创建失败原因
	Reason *string `json:"Reason"`
	// 地域ID，地域，一批可共享的物理资源使用集合
	Region *string `json:"Region"`
	// 地域别名，地域的别名
	RegionAlias *string `json:"RegionAlias"`
	// 备注，用于进行说明和注释，长度为0-100个英文或中文字符，不能使用的http://或https://等非法字符，可为空
	Remark *string `json:"Remark"`
	// MySQL角色，取值范围：1、Master（主节点）2、Slave（从节点）
	Role *string `json:"Role"`
	// 从库信息，从库实例信息列表
	SlaveInfos []MySQLSlaveInfo `json:"SlaveInfos"`
	// MySQL资源状态，实例状态
	Status *string `json:"Status"`
	// 存储集群架构，实例存储集群架构
	StorageSetArch *string `json:"StorageSetArch"`
	// 存储集群ID，实例存储集群ID
	StorageSetType *string `json:"StorageSetType"`
	// 存储集群名称，实例存储集群名称
	StorageSetTypeAlias *string `json:"StorageSetTypeAlias"`
	// 子网ID，实例所属子网ID
	SubnetID *string `json:"SubnetID"`
	// 子网名称，实例所属子网名称
	SubnetName *string `json:"SubnetName"`
	// 标签，资源标签列表
	Tags []UnifiedTag `json:"Tags"`
	// 是否开启删除保护，0:开启;1:关闭
	TerminationPolicy *int `json:"TerminationPolicy"`
	// 更新时间，Unix时间戳（秒级）
	UpdateTime *int `json:"UpdateTime"`
	// 计算集群类型，实例所属计算集群类型
	VMType *string `json:"VMType"`
	// 计算集群名称，实例所属计算集群名称
	VMTypeAlias *string `json:"VMTypeAlias"`
	// VPCID，实例所属VPCID
	VPCID *string `json:"VPCID"`
	// VPC名称，实例所属VPC名称
	VPCName *string `json:"VPCName"`
	// MySQL版本，必须为'MySQL 5.7'或者'MySQL 8.0'
	Version *string `json:"Version"`
}
