// Code generated by sdk-generator. DO NOT EDIT.

package models


// Network 
type Network struct {
	// 虚拟网卡详情，节点网卡信息
	NICs []NIC `json:"NICs"`
	// 物理网卡详情，节点网卡信息
	PhyProductInfos []PhyProductInfo `json:"PhyProductInfos"`
}
