// Code generated by sdk-generator. DO NOT EDIT.

package models


// ObserverInfo 
type ObserverInfo struct {
	// 观察人邮箱地址，观察人的邮箱，用于接收审批进度通知
	ObserverEmail *string `json:"ObserverEmail"`
	// 观察人账号ID，可以查看审批进度但不参与审批决策的用户标识
	ObserverMemberID *int `json:"ObserverMemberID"`
}
