// Code generated by sdk-generator. DO NOT EDIT.

package models


// OPLogInfo 
type OPLogInfo struct {
	// API名称，触发该操作日志的接口名称
	APIName *string `json:"APIName"`
	// 客户端IP，发起请求的客户端IP地址
	ClientIp *string `json:"ClientIp"`
	// 租户ID，日志所属租户的唯一标识
	CompanyID *int `json:"CompanyID"`
	// 错误上下文，用于前端参数化翻译，包含错误相关的键值对
	Context *map[string]string `json:"Context"`
	// 创建时间，日志生成的Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// HTTP请求响应详情，记录请求与响应的原始信息
	HttpInfo *HttpInfo `json:"HttpInfo"`
	// 返回信息，API响应的描述信息
	Message *string `json:"Message"`
	// 操作日志ID，系统生成的唯一标识
	OPLogID *int `json:"OPLogID"`
	// 产品类型，操作涉及的产品分类
	ProductType *string `json:"ProductType"`
	// 地域ID，操作发生的地域标识
	Region *string `json:"Region"`
	// 地域别称，地域的显示名称
	RegionAlias *string `json:"RegionAlias"`
	// 资源ID，操作涉及的资源唯一标识
	ResourceID *string `json:"ResourceID"`
	// 操作后关联资源快照，记录资源名称、类型和IP信息
	ResourcesAfter []OPLogResource `json:"ResourcesAfter"`
	// 操作前关联资源快照，记录资源名称、类型和IP信息
	ResourcesBefore []OPLogResource `json:"ResourcesBefore"`
	// 返回码，API响应的状态码；0表示成功，非0表示失败
	RetCode *int `json:"RetCode"`
	// 更新时间，日志信息最后更新的Unix时间戳
	UpdateTime *int `json:"UpdateTime"`
	// 账号邮箱，执行操作的用户邮箱
	UserEmail *string `json:"UserEmail"`
}
