// Code generated by sdk-generator. DO NOT EDIT.

package models


// Order 
type Order struct {
	// 内部账户金额，从内部账户（赠金）扣除的金额，单位为元
	AmountFree *float64 `json:"AmountFree"`
	// 外部账户金额，从外部账户扣除的金额，单位为元
	AmountReal *float64 `json:"AmountReal"`
	// 总金额，订单的总金额，等于外部账户金额加内部账户金额，单位为元
	AmountTotal *float64 `json:"AmountTotal"`
	// 计费类型，资源的计费方式，Hour表示按小时计费、Month表示按月计费、Year表示按年计费
	ChargeType *string `json:"ChargeType"`
	// 租户ID，订单所属的租户唯一标识
	CompanyID *int `json:"CompanyID"`
	// 租户名称，订单所属的租户显示名称
	CompanyName *string `json:"CompanyName"`
	// 创建时间，订单的创建时间戳，单位为秒
	CreateTime *int `json:"CreateTime"`
	// 租户邮箱，订单所属的租户邮箱地址
	Email *string `json:"Email"`
	// 订单详情列表，包含订单中各个资源的详细计费信息
	OrderDetails []OrderDetail `json:"OrderDetails"`
	// 订单编号，订单的唯一标识
	OrderNO *string `json:"OrderNO"`
	// 订单类型，订单的业务类型，BUY表示购买、RENEW表示续费、REFUND表示退款
	OrderType *string `json:"OrderType"`
	// 地域，订单资源所属的地域标识
	Region *string `json:"Region"`
	// 地域别名，订单资源所属的地域显示名称，从DescribeRegion接口获取
	RegionAlias *string `json:"RegionAlias"`
	// 资源ID，订单关联的资源唯一标识，例如磁盘订单对应磁盘ID
	ResourceID *string `json:"ResourceID"`
	// 资源名称，订单关联资源的显示名称，若资源不存在则显示资源ID
	ResourceName *string `json:"ResourceName"`
}
