// Code generated by sdk-generator. DO NOT EDIT.

package models


// OSMediaInfoV2 
type OSMediaInfoV2 struct {
	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// 租户名称
	CompanyName *string `json:"CompanyName"`
	// 创建时间
	CreatedAt *int `json:"CreatedAt"`
	// 描述
	Description *string `json:"Description"`
	// 租户邮箱
	Email *string `json:"Email"`
	// 错误信息
	ErrorMessage *string `json:"ErrorMessage"`
	// 文件大小(字节)
	FileSize *int `json:"FileSize"`
	// 镜像ID
	ImageID *string `json:"ImageID"`
	// 是否默认系统镜像
	IsDefault *bool `json:"IsDefault"`
	// 系统镜像ID（Taishan生成）
	MediaID *string `json:"MediaID"`
	// 系统镜像名称
	Name *string `json:"Name"`
	// 操作系统发行版（如：CentOS、OpenEuler）
	OSDistribution *string `json:"OSDistribution"`
	// 操作系统完整名称（如：CentOS 7.4 x86_64）
	OSName *string `json:"OSName"`
	// 项目ID
	ProjectID *string `json:"ProjectID"`
	// 项目名称
	ProjectName *string `json:"ProjectName"`
	// 地域
	Region *string `json:"Region"`
	// SHA256校验和
	SHA256 *string `json:"SHA256"`
	// 状态
	Status *string `json:"Status"`
	// 标签
	Tags []UnifiedTag `json:"Tags"`
	// 系统镜像类型: ISO
	Type *string `json:"Type"`
	// 系统镜像URL地址
	URL *string `json:"URL"`
	// 更新时间
	UpdatedAt *int `json:"UpdatedAt"`
}
