// Code generated by sdk-generator. DO NOT EDIT.

package models


// PartitionTemplateRAIDConfig 
type PartitionTemplateRAIDConfig struct {
	// RAID设备名
	Device *string `json:"Device"`
	// 文件系统类型
	FSType *string `json:"FSType"`
	// RAID级别: 0,1,5,6,10
	Level *string `json:"Level"`
	// 成员磁盘
	Members []string `json:"Members"`
	// 挂载点
	MountPoint *string `json:"MountPoint"`
}
