// Code generated by sdk-generator. DO NOT EDIT.

package models


// PartitionTemplateInfo 
type PartitionTemplateInfo struct {
	// 分区配置
	Config *PartitionTemplateConfig `json:"Config"`
	// 创建时间
	CreatedAt *int `json:"CreatedAt"`
	// 创建者
	CreatedBy *string `json:"CreatedBy"`
	// 删除时间
	DeletedAt *int `json:"DeletedAt"`
	// 模板描述
	Description *string `json:"Description"`
	// 模板ID
	ID *string `json:"ID"`
	// 是否为默认模板
	IsDefault *bool `json:"IsDefault"`
	// 是否为系统预定义模板
	IsSystem *bool `json:"IsSystem"`
	// 模板名称
	Name *string `json:"Name"`
	// 操作系统发行版
	OSDistribution *string `json:"OSDistribution"`
	// 分区方案类型
	SchemeType *string `json:"SchemeType"`
	// 更新时间
	UpdatedAt *int `json:"UpdatedAt"`
	// 更新者
	UpdatedBy *string `json:"UpdatedBy"`
	// 版本号
	Version *int `json:"Version"`
}
