// Code generated by sdk-generator. DO NOT EDIT.

package models


// PartitionTemplateBtrfsSubvol 
type PartitionTemplateBtrfsSubvol struct {
	// 挂载点
	MountPoint *string `json:"MountPoint"`
	// 子卷名称
	Name *string `json:"Name"`
	// 挂载选项
	Options *string `json:"Options"`
}
