// Code generated by sdk-generator. DO NOT EDIT.

package models


// PCPUBindingInfo 
type PCPUBindingInfo struct {
	// CPU详情，节点NUMA拓扑CPU信息
	NUMANodes []NUMANode `json:"NUMANodes"`
	// 节点ID，用于标识节点唯一标识
	NodeID *string `json:"NodeID"`
}
