// Code generated by sdk-generator. DO NOT EDIT.

package models


// PhyProductInfo 
type PhyProductInfo struct {
	// 网卡型号标准编号，网卡型号标识
	Code *string `json:"Code"`
	// 节点下的同型号网卡列表
	PFInfos []PFInfo `json:"PFInfos"`
	// 网卡型号，网卡型号名称
	Product *string `json:"Product"`
	// 预占VF列表，已占用VF名额但未确定归属PF，例如绑定中的VF卡或未绑定IP的Eth0
	ReservedVFs []VFInfo `json:"ReservedVFs"`
	// 网卡厂商，网卡厂商名称
	Vendor *string `json:"Vendor"`
}
