// Code generated by sdk-generator. DO NOT EDIT.

package models


// QuotaUsage 
type QuotaUsage struct {
	// 配额因子，计量维度
	FactorType *string `json:"FactorType"`
	// 产品类型
	ProductType *string `json:"ProductType"`
	// 配额总量
	Quota *int `json:"Quota"`
	// 地域ID
	Region *string `json:"Region"`
	// 地域别名，地域的显示名称
	RegionAlias *string `json:"RegionAlias"`
	// 资源类型
	ResourceType *string `json:"ResourceType"`
	// 配额单位
	Unit *string `json:"Unit"`
	// 已使用配额量
	Usage *int `json:"Usage"`
}
