// Code generated by sdk-generator. DO NOT EDIT.

package models


// Quota 
type Quota struct {
	// 集群配额分配JSON字符串，记录计算或存储集群的配额分配
	Allocation *string `json:"Allocation"`
	// 租户ID，标识配额所属的租户
	CompanyID *int `json:"CompanyID"`
	// 创建时间，Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// 配额因子，计量维度
	FactorType *string `json:"FactorType"`
	// 产品类型
	ProductType *string `json:"ProductType"`
	// 配额总量
	Quota *int `json:"Quota"`
	// 地域ID
	Region *string `json:"Region"`
	// 地域别名，地域的显示名称
	RegionAlias *string `json:"RegionAlias"`
	// 资源类型
	ResourceType *string `json:"ResourceType"`
	// 配额状态
	Status *string `json:"Status"`
	// 配额单位
	Unit *string `json:"Unit"`
	// 更新时间，Unix时间戳
	UpdateTime *int `json:"UpdateTime"`
}
