// Code generated by sdk-generator. DO NOT EDIT.

package models


// RedisInfo 
type RedisInfo struct {
	// 计算集群架构，实例计算架构
	Arch *string `json:"Arch"`
	// 计费类型，取值Dynamic/Month/Year，分别对应HOUR/MONTH/YEAR
	ChargeType *string `json:"ChargeType"`
	// 租户ID，用于标识资源所属的租户，实现多租户环境下的资源隔离
	CompanyID *int `json:"CompanyID"`
	// 租户名称，租户显示名称
	CompanyName *string `json:"CompanyName"`
	// 配置文件ID，实例使用的配置模板ID
	ConfigID *string `json:"ConfigID"`
	// 创建时间，Unix时间戳（秒级）
	CreateTime *int `json:"CreateTime"`
	// 租户邮箱，租户注册时提供的用于接收通知和联系的邮箱
	Email *string `json:"Email"`
	// 网络信息，实例访问地址列表
	Endpoints []RedisEndpoint `json:"Endpoints"`
	// 过期时间，Unix时间戳（秒）
	ExpireTime *int `json:"ExpireTime"`
	// 高可用类型，Standalone或ActiveStandy
	HighAvailability *string `json:"HighAvailability"`
	// 内存大小，单位GiB
	Memory *int `json:"Memory"`
	// 内存使用情况，实例内存使用信息
	MemoryUsage *MemoryUsage `json:"MemoryUsage"`
	// Redis名称，实例名称
	Name *string `json:"Name"`
	// 项目组ID，用于资源分组管理
	ProjectID *string `json:"ProjectID"`
	// 项目组名称，项目组显示名称
	ProjectName *string `json:"ProjectName"`
	// 创建失败原因，实例创建失败原因
	Reason *string `json:"Reason"`
	// Redis实例ID，实例唯一标识
	RedisID *string `json:"RedisID"`
	// 地域ID，地域，一批可共享的物理资源使用集合
	Region *string `json:"Region"`
	// 地域别名，地域展示名称
	RegionAlias *string `json:"RegionAlias"`
	// 备注，用于进行说明和注释，长度为0-100个英文或中文字符，不能使用的http://或https://等非法字符，可为空
	Remark *string `json:"Remark"`
	// 角色，实例角色类型
	Role *string `json:"Role"`
	// 计算集群类型，实例所属计算集群类型
	SetType *string `json:"SetType"`
	// 从节点数量，从库数量
	SlaveCount *int `json:"SlaveCount"`
	// 从库信息，从库实例列表
	SlaveInfos []SlaveRedisInfo `json:"SlaveInfos"`
	// 资源状态，实例状态字符串
	Status *string `json:"Status"`
	// 存储集群类型，实例数据盘所属存储集群类型
	StorageSetType *string `json:"StorageSetType"`
	// 子网ID，实例所属子网ID
	SubnetID *string `json:"SubnetID"`
	// 子网名称，实例所属子网名称
	SubnetName *string `json:"SubnetName"`
	// 标签，用于资源标记和分类管理，格式为key:value的字符串，传入Base64编码的字符串，
	Tags []UnifiedTag `json:"Tags"`
	// 删除保护策略，0开启，1关闭
	TerminationPolicy *int `json:"TerminationPolicy"`
	// 线程数量，Redis7.0有效
	Threads *int `json:"Threads"`
	// 更新时间，Unix时间戳（秒级）
	UpdateTime *int `json:"UpdateTime"`
	// VPCID，实例所属VPCID
	VPCID *string `json:"VPCID"`
	// VPC名称，实例所属VPC名称
	VPCName *string `json:"VPCName"`
	// Redis版本，实例版本
	Version *string `json:"Version"`
}
