// Code generated by sdk-generator. DO NOT EDIT.

package models


// RedisPriceInfo 
type RedisPriceInfo struct {
	// 计费类型，取值Dynamic/Month/Year
	ChargeType *string `json:"ChargeType"`
	// 订单类型，表示计费订单类型
	OrderType *string `json:"OrderType"`
	// 价格，订单价格
	Price *float64 `json:"Price"`
}
