// Code generated by sdk-generator. DO NOT EDIT.

package models


// RegionNetworkLatency 
type RegionNetworkLatency struct {
	// 延迟时间，网络探测的耗时，单位毫秒
	Latency *float64 `json:"Latency"`
	// 探测类型，网络延迟探测方式，如tcp
	ProbeType *string `json:"ProbeType"`
}
