// Code generated by sdk-generator. DO NOT EDIT.

package models


// ResourceTemplateInfo 
type ResourceTemplateInfo struct {
	// 绑定的弹性伸缩组ID列表，模板绑定弹性伸缩组后不允许修改VPCID
	BindAsGroupIDs []string `json:"BindAsGroupIDs"`
	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// 租户名称
	CompanyName *string `json:"CompanyName"`
	// 模板内容，JSON字符串格式，包含创建资源所需的完整配置参数
	Content *string `json:"Content"`
	// 创建时间，秒级Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// 删除时间，秒级Unix时间戳，未删除时为0
	DeleteTime *int `json:"DeleteTime"`
	// 租户邮箱地址
	Email *string `json:"Email"`
	// 模板名称，用于展示模板的标识名称
	Name *string `json:"Name"`
	// 项目ID，模板所属项目分组标识
	ProjectID *string `json:"ProjectID"`
	// 项目名称
	ProjectName *string `json:"ProjectName"`
	// 失败原因，当模板状态异常时记录失败原因
	Reason *string `json:"Reason"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region"`
	// 地域别名，地域的人性化显示名称
	RegionAlias *string `json:"RegionAlias"`
	// 备注，用于补充说明模板用途
	Remark *string `json:"Remark"`
	// 模板状态，取值Available/Deleted/Deleting/Failed等资源状态
	Status *string `json:"Status"`
	// 资源标签列表，用于资源分类和管理
	Tags []UnifiedTag `json:"Tags"`
	// 模板ID
	TemplateID *string `json:"TemplateID"`
	// 模板类型，取值：VM（虚拟机）
	TemplateType *string `json:"TemplateType"`
	// 更新时间，秒级Unix时间戳
	UpdateTime *int `json:"UpdateTime"`
}
