// Code generated by sdk-generator. DO NOT EDIT.

package models


// RoleInfo 
type RoleInfo struct {
	// 租户ID，标识角色所属的租户组织
	CompanyID *int `json:"CompanyID"`
	// 创建时间，角色首次定义的Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// 角色名称，用于在控制台显示
	Name *string `json:"Name"`
	// 备注，用于补充说明角色用途和权限范围
	Remark *string `json:"Remark"`
	// 角色ID，系统生成的权限定义唯一标识符
	RoleID *string `json:"RoleID"`
	// 角色授权层级，取值：System、Region或Company
	Stratum *string `json:"Stratum"`
	// 角色类型，标识角色来源，取值：System或Custom
	Type *string `json:"Type"`
	// 更新时间，角色信息最后修改的Unix时间戳
	UpdateTime *int `json:"UpdateTime"`
}
