// Code generated by sdk-generator. DO NOT EDIT.

package models


// SetVGPUUsedInfo 
type SetVGPUUsedInfo struct {
	// 虚拟GPU可分配量，该类型vGPU当前可用于分配的数量，计算方式为Count-Used-Locked
	Allocable *int `json:"Allocable"`
	// 虚拟GPU总数，该类型vGPU的总数量
	Count *int `json:"Count"`
	// 虚拟GPU已锁定量，该类型vGPU已锁定但尚未分配的数量，如虚拟机创建中
	Locked *int `json:"Locked"`
	// 虚拟GPU设备类型名称，Mdev设备类型标识，如nvidia-63等
	MdevName *string `json:"MdevName"`
	// 虚拟GPU使用量，该类型vGPU已分配给虚拟机的数量
	Used *int `json:"Used"`
}
