// Code generated by sdk-generator. DO NOT EDIT.

package models


// SGRuleInfo 
type SGRuleInfo struct {
	// 目标端口，规则匹配的目标端口号或端口范围
	DstPort *string `json:"DstPort"`
	// IP组ID，当规则引用IP组时的IP组唯一标识符
	IPGroupID *string `json:"IPGroupID"`
	// IP组名称
	IPGroupName *string `json:"IPGroupName"`
	// IP组规则内容，IP组包含的IP地址列表
	IPGroupRules *string `json:"IPGroupRules"`
	// 流量方向，取值1为入站、0为出站
	IsIn *string `json:"IsIn"`
	// 端口组ID，当规则引用端口组时的端口组唯一标识符
	PortGroupID *string `json:"PortGroupID"`
	// 端口组名称
	PortGroupName *string `json:"PortGroupName"`
	// 端口组规则内容，端口组包含的协议与端口组合
	PortGroupRules *string `json:"PortGroupRules"`
	// 优先级，取值HIGH/MEDIUM/LOW
	Priority *string `json:"Priority"`
	// 项目ID
	ProjectID *string `json:"ProjectID"`
	// 项目名称
	ProjectName *string `json:"ProjectName"`
	// 协议类型，支持TCP/UDP/ICMP/ICMPv4/ICMPv6/ALL
	ProtocolType *string `json:"ProtocolType"`
	// 备注，规则的补充说明信息
	Remark *string `json:"Remark"`
	// 规则动作，取值ACCEPT（允许通过）或DROP（拒绝并丢弃）
	RuleAction *string `json:"RuleAction"`
	// 规则ID，安全组规则的唯一标识符
	RuleID *string `json:"RuleID"`
	// 安全组ID，规则所属的安全组唯一标识符
	SGID *string `json:"SGID"`
	// 源IP地址，规则匹配的源IP地址或CIDR地址段
	SrcIP *string `json:"SrcIP"`
	// 规则状态，安全组规则的当前状态
	State *string `json:"State"`
}
