// Code generated by sdk-generator. DO NOT EDIT.

package models


// SMCInfo 
type SMCInfo struct {
	// 源端CPU架构，如x86_64或aarch64
	Arch *string `json:"Arch"`
	// 带宽限速，单位Mbps，用于控制迁移数据传输的网络速率，0表示不限速
	Bandwidth *int `json:"Bandwidth"`
	// 源端启动加载器类型，如BIOS或UEFI，影响目标VM启动配置
	BootloaderType *string `json:"BootloaderType"`
	// 租户ID，SMC任务所属的租户
	CompanyID *int `json:"CompanyID"`
	// 租户名称，租户的可读化展示名称
	CompanyName *string `json:"CompanyName"`
	// 源端CPU核心数，影响迁移性能
	Cores *int `json:"Cores"`
	// 创建时间，Unix时间戳，表示SMC任务创建的时间
	CreateTime *int `json:"CreateTime"`
	// 磁盘映射关系列表，包含源端磁盘与目标云硬盘的映射信息
	DiskMappings []DiskMapping `json:"DiskMappings"`
	// 源端操作系统发行版，如CentOS、Ubuntu、Debian等
	Distribution *string `json:"Distribution"`
	// 源端操作系统发行版版本号，如7.9、20.04等
	DistributionVersion *string `json:"DistributionVersion"`
	// 已完成的子任务数量，用于计算迁移进度
	DoneSubtask *int `json:"DoneSubtask"`
	// 租户邮箱，用于联系租户的邮件地址
	Email *string `json:"Email"`
	// 传输IP地址，目标VM的内网IP地址，用于SSH数据传输
	Host *string `json:"Host"`
	// 源端主机名，源服务器的网络标识
	Hostname *string `json:"Hostname"`
	// 源端IP地址，用于与源服务器通信
	IP *string `json:"IP"`
	// 源端操作系统内核版本号，如3.10.0-1160等
	Kernel *string `json:"Kernel"`
	// 最后同步时间，Unix时间戳，表示任务最后一次同步成功的时间
	LastSyncedTime *int `json:"LastSyncedTime"`
	// 是否已锁定，锁定后不能再进行SetupSMC配置修改，可以防止误操作
	Locked *bool `json:"Locked"`
	// 源端内存大小，单位MB
	Memory *int `json:"Memory"`
	// SMC任务名称，由用户创建时指定的任务标识名
	Name *string `json:"Name"`
	// 源端操作系统类型，如Linux或Windows
	OS *string `json:"OS"`
	// 项目ID，SMC任务所属的项目，用于资源分组管理
	ProjectID *string `json:"ProjectID"`
	// 项目名称，项目的可读化展示名称
	ProjectName *string `json:"ProjectName"`
	// 原因或错误信息，当任务处于异常状态时，此字段记录失败原因或错误信息
	Reason *string `json:"Reason"`
	// 地域ID，SMC任务所属的物理区域
	Region *string `json:"Region"`
	// 地域别名，地域的可读化展示名称
	RegionAlias *string `json:"RegionAlias"`
	// 备注说明，由用户创建时填写的任务备注信息
	Remark *string `json:"Remark"`
	// SMC任务唯一标识ID，全局唯一标识符
	SMCID *string `json:"SMCID"`
	// 当前任务状态，当资源状态为非AVAILABLE时，此字段显示资源状态而非SMC状态，如CREATING、DELETING、EXCEPTION等
	State *string `json:"State"`
	// 子任务列表，包含各个子任务的详细信息
	Subtasks []SMCSubtask `json:"Subtasks"`
	// 标签列表，用户为该SMC任务添加的标签
	Tags []UnifiedTag `json:"Tags"`
	// 子任务总数量，迁移任务分解的总子任务数
	TotalSubtask *int `json:"TotalSubtask"`
	// 更新时间，Unix时间戳，表示SMC任务最后一次修改的时间
	UpdateTime *int `json:"UpdateTime"`
	// 目标虚拟机SSH用户名，用于数据传输的认证
	User *string `json:"User"`
	// 目标传输虚拟机ID，接收迁移数据的目标VM
	VMID *string `json:"VMID"`
}
