// Code generated by sdk-generator. DO NOT EDIT.

package models


// SnapshotInfo 
type SnapshotInfo struct {
	// 租户ID，快照所属租户标识
	CompanyID *int `json:"CompanyID"`
	// 租户名称，快照所属租户名称
	CompanyName *string `json:"CompanyName"`
	// 创建时间，Unix 时间戳（秒级）
	CreateTime *int `json:"CreateTime"`
	// 磁盘关联资源ID，快照源磁盘当前挂载的资源标识
	DiskAttachResourceID *string `json:"DiskAttachResourceID"`
	// 磁盘关联资源类型，快照源磁盘挂载资源类型
	DiskAttachResourceType *string `json:"DiskAttachResourceType"`
	// 磁盘ID，快照所属的源磁盘标识
	DiskID *string `json:"DiskID"`
	// 磁盘名称，快照源磁盘名称
	DiskName *string `json:"DiskName"`
	// 磁盘类型，取值范围：Boot、Data、cdrom、SaveMem、BootImage
	DiskType *string `json:"DiskType"`
	// 租户邮箱，快照所属租户联系邮箱
	Email *string `json:"Email"`
	// 是否加密，标识快照是否继承源磁盘加密属性
	Encrypted *bool `json:"Encrypted"`
	// 快照名称，快照展示名称
	Name *string `json:"Name"`
	// 项目组ID，快照所属项目组
	ProjectID *string `json:"ProjectID"`
	// 项目组名称，快照所属项目组名称
	ProjectName *string `json:"ProjectName"`
	// 失败原因，创建或回收失败的原因
	Reason *string `json:"Reason"`
	// 地域，快照所属的地域
	Region *string `json:"Region"`
	// 地域别名，用于展示
	RegionAlias *string `json:"RegionAlias"`
	// 备注，用于说明快照用途
	Remark *string `json:"Remark"`
	// 快照ID，快照标识
	SnapshotID *string `json:"SnapshotID"`
	// 快照大小，单位GiB
	SnapshotSize *int `json:"SnapshotSize"`
	// 快照状态，取值范围：Unknown、Creating、Normal、Rollbacking、Deleting、Deleted
	SnapshotStatus *string `json:"SnapshotStatus"`
	// 标签，用于资源分类和检索
	Tags []UnifiedTag `json:"Tags"`
	// 快照类型，取值范围：Manual（手动快照）
	Type *string `json:"Type"`
}
