// Code generated by sdk-generator. DO NOT EDIT.

package models


// SpecificationInfo 
type SpecificationInfo struct {
	// 产品类型列表，规格管理中可用的产品类型
	ProductTypes []string `json:"ProductTypes"`
	// 集群类型列表，规格管理中可用的集群类型
	SetTypes []string `json:"SetTypes"`
}
