// Code generated by sdk-generator. DO NOT EDIT.

package models


// StorageSetInfo 
type StorageSetInfo struct {
	// 授权标识，表示该存储集群的授权状态
	Authorized *string `json:"Authorized"`
	// 卷备份对端集群ID，用于卷备份的对端存储集群标识
	BlockBackupPeerSetID *string `json:"BlockBackupPeerSetID"`
	// 集群卷备份状态，包含备份健康状态、备份卷总数、异常卷列表等信息
	BlockBackupStatus *StorageSetBlockBackupStatus `json:"BlockBackupStatus"`
	// 逻辑绑定计算集群列表，当前存储集群绑定的计算集群列表，软限制，可通过UpdateVMSetBoundStorageSet修改
	BoundVMSetList []VmSetItem `json:"BoundVMSetList"`
	// 缓存状态，表示是否开启了OpenCAS缓存加速，值为true或false
	Cache *string `json:"Cache"`
	// 创建时间，Unix时间戳，单位为秒
	CreateTime *int `json:"CreateTime"`
	// DOS多站点角色，分布式对象存储多站点角色，值为master、slave或空字符串
	DOSMultisiteRole *string `json:"DOSMultisiteRole"`
	// 存储集群冗余策略，数据冗余保护策略，如三副本、纠删码等
	Redundancy *string `json:"Redundancy"`
	// 地域ID，存储集群所属的物理区域
	Region *string `json:"Region"`
	// 集群别名，存储集群的自定义名称
	SetAlias *string `json:"SetAlias"`
	// 集群架构，存储集群的硬件架构类型
	SetArch *string `json:"SetArch"`
	// 卷备份角色，当前存储集群在卷备份中的角色，值为master、slave或空字符串
	SetBlockBackupRole *string `json:"SetBlockBackupRole"`
	// set数量，UDisk存储集群的set个数，用于前端计算分配率，仅UDisk类型返回
	SetCount *int `json:"SetCount"`
	// 集群ID，存储集群的唯一标识，由底层Huanghe系统生成和管理
	SetID *string `json:"SetID"`
	// 集群制备器，存储集群的底层存储提供商类型
	SetProvider *string `json:"SetProvider"`
	// 集群类型，存储集群的类型标识
	SetType *string `json:"SetType"`
	// 存储集群总容量，集群的总存储容量，单位为GB
	StorageCap *int `json:"StorageCap"`
	// 存储集群最大超分比例
	StorageMaxOverCommitRatio *float64 `json:"StorageMaxOverCommitRatio"`
	// 存储集群物理可用量，物理层面可用的存储空间，单位为GB
	StoragePhysicAvailable *int `json:"StoragePhysicAvailable"`
	// 存储集群其他用量，非PVC占用的其他存储空间，如元数据等，单位为GB
	StoragePhysicOther *int `json:"StoragePhysicOther"`
	// 存储集群物理使用量，实际占用的物理存储空间，单位为GB
	StoragePhysicUsed *int `json:"StoragePhysicUsed"`
	// 存储集群PVC总容量，已分配给持久化卷声明的总容量，单位为GB
	StorageUsed *int `json:"StorageUsed"`
	// 更新时间，Unix时间戳，单位为秒
	UpdateTime *int `json:"UpdateTime"`
	// 物理绑定计算集群列表，可以使用该存储集群的计算集群列表，硬限制，由底层物理网络拓扑决定
	VmSetList []VmSetItem `json:"VmSetList"`
}
