// Code generated by sdk-generator. DO NOT EDIT.

package models


// SuperNodeInfo 
type SuperNodeInfo struct {
	// 节点可调最大CPU数量
	AdjustableMaxCPU *int `json:"AdjustableMaxCPU"`
	// 节点可调最大内存容量
	AdjustableMaxMemory *int `json:"AdjustableMaxMemory"`
	// 节点可调最大pod数量
	AdjustableMaxPods *int `json:"AdjustableMaxPods"`
	// 架构类型
	ArchType *string `json:"ArchType"`
	// 集群Id
	ClusterID *string `json:"ClusterID"`
	// 计算集群类型
	ComputeclassType *string `json:"ComputeclassType"`
	// 节点GPU信息
	GPUInfos []SuperNodeGPUInfo `json:"GPUInfos"`
	// 
	InternalIP *string `json:"InternalIP"`
	// 默认节点
	IsDefault *bool `json:"IsDefault"`
	// 节点最大CPU数量
	MaxCPU *int `json:"MaxCPU"`
	// 节点最大内存容量
	MaxMemory *int `json:"MaxMemory"`
	// 节点最大pod数量
	MaxPods *int `json:"MaxPods"`
	// 节点名称
	NodeName *string `json:"NodeName"`
	// 节点状态
	NodeStatus *string `json:"NodeStatus"`
	// 系统类型
	OSType *string `json:"OSType"`
	// 状态
	Status *string `json:"Status"`
	// 存储集群类型
	StorageclassType *string `json:"StorageclassType"`
	// 子网Id 列表
	SubnetIDs []string `json:"SubnetIDs"`
	// 子网名称列表
	SubnetNames []string `json:"SubnetNames"`
	// 不可调度
	Unschedulable *bool `json:"Unschedulable"`
	// 节点已使用CPU数量
	UsedCPU *float64 `json:"UsedCPU"`
	// 节点已使用内存容量
	UsedMemory *float64 `json:"UsedMemory"`
	// 节点已使用pod数量
	UsedPods *float64 `json:"UsedPods"`
	// VpcID
	VpcID *string `json:"VpcID"`
	// VpcName
	VpcName *string `json:"VpcName"`
	// yaml数据
	YamlData *string `json:"YamlData"`
}
