// Code generated by sdk-generator. DO NOT EDIT.

package models


// TaskTypeInfo 
type TaskTypeInfo struct {
	// 支持的资源类型列表，任务可作用的资源类型
	ResourceTypes []string `json:"ResourceTypes"`
	// 任务名称，编排任务名称
	TaskName *string `json:"TaskName"`
	// 任务类型，编排任务类型标识
	TaskType *string `json:"TaskType"`
}
