// Code generated by sdk-generator. DO NOT EDIT.

package models


// TenantTenantInfoRes 
type TenantTenantInfoRes struct {
	// 租户余额，计费账户可用资金额度，用于余额展示与审核
	Amount *float64 `json:"Amount"`
	// 信用额度，授予的欠费限制额度，用于信用额度展示
	AmountCredit *float64 `json:"AmountCredit"`
	// 免费额度，系统发放的免额余额，用于抵扣展示
	AmountFree *float64 `json:"AmountFree"`
	// 审批开关，标识资源申请是否需审批；1表示开启审批，0表示关闭
	Audit *int `json:"Audit"`
	// 自动审批开关，标识资源申请是否自动通过；1表示开启自动审批，0表示关闭
	AutoAudit *int `json:"AutoAudit"`
	// 租户ID，查询结果返回的租户唯一标识，用于资源归属与权限隔离
	CompanyID *int `json:"CompanyID"`
	// 创建时间，租户创建的Unix时间戳，用于时间排序与审计展示
	CreateTime *int `json:"CreateTime"`
	// 租户邮箱，查询结果返回的主账号邮箱，用于登录与通知展示
	Email *string `json:"Email"`
	// 管理员邮箱，后台管理联系邮箱字段，当前与Email一致
	ManagerEmail *string `json:"ManagerEmail"`
	// 成员ID，查询结果返回的租户主账号成员ID，用于账号级权限与状态展示
	MemberID *int `json:"MemberID"`
	// 成员状态，主账号生命周期状态；AVAILABLE可用、FREEZE冻结、LOCKED锁定
	MemberStatus *string `json:"MemberStatus"`
	// 租户名称，组织显示名称，用于租户识别与展示
	Name *string `json:"Name"`
	// 手机号，查询结果返回的主账号安全手机号，用于短信验证码及敏感操作二次验证展示
	Phone *string `json:"Phone"`
	// API私钥，API调用请求签名RSA私钥，用于请求签名
	PrivateKey *string `json:"PrivateKey"`
	// API公钥，API调用身份验证RSA公钥，用于签名验证
	PublicKey *string `json:"PublicKey"`
	// 备注，说明或备注信息
	Remark *string `json:"Remark"`
	// 租户状态，租户生命周期状态；AVAILABLE可用、FREEZE冻结
	Status *string `json:"Status"`
	// 更新时间，租户信息最近变更的Unix时间戳，用于展示最近变更时间
	UpdateTime *int `json:"UpdateTime"`
	// 用户ID，查询结果返回的租户主账号ID；当前与CompanyID一致
	UserID *int `json:"UserID"`
}
