// Code generated by sdk-generator. DO NOT EDIT.

package models


// TestBMCTypeResult 
type TestBMCTypeResult struct {
	// JNLP文件内容
	JNLPContent *string `json:"JNLPContent"`
	// 消息
	Message *string `json:"Message"`
	// 步骤结果列表
	StepResults []BMCTypeTestStepResult `json:"StepResults"`
	// 测试是否成功
	Success *bool `json:"Success"`
	// 总步骤数
	TotalSteps *int `json:"TotalSteps"`
}
