// Code generated by sdk-generator. DO NOT EDIT.

package models


// TopMap 
type TopMap struct {
	// 名称，资源或进程的名称
	Name *string `json:"Name"`
	// 进程ID，进程标识符
	Pid *string `json:"Pid"`
	// 大小，资源大小或内存占用
	Size *string `json:"Size"`
	// 状态，资源或进程的当前状态
	Status *string `json:"Status"`
	// 使用量，资源使用量或占用率
	Use *string `json:"Use"`
}
