// Code generated by sdk-generator. DO NOT EDIT.

package models


// TrafficMirrorSourceInfo 
type TrafficMirrorSourceInfo struct {
	// 关联的资源ID，虚拟机的唯一标识符
	AssociatedResourceID *string `json:"AssociatedResourceID"`
	// 关联的资源名称，虚拟机的显示名称
	AssociatedResourceName *string `json:"AssociatedResourceName"`
	// 源设备信息列表，将该虚拟机下所有非Psbr网卡拆分为入/出两个方向返回，配合Available字段判断该方向是否已被其他流量镜像占用
	Sources []TrafficMirrorSimpleSource `json:"Sources"`
}
