// Code generated by sdk-generator. DO NOT EDIT.

package models


// UserAccessInfo 
type UserAccessInfo struct {
	// 总余额，账户可支配资金总额，单位为元
	Amount *float64 `json:"Amount"`
	// 外部余额，通过充值获得的余额，单位为元
	AmountCredit *float64 `json:"AmountCredit"`
	// 内部余额，系统发放的免额额度，单位为元
	AmountFree *float64 `json:"AmountFree"`
	// 审批开关，标识租户资源变更是否需人工审批
	Audit *int `json:"Audit"`
	// 租户ID，账号所属租户标识
	CompanyID *int `json:"CompanyID"`
	// 租户状态，标识账号所属租户当前是否可用
	CompanyStatus *string `json:"CompanyStatus"`
	// 创建时间，账号首次建立的Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// 账号邮箱，登录与通知邮箱
	Email *string `json:"Email"`
	// 授权等级列表，标识账号可管理的层级范围
	GrantLevels []string `json:"GrantLevels"`
	// 成员ID，当前账号唯一标识
	MemberID *int `json:"MemberID"`
	// 成员名称，账号展示名称用于管理界面显示
	MemberName *string `json:"MemberName"`
	// OAuth2唯一标识ID，用于绑定外部SSO系统的用户身份
	OAuth2UniqueID *string `json:"OAuth2UniqueID"`
	// 手机号，用于安全通知或验证码接收
	Phone *string `json:"Phone"`
	// API私钥，用于请求签名，需妥善保管
	PrivateKey *string `json:"PrivateKey"`
	// 权限级别，标识账号在租户内的管理范围
	Privileges *string `json:"Privileges"`
	// API公钥，用于请求签名校验与鉴权
	PublicKey *string `json:"PublicKey"`
	// 账号状态，标识账号当前可用性
	Status *string `json:"Status"`
	// 更新时间，账号信息最后一次修改的Unix时间戳
	UpdateTime *int `json:"UpdateTime"`
	// 用户邮箱，用于关联用户主体邮箱
	UserEmail *string `json:"UserEmail"`
	// 用户名称，兼容字段用于展示
	UserName *string `json:"UserName"`
}
