// Code generated by sdk-generator. DO NOT EDIT.

package models


// ValidatePartitionConfigResult 
type ValidatePartitionConfigResult struct {
	// 错误列表
	Errors []string `json:"Errors"`
	// 消息
	Message *string `json:"Message"`
	// 是否有效
	Valid *bool `json:"Valid"`
	// 警告列表
	Warnings []string `json:"Warnings"`
}
