// Code generated by sdk-generator. DO NOT EDIT.

package models


// ValidateKickstartTemplateResult 
type ValidateKickstartTemplateResult struct {
	// 错误列表
	Errors []string `json:"Errors"`
	// 从模板中提取的变量列表
	ExtractedVars []string `json:"ExtractedVars"`
	// 父模板名称（如果使用继承）
	ParentTemplate *string `json:"ParentTemplate"`
	// 模板名称
	TemplateName *string `json:"TemplateName"`
	// 是否使用模板继承
	UsesInheritance *bool `json:"UsesInheritance"`
	// 是否有效
	Valid *bool `json:"Valid"`
	// 警告列表
	Warnings []string `json:"Warnings"`
}
