// Code generated by sdk-generator. DO NOT EDIT.

package models


// VCPUUsageInfo 
type VCPUUsageInfo struct {
	// CPU可分配，集群中剩余可分配的CPU核数
	CPUAllocable *int `json:"CPUAllocable"`
	// CPU总量，集群中所有宿主机的逻辑CPU核数总和
	CPUCount *int `json:"CPUCount"`
	// 物理CPU总量，集群中所有宿主机的物理CPU核数总和
	CPUPhysicCount *int `json:"CPUPhysicCount"`
	// CPU使用率，已使用CPU占总量的百分比
	CPUUsageRate *float64 `json:"CPUUsageRate"`
	// CPU已使用，集群中已分配给虚拟机的CPU核数
	CPUUsed *int `json:"CPUUsed"`
	// 地域ID
	Region *string `json:"Region"`
	// 地域别名，地域的显示名称
	RegionAlias *string `json:"RegionAlias"`
	// 集群ID，计算集群的唯一标识符
	SetID *string `json:"SetID"`
}
