// Code generated by sdk-generator. DO NOT EDIT.

package models


// VMMigrationReport 
type VMMigrationReport struct {
	// CPU利用率，来源于资源标签CPUUtilization
	CPUUtilization *float64 `json:"CPUUtilization"`
	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// 任务完成时间，秒级Unix时间戳
	CompletionTime *int `json:"CompletionTime"`
	// 任务创建时间，秒级Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// 租户邮箱
	Email *string `json:"Email"`
	// DRS任务ID
	JobID *string `json:"JobID"`
	// 内存使用率，来源于资源标签MemUsage
	MemUsage *float64 `json:"MemUsage"`
	// 迁移详情
	MigrationInfo *VMMigrationInfo `json:"MigrationInfo"`
	// 虚拟机名称
	Name *string `json:"Name"`
	// 虚拟机备注
	Remark *string `json:"Remark"`
	// 虚拟机用途
	Usage *string `json:"Usage"`
	// 虚拟机ID
	VMID *string `json:"VMID"`
}
