// Code generated by sdk-generator. DO NOT EDIT.

package models


// VMNumaInfo 
type VMNumaInfo struct {
	// GPU列表，绑定到该NUMA节点的GPU设备
	GPUInfos []NumaGPUInfo `json:"GPUInfos"`
	// 物理NUMAID，宿主机的NUMA节点索引
	HostNumaID *int `json:"HostNumaID"`
	// 内存容量，分配给该NUMA节点的内存大小，单位：KiB
	Memory *int `json:"Memory"`
	// 虚拟NUMAID，虚拟机内部的NUMA节点索引
	NumaID *int `json:"NumaID"`
	// vCPU集合，绑定到该NUMA节点的vCPU列表
	VCPUSet *string `json:"VCPUSet"`
}
