// Code generated by sdk-generator. DO NOT EDIT.

package models


// VPCDetailInfo 
type VPCDetailInfo struct {
	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// 租户名称，资源所属租户名称
	CompanyName *string `json:"CompanyName"`
	// 创建时间，秒级Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// 租户邮箱，资源所属租户的联系邮箱
	Email *string `json:"Email"`
	// VPC名称
	Name *string `json:"Name"`
	// 网段，VPC主网段的CIDR地址范围
	Network *string `json:"Network"`
	// 对等连接详情列表，包含与该VPC建立的所有对等连接及其状态
	PeeringInfos []PeeringInfo `json:"PeeringInfos"`
	// 项目ID，资源所属项目分组标识
	ProjectID *string `json:"ProjectID"`
	// 项目名称，资源所属项目名称
	ProjectName *string `json:"ProjectName"`
	// 创建失败原因
	Reason *string `json:"Reason"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region"`
	// 地域别名，地域的人性化显示名称
	RegionAlias *string `json:"RegionAlias"`
	// 备注，用于补充说明
	Remark *string `json:"Remark"`
	// VPC状态，资源生命周期状态，当资源状态非Available时返回资源状态
	State *string `json:"State"`
	// 子网数量，展示该VPC下已划分的子网总数
	SubnetCount *int `json:"SubnetCount"`
	// 子网详情列表，包含该VPC下所有子网的配置及状态信息
	SubnetInfos []SubnetInfo `json:"SubnetInfos"`
	// 资源标签列表，用于资源分类和检索
	Tags []UnifiedTag `json:"Tags"`
	// 更新时间，秒级Unix时间戳
	UpdateTime *int `json:"UpdateTime"`
	// VPCID，虚拟私有网络的唯一标识符
	VPCID *string `json:"VPCID"`
}
