// Code generated by sdk-generator. DO NOT EDIT.

package models


// VPNTunnelInfo 
type VPNTunnelInfo struct {
	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 连接状态，IPSec隧道连接状态，创建/更新/删除中为空
	ConnectState *string `json:"ConnectState"`
	// 创建时间，秒级Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// 删除时间，秒级Unix时间戳
	DeleteTime *int `json:"DeleteTime"`
	// 租户邮箱，资源所属租户的联系邮箱
	Email *string `json:"Email"`
	// IKE认证算法，IKE阶段使用的认证算法，取值：md5、sha1、sha256
	IKEAuthenticationAlgorithm *string `json:"IKEAuthenticationAlgorithm"`
	// IKE DH组，IKE阶段使用的Diffie-Hellman密钥交换组，取值范围：0、1、2、5、14、24（0为历史兼容值）
	IKEDhGroup *int `json:"IKEDhGroup"`
	// IKE加密算法，IKE阶段使用的加密算法，取值：3des、aes128、aes192、aes256
	IKEEncryptionAlgorithm *string `json:"IKEEncryptionAlgorithm"`
	// IKE交换模式，仅当IKEVersion为v1时有效，IKEVersion为v2时为空
	IKEExchangeMode *string `json:"IKEExchangeMode"`
	// IKE本端标识，IKE协商时本端身份标识，空值表示使用IP地址作为标识
	IKELocalLabel *string `json:"IKELocalLabel"`
	// IKE对端标识，IKE协商时对端身份标识，空值表示使用IP地址作为标识
	IKERemoteLabel *string `json:"IKERemoteLabel"`
	// IKE SA生存时间，IKE安全关联的生存时间（秒）
	IKESALifetime *int `json:"IKESALifetime"`
	// IKE协议版本，Internet Key Exchange协议版本，取值：v1、v2
	IKEVersion *string `json:"IKEVersion"`
	// IPSec认证算法，IPSec阶段使用的认证算法，取值：md5、sha1、sha256
	IPSecAuthenticationAlgorithm *string `json:"IPSecAuthenticationAlgorithm"`
	// IPSec加密算法，IPSec阶段使用的加密算法，仅当IPSecProtocol为ESP时有效，IPSecProtocol为AH时为空，取值：3des、aes128、aes192、aes256
	IPSecEncryptionAlgorithm *string `json:"IPSecEncryptionAlgorithm"`
	// IPSec PFS DH组，Perfect Forward Secrecy使用的Diffie-Hellman组，取值范围：0、1、2、5、14、24（0表示不启用PFS）
	IPSecPFSDhGroup *int `json:"IPSecPFSDhGroup"`
	// IPSec安全协议，IPSec使用的安全传输协议，取值：AH、ESP
	IPSecProtocol *string `json:"IPSecProtocol"`
	// IPSec SA生存时间，IPSec安全关联的生存时间（秒）
	IPSecSALifetime *int `json:"IPSecSALifetime"`
	// 本端子网ID列表，通过隧道互通的本端子网ID列表
	LocalSubnetIDs []string `json:"LocalSubnetIDs"`
	// VPN隧道名称，用于展示资源名称
	Name *string `json:"Name"`
	// 预共享密钥，IPSec隧道协商使用的预共享密钥
	PreSharedKey *string `json:"PreSharedKey"`
	// 项目ID，资源所属项目分组
	ProjectID *string `json:"ProjectID"`
	// 项目名称，资源所属项目名称
	ProjectName *string `json:"ProjectName"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region"`
	// 备注，VPN隧道的描述信息
	Remark *string `json:"Remark"`
	// 对端子网CIDR列表，通过隧道互通的对端网段列表
	RemoteSubnets []string `json:"RemoteSubnets"`
	// 对端网关ID，对端VPN网关唯一标识
	RemoteVPNGWID *string `json:"RemoteVPNGWID"`
	// 对端网关IP，用于详情和列表展示
	RemoteVPNGWIP *string `json:"RemoteVPNGWIP"`
	// 对端网关名称，用于详情和列表展示
	RemoteVPNGWName *string `json:"RemoteVPNGWName"`
	// 隧道状态，来自资源状态与底层隧道状态，创建/更新/删除中可能覆盖为资源状态
	State *string `json:"State"`
	// 本端子网CIDR列表，用于详情和列表展示
	Subnets []string `json:"Subnets"`
	// 标签列表，用于资源标记和分类管理
	Tags []UnifiedTag `json:"Tags"`
	// 更新时间，秒级Unix时间戳
	UpdateTime *int `json:"UpdateTime"`
	// VPCID，VPN网关所属VPC
	VPCID *string `json:"VPCID"`
	// VPN网关ID，本地VPN网关唯一标识
	VPNGWID *string `json:"VPNGWID"`
	// 本地VPN网关外网IP，用于详情和列表展示
	VPNGWIP *string `json:"VPNGWIP"`
	// 本地VPN网关名称，用于详情和列表展示
	VPNGWName *string `json:"VPNGWName"`
	// VPN隧道ID，VPN隧道唯一标识
	VPNTunnelID *string `json:"VPNTunnelID"`
}
