// Code generated by sdk-generator. DO NOT EDIT.

package models


// WorkflowApplicationNode 
type WorkflowApplicationNode struct {
	// 审批资源对应的API名称，标识审批通过后将执行的API操作，例如创建磁盘操作对应CreateDisk
	APIName *string `json:"APIName"`
	// 申请人账号邮箱，提交审批的用户邮箱地址
	ApplicationEmail *string `json:"ApplicationEmail"`
	// 审批工单ID，该节点所属的审批工单标识
	ApplicationID *string `json:"ApplicationID"`
	// 申请人账号ID，标识提交审批的用户，通常为子账号ID
	ApplicationMemberID *int `json:"ApplicationMemberID"`
	// 审批工单名称，该节点所属审批工单的名称
	ApplicationName *string `json:"ApplicationName"`
	// 节点是否自动审批，true表示该节点自动通过无需人工审批，false表示需要人工审批
	AutoAudit *bool `json:"AutoAudit"`
	// 创建时间，Unix时间戳（秒），标识该节点的创建时刻
	CreateTime *int `json:"CreateTime"`
	// 审批节点ID，在审批流程中唯一标识该节点的顺序编号
	NodeID *string `json:"NodeID"`
	// 审批节点名称，该节点的显示名称，用于标识审批环节
	NodeName *string `json:"NodeName"`
	// 节点审批人邮箱，负责该节点审批的用户邮箱地址
	NodeOperator *string `json:"NodeOperator"`
	// 节点审批人租户ID，审批人所属的租户组织标识
	NodeOperatorCompanyID *int `json:"NodeOperatorCompanyID"`
	// 节点审批人账号ID，负责该节点审批的用户账号标识
	NodeOperatorID *int `json:"NodeOperatorID"`
	// 节点观察人信息列表，可以查看该节点审批进度但不参与审批决策的用户列表
	ObserverInfos []ObserverInfo `json:"ObserverInfos"`
	// 审批节点备注，审批人在审批时填写的备注信息，用于说明审批意见或理由
	Remark *string `json:"Remark"`
	// 审批资源类型，标识审批涉及的资源类型，可以通过ListProductResources获取支持的类型
	ResourceType *string `json:"ResourceType"`
	// 审批节点状态，标识该节点的处理状态，Undo：未处理，Committed：已提交，Rejected：已拒绝，Aborted：已终止，Approved：已批准，Handling：处理中，Succeed：成功，Failed：失败
	State *string `json:"State"`
	// 更新时间，Unix时间戳（秒），标识该节点的最后修改时刻
	UpdateTime *int `json:"UpdateTime"`
}
