// Code generated by sdk-generator. DO NOT EDIT.

package models


// AlertTemplateTargetInfo 
type AlertTemplateTargetInfo struct {
	// 绑定的目标资源ID，目标资源ID
	TargetID *string `json:"TargetID"`
	// 绑定的目标资源名称，目标资源名称
	TargetName *string `json:"TargetName"`
	// 告警模板ID，告警模板ID
	TemplateID *string `json:"TemplateID"`
	// 告警模板名称，告警模板名称
	TemplateName *string `json:"TemplateName"`
}
