// Code generated by sdk-generator. DO NOT EDIT.

package models


// AlertTemplateRuleInfo 
type AlertTemplateRuleInfo struct {
	// 条件类型，取值：GE/LE/ET/NE/LT/GT
	ConditionType *string `json:"ConditionType"`
	// 创建时间，告警规则创建时间戳
	CreateTime *int `json:"CreateTime"`
	// 持续时间，告警持续时间（秒）
	ForSeconds *int `json:"ForSeconds"`
	// 监控指标名称，Prometheus指标名称
	Metric *string `json:"Metric"`
	// 关联通知组ID，通知组ID
	NotifyGroupID *string `json:"NotifyGroupID"`
	// 关联通知组名称，通知组名称
	NotifyGroupName *string `json:"NotifyGroupName"`
	// PromQL查询表达式，告警表达式
	Query *string `json:"Query"`
	// 告警规则ID，告警规则唯一标识
	RuleID *string `json:"RuleID"`
	// 告警级别，取值：warning/critical/error
	Severity *string `json:"Severity"`
	// 告警摘要描述，告警触发条件描述
	Summary *string `json:"Summary"`
	// 所属告警模板ID，告警模板ID
	TemplateID *string `json:"TemplateID"`
	// 告警阈值，触发告警的指标值
	Thresholds *float64 `json:"Thresholds"`
	// 更新时间，告警规则更新时间戳
	UpdateTime *int `json:"UpdateTime"`
}
