// Code generated by sdk-generator. DO NOT EDIT.

package models


// AlertNotifyWebhookInfo 
type AlertNotifyWebhookInfo struct {
	// 创建时间，Webhook创建时间戳
	CreateTime *int `json:"CreateTime"`
	// HTTP请求的方法，取值：Post/Get
	Method *string `json:"Method"`
	// Webhook名称，Webhook名称
	Name *string `json:"Name"`
	// 通知组ID，Webhook所属通知组ID
	NotifyGroupID *string `json:"NotifyGroupID"`
	// 通知组WebhookID，Webhook ID
	NotifyWebhookID *string `json:"NotifyWebhookID"`
	// 更新时间，Webhook更新时间戳
	UpdateTime *int `json:"UpdateTime"`
	// Webhook URL地址，Webhook目标URL
	Url *string `json:"Url"`
}
