// Code generated by sdk-generator. DO NOT EDIT.

package models


// AssociatedResources 
type AssociatedResources struct {
	// 资源ID，关联虚拟机或弹性网卡的唯一标识符
	ResourceID *string `json:"ResourceID"`
	// 资源名称，关联虚拟机或弹性网卡的名称
	ResourceName *string `json:"ResourceName"`
}
