// Code generated by sdk-generator. DO NOT EDIT.

package models


// BMCStep 
type BMCStep struct {
	// 请求体模板
	BodyTpl *string `json:"BodyTpl"`
	// 数据提取规则
	DataExtractionRules []KeyValuePair `json:"DataExtractionRules"`
	// 动态请求头
	DynamicHeaders []KeyValuePair `json:"DynamicHeaders"`
	// 静态请求头
	Headers []KeyValuePair `json:"Headers"`
	// 是否为最终JNLP步骤
	IsFinalJNLPStep *bool `json:"IsFinalJNLPStep"`
	// 是否为JNLP URL步骤
	IsJNLPUrlStep *bool `json:"IsJNLPUrlStep"`
	// JNLP URL JSON字段
	JNLPUrlJsonField *string `json:"JNLPUrlJsonField"`
	// HTTP方法
	Method *string `json:"Method"`
	// 步骤名称
	Name *string `json:"Name"`
	// 传递Cookie的步骤
	PassCookiesFromStep *string `json:"PassCookiesFromStep"`
	// 数据后处理规则
	PostProcessRules []KeyValuePair `json:"PostProcessRules"`
	// 请求URL
	URL *string `json:"URL"`
}
