// Code generated by sdk-generator. DO NOT EDIT.

package models


// BucketLifecycleRule 
type BucketLifecycleRule struct {
	// 过期天数，对象过期天数
	ExpirationDays *int `json:"ExpirationDays"`
	// 过期类型，生命周期规则适用对象，取值范围：CurrentVersion（当前版本）、NonCurrentVersion（非当前版本）、Multipart（碎片）
	ExpirationType *string `json:"ExpirationType"`
	// 生命周期ID，生命周期规则标识
	LifeCycleID *string `json:"LifeCycleID"`
	// 对象名前缀，用于匹配生命周期规则
	ObjectKeyPrefix *string `json:"ObjectKeyPrefix"`
	// 归档存储类，生命周期转储的存储类型
	TransitionStorageClass *string `json:"TransitionStorageClass"`
}
