// Code generated by sdk-generator. DO NOT EDIT.

package models


// ChartItem 
type ChartItem struct {
	// 显示值，数据项经过单位换算后的显示数值
	DisplayValue *float64 `json:"DisplayValue"`
	// 项目ID，数据项的唯一标识
	ItemID *string `json:"ItemID"`
	// 图表项名称，数据项的显示名称
	Name *string `json:"Name"`
	// 子图表元素列表，包含该数据项的细分数据
	SubItems []ChartSubItem `json:"SubItems"`
	// 单位，数据项的计量单位
	Unit *string `json:"Unit"`
	// 图表值，数据项的原始数值
	Value *float64 `json:"Value"`
}
