// Code generated by sdk-generator. DO NOT EDIT.

package models


// CIInfo 
type CIInfo struct {
	// 绑定资源ID，虚拟机关联资源标识
	BindResourceID *string `json:"BindResourceID"`
	// 绑定资源名称，虚拟机关联资源名称
	BindResourceName *string `json:"BindResourceName"`
	// 绑定资源类型，虚拟机关联的资源类型
	BindResourceType *string `json:"BindResourceType"`
	// CPU核数，虚拟机分配的vCPU数量
	CPU *int `json:"CPU"`
	// 是否可取消迁移，当前迁移是否允许取消
	CanMigrateAbort *bool `json:"CanMigrateAbort"`
	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// 创建时间，秒级Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// 所属租户邮箱，资源归属租户的联系邮箱
	Email *string `json:"Email"`
	// GPU数量，虚拟机分配的GPU数量
	GPU *int `json:"GPU"`
	// GPU规格，物理GPU规格名称
	GPUMdevName *string `json:"GPUMdevName"`
	// 物理机ID，虚拟机所在宿主机标识
	HostID *string `json:"HostID"`
	// 物理机IP地址，宿主机管理IP地址
	HostIP *string `json:"HostIP"`
	// 物理机IPv6地址，宿主机管理IPv6地址
	HostIPv6 *string `json:"HostIPv6"`
	// 镜像ID，虚拟机启动镜像标识
	ImageID *string `json:"ImageID"`
	// 镜像名称，虚拟机启动镜像名称
	ImageName *string `json:"ImageName"`
	// 内网IP地址，虚拟机内网地址，优先返回IPv4地址
	InternalIP *string `json:"InternalIP"`
	// vGPU规格，虚拟GPU配置规格名称
	MdevName *string `json:"MdevName"`
	// 内存大小，虚拟机分配内存容量，单位MiB
	Memory *int `json:"Memory"`
	// 虚拟机名称，宿主机上运行的虚拟机名称
	Name *string `json:"Name"`
	// 地域ID，虚拟机所属地域
	Region *string `json:"Region"`
	// 地域别名，地域的人性化显示名称
	RegionAlias *string `json:"RegionAlias"`
	// 虚拟机描述，资源用途说明
	Remark *string `json:"Remark"`
	// 集群别名，虚拟机所在计算集群的自定义名称
	SetAlias *string `json:"SetAlias"`
	// 计算集群架构，虚拟机所在集群CPU架构
	SetArch *string `json:"SetArch"`
	// 计算集群ID，虚拟机所在计算集群标识
	SetID *string `json:"SetID"`
	// 集群类型，虚拟机所在计算集群的类型标识
	SetType *string `json:"SetType"`
	// 运行状态，虚拟机当前状态
	Status *string `json:"Status"`
	// 虚拟机用途，业务用途说明
	Usage *string `json:"Usage"`
	// vCPU绑定节点，虚拟机绑定的物理节点
	VCPUBindingNode *string `json:"VCPUBindingNode"`
	// vGPUID，虚拟GPU实例标识
	VGPUID *string `json:"VGPUID"`
	// 虚拟机ID，虚拟机唯一标识
	VMID *string `json:"VMID"`
}
