// Code generated by sdk-generator. DO NOT EDIT.

package models


// ClusterSubnetInfo 
type ClusterSubnetInfo struct {
	// 子网Id
	SubnetID *string `json:"SubnetID"`
	// 子网名称
	SubnetName *string `json:"SubnetName"`
}
