// Code generated by sdk-generator. DO NOT EDIT.

package models


// ConfigInfo 
type ConfigInfo struct {
	// 所属类别标识
	Category *string `json:"Category"`
	// 所属类别名称，支持国际化
	CategoryName *string `json:"CategoryName"`
	// 配置键，配置项的唯一标识符
	ConfigKey *string `json:"ConfigKey"`
	// 配置排序位置，用于前端展示排序
	ConfigPosition *int `json:"ConfigPosition"`
	// 配置类型，用于分类过滤
	ConfigType *string `json:"ConfigType"`
	// 配置值，当前配置项的取值
	ConfigValue *string `json:"ConfigValue"`
	// 配置描述，说明配置项的用途和含义，支持国际化
	Description *string `json:"Description"`
	// 是否可编辑，true表示可编辑，false表示只读
	Editable *string `json:"Editable"`
	// 配置提示信息，帮助用户理解如何使用该配置，支持国际化
	Hint *string `json:"Hint"`
	// 配置值单位，如秒、MB等，支持国际化
	Unit *string `json:"Unit"`
	// 配置值范围，可选值或取值范围说明，支持国际化
	ValueRange *string `json:"ValueRange"`
	// 配置值类型，如string、int、bool等
	ValueType *string `json:"ValueType"`
}
