// Code generated by sdk-generator. DO NOT EDIT.

package models


// ContainerImageInfo 
type ContainerImageInfo struct {
	// 租户ID，镜像所属租户
	CompanyID *int `json:"CompanyID"`
	// 镜像拉取次数，镜像被拉取的次数
	ContainerImagePullNumbers *int `json:"ContainerImagePullNumbers"`
	// 镜像仓库ID，镜像所属仓库ID
	ContainerImageRepositoryID *string `json:"ContainerImageRepositoryID"`
	// 创建时间，镜像创建时间戳
	CreateTime *int `json:"CreateTime"`
	// 镜像完整名字，镜像外网完整地址
	FullName *string `json:"FullName"`
	// 镜像完整名字，镜像内网完整地址
	InternalFullName *string `json:"InternalFullName"`
	// 最新tag名称，镜像最新标签
	LatestTag *string `json:"LatestTag"`
	// 名称，镜像名称
	Name *string `json:"Name"`
}
