// Code generated by sdk-generator. DO NOT EDIT.

package models


// ControllerPlaneStatus 
type ControllerPlaneStatus struct {
	// 集群svc插件状态
	CCM *ComponentStatus `json:"CCM"`
	// 集群存储插件状态
	CSI *ComponentStatus `json:"CSI"`
	// 集群ETCD状态
	ETCD *ComponentStatus `json:"ETCD"`
	// 集群KubeApiserver状态
	KubeApiserver *ComponentStatus `json:"KubeApiserver"`
	// 集群KubeControllerManager状态
	KubeControllerManager *ComponentStatus `json:"KubeControllerManager"`
	// 集群KubeScheduler状态
	KubeScheduler *ComponentStatus `json:"KubeScheduler"`
	// 集群Kubeutil状态
	KubeTerminal *ComponentStatus `json:"KubeTerminal"`
	// 集群默认超级节点状态
	VK *ComponentStatus `json:"VK"`
}
