// Code generated by sdk-generator. DO NOT EDIT.

package models


// DHCPPoolCreate 
type DHCPPoolCreate struct {
	// 是否启用
	Enabled *bool `json:"Enabled"`
	// 结束 IP
	EndIP *string `json:"EndIP" required:"true"`
	// 机房名称
	Name *string `json:"Name" required:"true"`
	// PXE 地址池网段 CIDR
	Network *string `json:"Network" required:"true"`
	// 跨网段路由网关
	RouteGateway *string `json:"RouteGateway"`
	// 起始 IP
	StartIP *string `json:"StartIP" required:"true"`
}
