// Code generated by sdk-generator. DO NOT EDIT.

package models


// DirectConnectDetailInfo 
type DirectConnectDetailInfo struct {
	// 带宽限制，单位为Mbps
	Bandwidth *int `json:"Bandwidth"`
	// 创建时间，Unix时间戳（秒级）
	CreateTime *int `json:"CreateTime"`
	// 网卡名称，专线接入绑定的物理网卡标识
	Device *string `json:"Device"`
	// 专线接入ID，资源的唯一标识，系统自动生成的14位随机字符串
	DirectConnectID *string `json:"DirectConnectID"`
	// 本端网关IP，UCloudStack侧网络接口互联的带掩码IP地址
	LocalGatewayIP *string `json:"LocalGatewayIP"`
	// 专线接入名称
	Name *string `json:"Name"`
	// 访问权限，该专线接入可以被哪些租户访问，值为all表示所有租户可用，否则为租户ID列表（逗号分隔）
	Permission *string `json:"Permission"`
	// 权限模式，控制租户访问权限的模式，可选值：all（所有租户可用）、whitelist（白名单，仅指定租户可用）、blacklist（黑名单，仅指定租户不可用）
	PermissionMode *string `json:"PermissionMode"`
	// 地域ID，专线接入所属的物理区域标识
	Region *string `json:"Region"`
	// 备注，用于进行说明和注释，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符
	Remark *string `json:"Remark"`
	// 远端网关IP，用户本地数据中心侧网络的互联的带掩码IP地址
	RemoteGatewayIP *string `json:"RemoteGatewayIP"`
	// 远端子网网段列表，用户数据中心通过专线互连的网段列表
	RemoteSubnetCIDRs []string `json:"RemoteSubnetCIDRs"`
	// 当前专线接入状态，如Available（可用）、Deleting（删除中）等
	Status *string `json:"Status"`
	// 标签列表，用于资源标记和分类管理
	Tags []UnifiedTag `json:"Tags"`
	// 更新时间，Unix时间戳（秒级）
	UpdateTime *int `json:"UpdateTime"`
	// VLAN ID，虚拟局域网标识，可选，取值范围1-4094，不传或传0表示不设置VLAN
	VLAN *string `json:"VLAN"`
	// 关联的VPC信息列表，与该专线接入建立对等连接的VPC资源信息
	VPCInfos []VPCInfo `json:"VPCInfos"`
}
