// Code generated by sdk-generator. DO NOT EDIT.

package models


// EIPInfo 
type EIPInfo struct {
	// EIP带宽，单位为Mbps
	Bandwidth *int `json:"Bandwidth"`
	// 绑定的资源ID，EIP绑定的资源唯一标识符
	BindResourceID *string `json:"BindResourceID"`
	// 绑定的资源名称，EIP绑定资源的名称
	BindResourceName *string `json:"BindResourceName"`
	// 绑定资源所属的项目ID
	BindResourceProjectID *string `json:"BindResourceProjectID"`
	// 绑定的资源类型，取值VM/NATGW/VPNGW/LB/K8S/DTS/OSS/FS/MYSQL/REDIS
	BindResourceType *string `json:"BindResourceType"`
	// 绑定时间，秒级Unix时间戳
	BindTime *int `json:"BindTime"`
	// 是否可以作为默认网关，0表示否，1表示是
	CanDefaultGW *int `json:"CanDefaultGW"`
	// 计费类型，EIP的计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费），兼容hour/month/year，计费类型别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR，hour->HOUR、month->MONTH、year->YEAR
	ChargeType *string `json:"ChargeType"`
	// 租户唯一标识ID，资源所属租户标识
	CompanyID *int `json:"CompanyID"`
	// 租户名称，资源所属租户名称
	CompanyName *string `json:"CompanyName"`
	// 创建时间，秒级Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// EIP资源ID，弹性IP的唯一标识符
	EIPID *string `json:"EIPID"`
	// 租户邮箱，资源所属租户联系邮箱
	Email *string `json:"Email"`
	// 过期时间，秒级Unix时间戳
	ExpireTime *int `json:"ExpireTime"`
	// IP地址，弹性IP对应的公网地址
	IP *string `json:"IP"`
	// IP版本，取值IPv4/IPv6
	IPVersion *string `json:"IPVersion"`
	// 是否是默认网关，0表示否，1表示是
	ISDefaultGW *int `json:"ISDefaultGW"`
	// 是否为VIP，0表示否，1表示是，用于标识该IP是否为虚拟IP
	ISVIP *int `json:"ISVIP"`
	// 是否弹性，N表示普通EIP，Y表示弹性网卡EIP或VIP
	IsElastic *string `json:"IsElastic"`
	// EIP模式，取值NAT/Direct
	Mode *string `json:"Mode"`
	// 网卡ID，当IsElastic为Y时表示关联的弹性网卡ID或VIP所在网卡ID
	NICID *string `json:"NICID"`
	// EIP名称，用于标识弹性IP资源
	Name *string `json:"Name"`
	// 运营商网段别名
	OperatorAlias *string `json:"OperatorAlias"`
	// 运营商网段名称
	OperatorName *string `json:"OperatorName"`
	// 项目ID，资源所属项目分组标识
	ProjectID *string `json:"ProjectID"`
	// 项目名称，资源所属项目名称
	ProjectName *string `json:"ProjectName"`
	// 失败原因，当EIP创建失败时记录具体错误信息
	Reason *string `json:"Reason"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region"`
	// 地域别名，地域的人性化显示名称
	RegionAlias *string `json:"RegionAlias"`
	// EIP备注，用于补充说明
	Remark *string `json:"Remark"`
	// EIP状态，取值范围：Bound（已绑定）、Bounding（绑定中）、Unbounding（解绑中）、Free（未绑定）、SCHEDULING（调度中）、AVAILABLE（可用）、FAILED（创建失败）、DELETING（删除中）等资源状态
	Status *string `json:"Status"`
	// 标签列表，资源关联的标签信息
	Tags []UnifiedTag `json:"Tags"`
	// 更新时间，秒级Unix时间戳
	UpdateTime *int `json:"UpdateTime"`
}
