// Code generated by sdk-generator. DO NOT EDIT.

package models


// ErrorLogInfo 
type ErrorLogInfo struct {
	// 记录时间，错误日志的记录时间戳
	CreateTime *int `json:"CreateTime"`
	// 日志内容，错误日志的内容
	LogContent *string `json:"LogContent"`
}
