// Code generated by sdk-generator. DO NOT EDIT.

package models


// FlatNetworkRoute 
type FlatNetworkRoute struct {
	// 目的地址CIDR，路由的目标网段
	Destination *string `json:"Destination"`
	// 扁平网络ID，路由所属的扁平网络唯一标识
	FlatNetworkID *string `json:"FlatNetworkID"`
	// 扁平网络名称，路由所属网络的名称
	FlatNetworkName *string `json:"FlatNetworkName"`
	// 下一跳地址，数据包转发的网关IP
	NextHop *string `json:"NextHop"`
	// 下一跳IP地址，下一跳的具体IP地址
	NextHopAddr *string `json:"NextHopAddr"`
	// 下一跳名称，下一跳网络或设备的名称
	NextHopName *string `json:"NextHopName"`
	// 下一跳类型，路由的下一跳类型，如local表示本地路由
	NextHopType *string `json:"NextHopType"`
	// 备注信息，路由的说明或用途描述
	Remark *string `json:"Remark"`
}
