// Code generated by sdk-generator. DO NOT EDIT.

package models


// HostDeviceInfo 
type HostDeviceInfo struct {
	// 绑定类型，设备与虚拟机的关联方式
	AttachedType *string `json:"AttachedType"`
	// 绑定虚拟机ID，当前挂载该设备的虚拟机标识
	AttachedVMID *string `json:"AttachedVMID"`
	// 总线编号，设备在节点上的总线编号
	Bus *int `json:"Bus"`
	// 租户唯一标识ID，资源归属租户，仅在设备已创建为资源时返回
	CompanyID *int `json:"CompanyID"`
	// 租户名称，资源归属租户名称，仅在设备已创建为资源时返回
	CompnayName *string `json:"CompnayName"`
	// 创建时间，资源创建时间的秒级Unix时间戳，仅在设备已创建为资源时返回
	CreateTime *int `json:"CreateTime"`
	// 设备编号，设备在节点上的设备编号
	Device *int `json:"Device"`
	// 租户邮箱，资源归属租户联系邮箱，仅在设备已创建为资源时返回
	Email *string `json:"Email"`
	// 外置设备ID，设备资源唯一标识，未创建为资源时可能为空
	HostDeviceID *string `json:"HostDeviceID"`
	// 外置设备名称，资源名称，仅在设备已创建为资源时返回
	HostDeviceName *string `json:"HostDeviceName"`
	// 设备类型，依据设备模板识别的类型，可能返回USB或GPU，未匹配模板时可能为空
	HostDeviceType *string `json:"HostDeviceType"`
	// 产品ID，物理设备的型号标识码
	ProductID *string `json:"ProductID"`
	// 产品名称，设备模板对应的产品名称，未匹配模板时可能为空
	ProductName *string `json:"ProductName"`
	// 项目ID，资源所属项目标识，仅在设备已创建为资源时返回
	ProjectID *string `json:"ProjectID"`
	// 项目名称，资源所属项目名称，仅在设备已创建为资源时返回
	ProjectName *string `json:"ProjectName"`
	// 失败原因，资源状态异常时的失败原因，仅在设备已创建为资源时返回
	Reason *string `json:"Reason"`
	// 备注信息，资源备注，仅在设备已创建为资源时返回
	Remark *string `json:"Remark"`
	// 序列号，物理设备的唯一序列号
	Serial *string `json:"Serial"`
	// 设备状态，节点扫描状态可能为Attached、Attaching、Detached、Detaching、UnKnown、Lost；当资源状态非Available时返回资源状态Initializing、Failed、Deleting、Terminating、Deleted、Terminated
	Status *string `json:"Status"`
	// 更新时间，资源更新时间的秒级Unix时间戳，仅在设备已创建为资源时返回
	UpdateTime *int `json:"UpdateTime"`
	// 厂商ID，物理设备的制造商标识码
	VendorID *string `json:"VendorID"`
	// 厂商名称，设备模板对应的厂商名称，未匹配模板时可能为空
	VendorName *string `json:"VendorName"`
}
