// Code generated by sdk-generator. DO NOT EDIT.

package models


// ImageOSInfo 
type ImageOSInfo struct {
	// 操作系统版本ID，标识特定操作系统枚举记录
	ImageOSID *string `json:"ImageOSID"`
	// 网络配置模式，取值NetworkScripts、Interfaces、Netplan、None
	NetworkMode *string `json:"NetworkMode"`
	// 发行版名称，操作系统的具体品牌或系列
	OSDistribution *string `json:"OSDistribution"`
	// 操作系统类型，如Linux、Windows
	OSType *string `json:"OSType"`
	// 具体版本号，标识发行版内部的具体版本信息
	OSVersion *string `json:"OSVersion"`
	// 备注信息，对该操作系统版本的补充说明
	Remark *string `json:"Remark"`
	// 架构类型，基于计算集群支持的指令集，如x86_64、aarch64
	SetArch *string `json:"SetArch"`
	// 就绪状态，标识该操作系统版本是否可用
	Status *string `json:"Status"`
}
