// Code generated by sdk-generator. DO NOT EDIT.

package models


// InspectionResourceUsageCompanyInfo 
type InspectionResourceUsageCompanyInfo struct {
	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// 邮箱，租户的邮箱地址
	Email *string `json:"Email"`
	// 租户名称，租户的显示名称
	Name *string `json:"Name"`
}
