// Code generated by sdk-generator. DO NOT EDIT.

package models


// InstallPhysicalConfig 
type InstallPhysicalConfig struct {
	// 是否使用 DHCP
	DHCP *bool `json:"DHCP"`
	// IP地址列表
	IPs []InstallIPConfig `json:"IPs"`
	// 物理网卡名称或 MAC 地址
	Interface *string `json:"Interface"`
	// 所属 Bond 名称
	Master *string `json:"Master"`
}
