// Code generated by sdk-generator. DO NOT EDIT.

package models


// InstallIPConfig 
type InstallIPConfig struct {
	// IP地址
	Address *string `json:"Address"`
	// DNS 服务器列表
	DNS []string `json:"DNS"`
	// EIP ID
	EIPID *string `json:"EIPID"`
	// 网关
	Gateway *string `json:"Gateway"`
	// IP版本
	IPVersion *string `json:"IPVersion"`
	// 子网掩码
	Netmask *string `json:"Netmask"`
	// 网络段ID
	SegmentID *string `json:"SegmentID"`
}
