// Code generated by sdk-generator. DO NOT EDIT.

package models


// InstallTaskInfoV2 
type InstallTaskInfoV2 struct {
	// 租户ID
	CompanyID *int `json:"CompanyID"`
	// 租户名称
	CompanyName *string `json:"CompanyName"`
	// 配置快照 (JSON)
	ConfigSnapshot *string `json:"ConfigSnapshot"`
	// 创建时间
	CreatedAt *int `json:"CreatedAt"`
	// 当前阶段
	CurrentStage *string `json:"CurrentStage"`
	// 租户邮箱
	Email *string `json:"Email"`
	// 结束时间
	EndTime *int `json:"EndTime"`
	// 错误信息
	ErrorMessage *string `json:"ErrorMessage"`
	// 预计完成时间
	EstimatedCompletionTime *int `json:"EstimatedCompletionTime"`
	// 主机名
	Hostname *string `json:"Hostname"`
	// 镜像ID（用于克隆模式）
	ImageID *string `json:"ImageID"`
	// 镜像URL（用于克隆模式）
	ImageURL *string `json:"ImageURL"`
	// 安装模式: clone, kickstart
	InstallMode *string `json:"InstallMode"`
	// 安装重试次数
	InstallRetries *int `json:"InstallRetries"`
	// 系统镜像名称
	MediaName *string `json:"MediaName"`
	// 系统镜像类型
	MediaType *string `json:"MediaType"`
	// 网络配置 (JSON)
	NetworkConfig *string `json:"NetworkConfig"`
	// 裸金属ID
	PMID *string `json:"PMID"`
	// 进度 (0-100)
	Progress *int `json:"Progress"`
	// 项目ID
	ProjectID *string `json:"ProjectID"`
	// 地域
	Region *string `json:"Region"`
	// 序列号
	SN *string `json:"SN"`
	// 开始时间
	StartTime *int `json:"StartTime"`
	// 状态: waiting, installing, completed, failed, canceled
	Status *string `json:"Status"`
	// 目标磁盘
	TargetDisk *string `json:"TargetDisk"`
	// 任务ID
	TaskID *string `json:"TaskID"`
	// 更新时间
	UpdatedAt *int `json:"UpdatedAt"`
}
