// Code generated by sdk-generator. DO NOT EDIT.

package models


// IPInfo 
type IPInfo struct {
	// IP地址，具体的网络地址值
	IP *string `json:"IP"`
	// IPID，IP资源唯一标识
	IPID *string `json:"IPID"`
	// IP版本，网络地址协议版本，取值：IPv4、IPv6
	IPVersion *string `json:"IPVersion"`
	// 默认网关，标识是否为系统默认路由出口
	ISDefaultGW *int `json:"ISDefaultGW"`
	// 网卡ID，虚拟网卡接口标识
	InterfaceID *string `json:"InterfaceID"`
	// 接口名称，操作系统内的网卡设备名
	InterfaceName *string `json:"InterfaceName"`
	// 弹性IP，标识是否为弹性公网IP
	IsElastic *string `json:"IsElastic"`
	// VIP标识，标识是否为虚拟IP
	IsVIP *string `json:"IsVIP"`
	// MAC地址，虚拟网卡的物理地址
	MAC *string `json:"MAC"`
	// 绑定模式，IP与网卡的关联模式，取值：Direct、NAT
	Mode *string `json:"Mode"`
	// 网卡型号编码，物理网卡的标准型号编号
	NicPFCode *string `json:"NicPFCode"`
	// 网卡产品型号，物理网卡的具体产品型号
	NicPFProduct *string `json:"NicPFProduct"`
	// 网卡厂商，物理网卡的制造厂商
	NicPFVendor *string `json:"NicPFVendor"`
	// 网卡类型，取值：LAN（内网）、WAN（外网）、Flat（扁平网络）
	NicType *string `json:"NicType"`
	// 安全组ID，绑定的安全组资源标识
	SGID *string `json:"SGID"`
	// 安全组名称，绑定的安全组可视化名称
	SGName *string `json:"SGName"`
	// 网络类型，标识IP的网络属性，取值：public（公网）、private（私网）
	Type *string `json:"Type"`
}
