// Code generated by sdk-generator. DO NOT EDIT.

package models


// LbCertificateInfo 
type LbCertificateInfo struct {
	// 证书内容，证书的PEM格式内容
	CertificateContent *string `json:"CertificateContent"`
	// 证书ID，用于标识证书
	CertificateID *string `json:"CertificateID"`
	// 证书类型，证书的类型，取值范围：ServerCrt（服务器证书）、CACrt（CA证书）
	CertificateType *string `json:"CertificateType"`
	// 主域名，证书的主域名（CN字段）
	CommonName *string `json:"CommonName"`
	// 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
	CompanyID *int `json:"CompanyID"`
	// 创建时间，证书在平台上的秒级Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// 邮箱，资源所有者的邮箱地址，用于展示联系人信息
	Email *string `json:"Email"`
	// 过期时间，证书内容的秒级Unix时间戳
	ExpireTime *int `json:"ExpireTime"`
	// 证书指纹，证书的指纹（通常为SHA-1哈希值）
	Fingerprint *string `json:"Fingerprint"`
	// 名称，证书的名称
	Name *string `json:"Name"`
	// 私钥内容，证书的私钥内容
	Privatekey *string `json:"Privatekey"`
	// 项目ID，用于标识证书所属项目分组
	ProjectID *string `json:"ProjectID"`
	// 项目名称，用于展示证书所属项目分组名称
	ProjectName *string `json:"ProjectName"`
	// 地域ID，用于标识资源所属的地理区域
	Region *string `json:"Region"`
	// 备注，证书的描述信息
	Remark *string `json:"Remark"`
	// 状态，证书的生命周期状态
	State *string `json:"State"`
	// 备选域名列表，证书的SANs（Subject Alternative Names）
	SubjectAlternativeNames []string `json:"SubjectAlternativeNames"`
	// 标签列表，用于展示证书关联标签
	Tags []UnifiedTag `json:"Tags"`
	// 虚拟服务器绑定列表，证书关联的虚拟服务器列表
	VSInfos []LbBindVSInfo `json:"VSInfos"`
}
