// Code generated by sdk-generator. DO NOT EDIT.

package models


// LbPriceInfo 
type LbPriceInfo struct {
	// 计费类型，取值范围：Dynamic、Month、Year；兼容历史值：hour、month、year，别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR
	ChargeType *string `json:"ChargeType"`
	// 订单类型，用于说明价格对应的订单场景（如新购、升级、降级）
	OrderType *string `json:"OrderType"`
	// 价格，用于展示对应计费周期的价格信息
	Price *float64 `json:"Price"`
}
