// Code generated by sdk-generator. DO NOT EDIT.

package models


// MySQLConfigOpLogInfo 
type MySQLConfigOpLogInfo struct {
	// 修改后的值，新参数值
	NewValue *string `json:"NewValue"`
	// 修改前的值，原参数值
	OldValue *string `json:"OldValue"`
	// 参数名称，配置参数名称
	ParameterName *string `json:"ParameterName"`
	// 更新时间，Unix时间戳（秒）
	UpdateTime *int `json:"UpdateTime"`
}
