// Code generated by sdk-generator. DO NOT EDIT.

package models


// NATGWEIPInfo 
type NATGWEIPInfo struct {
	// IP地址，EIP的公网IP地址
	IP *string `json:"IP"`
	// 弹性公网IPID，用于标识EIP资源
	IPID *string `json:"IPID"`
	// IP状态，EIP的当前状态
	IPStatus *string `json:"IPStatus"`
}
