// Code generated by sdk-generator. DO NOT EDIT.

package models


// NUMANode 
type NUMANode struct {
	// NUMA节点CPU列表，该NUMA节点包含的CPU核心详情
	CPUs []NUMANodeCPU `json:"CPUs"`
	// NUMA节点ID，物理NUMA拓扑节点标识
	NUMAID *int `json:"NUMAID"`
	// 物理NUMA内存
	TotalMemory *int `json:"TotalMemory"`
	// 物理NUMA已被虚拟机使用的内存
	UsedMemory *int `json:"UsedMemory"`
}
