// Code generated by sdk-generator. DO NOT EDIT.

package models


// OPLogIPInfo 
type OPLogIPInfo struct {
	// 具体IP地址，操作发生时记录的IP值
	IP *string `json:"IP"`
	// IP资源ID，关联IP资源的唯一标识
	IPID *string `json:"IPID"`
	// IP资源类型，EIP/FLATIP/VIP
	IPType *string `json:"IPType"`
}
