// Code generated by sdk-generator. DO NOT EDIT.

package models


// OrderDetail 
type OrderDetail struct {
	// 计费因子，计费规则的因子值，用于价格计算，与产品计费方式相关
	Factor *int `json:"Factor"`
	// 产品名称，订单关联的产品显示名称，例如磁盘、云主机等
	ProductName *string `json:"ProductName"`
	// 集群类型，资源所属的集群类型标识，用于区分不同的存储或计算集群
	Property *string `json:"Property"`
	// 资源数量，本次操作涉及的资源数量，例如创建磁盘的数量或购买的容量大小，单位与产品类型相关
	Quantity *int `json:"Quantity"`
	// 资源ID，订单关联的资源唯一标识，例如磁盘订单对应磁盘ID
	ResourceID *string `json:"ResourceID"`
	// 计量单位，资源的计量单位，例如GB、个、核等
	Unit *string `json:"Unit"`
}
