// Code generated by sdk-generator. DO NOT EDIT.

package models


// ParametersHistoriesInfos 
type ParametersHistoriesInfos struct {
	// 新值，参数修改后的值
	NewValue *string `json:"NewValue"`
	// 旧值，参数修改前的值
	OldValue *string `json:"OldValue"`
	// 参数名称，数据库配置参数的名称
	ParameterName *string `json:"ParameterName"`
	// 更新时间，从审计日志中的UpdateTime字段解析出的Unix时间戳
	Updatetime *int `json:"Updatetime"`
}
