// Code generated by sdk-generator. DO NOT EDIT.

package models


// PartitionTemplateConfig 
type PartitionTemplateConfig struct {
	// Btrfs子卷配置
	BtrfsSubvols []PartitionTemplateBtrfsSubvol `json:"BtrfsSubvols"`
	// LVM卷组名称
	LVMVolumeGroup *string `json:"LVMVolumeGroup"`
	// 分区列表
	Partitions []PartitionTemplatePartition `json:"Partitions"`
	// RAID配置
	RAIDConfigs []PartitionTemplateRAIDConfig `json:"RAIDConfigs"`
	// 分区方案: standard, lvm, raid, btrfs
	Scheme *string `json:"Scheme"`
}
