// Code generated by sdk-generator. DO NOT EDIT.

package models


// PeeringInfo 
type PeeringInfo struct {
	// 对端网段列表，目标网络所涵盖的所有地址范围
	PeerCIDRs []string `json:"PeerCIDRs"`
	// 对端ID，建立网络互通连接的目标网络标识符
	PeerID *string `json:"PeerID"`
	// 对端名称，目标网络的显示名称，查询时根据PeerType填充
	PeerName *string `json:"PeerName"`
	// 对端类型，标识互通目标的资源类型，取值VPC/DC
	PeerType *string `json:"PeerType"`
	// 连接状态，标识对等连接当前的可用性
	Status *string `json:"Status"`
}
