// Code generated by sdk-generator. DO NOT EDIT.

package models


// Permission 
type Permission struct {
	// 操作类型，标识该权限所属分类
	ActionType *string `json:"ActionType"`
	// 是否授权，标识是否拥有该动作权限；0表示否，1表示是
	IsPermission *int `json:"IsPermission"`
	// 权限名称，对应API的Action标识
	Name *string `json:"Name"`
	// 权限值，内部使用的权限位标识
	Permission *int `json:"Permission"`
	// 备注，对该权限功能的业务描述
	Remark *string `json:"Remark"`
}
