// Code generated by sdk-generator. DO NOT EDIT.

package models


// ProjectInfo 
type ProjectInfo struct {
	// 租户邮箱，该项目所属租户的主账号邮箱
	CompanyEmail *string `json:"CompanyEmail"`
	// 租户ID，标识项目所属的租户组织
	CompanyID *int `json:"CompanyID"`
	// 租户名称，所属租户的显示名称
	CompanyName *string `json:"CompanyName"`
	// 创建时间，项目创建的Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// 默认项目，标识该项目是否为系统默认项目
	IsDefault *bool `json:"IsDefault"`
	// 项目名称，资源逻辑分组的显示名称
	Name *string `json:"Name"`
	// 项目ID，用于对云资源进行逻辑分组的唯一标识符
	ProjectID *string `json:"ProjectID"`
	// 备注，对项目用途或管理范围的补充说明
	Remark *string `json:"Remark"`
	// 更新时间，项目配置最后修改的Unix时间戳
	UpdateTime *int `json:"UpdateTime"`
}
