// Code generated by sdk-generator. DO NOT EDIT.

package models


// RecycleResourceInfo 
type RecycleResourceInfo struct {
	// 租户ID，资源所属租户
	CompanyID *int `json:"CompanyID"`
	// 租户名称，资源所属租户的显示名称
	CompanyName *string `json:"CompanyName"`
	// 创建时间，Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// 删除时间，资源进入回收站的时间，Unix时间戳
	DeleteTime *int `json:"DeleteTime"`
	// 资源描述，资源备注或说明信息
	Description *string `json:"Description"`
	// 租户邮箱，资源所属租户的联系邮箱
	Email *string `json:"Email"`
	// 过期时间，资源到期时间，0表示永不过期
	ExpireTime *int `json:"ExpireTime"`
	// 是否自动销毁，true表示回收站资源将自动销毁
	IsAutoTerminated *bool `json:"IsAutoTerminated"`
	// 是否失败，true表示资源处于失败状态
	IsFailed *bool `json:"IsFailed"`
	// 资源名称，资源的自定义显示名称
	Name *string `json:"Name"`
	// 项目ID，资源所属项目ID
	ProjectID *string `json:"ProjectID"`
	// 项目名称，资源所属项目的显示名称
	ProjectName *string `json:"ProjectName"`
	// 资源操作原因，记录资源状态变更或操作原因
	Reason *string `json:"Reason"`
	// 地域ID，资源所属的物理区域
	Region *string `json:"Region"`
	// 地域别名，地域的展示名称
	RegionAlias *string `json:"RegionAlias"`
	// 资源备注，用于记录资源用途或说明
	Remark *string `json:"Remark"`
	// 资源ID，回收站资源的唯一标识
	ResourceID *string `json:"ResourceID"`
	// 资源类型，资源类型字符串，如VM、DISK、EIP等
	ResourceType *string `json:"ResourceType"`
	// 状态字符串，资源业务状态的字符串表示
	State *string `json:"State"`
	// 状态码，资源状态的数值表示
	Status *int `json:"Status"`
	// 更新时间，Unix时间戳
	UpdateTime *int `json:"UpdateTime"`
	// 预计销毁时间，回收站资源自动销毁时间
	WillTerminateTime *int `json:"WillTerminateTime"`
}
