// Code generated by sdk-generator. DO NOT EDIT.

package models


// RedisSlowlog 
type RedisSlowlog struct {
	// 客户端地址，执行命令的客户端地址
	ClientAddr *string `json:"ClientAddr"`
	// 客户端名称，执行命令的客户端名称
	ClientName *string `json:"ClientName"`
	// 执行命令，慢日志命令内容
	Command *string `json:"Command"`
	// 耗时（微秒），执行命令耗时
	ExecSpend *int `json:"ExecSpend"`
	// 执行时间，Unix时间戳（秒）
	StartTime *int `json:"StartTime"`
}
