// Code generated by sdk-generator. DO NOT EDIT.

package models


// SetGPUUsedInfo 
type SetGPUUsedInfo struct {
	// GPU可分配量，该类型GPU当前可用于分配的数量，计算方式为Count-Used-Locked
	Allocable *int `json:"Allocable"`
	// GPU总数，该类型GPU的总数量
	Count *int `json:"Count"`
	// GPU硬件名称，物理GPU硬件设备名称
	HDName *string `json:"HDName"`
	// GPU已锁定量，该类型GPU已锁定但尚未分配的数量，如虚拟机创建中
	Locked *int `json:"Locked"`
	// 虚拟GPU设备类型名称，该物理GPU支持的Mdev设备类型
	MdevName *string `json:"MdevName"`
	// GPU使用量，该类型GPU已分配给虚拟机的数量
	Used *int `json:"Used"`
}
