// Code generated by sdk-generator. DO NOT EDIT.

package models


// SetInfo 
type SetInfo struct {
	// 绑定镜像ID列表，当前计算集群绑定的镜像ID，以逗号分隔，值为all表示绑定所有镜像，可通过UpdateVMSetBoundImage修改
	BoundImageIDs *string `json:"BoundImageIDs"`
	// 逻辑绑定存储集群列表，当前计算集群绑定的存储集群列表，逻辑绑定，软限制，可通过UpdateVMSetBoundStorageSet修改，从物理绑定列表中筛选
	BoundStorageClassList []StorageClassItem `json:"BoundStorageClassList"`
	// CPU可分配量，当前可用于分配的CPU核心数，计算方式为CPUCount-CPUUsed-CPULocked
	CPUAllocable *int `json:"CPUAllocable"`
	// CPU分配比例，CPU超分比例，表示物理CPU可以虚拟化出多少倍的逻辑CPU
	CPUAllocationRatio *float64 `json:"CPUAllocationRatio"`
	// CPU数量，集群中可分配的总CPU核心数，考虑超分比例后的逻辑数量
	CPUCount *int `json:"CPUCount"`
	// CPU已锁定量，已锁定但尚未分配的CPU核心数，如虚拟机创建中
	CPULocked *int `json:"CPULocked"`
	// CPU型号列表，集群中包含的CPU制造商和型号信息
	CPUManufacturer []string `json:"CPUManufacturer"`
	// CPU模型差集，集群内部分主机支持但非全部主机支持的CPU模型列表
	CPUModelDiffsection []CPUModelInfo `json:"CPUModelDiffsection"`
	// CPU模型交集，集群内所有主机都支持的CPU模型列表，用于确保虚拟机在集群内任意主机间迁移时的兼容性
	CPUModelIntersection []CPUModelInfo `json:"CPUModelIntersection"`
	// 物理CPU数量，集群中实际物理CPU核心总数
	CPUPhysicCount *int `json:"CPUPhysicCount"`
	// CPU使用量，已分配给虚拟机的CPU核心数
	CPUUsed *int `json:"CPUUsed"`
	// 创建时间，Unix时间戳，单位为秒
	CreateTime *int `json:"CreateTime"`
	// GPU可分配量，当前可用于分配的GPU卡数，计算方式为GPUCount-GPUUsed-GPULocked
	GPUAllocable *int `json:"GPUAllocable"`
	// GPU数量，集群中可分配的总GPU卡数
	GPUCount *int `json:"GPUCount"`
	// 物理GPU使用信息列表，包含各种物理GPU型号的数量、使用量、可分配量等统计信息
	GPUInfos []SetGPUUsedInfo `json:"GPUInfos"`
	// GPU已锁定量，已锁定但尚未分配的GPU卡数，如虚拟机创建中
	GPULocked *int `json:"GPULocked"`
	// GPU使用量，已分配给虚拟机的GPU卡数
	GPUUsed *int `json:"GPUUsed"`
	// 内存可分配量，当前可用于分配的内存容量，计算方式为MemoryCap-MemoryUsed-MemoryReserved-MemoryLocked，单位为GB
	MemoryAllocable *float64 `json:"MemoryAllocable"`
	// 内存容量，集群中可分配的总内存容量，单位为GB
	MemoryCap *float64 `json:"MemoryCap"`
	// 内存已锁定量，已锁定但尚未分配的内存容量，单位为GB，如虚拟机创建中
	MemoryLocked *float64 `json:"MemoryLocked"`
	// 内存物理使用量，虚拟机实际使用的物理内存总量，单位为GB
	MemoryPhysicUsed *float64 `json:"MemoryPhysicUsed"`
	// 内存预留量，系统预留的内存容量，不可分配给虚拟机，单位为GB
	MemoryReserved *float64 `json:"MemoryReserved"`
	// 内存使用量，已分配给虚拟机的内存总量，单位为GB
	MemoryUsed *float64 `json:"MemoryUsed"`
	// 物理网卡信息列表，集群中各节点的物理网卡（PF）信息，包含VF资源使用情况，用于SR-IOV网卡直通
	PFNodeInfos []PFNodeInfo `json:"PFNodeInfos"`
	// 地域ID，计算集群所属的物理区域
	Region *string `json:"Region"`
	// 集群别名，计算集群的自定义名称
	SetAlias *string `json:"SetAlias"`
	// 集群架构，计算集群的硬件架构类型
	SetArch *string `json:"SetArch"`
	// 集群ID，计算集群的唯一标识，由底层Huanghe系统生成和管理
	SetID *string `json:"SetID"`
	// 集群类型，计算集群的类型标识
	SetType *string `json:"SetType"`
	// 物理绑定存储集群列表，当前计算集群可用的存储集群列表，物理绑定，硬限制，由底层物理网络拓扑决定
	StorageClassList []StorageClassItem `json:"StorageClassList"`
	// DRS是否暂停
	Suspend *bool `json:"Suspend"`
	// 更新时间，Unix时间戳，单位为秒
	UpdateTime *int `json:"UpdateTime"`
	// 虚拟GPU使用信息列表，包含各种vGPU型号的数量、使用量、可分配量等统计信息
	VGPUInfos []SetVGPUUsedInfo `json:"VGPUInfos"`
}
