// Code generated by sdk-generator. DO NOT EDIT.

package models


// SetTypeInfo 
type SetTypeInfo struct {
	// 权限控制，该计算集群类型的访问权限，值为all表示所有租户可用，或以逗号分隔的租户ID列表
	Permission *string `json:"Permission"`
	// 地域ID，计算集群类型所属的物理区域
	Region *string `json:"Region"`
	// 计算集群架构，计算集群的硬件架构类型
	SetArch *string `json:"SetArch"`
	// 计算集群类型名称，计算集群的类型标识
	VMType *string `json:"VMType"`
	// 计算集群类型别名，计算集群类型的自定义名称
	VMTypeAlias *string `json:"VMTypeAlias"`
}
