// Code generated by sdk-generator. DO NOT EDIT.

package models


// SourceInfo 
type SourceInfo struct {
	// 源虚拟机ID，被克隆的源虚拟机标识
	SourceVMID *string `json:"SourceVMID"`
	// 整机快照ID，克隆使用的快照标识
	VMSPID *string `json:"VMSPID"`
}
