// Code generated by sdk-generator. DO NOT EDIT.

package models


// Specification 
type Specification struct {
	// 创建时间，Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// 是否为默认规格，Yes表示默认，No表示非默认
	Default *string `json:"Default"`
	// 规格维度信息
	Dimension *Dimension `json:"Dimension"`
	// 产品类型
	ProductType *string `json:"ProductType"`
	// 地域ID
	Region *string `json:"Region"`
	// 资源类型
	ResourceType *string `json:"ResourceType"`
	// 集群类型，标识规格所属的集群类型
	SetType *string `json:"SetType"`
	// 规格ID，规格的唯一标识符
	SpecificationID *string `json:"SpecificationID"`
	// 规格名称
	SpecificationName *string `json:"SpecificationName"`
	// 更新时间，Unix时间戳
	UpdateTime *int `json:"UpdateTime"`
	// 规格值，规格的具体配置值
	Value *string `json:"Value"`
}
