// Code generated by sdk-generator. DO NOT EDIT.

package models


// StorageSetTypeInfo 
type StorageSetTypeInfo struct {
	// 权限控制，该存储类型的访问权限，值为all表示所有租户可用，或以逗号分隔的租户ID列表
	Permission *string `json:"Permission"`
	// 地域ID，存储集群类型所属的物理区域
	Region *string `json:"Region"`
	// 存储集群架构，存储集群的硬件架构类型
	SetArch *string `json:"SetArch"`
	// 存储集群类型，存储集群的类型标识
	StorageType *string `json:"StorageType"`
	// 存储集群类型别名，存储集群类型的自定义名称
	StorageTypeAlias *string `json:"StorageTypeAlias"`
}
