// Code generated by sdk-generator. DO NOT EDIT.

package models


// TaskStage 
type TaskStage struct {
	// 任务阶段，数据传输任务的阶段名称
	Stage *string `json:"Stage"`
	// 任务阶段状态，阶段执行状态
	Status *string `json:"Status"`
}
