// Code generated by sdk-generator. DO NOT EDIT.

package models


// TaskStep 
type TaskStep struct {
	// 步骤延迟，执行该步骤前等待的时间（秒）
	Delay *int `json:"Delay"`
	// 步骤次序，步骤执行顺序
	Order *int `json:"Order"`
	// 步骤包含的资源信息，步骤关联资源的执行情况
	Resources []TaskStepResource `json:"Resources"`
}
