// Code generated by sdk-generator. DO NOT EDIT.

package models


// TaskExecution 
type TaskExecution struct {
	// 最新执行结束时间，执行结束时间戳，为0表示未结束
	EndsAt *int `json:"EndsAt"`
	// 最新执行信息，执行结果说明
	Message *string `json:"Message"`
	// 最新执行结果，取值可能为NotStarted/Succeed/Failed/Interrupted或空字符串
	Result *string `json:"Result"`
	// 最新执行开始时间，执行开始时间戳
	StartsAt *int `json:"StartsAt"`
}
