// Code generated by sdk-generator. DO NOT EDIT.

package models


// TimerResources 
type TimerResources struct {
	// 资源ID，定时器绑定的目标资源唯一标识符
	ResourceID *string `json:"ResourceID"`
	// 资源名称，资源显示名称
	ResourceName *string `json:"ResourceName"`
}
