// Code generated by sdk-generator. DO NOT EDIT.

package models


// USBInfo 
type USBInfo struct {
	// 加载类型，取值Passthrough、redir
	AttachedType *string `json:"AttachedType"`
	// 已加载的虚拟机ID，当状态为Attached时有效
	AttachedVMID *string `json:"AttachedVMID"`
	// 产品类型，USB设备类型
	Class *string `json:"Class"`
	// 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
	CompanyID *int `json:"CompanyID"`
	// 租户名称，资源归属租户的可读名称
	CompanyName *string `json:"CompanyName"`
	// 计算集群ID，USB设备所在计算集群标识
	ComputeSetID *string `json:"ComputeSetID"`
	// 创建时间，USB设备纳管的秒级Unix时间戳
	CreateTime *int `json:"CreateTime"`
	// 租户邮箱，归属租户的联系电子邮箱
	Email *string `json:"Email"`
	// 宿主机IP，USB设备所在宿主机IP
	HostIP *string `json:"HostIP"`
	// 设备名称，USB设备在平台中的显示名称
	Name *string `json:"Name"`
	// 产品名称，USB设备产品名称
	Product *string `json:"Product"`
	// 项目ID，资源所属的项目分组标识
	ProjectID *string `json:"ProjectID"`
	// 项目名称，资源归属项目的显示名称
	ProjectName *string `json:"ProjectName"`
	// 加载失败原因，USB设备加载失败时的错误说明
	Reason *string `json:"Reason"`
	// 地域ID，USB设备所属的地理标识
	Region *string `json:"Region"`
	// 地域别名，地域的人性化显示名称
	RegionAlias *string `json:"RegionAlias"`
	// 备注信息，USB设备的补充说明
	Remark *string `json:"Remark"`
	// 序列号，USB设备的硬件序列号
	Serial *string `json:"Serial"`
	// 加载状态，取值Attached、Detached、Lost
	Status *string `json:"Status"`
	// USB设备ID，USB设备资源标识
	USBDeviceID *string `json:"USBDeviceID"`
	// 厂商名称，USB设备厂商名称
	Vendor *string `json:"Vendor"`
	// USB协议版本
	Version *string `json:"Version"`
}
