// Code generated by sdk-generator. DO NOT EDIT.

package models


// VmSetItem 
type VmSetItem struct {
	// 计算集群ID，计算集群的唯一标识
	VmSetID *string `json:"VmSetID"`
	// 计算集群名称，计算集群的自定义名称
	VmSetName *string `json:"VmSetName"`
	// 计算集群类型，计算集群的类型标识
	VmSetType *string `json:"VmSetType"`
}
