// Code generated by sdk-generator. DO NOT EDIT.

package models


// VPCInfo 
type VPCInfo struct {
	// 租户ID，VPC所属的租户唯一标识，用于实现多租户环境下的资源隔离
	CompanyID *int `json:"CompanyID"`
	// 租户邮箱，租户注册时提供的用于接收通知和联系的邮箱地址
	Email *string `json:"Email"`
	// VPC名称
	Name *string `json:"Name"`
	// 备注，用于进行说明和注释，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符
	Remark *string `json:"Remark"`
	// VPC ID，VPC资源的唯一标识
	VPCID *string `json:"VPCID"`
}
